### ISSUE TITLE
Fatal Error after configuration

### ISSUE THREAD

**Issue by Benedikt1992** [tkrebs/ep3-bs#10]
Hello,

after the installation finished successfully, I got a Fatal Error Message by trying to load the website. The error message:
Fatal error: Uncaught exception 'Zend\Session\Exception\InvalidArgumentException' with message ''session.save_path' is not a valid sessions-related ini setting.' in /.../vendor/zendframework/zendframework/library/Zend/Session/Config/SessionConfig.php:90 Stack trace: #0 /xxx/vendor/zendframework/zendframework/library/Zend/Session/Config/StandardConfig.php(237): Zend\Session\Config\SessionConfig->setStorageOption('save_path', '/xxx/...') #1 /xxx/vendor/zendframework/zendframework/library/Zend/Session/Config/SessionConfig.php(157): Zend\Session\Config\StandardConfig->setSavePath('/xxx/...') #2 /xxx/vendor/zendframework/zendframework/library/Zend/Session/Config/StandardConfig.php(115): Zend\Session\Config\SessionConfig->setSavePath('/xxx/...') #3 /xxx/vendor/zendframework/zendframework/library/Zend/Session/Service/SessionConfigFactory.php(60): Zend\Session\Config\StandardConfig->setOptions(Array) #4 [internal function]: Zend\Session\Service\SessionConfigFactory->createService(Object(Zend\ServiceManager\ServiceManager), 'zendsessionconf...', 'Zend\\Session\\Co...') #5 /xxx/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(902): call_user_func(Array, Object(Zend\ServiceManager\ServiceManager), 'zendsessionconf...', 'Zend\\Session\\Co...') #6 /xxx/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(1032): Zend\ServiceManager\ServiceManager->createServiceViaCallback(Array, 'zendsessionconf...', 'Zend\\Session\\Co...') #7 /xxx/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(612): Zend\ServiceManager\ServiceManager->createFromFactory('zendsessionconf...', 'Zend\\Session\\Co...') #8 /xxx/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(572): Zend\ServiceManager\ServiceManager->doCreate('Zend\\Session\\Co...', 'zendsessionconf...') in /xxx/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php on line 909

xxx = Individual Path to the ep3 Bookingsystem

ep3-Version 1.4

PHP Info of the webserver:
http://phpinfo.bplaced.net/

**Comment by Sommerwerk** [comment]
The same problem I have and know until now no solution

**Comment by Benedikt1992** [comment]
I made a little stack trace:

The call of Zend\Session\Config\SessionConfig->setStorageOption('save_path', '/xxx/...') in  /xxx/vendor/zendframework/zendframework/library/Zend/Session/Config/StandardConfig.php(237) leads to the Exception. In setStorageOption the  String 'save_path'  is expanded to 'session.save_path' which seems to be a invalid argument in the following call of ini_set($key, $storageValue) in /xxx/vendor/zendframework/zendframework/library/Zend/Session/Config/SessionConfig.php(88) where $key='session.save_path'


Because that is static library code I decided to rebuild the dependencies with composer. Unfortunately the error remains...

**Comment by tkrebs** [comment]
Unusual error message. Since we are dealing here with solid, well tested Zend Framework 2 code, I suppose your webserver, especially PHP, is misconfigured. Looking at the "strange" non-default phpinfo page you linked, it seems like your provider fiddled around with the default PHP settings and broke something. ;)

**Comment by Benedikt1992** [comment]
It's definitly a config problem. Local on a linux machine it works (Apache2, php 5.4.xx). PHP is older but I think that shouldn't matter... Any idea what could be misconfigured?

**Comment by tkrebs** [comment]
Well, I think the error message produced by PHP is pretty accurate here... ;)

" 'session.save_path' is not a valid sessions-related ini setting" (in default PHP it is)

Perhaps your hoster has disabled custom session save paths for safety.

Try removing the line

'save_path' => getcwd() . '/data/session/',

in /config/autoload/global.php

It will then save the session data wherever your hoster deems it necessary.

**Comment by Benedikt1992** [comment]
That works! Great thanks for your help
