### ISSUE TITLE
Kontaktseite ?

### ISSUE THREAD

**Issue by wklingberg** [tkrebs/ep3-bs#100]
Bei "Einstellungen" > "Namen und Texte" gibt es auch das Feld "Ihre Kontaktseite". Mit welchem Element sollte der dort eingegebene Link verbunden sein? In der Erläuterung heißt es "Die Internetadresse Ihrer Kontaktseite. Erscheint z.B. ganz oben in der Kopfleiste."

**Comment by tkrebs** [comment]
Das Buchungssystem wird üblicherweise zusammen mit einer regulären Website betrieben. Daher sollten unter "Namen und Texte" die URLs auf die Kontakt- und Impressum-Seite der Website eingefügt werden.

**Comment by wklingberg** [comment]
Klar, aber unter "Namen und Texte" gibt es 3 Felder: Ihre Webseite , Ihre Kontaktseite und Ihr Impressum.
Einen Link mit dem Wert der eingetragenen Kontaktseite kann ich aber auf der Buchungssystem-Seite nicht finden.

**Comment by tkrebs** [comment]
Die Kontaktseite wird in der Kopfleiste unter "Kontakt & Feedback" verlinkt, die Impressumseite im Footer unter "Impressum".

**Comment by wklingberg** [comment]
In der Kopfleiste hatte ich bisher "Kontakt & Feedback" nicht gesehen, da dieser Link nicht dargestellt wurde. (siehe issue # 102)

**Comment by tkrebs** [comment]
Okay, das eigentliche Problem ist also #102
