### ISSUE TITLE
Kopf-Bereich-Darstellung am Smartphone

### ISSUE THREAD

**Issue by wklingberg** [tkrebs/ep3-bs#102]
Am PC-Bildschirm wird der Kopfbereich einschl. "Telefonische Buchung", "Infos & Bilder über" und "Unsere Internetseite" im Normalfall komplett dargestellt. Wird das Fenster in der Breite reduziert, verschwinden diese 3 Bereich sukzessive von rechts. Am Smartphone wird deshalb keiner dieser 3 Bereiche angezeigt.

**Comment by gitroli** [comment]
Das ist das Responsive Webdesign, damit ist die Darstellung für unterschiedliche Endgeräte optimiert.
Wenn du das nich willst kannst du in der layout.phtml das umschreiben, indem du allen class "responsive-pass-5" gibst, dann verschwindet es nur bei sehr schmaler Ansicht oder du lässt die class überhaupt weg, dann bleibt es immer stehen.

**Comment by tkrebs** [comment]
Ist in der neuen [Version 1.6.3](https://github.com/tkrebs/ep3-bs/tree/develop) korrigiert.
