### ISSUE TITLE
Links in der Fußzeile

### ISSUE THREAD

**Issue by wklingberg** [tkrebs/ep3-bs#103]
Bei den 3 Links in der Fußzeile wird das Ziel jeweils im gleichen Fenster angezeigt und überschreibt damit das Anwendungsfenster.

**Comment by gitroli** [comment]
Du kannst in der layout.phtml unter folgendem Pfad module\Base\view\layout bei den Hyperlinks das target mitangeben "_blank"

**Comment by wklingberg** [comment]
Vielen Dank für die Fundstelle.

**Comment by mjmpeace** [comment]
Der einzutragende Wert nach dem Platzhalter: " target="_blank" class="unlined white">

**Comment by wklingberg** [comment]
Was bewirkt die class-Angabe ? Ich kann keinen Unterschied erkennen.

**Comment by mjmpeace** [comment]
Nicht unterstrichen und weiß wenn man es angeklickt hat. soll es bewirken.
