### ISSUE TITLE
Umlaut-Problem bei "erweiterter Suche" in Benutzerverwaltung

### ISSUE THREAD

**Issue by wklingberg** [tkrebs/ep3-bs#104]
Bei der Auswahl "Status = gelöschter Benutzer" bei einer erweiterten Suche in der Benutzerverwaltung tritt ein Umlaut-Problem auf.
 (status = gel��schter benutzer)

**Comment by tkrebs** [comment]
Das wurde korrigiert und müsste in der letzten Version behoben sein.
