### ISSUE TITLE
Benachrichtigung nach Aktivierung

### ISSUE THREAD

**Issue by wklingberg** [tkrebs/ep3-bs#106]
Nach einer Registrierung erhält der Benutzer den Hinweis
“Allerdings ist Ihr Benutzerkonto noch nicht freigeschaltet. Dies geschieht nach einer kurzen manuellen Prüfung Ihrer Daten. Bitte haben Sie etwas Geduld.” 
Da es ja doch mal etwas länger dauern kann, bis der Admin die Aktivierung durchführt, wäre ein entsprechende Änderung des Hinweistextes sinnvoll.
Optimal wäre es, wenn der Benutzer nach Aktivierung eine E-Mail erhalten würde.

**Comment by monoseo** [comment]
Ja, diese Option würden ich gerne auch nutzen!
