### ISSUE TITLE
Nur bestimmte Plätze im Kalendar anzeigen

### ISSUE THREAD

**Issue by gitroli** [tkrebs/ep3-bs#107]
Mein Beispiel sieht folgendermaßen aus:
4 Plätze: 2x Tennis (Buchung immer 60min), 2x Badminton (Buchung immer 45min)
Alle 4 Plätze sind aktiv.

Nun möchte ich den Code so ändern, dass entweder 2 Tennis oder 2 Badminton Plätze angezeigt werden.
Realisieren möchte ich das ganze einfach über 2 URLs:
tennis-reservierung.domain.com
badminton-reservierung.domain.com

Oben bau ich einfach einen Link ein, damit man schnell zwischen den beiden Seiten hin und her kann.

Bedingung ist allerdings das beide Instanzen im Hintergrund nur eine DB verwenden, damit sich die gleichen User anmelden können.

Wo finde ich die entsprechende Code Stelle, damit ich nur bestimmte aktive Plätze anzeigen kann?

Danke

**Comment by tkrebs** [comment]
Gute Nachrichten: Diese Funktion ist bereits eingebaut. Du kannst nur bestimmte Plätze anzeigen lassen, indem du den Parameter `squares` mit den kommagetrennten IDs an die URL anhängst, also z. B.

http://demo.bs.hbsys.de/?squares=1,2

**Comment by gitroli** [comment]
Hast du noch einen Tipp für mich, wo ich das permanent anhängen kann, gleich beim Aufruf der URL und beim Hin und Her Blättern des Kalenders, denn da werden dann wieder alle Plätze angezeigt.

**Comment by gitroli** [comment]
Mir ist noch was aufgefallen, die Badminton Plätze haben eine Zeitblockteilung von 45 min und die Tennisplätze von 60 min. Wenn ich mir über die URL /?squares=1,2 die beiden Tennisplätze anzeigen lasse, bleibt trotzdem die Zeitblockteilung auf 45 min und der User könnte Tennisplätze für 45 min buchen.
