### ISSUE TITLE
Mcrypt ist ab php7.2 nicht mehr verfügbar

### ISSUE THREAD

**Issue by schnuckelg** [tkrebs/ep3-bs#109]
Macht es Sinn dieses Issue bereits jetzt zu adressieren?

**Comment by tkrebs** [comment]
Mcrypt war bisher hauptsächlich eine Voraussetzung des darunterliegenden Zend Framework 2.

Wenn die aktuelle Version des 2.4.*-Zweiges ohne Mcrypt auskommt, ist das kein Problem. Ansonsten müsste auf Zend Framework 3 geupgraded werden.

**Comment by schnuckelg** [comment]
Bei der Registrierung wird die zend\mcrypt benötigt. Warum genau habe ich noch nicht nachgesehen. Aber mit php7.2 ist eine Registrierung nicht möglich.

**Comment by tkrebs** [comment]
Ich habe die Registrierung korrigiert, sodass das System nun mit PHP 7.2 kompatibel sein sollte.

Verantwortlich und auszutauschen ist folgende Datei:

https://github.com/tkrebs/ep3-bs/blob/90b9a7878157af8025d393a1cd46c8bbdcf4f536/module/User/src/User/Form/RegistrationForm.php
