### ISSUE TITLE
Oops ... da ist wohl etwas schief gelaufen - Dieses Kalenderdatum ist ungültig

### ISSUE THREAD

**Issue by weicky-xtal** [tkrebs/ep3-bs#112]
Hallo zusammen,
trotz neu installation und setzten des 4 bei "service.calendar.days" in der Datenbank bleibt der Fehler, was kann ich tun?

Nette Grüße
Uwe

**Comment by tkrebs** [comment]
Versuch mal, die Cookies des Buchungssystems im Webbrowser zu löschen oder alternativ in einem privaten Tab zu öffnen.

**Comment by weicky-xtal** [comment]
Hallo tkrebs,
danke für die schnelle Reaktion.
bei IE, Firefox und Chrome die Cookies gelöscht (bzw. Chrome neu installiert, war bisher noch nicht installiert), überall der gleiche Fehler.

Nette Grüße
Uwe

**Comment by tkrebs** [comment]
Wenn du diese Zeile:

`throw new RuntimeException('The passed calendar date is invalid:' . $e->getMessage());`

in diese Datei und Zeile einfügst:

https://github.com/tkrebs/ep3-bs/blob/master/module/Calendar/src/Calendar/Controller/Plugin/DetermineDate.php#L37

müsstest du den genauen Grund für den Fehler ausgegeben bekommen.

**Comment by weicky-xtal** [comment]
Hallo Tobias,
dann kommt folgende Meldung:

"The passed calendar date is invalid:DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone."

In der local.php steht folgendes:
    ini_set('date.timezone', 'Europe/Berlin');
und
    'i18n' => array(
        //'locale' => 'en-US',
        //'currency' => 'USD',
		'locale' => 'de-DE',
        'currency' => 'EUR',
    ),

Das ist doch das was angemeckert wird, oder?

LG Uwe

**Comment by tkrebs** [comment]
Lösche mal alle Dateien im `data/cache/`-Verzeichnis und teste, ob der Fehler anschließend immer noch erscheint.

**Comment by weicky-xtal** [comment]
Hallo Tobias,
wenn ich die Dateien lösche funktioniert die Seite, biss ich mich anmelden, oder sonst was machen will, dann kommt der Ferhler wieder. Die Dateien werden ja neu geschrieben. Lösche ich die Dateien wieder, dann geht es wieder weiter. Dann Dateien wieder da und Fehler kommt, Dateien löschen und es geht weiter.

LG Uwe

**Comment by weicky-xtal** [comment]
Hallo nochmal,
aus versehen geschlossen ;-)

Habe noch fest gestellt, das es reicht die Datei "module-config-cache.ep3-bs.php" zu löschen!

LG Uwe

**Comment by weicky-xtal** [comment]
Folgender test brachte leider auch keinen Erfolg:

Dateien gelöscht, dann Cache geleert, Browser neu gestartet -> Fehler bleibt.

**Comment by tkrebs** [comment]
Ja, das Löschen des Caches war nur ein Hinweis darauf, wo das Problem liegt, nicht die Lösung.

Die Lösung ist die backfrische Version 1.6.2, welche du hier auf GitHub oder auf der Website herunterladen kannst:

http://bs.hbsys.de/download

Es reicht aus, folgende Verzeichnisse auszutauschen:

config/
data/
public/

Anschließend die (nun aktualisierten) Schritte in der data/docs/install.txt wiederholen. Dann müsste es rund laufen.

**Comment by weicky-xtal** [comment]
Hallo Tobias,
jetzt klappt alles! 
Vielen Dank für die tolle Hilfe.

LG Uwe
