### ISSUE TITLE
Wie sieht es mit Bezahlsystemen wie z.B. Paypal, Kreditkarte aus?

### ISSUE THREAD

**Issue by weicky-xtal** [tkrebs/ep3-bs#114]
Hallo,
wollte mal wissen, ob und wann z.B. Paypal und/oder Kreditkarte als Bezahlsystem genutzt werden kann.

Wäre für meine Schwägering wichtig.

LG Uwe

**Comment by tkrebs** [comment]
Dazu gibt es hier #63 ein laufendes Ticket.

Wie dort beschrieben, ist ein PayPal-Modul in Arbeit, es gibt aber noch keine weiteren Details dazu.
