### ISSUE TITLE
Einloggen bei 'Wartungsarbeiten' nicht möglich

### ISSUE THREAD

**Issue by wagpat** [tkrebs/ep3-bs#115]
Wie kann ich mich als Admin im Status 'Wartungsarbeiten' einloggen?

Danke.

**Comment by weicky-xtal** [comment]
Hallo,
geh mal direkt auf ".../public/user/login", dann sollte die Loginseite kommen.

LG Uwe

**Comment by Michele1983** [comment]
Habe das selbe Problem /public/user/login funktioniert nicht!
