### ISSUE TITLE
Hinweis auf Javascript-Aktivierung, obwohl aktiviert

### ISSUE THREAD

**Issue by wklingberg** [tkrebs/ep3-bs#118]
Bei der Buchung, also nach Bestätigen von "Jetzt buchen" wird mit der Meldung
"JavaScript muss in Ihrem Webbrowser aktiviert sein um fortzufahren. Im Zweifelsfall benutzen Sie einfach einen anderen Webbrowser (z.B. Mozilla Firefox)." abgebrochen.
Buche ich als Administrator für den Benutzer, klappt die Buchung.
Erledigt: Hatte Anpassungen am layout.phtml vorgenommen. Mit dem Original ist wieder alles normal.

**Comment by boettges** [comment]
Der Vollständigkeit halber: Die Probleme rühren scheinbar daher, dass die "locale" falsch gesetzt ist. Reproduzierbar passiert das bei mir, wenn ich `en-GB` anstatt `en-US` oder `de-DE` nutze. 

Ich hätte en-GB wegen des 24 Stunden Zeitformats präferiert, habe die Einstellung nun jedoch global auf "en-US" gelassen und stattdessen in:
[/module/Base/src/Base/View/Helper/DateFormatFactory.php Line 20](https://github.com/tkrebs/ep3-bs/blob/463c278f059cacb76f3e4880c6e2e70d491385fa/module/Base/src/Base/View/Helper/DateFormatFactory.php#L20)
manuell dies ergänzt:
`$dateFormat->setLocale('en-GB');`

Funktioniert bisweilen tadellos und das UI ist auf Englisch, die Uhrzeiten aber im 24 Stunden Format.
