### ISSUE TITLE
nach Update  kommt die Meldung ,

### ISSUE THREAD

**Issue by mumulusul** [tkrebs/ep3-bs#120]
![bildschirmfoto 2018-03-03 um 16 29 37](https://user-images.githubusercontent.com/33692234/36936051-20d0d760-1f00-11e8-93d1-6e2b3a5adfc1.png)

**Comment by mumulusul** [comment]
#0 /var/www/vhosts/**/tuerkheim/module/Square/src/Square/Service/SquareValidator.php(237): Square\Service\SquareValidator->isValid(Object(DateTime), Object(DateTime), Object(DateTime), Object(DateTime), Object(Square\Entity\Square))
#1 /var/www/vhosts/**/module/Square/src/Square/Controller/SquareController.php(23): Square\Service\SquareValidator->isBookable('2018-03-29', NULL, '19:00', '20:00', '3')
#2 /var/www/vhosts/*.*/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php(82): Square\Controller\SquareController->indexAction()
#3 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#4 /var/www/vhosts/*.*/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#5 /var/www/vhosts/*.*/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#6 /var/www/vhosts/*.*/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#7 /var/www/vhosts/*.*/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#8 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#9 /var/www/vhosts/*-*/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#10 /var/www/vhosts/*.*/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /var/www/vhosts/*.*/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /var/www/vhosts/*.*/public/index.php(73): Zend\Mvc\Application->run()
#13 {main}

**Comment by mumulusul** [comment]
HILFE :-) , wer kann mir hier ein tipp geben ? Vielen Dank

**Comment by tkrebs** [comment]
Wie viele Tage sind denn für den Platz unter "Buchung im Voraus" in der Platzverwaltung eingestellt?

**Comment by mumulusul** [comment]
7 Tage 



Am 11.04.18 um 01:48 schrieb Tobias Krebs

**Comment by mumulusul** [comment]
vor dem Update waren auch 7 Tage,  gab es aber keine Pobleme

**Comment by tkrebs** [comment]
Tritt das Problem bei allen Plätzen (sofern es mehrere gibt) auf?
Kommt der Fehler immer (also z. B. auch am jeweils "heutigen" Tag) oder erst ab einer bestimmten Anzahl Tagen in der Zukunft?

(lösche auch mal probeweise alle Dateien im Ordner `data/cache/`)

**Comment by mumulusul** [comment]
Die Fehlermeldung kommt nur bei mehr als 7 Tage in der Zukunft, Cache löschen hat nichts gebracht,



Am 12.04.18 um 20:35 schrieb Tobias Krebs

**Comment by mumulusul** [comment]
sonnst versuche ich irgendwann neu aufzusetzen , Danke für deine Unterstützung,

**Comment by tkrebs** [comment]
... ? Dann macht sie doch genau das, was sie soll, nämlich keine Buchungen weiter als 7 Tage im Voraus zu erlauben. Willst du mehr erlauben, setzt du die Einstellung hoch.

**Comment by mumulusul** [comment]
das ist ok, aber was mich stört sind diese Zeilen , kann man die unterdrücken ??
#0 /var/www/vhosts//module/Square/src/Square/Service/SquareValidator.php(237): Square\Service\SquareValidator->isValid(Object(DateTime), Object(DateTime), Object(DateTime), Object(DateTime), Object(Square\Entity\Square))
#1 /var/www/vhosts//module/Square/src/Square/Controller/SquareController.php(23): Square\Service\SquareValidator->isBookable('2018-03-29', NULL, '19:00', '20:00', '3')
#2 /var/www/vhosts/./vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php(82): Square\Controller\SquareController->indexAction()
#3 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#4 /var/www/vhosts/./vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#5 /var/www/vhosts/./vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#6 /var/www/vhosts/./vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#7 /var/www/vhosts/./vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#8 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#9 /var/www/vhosts/-/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#10 /var/www/vhosts/./vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /var/www/vhosts/./vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /var/www/vhosts/./public/index.php(73): Zend\Mvc\Application->run()
#13 {main}

**Comment by tkrebs** [comment]
Das liegt daran, dass das System im "Debug"-Modus ist.

Das kannst du in der init.php umstellen:

https://github.com/tkrebs/ep3-bs/blob/master/config/init.php.dist

Bei älteren Versionen war die Einstellung in der application.php zu finden:

https://github.com/tkrebs/ep3-bs/blob/master/config/application.php
