### ISSUE TITLE
DB-Tabelle bs_options ?

### ISSUE THREAD

**Issue by wklingberg** [tkrebs/ep3-bs#124]
Werden die meisten Werte in der DB-Tabelle "bs_options" nur beim Einrichten des Systems geschrieben, aber  bei Änderung über Einstellungen -> "Namen und Texte" nicht mehr aktualisiert?

**Comment by tkrebs** [comment]
Die Texte sollten beim Speichern unter "Namen und Texte" ganz normal in die Datenbank geschrieben werden.

**Comment by wklingberg** [comment]
Ändere ich die "Tage im Kalender" beim Verhalten wird es in die DB geschrieben.
Ändere ich die "Bezeichnung Ihrer Plätze" bei Namen und Text wird es nicht in die DB geschrieben, aber am Frontend geändert angezeigt.

**Comment by tkrebs** [comment]
Wenn die Änderungen im Frontend angezeigt werden, müssten die Daten auch in der Datenbank stehen, da sie ausschließlich daraus gelesen werden.

**Comment by wklingberg** [comment]
Wie meistens: Das Problem sitzt vor dem Bildschirm.
In meiner phpMyAdmin-Oberfläche werden standardmäßig nur die ersten 25 Felder angezeigt. Deshalb habe ich nicht erkannt, dass die meisten Felder der Tabelle bei Änderungen zweimal vorhanden sind, einmal mit locale = NULL und einmal mit local de-DE.
