### ISSUE TITLE
IFrame

### ISSUE THREAD

**Issue by weicky-xtal** [tkrebs/ep3-bs#125]
Hallo,
sind Probleme bekannt, wenn man das Buchungssystem per IFrame einbinden möchte?

Wenn ich die Seite in WP mit 
<iframe style="border: 0px #FFFFFF none;" src="http://......../public/?squares=1,2,3" name="Tennis" width="640" height="480" frameborder="0" marginwidth="0px" marginheight="0px" scrolling="auto" align="aus"><span style="display: inline-block; width: 0px; overflow: hidden; line-height: 0;" data-mce-type="bookmark" class="mce_SELRES_start">﻿</span></iframe>

Wird nur eine leere Seite angezeigt.

Nette Grüße
Uwe

**Comment by tkrebs** [comment]
Sorry, dass das damals niemand beantwortet hat. Ich schließe das Thema nun beschämt.
