### ISSUE TITLE
/user Verzeichnis fehlt

### ISSUE THREAD

**Issue by akanneng** [tkrebs/ep3-bs#126]
Beim einloggen oder registrieren bekomme ich eine Fehlermeldung, dass das /user Verzeichnis fehlt:
The requested URL /user/registration was not found on this server.
The requested URL /user/login was not found on this server.

**Comment by weicky-xtal** [comment]
Hallo,
schon mal per FTP drauf gewesen und geschaut, ob dem auch so ist?
Falls ja, einfach nochmal hoch laden!

**Comment by akanneng** [comment]
Es ist kein user Verzeichnis vorhanden. Habe das installer Paket entpackt. Dort ist es wohl nicht enthalten?

**Comment by weicky-xtal** [comment]
Hallo,
Du hast Recht ist nicht vorhanden, wird wohl erst später angelegt. Bist Du die instalaltiion wie unter http://bs.hbsys.de/documentation/de/installation/einrichtung#docs beschrieben durchgegangen?

**Comment by akanneng** [comment]
ja habe ich ganz genau so gemacht. Sogar mehrmals :-(

**Comment by akanneng** [comment]
Ich habe es nun auch mittels git Installation probiert, dort fehlt auch das user Verzeichnis

**Comment by tkrebs** [comment]
Dein Problem wurde samt Lösungsansätzen hier schon mal besprochen:

#15

**Comment by tkrebs** [comment]
Dieses Ticket behandelt das Thema ebenfalls und könnte auch interessant sein:

#12

**Comment by akanneng** [comment]
#12 hat mir geholfen.
Nicht nur "AllowOverride FileInfo" hinzufügen sondern auch "Options FollowSymLinks"

Item kann geschlossen werden.
Vielen Dank für den schnellen Support.
