### ISSUE TITLE
Text nach Registrierung

### ISSUE THREAD

**Issue by wklingberg** [tkrebs/ep3-bs#128]
Nach einer Registrierung wird aktuell der Text "Allerdings ist Ihr Benutzerkonto noch nicht freigeschaltet.
Dies geschieht nach einer kurzen manuellen Prüfung Ihrer Daten. Bitte haben Sie etwas Geduld." ausgegeben. Wo könnte der Text angepasst werden?

**Comment by chrismeitzler** [comment]
Hi!
Ich würde einfach die deutsche Übersetzung in den Standardtexten ändern. Unter /data/res/i18n/de-DE und dort in der user.php. Dort kannst du auch den Text von dem "Passwort ändern"-Button ändern. Ich hoffe, ich konnte helfen.

Gruß

**Comment by wklingberg** [comment]
Vielen Dank für die Fundstelle!
