### ISSUE TITLE
Ansicht ändern

### ISSUE THREAD

**Issue by chrismeitzler** [tkrebs/ep3-bs#129]
Hallo,

kann man die Kalenderansicht irgendwie auf Monatsübersicht ändern? Sodass man gleich sehen kann, wann welcher Raum belegt ist?

Gruß

**Comment by tkrebs** [comment]
Hallo, prinzipiell eine gute Idee, eine solche Ansicht ist aber im Moment leider nicht vorhanden.

**Comment by chrismeitzler** [comment]
Hallo,

schade. Ich würde das Buchungssystem nämlich gerne als Online-Trauungskalender auf unserer Homepage einbinden (trauung.schulen-borchen.de). Die Leute sollen sehen, wann unser Trauzimmer noch frei ist und entsprechend eine Mail an unsere Standesbeamtin mit einer Terminanfrage senden. Dazu wäre eine Monatsübersicht halt etwas übersichtlicher. 

Trotzdem vielen Dank für die Antwort und ein dickes Lob an den Entwickler. Das System habe ich jetzt schon mehrfach eingesetzt, um z.B. unsere Sporthallen zu verwalten.
