### ISSUE TITLE
Namen im Kalender anzeigen

### ISSUE THREAD

**Issue by Michele1983** [tkrebs/ep3-bs#13]
Hallo,

wir würden das System gerne für unsere Tennisanlage nutzen.
Bisher habe ich nur gesehen, dass die Buchungen sehr allgemein angezeigt werden.
Schön wäre es, wenn die Mitglieder in der Kalenderansicht auch sehen würden welche Personen die Plätze belegen, damit man sich evtl. auch zu einem Doppel verabreden könnte. 
Ist das bereits möglich? Oder einstellbar.

Wir fänden es super, wenn man einstellen könnte ob es personenbezogene Datenanzeigen im Kalender gibt oder nur allgemeingehaltene (Abo usw.)

Für eine Rückmeldung über Machbarkeit oder bereits existierende Möglichkeiten wären wir sehr dankbar.

Beste Grüße

**Comment by tkrebs** [comment]
In den Platzeinstellungen gibt es eine Option namens "Öffentliche Namen", die genau das ermöglicht.

**Comment by Michele1983** [comment]
Ah super!!!! Danke für die Hilfe!!! Hab ich leider übersehen...

schönes Wochenende!
