### ISSUE TITLE
Oops - Diese Seite gibt es (noch) nicht  ---- bei Abbruch "Buchung stornieren"

### ISSUE THREAD

**Issue by wklingberg** [tkrebs/ep3-bs#133]
Bricht man eine Stornierung über den Weg "Meine Buchungen" -> "Buchung stornieren" -> "Nein, zurück" ab, kommt ein Fenster mit "Oops ... da ist wohl etwas schief gelaufen  Diese Seite gibt es (noch) nicht".

Klickt man im Kalender auf die gebuchte Stunde, dann auf "Buchung stornieren" -> "Nein, zurück" tritt dieser Effekt nicht auf.

**Comment by tkrebs** [comment]
Ist in der neuen [Version 1.6.3](https://github.com/tkrebs/ep3-bs/tree/develop) behoben.
