### ISSUE TITLE
Oops ... da ist wohl etwas schief gelaufen Dieses Datum liegt noch zu weit in der Ferne

### ISSUE THREAD

**Issue by wklingberg** [tkrebs/ep3-bs#134]
Versucht man eine Buchung, die weiter in der Zukunft liegt, als bei "Plätze" -> "Buchung im Voraus" festgelegt, dann bekommt man obige Meldung.
Es wäre gut, wenn diese Zeiten ähnlich derer, die vorbei sind, gar nicht zur Buchung aktivieren könnte.

**Comment by tkrebs** [comment]
Ist in der neuen [Version 1.6.3](https://github.com/tkrebs/ep3-bs/tree/develop) implementiert.
