### ISSUE TITLE
Link in Mail "Passwort vergessen?" passt nicht

### ISSUE THREAD

**Issue by wklingberg** [tkrebs/ep3-bs#136]
In der Mail, die der Benutzer erhält, wenn er bei "Passwort vergessen" seine Mail-Adresse absendet, passt der Link nicht ganz.
Beispiel: http://www.xxx.yyy.de/ep3/ep3/public/user/password-reset?id=5&code=RzExdVJyeko%3D

In der Datenbank ist bei "service.website" der Wert "http://www.xxx.yyy.de/ep3/" erfasst, damit der Link zur Startseite in der Mail passt (siehe unten)

Viele Grüße,
Ihr XXXX Buchung Tennisplätze
http://www.xxx.yyy.de/ep3/

**Comment by tkrebs** [comment]
Ist in der neuen [Version 1.6.3](https://github.com/tkrebs/ep3-bs/tree/develop) behoben.
