### ISSUE TITLE
CSS, Font color Changes

### ISSUE THREAD

**Issue by betta1981** [tkrebs/ep3-bs#137]
css/default.css
css-client/default.css

Ich konnte die Font-Farbe /speziell Hellgrau und weiß) nicht anpassen, habe auch in der css/default.css herumgepfuscht um zu sehen ob Änderungen sichtbar werden. 

![platzreservierungen](https://user-images.githubusercontent.com/37598293/37682794-6d2355ae-2c82-11e8-85dd-9fb598a76330.png)

Danke für das tolle Projekt, das hilft uns als kleinem Club weiter!!

**Comment by tkrebs** [comment]
Über die `css-client/default.css` lassen sich grundsätzlich alle Stile anpassen. Vermutlich sind deine CSS-Selektoren nur nicht spezifisch genug.

**Comment by betta1981** [comment]
Danke, ich habe jetzt schon viel Zeit investiert um herauszufinden zu welchem font oder Bereich die Schriften in der Kopfzeile zugehörig sind. Ein Tipp wo sich die Texte die Farbattribute holen würde mir weiterhelfen. Danke.

**Comment by mjmpeace** [comment]
Leider geht es mir auch so - ich finde zwar im Google Chrome die Anweisungen beim Untersuchen, aber ich füge Änderung in die css Datei im Ordner Client-CSS ein und es passiert nix.
Ich würde es sehr begrüßen, wenn die Farbanpassungen mal vernünftig dokumentiert werden, damit man da nicht herumsuchen muss, zumal manches auch noch ganz woanders versteckt ist.
Vielleicht hat ja jemand dazu Zeit und Lust, den geschätzten Benutzern mit CSS-Kenntnissen - aber nicht genügend Durchblick in diesem "verschachtelten System" zu helfen.
Mein Ziel wäre klar definiert zu erfahren:
Wo wird die Hintergrundfarbe eingestellt. Warum ein Hintergrund-Bild und nicht einfach Farbe ?
Wo werden die Farben für die Kopfzeile eingestellt, es gibt da mehrere Bereiche, die seperat einzustellen sind. Wo werden die Farben in der Fußzeile eingestellt.
Wie gesagt wie die css Definitionen lauten, weiß ich ja, aber wohin damit, damit es funktioniert!

**Comment by mjmpeace** [comment]
@tkrebs: Es wäre sehr hilfreich, wenn Du dazu nochmal eine Antwort geben könntest.
![footer](https://user-images.githubusercontent.com/46706899/51457365-67a60200-1d51-11e9-98a6-2a7c8b93918a.JPG)
![kopf](https://user-images.githubusercontent.com/46706899/51457366-67a60200-1d51-11e9-887b-302025c915b9.JPG)
So hätte ich es gern. Im Google Chrome habe ich das mit Untersuchen so verändert.

**Comment by tkrebs** [comment]
Die über die Entwicklerwerkzeuge (von Google Chrome) angepassten CSS-Regeln können direkt in die `css-client/default.css` übernommen werden. Da diese Datei als letzte in der Reihenfolge geladen wird, gelten hierbei die Regeln der Spezifität:

https://developer.mozilla.org/de/docs/Web/CSS/Spezifit%C3%A4t

Eventuell hast du aber auch vergessen, die Seite **mitsamt Browsercache** neuzuladen (z. B. via Shift + Reload).
