### ISSUE TITLE
Nach Installation Fehlermeldung

### ISSUE THREAD

**Issue by danielbb** [tkrebs/ep3-bs#14]
Hallo zusammen,

habe das ep-3 Buchungssystem installiert. Scheint soweit auch alles funktioniert zu haben, allerdings kommt unmittelbar nach Abschluss der Installation folgende Fehlermeldung:

"Fatal error: Uncaught exception 'Zend\Session\Exception\InvalidArgumentException' with message ''session.save_path' is not a valid sessions-related ini setting.' in /users/bussi-bus/www/vendor/zendframework/zendframework/library/Zend/Session/Config/SessionConfig.php:90 Stack trace: #0 /users/bussi-bus/www/vendor/zendframework/zendframework/library/Zend/Session/Config/StandardConfig.php(236): Zend\Session\Config\SessionConfig->setStorageOption('save_path', '/users/bussi-bu...') #1 /users/bussi-bus/www/vendor/zendframework/zendframework/library/Zend/Session/Config/SessionConfig.php(158): Zend\Session\Config\StandardConfig->setSavePath('/users/bussi-bu...') #2 /users/bussi-bus/www/vendor/zendframework/zendframework/library/Zend/Session/Config/StandardConfig.php(114): Zend\Session\Config\SessionConfig->setSavePath('/users/bussi-bu...') #3 /users/bussi-bus/www/vendor/zendframework/zendframework/library/Zend/Session/Service/SessionConfigFactory.php(60): Zend\Session\Config\StandardConfig->setOptions(Array) #4 [internal function]: Zend\Session\Service\SessionConfigFactory->createService(Object(Zend\ServiceManager\ServiceManager), 'zendsessionconf...', 'Zend\\Session\\Co...') #5 /users/bussi-bus/www/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(939): call_user_func(Array, Object(Zend\ServiceManager\ServiceManager), 'zendsessionconf...', 'Zend\\Session\\Co...') #6 /users/bussi-bus/www/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(1097): Zend\ServiceManager\ServiceManager->createServiceViaCallback(Array, 'zendsessionconf...', 'Zend\\Session\\Co...') #7 /users/bussi-bus/www/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(638): Zend\ServiceManager\ServiceManager->createFromFactory('zendsessionconf...', 'Zend\\Session\\Co...') #8 /users/bussi-bus/www/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(598): Zend\ServiceManager\ServiceManager->doCreate('Zend\\Session\\Co...', 'zendsessionconf...') #9 /user in /users/bussi-bus/www/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php on line 946"

Wo liegt das Problem? Komme selbst leider nicht darauf.

Danke und Gruß

**Comment by tkrebs** [comment]
Siehe hier:

https://github.com/tkrebs/ep3-bs/issues/10

**Comment by danielbb** [comment]
Danke, hat funktioniert!
