### ISSUE TITLE
"Configuration required" obwohl vorhanden

### ISSUE THREAD

**Issue by RolandGe** [tkrebs/ep3-bs#140]
Hallo,

ich habe das System auf einen neuen Server umgezogen und die Datenbank-Zugangsdaten unter config/autoload/local.php aktualisiert. Wenn ich das System starte, erhalte ich die Meldung 

> Configuration required
Please provide database configuration prior to first usage in file config/autoload/local.php

Aber dort habe ich bereits alles richtig eingegeben. Was kann ich jetzt noch tun?

Danke vorab!

**Comment by tkrebs** [comment]
Ist der neue Datenbank-Server vielleicht unter einer anderen Adresse als "localhost" erreichbar?
Das ist eine "beliebte" Fehlerquelle.

**Comment by RolandGe** [comment]
Bedeutet diese Meldung denn, dass die Datenbank generell nicht erreichbar 
ist? Dann hätte ich einen Ansatz, wo ich weiter nachforschen muss.

Am 5. April 2018 5:27:25 nachm. schrieb Tobias Krebs 
<notifications@github.com>:

Ist der neue Datenbank-Server vielleicht unter einer anderen Adresse als 
"localhost" erreichbar?
Das ist eine "beliebte" Fehlerquelle.

**Comment by tkrebs** [comment]
Ja, die Fehlermeldung tritt nur bei Verbindungsproblemen mit der Datenbank auf.
