### ISSUE TITLE
Wrong paths / Missing maps

### ISSUE THREAD

**Issue by bugfinders1** [tkrebs/ep3-bs#141]
Hello, there seems to been an error on the last update? 
Alot of the maps are missing for an example when trying to book a time we gott ( public/square was not found on this server. ) 
There must be a wrong path in or  maps missing?

**Comment by tkrebs** [comment]
Sounds like a problem with the Apache rewrite module. Maybe your public/.htaccess file has been overwritten during the update:

https://github.com/tkrebs/ep3-bs/blob/master/public/.htaccess
