### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by schalky73** [tkrebs/ep3-bs#144]
Hallo folgendes wurde mir nach der Installation angezeigt:  
Fatal error: Uncaught exception 'Zend\Session\Exception\InvalidArgumentException' with message 'Invalid save_path provided; not writable' in /www/htdocs/w01817af/buchung.drk-bs.de/vendor/zendframework/zendframework/library/Zend/Session/Config/StandardConfig.php:232 Stack trace: #0 /www/htdocs/w01817af/buchung.drk-bs.de/vendor/zendframework/zendframework/library/Zend/Session/Config/SessionConfig.php(158): Zend\Session\Config\StandardConfig->setSavePath('/www/htdocs/w01...') #1 /www/htdocs/w01817af/buchung.drk-bs.de/vendor/zendframework/zendframework/library/Zend/Session/Config/StandardConfig.php(114): Zend\Session\Config\SessionConfig->setSavePath('/www/htdocs/w01...') #2 /www/htdocs/w01817af/buchung.drk-bs.de/vendor/zendframework/zendframework/library/Zend/Session/Service/SessionConfigFactory.php(60): Zend\Session\Config\StandardConfig->setOptions(Array) #3 [internal function]: Zend\Session\Service\SessionConfigFactory->createService(Object(Zend\ServiceManager\ServiceManager), 'zendsessionconf...', 'Zend\\Session\\Co...') in /www/htdocs/w01817af/buchung.drk-bs.de/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php on line 946

Kann mir da bitte jemand helfen, habe leider keine identischen Fehler gefunden. 
Mein System: 

PHP Version | 5.6.32
-- | --
MySQL Version | 5.6.38

**Comment by tkrebs** [comment]
Hast du die Verzeichnisberechtigungen korrekt gesetzt, wie in der Installation-Dokumentation beschrieben?

https://github.com/tkrebs/ep3-bs/blob/master/data/docs/install.txt

Also vor allem Schreibrechte auf das `data/session`-Verzeichnis gegeben?

**Comment by schalky73** [comment]
Vielen Dank - daran hat es gelegen, nach dem 3. Versuch hat es geklappt.
