### ISSUE TITLE
PHP Intl Extension required but not installed

### ISSUE THREAD

**Issue by mrlahov** [tkrebs/ep3-bs#146]
Guten Tag
Beim Versuch das Problem mit meinem Hoster zu lösen habe ich folgende Antwort vom Hoster erhalten:

Wir haben die phpinfo-Datei hochgeladen und hierbei folgende Resultate erhalten:
'--enable-intl=shared'
Das heisst, intl ist aktiviert, als shared.
Ob dies mit Ihrer Software kompatibel ist, wenden Sie sich ansonsten bitte an den entsprechenden Hersteller/Anbieter.

Leider wurde das Problem nicht behoben. Läuft die SW nicht in einer geshareten Umgebung? Was könnte die Lösung sein?

Besten Dank!

**Comment by mrlahov** [comment]
Habe die Änderung bei index.php UND setup.php vorgenommen. Geht leider immer noch nicht (selbe Fehlermeldung).

**Comment by mrlahov** [comment]
Zwischenzeitliche Meldung vom Hoster: Wir haben in Ihrem Fall das OpenSource CMS ep-3 getestet.
Nach unseren Tests ist das ep-3 Bookingsystem mit dem shared hosting Comfort nicht kompatibel.

Ende der Fahnenstange?

**Comment by tkrebs** [comment]
Ja, das Buchungssystem läuft ohne die genannte intl-Erweiterung leider nicht.

**Comment by mrlahov** [comment]
Können Sie ein kompatibles Hosting für Ihr Buchungssystem empfehlen?
Danke für Info

**Comment by tkrebs** [comment]
Die [Demo](http://demo.bs.hbsys.de/) läuft auf einem [all-inkl.com](https://all-inkl.com/)-Server.

Dort kann man auch vorab einen [Test-Account](Test-Account) beantragen.

**Comment by mrlahov** [comment]
Bin jetzt auf all-inkl.com umgestiegen. Danke für die Empfehlung.
Beim Setup erhalte ich folgende Fehlermeldung:

Fatal error: Interface 'Zend\Form\FormInterface' not found in /www/htdocs/w0181efa/infrares.ch/vendor/zendframework/zendframework/library/Zend/Form/Form.php on line 24

Danke für Hilfe

**Comment by tkrebs** [comment]
Möglicherweise wurden die Dateien nicht vollständig übertragen?

**Comment by mrlahov** [comment]
Habe alles runtergenommen, frisch runtergeladen, angepasst und hochgeladen. Jetzt Fehlermeldung:

Fatal error: Class 'Zend\I18n\View\Helper\AbstractTranslatorHelper' not found in /www/htdocs/w0181efa/infrares.ch/vendor/zendframework/zendframework/library/Zend/I18n/View/Helper/Translate.php on line 17

Ich geb's auf :-( können sie bitte für mich die installation machen? ich zahle auch gerne dafür.

**Comment by tkrebs** [comment]
Sie können mich gerne per E-Mail kontaktieren, dann schaue ich mir das mal an:

info@bs.hbsys.de
