### ISSUE TITLE
Bilder bei Veranstaltungen werden nicht angezeigt

### ISSUE THREAD

**Issue by TCRW** [tkrebs/ep3-bs#147]
Hallo,

die Bilder werden auf den Server hochgeladen und in der code- Einbettung richtig angezeigt.
Im Frontend sind Sie nicht zu sehen und im Backend bei der Bearbeitung lediglich ein Rahmen.
![grafik](https://user-images.githubusercontent.com/38580621/39081723-a354713a-4546-11e8-9d19-d08984ac3de1.png)

code sieht so aus:
![grafik](https://user-images.githubusercontent.com/38580621/39081739-e95d5548-4546-11e8-8861-6d4c1467dcde.png)

**Comment by TCRW** [comment]
Hi,

habe ich eingestellt, jedoch keine Änderung feststellbar.

Gruss

**Comment by TCRW** [comment]
PS: ich korrigiere, hatte das auf die falsche Domain angewendet - es funktioniert !!

Danke !

**Comment by mumulusul** [comment]
Super , 

Gruss Adrian



Am 25.04.18 um 18:07 schrieb TCRW
