### ISSUE TITLE
Konflikte ausfindig machen / Finding conflicts

### ISSUE THREAD

**Issue by ThoughtLife** [tkrebs/ep3-bs#148]
Hallo,

ich habe das Problem, dass einige Serientermine nun mit der Bezeichnung "Konflikt" erscheinen.
Wenn ich mir jedoch die Buchungsübersicht anschaue, gibt es keinen Konflikt mit einer anderen Buchung?
Wieso wird dann ein Konflikt angezeigt?
----------------------------------------------------
I´ve the problem, that i see some conflicts in the booking overview. But if i search for these conflicts i don`t find any double booking. Why is this conflict shown as name of the recurring appointment?

**Comment by tkrebs** [comment]
Die Bezeichnung "Konflikt" wird auch dann angezeigt, wenn die Personenzahl einer Buchung die Kapazität des Platzes überschreitet, z. B. eine Buchung von 5 Spielern auf einem Platz der nur 4 Spieler gleichzeitig erlaubt. Liegt es evtl. daran?

**Comment by ThoughtLife** [comment]
Oh, das wusste ich nicht. Perfekt, dann war es das schon! Vielen Dank!!
