### ISSUE TITLE
Anmeldung nach Wartungsmodus nicht möglich

### ISSUE THREAD

**Issue by Michele1983** [tkrebs/ep3-bs#152]
Hallo,

leider komme ich als Administrator nicht mehr auf die Anmeldeseite, um den Wartungsmodus zu deaktivieren. Gibt es da irgendeine Standardendung in der Adresse?

Danke schon mal

**Comment by Michele1983** [comment]
auch mit der Endung "/public/user/login" geht nichts

**Comment by tkrebs** [comment]
Die Login-Seite über den Pfad `[/public]/user/login` sollte eigentlich funktionieren. Falls nicht, liegt evtl. ein Fehler vor (das muss mir mal ansehen).

Notfalls kann der Wartungsmodus auch direkt über die Datenbank deaktiviert werden, indem in der `bs_options`-Tabelle der Eintrag `service.maintenance` auf 0 gesetzt wird.

**Comment by Michele1983** [comment]
In der Datenbank hat es geklappt
