### ISSUE TITLE
Änderung Aktivierungsmail - Deutsch oder Englisch?

### ISSUE THREAD

**Issue by wagpat** [tkrebs/ep3-bs#153]
Hallo,
ich möchte den Text vom Aktivierungs-Email ändern. Ich hätte in diesem File die Änderungen gemacht: module/User/src/User/Controller/AccountController.php --> Ist das richtig?

Mein Plan wäre, zu diesem Teil:
"welcome to the %s %s!\r\n\r\nThank you for your registration to our service.\r\n\r\nBefore you can completely use your new user account to book spare %s online, you have to activate it by simply clicking the following link. That's all!\r\n\r\n%s"

Den folgenden Teil noch dazuzugeben (vor '%s"'):
Just a few information regarding data protection:\r\n\r\n- Your data will be stored until you delete your user.\r\n\r\n- Your data will not be forwarded to a third party.\r\n\r\n- With clicking on the activiation link, you accept that we get in contact with you.\r\n\r\n- With clicking the activitation link, you accept that your user name will be shown public in our reservation calender.\r\n\r\n%s"

Es funktioniert, aber leider wird der Text nicht mehr in's Deutsche übersetzt.
Habt ihr eine warum das so ist? Bzw. wie ich es schaffen könnte, dass der zusätzliche Text übersetzt wird?

Danke für eure Unterstützung.

Viele Grüße,
Patrick

**Comment by tkrebs** [comment]
Wenn die englischen Texte geändert werden, muss dafür eine entsprechende (deutsche) Übersetzung hinzugefügt werden:

https://github.com/tkrebs/ep3-bs/tree/master/data/res/i18n-custom/de-DE

Analog zu den bestehenden Übersetzungsdateien:

https://github.com/tkrebs/ep3-bs/tree/master/data/res/i18n/de-DE

**Comment by tkrebs** [comment]
#169
