### ISSUE TITLE
DSGVO Konformität?

### ISSUE THREAD

**Issue by Michele1983** [tkrebs/ep3-bs#154]
Hallo,

leider bin ich eher ein Laie was das Topic angeht.
Ist es denn nicht notwendig, dass sich User, die das Buchungssystem nutzen AKTIV der Verarbeitung Ihrer Daten zustimmen müssen. Müsste so etwas nicht eigentlich im Zuge des Registrierungsformulars erfolgen?
-> müsste man so etwas dann wohl einprogrammieren?

Oder reicht es etwa aus, dass der Haken bei Datenschutz gelesen angehakt wird (vorausgesetzt in der Datenschutzerklärung ist das Prozedere im Umgang mit den Nutzerdaten beschrieben?
-> Hätte hier jemand evtl. ein gutes Beispiel für den Absatz in der Datenschutzerklärung bei Nutzung des Systems? 

Danke für eure Rückmeldungen!

**Comment by tkrebs** [comment]
Die in der neuen Version 1.6.3 eingebaute Checkbox **ist** eine aktive Zustimmung der Datenverarbeitung.
Wie soll man noch aktiver zustimmen? ;)

**Comment by mumulusul** [comment]
In Verbindung mit Ihrem Zugriff werden in unserem Server automatisch in Server-Log-Files folgende Informationen gespeichert, die der Browser an ihn übermittelt:
· Browsertyp/-version  
· verwendetes Betriebssystem  
· Referrer URL (die zuvor besuchte Seite)  
· Hostname des zugreifenden Rechners (IP-Adresse)  
· Datum und Uhrzeit des Zugriffs  Diese Daten sind für uns bestimmten Personen nicht zuordenbar. Eine Zusammenführung mit anderen Datenquellen wird nicht vorgenommen. Eine Auswertung erfolgt nur zur Fehleranalyse.  Im Buchungssystem werden bei der Registrierung personenbezogene Daten (Vor- und Nachname, Passwort, Anschrift, Telefonnummer und E-Mail- Adresse) erhoben. Diese Daten werden ohne Ihre ausdrückliche Zustimmung nicht an Dritte weitergegeben. Sie dienen nur für die
· Aktivierung des Benutzerkontos durch den Administrator  
· automatische Benachrichtigung zu Buchungen und Stornierungen, · Abrechnung von Buchungen mit Gast-Spielern  
· einfachen statistischen Auswertungen durch den
Administrator  Diese Informationen werden nur solange gespeichert, bis Ihr Benutzerkonto durch Sie oder den Administrator gelöscht wird.  Bei einer Platzbuchung werden neben den Termin- und Platzdaten auch die zusätzlich von Ihnen erfassten Daten (Anzahl der Spieler, Namen der Mitspieler, Zusatzprodukte wie Gast- Spieler) gespeichert. Diese Daten werden nur für die Abrechnung der kostenpflichtigen Produkte verwendet. Sie werden nur bis zum Saisonende gespeichert bzw. bis Ihr Benutzerkonto gelöscht wird.

**Comment by Michele1983** [comment]
Vielen lieben Dank!!!!

Am 15.06.18 um 22:32 schrieb mumulusul
