### ISSUE TITLE
 Verzeichnisse public \ users, public \ square, public \ service nicht gefunden

### ISSUE THREAD

**Issue by jfcnetto** [tkrebs/ep3-bs#156]
Hallo, ich bin ein Entwickler aus Brasilien, und ich versuche, das Projekt (ep3-bs) einzurichten, aber ich kann die public \ users, public \ square, public \ service Verzeichnisse, die ich in GitHub heruntergeladen habe, nicht finden.
Könnten Sie mir helfen, dieses Problem zu lösen, das ich aktualisieren muss?

Danke.
João Neto

**Comment by tkrebs** [comment]
Das Apache-Modul "mod_rewrite" muss serverseitig installiert und eingerichtet sein damit die Software korrekt funktionieren kann.

Dazu gab es bereits zwei größere Tickets, die bei der Einrichtung helfen sollten:
#12 und #15

**Comment by jfcnetto** [comment]
Arbeitete mit diesem .htaccess

Vielen Dank.

<IfModule mod_rewrite.c>

    RewriteEngine On

    RewriteRule ^(favicon\.ico)$ imgs-client/icons/fav.ico [L]
    RewriteRule ^(robots\.txt)$ misc/$1 [L]

    RewriteCond %{REQUEST_FILENAME} -s [OR]
    RewriteCond %{REQUEST_FILENAME} -l [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^.*$ - [NC,L]

    RewriteCond %{REQUEST_URI}::$1 ^(/.+)(.+)::\2$
    RewriteRule ^(.*) - [E=BASE:%1]
    RewriteRule ^(.*)$ %{ENV:BASE}index.php [NC,L]

</IfModule>
