### ISSUE TITLE
Benutzerverwaltung und Buchungsverwaltung funktioniert nicht

### ISSUE THREAD

**Issue by bhurni** [tkrebs/ep3-bs#157]
Funktioniert alles perfekt jedoch die Benutzer und Buchungsverwaltung funktioniert nicht. Seite sieht auch anders aus als die anderen. Keinen Hintergrund => Weiss. Habe diverse Ansätze probiert, hat jedoch nicht funktioniert. Mit dem mod_rewrite kann es auch meiner Sicht auch nicht zusammenhängen, da der Rest ja tadellos läuft.

Abfragen liefern kein Ergebnis. Kann mir da jemand helfen ? Sonst ist das ganze für mich nicht zu gebrauchen.

Danke

**Comment by tkrebs** [comment]
Eine weiße Seite klingt nach einem PHP-Fehler, der aber nicht angezeigt wird. Versuche mal die Fehleranzeige einzuschalten via

`define('EP3_BS_DEV_TAG', true);`

in der Datei `config/init.php`

Alternativ einen Blick in die Fehlerlogs des Webservers werfen.

**Comment by bhurni** [comment]
Habe den Fehler gefunden. Dieser hatte aber keinen Ursprung in der PHP Umgebung.

 

Es war ein syntax error in der Programmierung:

 

/var/www/html/ep3-bs/module/Backend/src/Backend/View/Helper/UserFilterHelp.php 

 

mb_strtolower($view->t($value)));   war mit einem # auskommentiert. Jetzt läuft alles wie es soll.

 

Trotzdem Danke für die Tipps.

 

Freundliche Grüsse

 

Von: Tobias Krebs <notifications@github.com> 
Gesendet: Donnerstag, 28. Juni 2018 01:13
An: tkrebs/ep3-bs <ep3-bs@noreply.github.com>
Cc: bhurni <Benjamin-hurni@bluewin.ch>; Author <author@noreply.github.com>
Betreff: Re: [tkrebs/ep3-bs] Benutzerverwaltung und Buchungsverwaltung funktioniert nicht (#157)

 

Eine weiße Seite klingt nach einem PHP-Fehler, der aber nicht angezeigt wird. Versuche mal die Fehleranzeige einzuschalten via

define('EP3_BS_DEV_TAG', true);

in der Datei config/init.php

Alternativ einen Blick in die Fehlerlogs des Webservers werfen.
