### ISSUE TITLE
Senden von E-Mails mit Xampp und Gmail

### ISSUE THREAD

**Issue by jfcnetto** [tkrebs/ep3-bs#158]
Hallo,

Ich versuche, einen neuen Benutzer mit E-Mail-Bestätigung zu registrieren, ich benutze Google Mail SMTP und Xampp Server, aber ich bekomme den folgenden Fehler:

Exception details
Type
Zend\ServiceManager\Exception\ServiceNotCreatedException
Mensagem
An exception was raised while creating "User\Service\MailService"; no instance returned
File
C:\xampp\htdocs\SysQuadra\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php:946

Das ist meine local.php
'mail' => array(
         'ssl'      => 'tls',
         'type' => 'smtp-tls', // or 'smtp' or 'smtp-tls'
        'address' => 'XXXXXX@gmail.com',

        'host' => 'smtp.gmail.com', // for 'smtp' type only, otherwise remove or leave as is
        'user' => 'XXXXXX@gmail.com', // for 'smtp' type only, otherwise remove or leave as is
        'pw' => '********', // for 'smtp' type only, otherwise remove or leave as is

        'port' => 587, // for 'smtp' type only, otherwise remove or leave as is
        'auth' => 'login', // for 'smtp' type only, change this to 'login' if you have problems with SMTP authentication

Danke für deine Hilfe

João Neto

**Comment by tkrebs** [comment]
Schwer zu sagen. Der Fehler entsteht vermutlich hier:

https://github.com/tkrebs/ep3-bs/blob/master/module/Base/src/Base/Service/MailTransportService.php

Ohne genauere Fehlermeldung ist das aber schwierig zu debuggen. Das muss ich mir noch mal genauer ansehen.
