### ISSUE TITLE
Nur Startseite wird angezeigt

### ISSUE THREAD

**Issue by david4321233** [tkrebs/ep3-bs#161]
Hallo,
sobald ich auf einen Link klicke und die Seite aufrufe, bekomme ich eine Fehlermeldung, dass die Seite nicht existiert (Error 404). Die Startseite kann ich ganz normal aufrufen.
Ich hoffe, ihr könnt mir helfen!
Vielen Dank

**Comment by david4321233** [comment]
Ich hab den Fehler gefunden. Die .htaccess_original Datei musste zu .htaccess umbenannt werden.

**Comment by tkrebs** [comment]
In der Tat :+1:
