### ISSUE TITLE
Language settings changes back to the "default" after any action - animgif attached

### ISSUE THREAD

**Issue by pongraczi** [tkrebs/ep3-bs#164]
After a localization, there are three icons available, as expected.  
I got the default language somehow the new language.  
That means, after changing the language to English, using the flag icon, on the next click I got the Hungarian language. So, the selection is not permanent.  
Please check it in action:  
![peek_2018-08-05 11-26](https://user-images.githubusercontent.com/5891983/43684552-820685fe-98a2-11e8-9641-c0f6861e641a.gif)

**Comment by tkrebs** [comment]
BTW: Which tool did you use for the animated gif? :)

**Comment by pongraczi** [comment]
I used Peek in linux to catch short actions: https://github.com/phw/peek

Yes, in my test environment, I added the Hungarian language, but it seems I used the locale force to hu-HU instead of choice in the local.php.

So, my **local.php** was this:  
```
'i18n' => array(
        'locale' => 'hu-HU',
        'currency' => 'HUF',
```
while the **global.php** was this:  
```
   'i18n' => array(
        'choice' => array(

            'en-US' => 'English',
            'de-DE' => 'Deutsch',
            'hu-HU' => 'Magyar',
        ),
```

Now I modified my local.php to have the choice instead of the forced value:  
```
    'i18n' => array(
        'choice' => array(
	'hu-HU' => 'Hungary',
	'en-US' => 'English',
	'de-DE' => 'Deutsch',
	),
        'currency' => 'HUF',
    ),
```

Unfortunately I am still experienced this kind of issue.  
I logout, choose the English, I got the main page in English, as expected, but when I click on a Free time to book, the popup appeared in Hungarian.

**Comment by pongraczi** [comment]
Further info:  
* browser cache deleted
* data/cache is empty
* I modified the cookie name from the default

My global.php seems like this:  
```
<?php
/**
 * Global application configuration
 *
 * Usually, you can leave this file as is
 * and do not need to worry about its contents.
 */

return array(
    'db' => array(
        'driver' => 'pdo_mysql',
        'charset' => 'UTF8',
    ),
    'cookie_config' => array(
        'cookie_name_prefix' => 'tenulhu',
    ),
    'redirect_config' => array(
        'cookie_name' => 'tenisz',
        'default_origin' => 'frontend',
    ),
    'session_config' => array(
        'name' => 'tenisz-session',
        'use_cookies' => true,
        'use_only_cookies' => true,
    ),
    'i18n' => array(
        'choice' => array(

            'en-US' => 'English',
            'de-DE' => 'Deutsch',
            'hu-HU' => 'Magyar',

        ),
    ),
);
```

Probably this settings is the problem....

**Comment by pongraczi** [comment]
the cookie seems contains the en-US
![kijeloles_757](https://user-images.githubusercontent.com/5891983/43687259-588b4608-98d2-11e8-970d-971927207644.png)

**Comment by pongraczi** [comment]
Ok, I found and proved it: it caused by the changed  cookie and session names.  
I tested it with php 7.2 and 7.0, too.  
Keep the php 7.2
