### ISSUE TITLE
Question: how to show Square info and rules?

### ISSUE THREAD

**Issue by pongraczi** [tkrebs/ep3-bs#166]
I already wrote some information about each squares, but until now I cannot see them in action.  
I mean, I have no idea, where and when these info should appear.  
Could you give me a hint, how to show them?  
I have about 18 squares if that matters....

**Comment by tkrebs** [comment]
The square info texts are displayed when clicking on a calendar cell. The rules will be displayed before booking a square.

**Comment by pongraczi** [comment]
Thanks, correct, the info is there, thanks!
