### ISSUE TITLE
Verzeichniss public/user/login ???

### ISSUE THREAD

**Issue by tickel69** [tkrebs/ep3-bs#168]
Inst. hat geklappt, aber sobald ich mich einloggen will heisst es die Seite konnte nicht gefunden werden ??
Das Verzeichniss public/user ...gibt es nicht ? Was mache ich falsch ? Danke.

**Comment by tkrebs** [comment]
Das Apache-Modul "mod_rewrite" muss serverseitig installiert und eingerichtet sein damit die Software korrekt funktionieren kann.

Dazu gab es bereits zwei größere Tickets, die bei der Einrichtung helfen sollten:
#12 und #15
