### ISSUE TITLE
Ein Platz - Verschiedene Öffnungszeiten & Preise

### ISSUE THREAD

**Issue by hirnie** [tkrebs/ep3-bs#17]
Hi ... mal angenommen, ich habe einen Platz. Dieser ist von Mo-Fr von 14.00-24.00 und von Sa-So von 10.00-24.00 geöffnet. Wie kann ich das denn im System hinterlegen ?

Und gibt es die Möglichkeit, verschiedene Preise für einen Timeslot aufzurufen ? Z.B.: 
Normaler Preis: 12€
Preis mit Kundenkarte: 10€

Vielen Dank und Daumen hoch für das Tool.

**Comment by tkrebs** [comment]
Verschiedene Öffnungszeiten für denselben Platz sind leider (technisch) derzeit nicht möglich, auch wenn der Wunsch schon öfter geäußert wurde.

Auch das Preissystem erlaubt leider nur einen gültigen Preis für den gleichen Zeitblock.
