### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by ElectricPixelfarm** [tkrebs/ep3-bs#171]
Hallo an die Gemeinde ;)
Habe das ep-3 BS installiert, das Setup gestartet und entsprechend bearbeitet und dann nach der Bestätigung folgende Feflermeldung bekommen:

Fatal error: Uncaught exception 'Zend\ServiceManager\Exception\ServiceNotCreatedException' with message 'While attempting to create zendsessionconfigconfiginterface(alias: Zend\Session\Config\ConfigInterface) an invalid factory was registered for this instance type.' in /kunden/225475_40476/webseiten/ep3_eisstockschiessen/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php:1101 Stack trace: #0 /kunden/225475_40476/webseiten/ep3_eisstockschiessen/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(638): Zend\ServiceManager\ServiceManager->createFromFactory('zendsessionconf...', 'Zend\\Session\\Co...') #1 /kunden/225475_40476/webseiten/ep3_eisstockschiessen/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(598): Zend\ServiceManager\ServiceManager->doCreate('Zend\\Session\\Co...', 'zendsessionconf...') #2 /kunden/225475_40476/webseiten/ep3_eisstockschiessen/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager. in /kunden/225475_40476/webseiten/ep3_eisstockschiessen/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php on line 946

Ich hatte es Freitag schon einmal installiert und da lief es bei den gleichen Einstellungen. Woran kann das liegen? VG & Danke – Andy.

**Comment by tkrebs** [comment]
Versuch mal den Cache-Ordner zu löschen (data/cache/).

Falls das nicht hilft, könnte etwas mit der Konfiguration im [autoload-Ordner](https://github.com/tkrebs/ep3-bs/tree/master/config/autoload) nicht in Ordnung sein. Vergleiche die Dateien mal mit den Originaldateien, insbesondere mit dem Abschnitt 'session_config'.

**Comment by ElectricPixelfarm** [comment]
Danke für die schnelle Antwort. Leider lag es nicht am Cache-Ordner, bzw der session:config. Hab dann eine komplette Neuinstallation gemacht. Nun bekomme ich beim ersten Aufruf die Fehlermeldung:

Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /kunden/225475_40476/webseiten/ep3_eisstockschiessen/public/index.php on line 53

Parse error: syntax error, unexpected T_STRING in /kunden/225475_40476/webseiten/ep3_eisstockschiessen/public/index.php on line 53

**Comment by tkrebs** [comment]
Welche PHP-Version hast du im Einsatz?

Im Zweifelsfall in der ersten Zeile der public/index.php einmal folgendes einfügen und prüfen:

```php
exit(PHP_VERSION);

**Comment by ElectricPixelfarm** [comment]
Ich habe nochmal alles gelöscht (Verzeichnis, Datenbank, ..) und neu installiert / angelegt. Läuft. Weiss der Teufel, woran es lag. Habe hier doch mal etwas über einen Apache-Dino gelesen ;) Danke für die Hilfe.

**Comment by tkrebs** [comment]
Hauptsache es läuft wieder :)
