### ISSUE TITLE
404 Error /public/user/login was not found on this server.

### ISSUE THREAD

**Issue by overtoip** [tkrebs/ep3-bs#172]
also on registration
installed version 1.6.3 
tried both the ZIP and git clone
there is no /public/user directory in rither

**Comment by tkrebs** [comment]
You need to enable the Apache module "mod_rewrite" so that virtual directories like "user" will work.

**Comment by overtoip** [comment]
mod_rewrite is enabled.
I disabled it, restarted apache, re-enabled, restarted apache
