### ISSUE TITLE
Keine E-Mail Benachrichtigung bei Stornierungen

### ISSUE THREAD

**Issue by DanielM1991** [tkrebs/ep3-bs#174]
Hallo zusammen,

ist es normal, dass Kunden bei einer Stornierung/Löschung der Reservierung keine E-Mail erhalten? 

Danke schon mal und Grüße
Daniel M.

**Comment by tkrebs** [comment]
Wenn die Buchung von einem Mitarbeiter oder Admin storniert/gelöscht wird, gibt es keine automatische E-Mail. Der Grundgedanke hier ist: Eine Stornierung seitens des Betreibers hat immer einen besonderen Grund, welcher, idealerweise mit einem Alternativangebot, individuell kommuniziert werden sollte. Daher gibt es keine automatische Standard-Benachrichtigung. Geplant aber derzeit nicht vorhanden ist eine Eingabefeld für eben jene individuelle Nachricht an den Kunden.
