### ISSUE TITLE
Domainname in E-Mail Bestätigung

### ISSUE THREAD

**Issue by DanielM1991** [tkrebs/ep3-bs#177]
Hallo zusammen,

in der Reservierungsbestätigung wird stets eine Domain mit angegeben. Da ich die Domain gewechselt habe, wird dort immer noch eine alte Domain mit versendet.

Wie kann ich diese ändern? Wo ich den Text individuell anpassen kann, weiß ich. Allerdings finde ich nirgends die Angabe der Domain. 

Danke und Grüße
Daniel M.

**Comment by tkrebs** [comment]
Die neue Domain kann im Backend unter Einstellungen > Namen und Texte hinterlegt werden.

**Comment by DanielM1991** [comment]
Danke für die Flotte Antwort! Dort ist schon von Anfang an die (neue) Domain hinterlegt gewesen. Es wurde nur zum Test die alte Domain verwendet. Das Tool läuft nun auf der neuen Domain. Trotzdem erscheint in der Bestätigungsmail noch die alte Domain.

**Comment by DanielM1991** [comment]
Fehler gefunden! 
In der Datenbankdatei "bs_options" scheint die Domain hinterlegt zu werden, die bei der Einrichtung verwendet wurde. Eintrag manuell angepasst, jetzt funktioniert's.
