### ISSUE TITLE
Installation auf Shared Hosting mit CPanel

### ISSUE THREAD

**Issue by saschagithub** [tkrebs/ep3-bs#18]
Ist es möglich ep3-bs auf einen Shared Hosting mit CPanel Zugang zu installieren?
Falls ja, was muss man dabei beachten?

**Comment by tkrebs** [comment]
Grundsätzlich kann es auf jedem Webserver installiert werden, der die Voraussetzungen erfüllt:

http://bs.hbsys.de/documentation/de/installation/voraussetzungen#docs

Dazu gehören in der Regel auch die meisten Shared Hosting Umgebungen.
