### ISSUE TITLE
Benutzer Verwaltung funktioniert nicht

### ISSUE THREAD

**Issue by bradan86** [tkrebs/ep3-bs#180]
Hallo,

Ich habe mir heute auch mal das ep3-bs aufgesetzt. Leider habe ich ein kleines Problem:

Ich möchte den Standardbenutzern erlauben Notizen zu ihren Buchungen hinzuzufügen. Im Optimalfall sollen die Rechte automatisch bei der Registrierung mitgegeben werden. 
Ich würde die Rechteverwaltung auch manuell vornehmen, jedoch funktioniert die Benutzerverwaltung nicht. Ich komme zwar in eine Suchmaske, finde allerdings keine Benutzer. Weder über eine Nummer oder einen Vor-/Nachnamen. Das Layout der Suchmaske bezüglich Schriftart etc. passt auch nicht zum Rest des Programms. Somit kann ich leider keine Benutzerrechte verwalten. Das Gleiche gilt auch für die Suchfunktion nach den Buchungen.

Gibt es eine config-Datei in der man die Benutzerrechte verändern kann?

Gruß,
Daniel

**Comment by tkrebs** [comment]
Prinzipiell können die Berechtigungen pro Benutzer auch direkt in der Datenbank vorgenommen werden. Die möglichen Bezeichnungen finden sich hier:

https://github.com/tkrebs/ep3-bs/blob/master/data/docs/privileges.txt

Allerdings wäre es vermutlich einfacher, die Benutzerverwaltung ans Laufen zu bekommen. Werden denn auch keine Benutzer gefunden, wenn bspw. folgende Suche (inklusive der Klammern) verwendet wird:

(erstellt > 01.01.2018)

**Comment by tkrebs** [comment]
Ja, da stimmt etwas nicht.

Bekommst du eine Fehlermeldung angezeigt, wenn du in der Datei

`config/init.php`

das Debug-Tag setzt:

```php
define('EP3_BS_DEV_TAG', true);

**Comment by bradan86** [comment]
Ich habe mir die init.php angeschaut. Das Debug-Tag war dort bereits gesetzt ohne dass ich die Datei einmal angefasst hätte.:
![2018-10-18 07_44_21-buchungssystem auf sv-esxi-12 hwk-pfalz de](https://user-images.githubusercontent.com/44196714/47133671-054ce980-d2aa-11e8-908c-9883546dbc78.jpg)

Ansonsten geschieht bei einem Klick auf "Suche" oder "Erweiterte Suche" nichts. Auch keine Fehlermeldung.

**Comment by tkrebs** [comment]
Kannst du auf der Benutzerverwaltungseite einmal die Dev-Tools des Browsers öffnen (F12 drücken) und dort im Tab "Netzwerkanalyse" beim Neuladen der Seite nachsehen, ob Daten nicht richtig geladen werden (erkennbar an roten statt grünen Einträgen)?

**Comment by bradan86** [comment]
Die Dev-Tools geben Status 200 in grün zurück. Für mich sind keine Fehler ersichtlich.

![na-ep3](https://user-images.githubusercontent.com/44196714/47158306-a7d98c80-d2eb-11e8-8792-b4504a65eb72.jpg)

**Comment by tkrebs** [comment]
Zu den Fragen:

1: Der Status für normale Benutzer ist "enabled". Das Notizfeld können sie allerdings standardmäßig nicht benutzen.

2: Das ist technisch zwar nicht allzu schwierig umsetzbar, aber derzeit nicht vorgesehen.
