### ISSUE TITLE
md5sum auf Webseite falsch

### ISSUE THREAD

**Issue by botic** [tkrebs/ep3-bs#181]
Laut Webseite: `30500c53ef479b386b007aaeb08ee2cd`
Bei mir:

```
md5sum ep3-bs-package-1.6.3.zip
5722fed815a18db9541267c97ab13ec4  ep3-bs-package-1.6.3.zip
```

**Comment by tkrebs** [comment]
Vielen Dank für den Hinweis, bei der 1.6.3 wurde versehentlich der Hash des Dateinamens statt der Datei ausgegeben. Ist korrigiert. :thumbsup:
