### ISSUE TITLE
Labelbezeichnung bei der Reservierung ändern

### ISSUE THREAD

**Issue by Dallwatscher** [tkrebs/ep3-bs#182]
Hallo,
möchte das Buchungssystem für eine Fahrzeugreservierung /-buchung innerhalb der Firma verwenden und hat auch bis jetzt alles toll funktioniert - vielen Dank ;-)
Habe unter Einstellungen/Namen und Texte bei "Bezeichnung der Plätze" entsprechend "Fahrzeug/e" und bei "Bezeichnung der Spieler" "Fahrer" angegeben.
Jedoch erscheint bei der Reservierung der Fahrzeuge bei dessen Auswahl als Label immernoch "Platz" und weiter unten "Anahl Spieler"!
![ep-3-platz](https://user-images.githubusercontent.com/44529138/47606288-2502b100-da12-11e8-9ee3-57eeeb528793.PNG)

Wo kann man dies Anpassen - habe schon ein wenig gesucht, finde aber nicht die richtige Datei.
Gruß dallwatscher

**Comment by Dallwatscher** [comment]
Vielen Dank für die Rückmeldung, hat super funktioniert.
Hab leider noch ein Problem:
Wenn ich eine Buchung vornehme, bekomme ich die folgende Fehlermeldung:
![image](https://user-images.githubusercontent.com/44529138/47800536-c8163c00-dd2c-11e8-8ebf-7120d858e9ac.png)
Können Sie mir da weiterhelfen? 
Gruß dallwatscher

**Comment by azich01** [comment]
Es sieht so aus als wenn die Mail-Kommunikation des Servers noch nicht ( oder falsch )eingerichtet ist.
