### ISSUE TITLE
Formatierung von Bestätigungs-E-Mail

### ISSUE THREAD

**Issue by DanielM1991** [tkrebs/ep3-bs#183]
Hallo zusammen,

wie ist es möglich (ist es überhaupt möglich?) die Bestätigungs-E-Mail zu formatieren? 
Derzeit steht alles in einer Zeile.

Ich würde gerne die Uhrzeit und das Datum der Buchung gesondert hervorheben und einen Link zur Stornierung der Reservierung mit schicken. 

Danke und Grüße
Daniel M.

**Comment by tkrebs** [comment]
Es ist möglich, aber derzeit etwas umständlich und nur direkt im Code, in dieser Datei:

https://github.com/tkrebs/ep3-bs/blob/master/module/Booking/src/Booking/Service/Listener/NotificationListener.php

**Comment by tkrebs** [comment]
#169
