### ISSUE TITLE
Wie einen Cookiehinweis realisieren?

### ISSUE THREAD

**Issue by juergen2912** [tkrebs/ep3-bs#185]
Hallo, meine 'Hauptseite' läuft unter Joomla, da gab es eine App.......
aber wie kann ich einen Cookiehinweis für ep-3 als FAST-Unwissender realisieren?
Schon jetzt mal Vielen Dank!

**Comment by tkrebs** [comment]
Das Buchungssystem setzt bis zur Registrierung/Anmeldung keine Cookies, die personenbezogene Daten enthalten oder erheben. Eine ordnungsgemäße Datenschutzerklärung sollte also ausreichen.

**Comment by juergen2912** [comment]
Besser spät als nie Vielen dank für die Antwort!

**Comment by mjmpeace** [comment]
Das stimmt so nur halb und ist auch wohl nicht mehr ganz die aktuelle DSGVO - Antwort. Ohne Cookies ist eine Anmeldung nicht möglich und ohne Anmeldung schreibt das System mindestens 2 Cookies. Nach den aktuellen Empfehlungen müsste es also auch ein Cookie-Banner für das Buchungssystem geben. Lässt sich das einbauen und wenn ja wie?
