### ISSUE TITLE
Uhrzeit oben UND unten anzeigen lassen

### ISSUE THREAD

**Issue by DanielM1991** [tkrebs/ep3-bs#188]

**Comment by DanielM1991** [comment]
Besteht die Möglichkeit bei der Ansicht: Plätze als Zeile und Uhrzeiten in der Spalte?

**Comment by tkrebs** [comment]
Das wäre dann analog zu https://github.com/tkrebs/ep3-bs/issues/222#issuecomment-502051929 die folgende Datei:

https://github.com/tkrebs/ep3-bs/blob/master/module/Calendar/view/calendar/calendar/index.phtml#L13

Dort ist ab Zeile 13 die Logik, ob der "Landscape Mode" oder "Portrait Mode" verwendet werden soll, was zur Vertauschung von Platzbezeichnungen und Uhrzeiten führt.
