### ISSUE TITLE
Uhrzeit oben UND unten anzeigen lassen

### ISSUE THREAD

**Issue by DanielM1991** [tkrebs/ep3-bs#189]
Hallo zusammen, 

gibt es die Möglichkeit, die Uhrzeit auch unten anzeigen zu lassen? 

Ich habe das Design so angpasst, dass die Plätze in der Spalte links stehen und die Uhrzeiten oben. Allerdings habe ich viele Plätze angelegt, sodass wenn man einen der letzten Plätze buchen möchte, die Uhrzeit von oben nicht mehr sieht. 

Danke und Grüße

**Comment by tkrebs** [comment]
#188
