### ISSUE TITLE
Anzeige Buchungen

### ISSUE THREAD

**Issue by jet2future** [tkrebs/ep3-bs#19]
Besteht die Möglichkeit das nur eingeloggte User die Namen der Buchungen sehen?

Aus Datenschutz würde ich das gerne nicht öffentlich anzeigen 

Gruß

**Comment by tkrebs** [comment]
Ich habe diese Möglichkeit soeben im Entwicklungszweig eingebaut:

https://github.com/tkrebs/ep3-bs/tree/develop

**Comment by jet2future** [comment]
Hi,

ist die Funktion schon wieder draussen? bin erst heute zum Download gekommen..
bzw wie kann ich das aktivieren und deaktivieren

Gruß
