### ISSUE TITLE
ep-3 Buchungssystem  mit PHP 7.2  ?

### ISSUE THREAD

**Issue by ssswisss** [tkrebs/ep3-bs#193]
Hallo
Ich benutze ep-3 Buchungsystem  mit PHP 7.0 und 7.1
aber PHP 7.0 und 7.1 sind noch bis Ende März 2019 verfügbar.

dann es wird version PHP 7.2 und 
ep-3 Buchungsystem läuft nicht  mit Version 7.2 und bekomme folgende fehler 

:::::::::::::::::::::::::::::::::::::::::::::::::::::::::
Fatal error: Declaration of Zend\Session\AbstractContainer::offsetGet($key) must be compatible with & Zend\Stdlib\ArrayObject::offsetGet($key) in /home/stonear/www/MEINDOMAIN/vendor/zendframework/zendframework/library/Zend/Session/AbstractContainer.php on line 0
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

WAS MUSS ICH JETZ??  GIBT ES UPDATE PATCH ODER WIE??

DANKE FÜR IHRE HILFE

**Comment by tkrebs** [comment]
Die neueste Version des Buchungssystems ist mit PHP 7.2 kompatibel:

https://bs.hbsys.de/download
