### ISSUE TITLE
Kopfzeile Striche

### ISSUE THREAD

**Issue by mjmpeace** [tkrebs/ep3-bs#195]
In der Kopzeile sind merkwürdige Striche - wie bekomme ich die weg.
![tc](https://user-images.githubusercontent.com/46706899/51256038-beec5100-19a4-11e9-8b2c-a6001a88b2d6.JPG)

**Comment by mjmpeace** [comment]
Die Striche sind gelb umrandet zur besseren Sichtbarkeit.

**Comment by tkrebs** [comment]
Die Striche können, genau wie schon der rote Hintergrund, via CSS geändert oder ausgeblendet werden - moderate CSS-Kenntnisse vorausgesetzt.

**Comment by mjmpeace** [comment]
Auch in der Default.css ? Den Punkt konnte ich bisher nicht "ausmachen, wo diese Striche  gesetzt sind.
Den Hintergrund habe ich Background Datei ausgetauscht. Ich hätte das baer gern per css gesetzt - auch in der Default.css setzen den Hintergrund? Vermutlich? Einiges habe ich schon mit css hinbekommen. Ich übe an der einen oder anderen Stelle noch.

**Comment by tkrebs** [comment]
Genau, über die Datei `public/css-client/default.css` kann prinzipiell das gesamte Aussehen des Buchungssystems angepasst werden. Um die für die Striche benötigten CSS-Regeln zu identifizieren würde ich die Entwicklerwerkzeuge des Webbrowsers verwenden (meist via F12).

**Comment by mjmpeace** [comment]
Der senkrechte Strich kommt offensichtlich vom Element "Seperator" - diesen bekomme ich aber nicht weg bzw. den Strich nicht :-(
Der Unterstrich unter dem Wort ep-3 Buchungssystem scheint vom Branding zu kommen, was ich nicht lokalisieren kann, wie ich den Unterstrich weg bekomme. Es sieht für mich so aus, das es im "Branding" steckt. Wo das gesetzt wird, konnte ich bis jetzt nicht finden. Ich möchte das "Branding ja nicht beseitigen, aber die Unterstreichung ist altmodisch.

**Comment by tkrebs** [comment]
Okay, hänge den folgenden CSS-Code an deine default.css an:

```css
#branding a:link, #branding a:visited {
    border-bottom: none;
}

#topbar-separator {
    display: none;
}

**Comment by mjmpeace** [comment]
Es muss in beiden  CSS-Dateien eingefügt werden.  default und default.min.css

**Comment by tkrebs** [comment]
Siehe https://github.com/tkrebs/ep3-bs/issues/197#issuecomment-455267498
