### ISSUE TITLE
Einrichtungsprobleme

### ISSUE THREAD

**Issue by thomasziener** [tkrebs/ep3-bs#196]
Hallo, ich habe alles aufgesetzt und installiert. Ich geben meine Domain ein und lege die Datenbank an. Wenn ich jetzt die ganzen gefragten Informationen ausfülle wie Beschreibung etc. (Step 2) und dann auf speichern klicke, passiert nichts sondern ich lade eine Datei herunter die records heißt und folgendes Beinhaltet:

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
</body></html>

Wo habe ich einen Fehler gemacht?

Ich hatte die Seite schon mal bei einem anderen Hostinganbieter am Laufen. Ich hatte dort den selben Datensatz verwendet!

Vielen Dank für die Hilfe!
Gruß
Thomas

**Comment by tkrebs** [comment]
"503 Service Unavailable" kann zahlreiche Gründe haben. In den Log-Daten des Apache-Webservers sollte eine genauere Fehlermeldung stehen.

**Comment by thomasziener** [comment]
Danke für den Tip mit den Logs... Manchmal sieht man den Wald vor lauter Bäumen nicht mehr ;-)
Irgendein Spamfilter war in den Servereinstellungen von STRATO aktiv und mit Deaktivierung funktioniert wieder alles bestens. Vielen Dank nochmal

**Comment by tkrebs** [comment]
Sehr gut! Danke auch für den Hinweis mit STRATO, falls noch mal jemand das gleiche Problem hat.
