### ISSUE TITLE
Vergangene Zeitblöcke nicht als Vorbei anzeigen, sondern immer die Buchungen

### ISSUE THREAD

**Issue by mjmpeace** [tkrebs/ep3-bs#197]
Statt "Vorbei" weiterhin die Buchung anzeigen - aber die übrige Funktionalität bei Versuch dort zu buchen, auf Fehler stossen, soll bleiben. Geht das?

**Comment by tkrebs** [comment]
Angemeldete Admins und Mitarbeiter mit den entsprechenden Berechtigungen können auch die vergangenen Buchungen im Kalender sehen.

Die Anforderung, die Vergangenheit auch für normale Besucher oder Kunden offen zu legen, gab es bisher noch nicht. Wie sähe denn der konkrete Anwendungsfall aus?

**Comment by mjmpeace** [comment]
Ich habe das System neu aufgesetzt und wir sind erst in der "Findungsphase". Das ich Benutzern solche Rechte einräumen kann, die z.B. die Abrechnung erledigen, wusste ich noch nicht.
Sieht man denn als Benutzer weiterhin die eigenen Buchungen in der Vergangenheit?
Ich könnte mir vorstellen, dass diese Anforderung kommt.
Ablösung der Papierform der Stundenbuchung per Aushang in der Halle, wo man sich eintragen kann, ist das Ziel für uns. Ziel ist eben dabei auch, dass man nicht mehr zur Halle fahren muss, um zu buchen. Das System erledigt das denke ich prima. Wer kein Internet hat ruft eben jemand an, der Buchen kann. Geschäftsstelle oder bekannt gegebene Mitglieder dafür im Tennisverein. Ich bin sehr dankbar, dieses System gefunden zu haben. Denn die kostenpflichtigen Systeme sind einfach für unseren kleinen Verein mit nur zwei Hallenplätzen überdimensioniert und zu teuer.

**Comment by tkrebs** [comment]
Ja, angemeldete Benutzer haben eine (vom Kalender separate) Historie ihrer Buchungen zur Verfügung.

**Comment by mjmpeace** [comment]
Danke der Hinweis hat sehr geholfen, da kann ich sehr gut einstellen, wer was machen darf. Ich denke, das hilft weiter für die Präsentation im Vorstand.

**Comment by mjmpeace** [comment]
Ich hatte zu dem Kopf noch eine Frage gestellt seperat. Vielleicht kannst du dir das nochmal ansehen, wo ich den senkrechten Strich bzw. den leeren Block nach dem Logo und der Vereinsbezeichnung weg bekomme und die Unterstreichung unter dem Branding.

**Comment by mjmpeace** [comment]
Gefunden - default.min.css - die Datei ist - warum auch immer das so ist - ohne Zeilenumbrüche. Daher schwer zu finden.

**Comment by tkrebs** [comment]
Das funktioniert zwar auch, richtig wäre aber die Datei

`css-client/default.css`
