### ISSUE TITLE
Bestätigungs Email wird nicht gesendet

### ISSUE THREAD

**Issue by Chris1405** [tkrebs/ep3-bs#200]
Hallo zusammen,
Das System funktioniert perfekt 
Ich habe ein Problem mit der Registrierung Bestätigungsmail kommt nicht an oder wird nicht gesendet.

Die 2 Frage Die ich habe, könnte man die Anmeldung modifizieren 
Ich benötige 
Vorname
Namen
Alter
Klasse   
Disziplin
Verein

Gruß
Chris

**Comment by tkrebs** [comment]
Der in der config/autoload/local.php voreingestellte E-Mail-Typ "sendmail" funktioniert nicht auf allen Systemen, insbesondere nicht in einer lokalen Umgebung. Die zuverlässigere Möglichkeit ist hier "smtp" mit einem richtigen E-Mail-Konto.

Zur zweiten Frage: Das geht derzeit nur direkt über den Code, da die Felder fest einprogrammiert sind. Erst die im 2. Quartal 2019 kommende Version wird dynamische Felder unterstützen.
