### ISSUE TITLE
Beim Starten der Seite "Database required Please setup the database prior to first usage  Use Setup Tool" 

### ISSUE THREAD

**Issue by sitze89** [tkrebs/ep3-bs#201]
Hallo zusammen, 
ich hoffe mir kann jemand helfen. Ich habe folgendes Problem: Habe alles eingerichtet wie in der Anleitung angegeben. Jetzt wenn ich die Seite aufrufe erscheint Folgendes Bild 
![bildschirmfoto 2019-02-10 um 18 18 12](https://user-images.githubusercontent.com/47503244/52536887-771cd780-2d60-11e9-928c-691a62c32f16.png) wenn ich auf Use Setup tool drücke erscheint nur ein weisser Bildschirm woran kann das liegen? Kann mir jemand erklären was ich alles in die Setup Datei schreiben muss?

Mit freundlichen Grüßen 
Daniel

**Comment by tkrebs** [comment]
Eine weiße Seite klingt nach einem PHP-Fehler. In den Error-Logs des Webservers sollte eine konkretere Fehlermeldung zu finden sein.

**Comment by sitze89** [comment]
Leider ist hier nichts zu finden..Die Error logs sind komplett leer...  Ich komme momentan auch gar nicht mehr weiter.. Sobald ich Use Setup tool klicke dann kommt die weisse Seite..

**Comment by mumulusul** [comment]
die local.php muss du anpassen,  
'database' => 'XXXXXXXX',
        'username' => 'XXXXXXX',
        'password' => 'XXXXXXXX',

more local.php
<?php
/**
 * Local application configuration
 *
 * Insert your local database credentials here
 * and provide the email address the system should use.
 */

ini_set('date.timezone', 'Europe/Berlin');

return array(
    'db' => array(
        'database' => 'XXXXXXXX',
        'username' => 'XXXXXXX',
        'password' => 'XXXXXXXX',

        'hostname' => 'localhost',
        'port' => null,
    ),
    'mail' => array(
        'type' => 'sendmail', // or 'smtp' or 'smtp-tls'
        'address' => 'info@info.de',

        'host' => '?', // for 'smtp' type only, otherwise remove or leave as is
        'user' => '?', // for 'smtp' type only, otherwise remove or leave as is
        'pw' => '?', // for 'smtp' type only, otherwise remove or leave as is

        'port' => 'auto', // for 'smtp' type only, otherwise remove or leave as is
    ),
    'i18n' => array(
        'locale' => 'DE',
        'currency' => 'EURO',
    ),
);

**Comment by sitze89** [comment]
So probiere jetzt schon mehrere Tage rum. Nun habe ich folgende meldung... kann mir das jemand erklären? mir behilflich sein? lg Daniel
![bildschirmfoto 2019-02-14 um 21 28 17](https://user-images.githubusercontent.com/47503244/52815762-c8e69a00-309f-11e9-9cd2-a54de3cc5048.png)

**Comment by tkrebs** [comment]
Diese Meldung erscheint, wenn man das Setup aufruft und die Datenbanktabellen unvollständig angelegt wurden. Am besten löschst du die unvollständigen Tabellen und startest das Setup noch mal neu.

**Comment by sitze89** [comment]
Das ganze funktioniert nicht, egal was ich probiere. Ist hier irgendjemand der mich bei der einrichtung unterstützen kann? Bzw das für mich übernehmen kann? Bin echt am verzweifeln :(

**Comment by tkrebs** [comment]
Weiße Seiten sind immer frustrierend, weil man die Fehlerursache nicht direkt feststellen kann. Je nach Apache- und/oder PHP-Einstellung können die Fehlermeldungen in unterschiedliche Log-Dateien geschrieben werden. Eventuell muss auch noch die php.ini richtig eingestellt werden. Letztendlich hilft nur die konkrete Fehlermeldung weiter.

Wirklich helfen kann man dabei aus der Ferne kaum, da das die Webserver-Einrichtung betrifft, die auf jedem Webserver im Detail etwas anders aussieht.
