### ISSUE TITLE
error in ConfigLocaleListener.php

### ISSUE THREAD

**Issue by TCRW** [tkrebs/ep3-bs#203]
just updated to the 1.6.3b and the following error appears:

`Notice: Undefined index: choice in /var/www/vhosts/web88.bob.kundenserver42.de/httpdocs/wordpress/public/module/Base/src/Base/Manager/Listener/ConfigLocaleListener.php on line 59

Warning: Invalid argument supplied for foreach() in /var/www/vhosts/web88.bob.kundenserver42.de/httpdocs/wordpress/public/module/Base/src/Base/Manager/Listener/ConfigLocaleListener.php on line 59

Notice: Undefined index: choice in /var/www/vhosts/web88.bob.kundenserver42.de/httpdocs/wordpress/public/module/Base/src/Base/Manager/Listener/ConfigLocaleListener.php on line 59

Warning: Invalid argument supplied for foreach() in /var/www/vhosts/web88.bob.kundenserver42.de/httpdocs/wordpress/public/module/Base/src/Base/Manager/Listener/ConfigLocaleListener.php on line 59

Notice: Undefined index: choice in /var/www/vhosts/web88.bob.kundenserver42.de/httpdocs/wordpress/public/module/Base/src/Base/Manager/Listener/ConfigLocaleListener.php on line 59

Warning: Invalid argument supplied for foreach() in /var/www/vhosts/web88.bob.kundenserver42.de/httpdocs/wordpress/public/module/Base/src/Base/Manager/Listener/ConfigLocaleListener.php on line 59`

**Comment by tkrebs** [comment]
Compare your `config/autoload/local.php` with the repository version:

https://github.com/tkrebs/ep3-bs/blob/master/config/autoload/local.php.dist

You probably don't have the "i18n" part, which you can copy over then.

**Comment by TCRW** [comment]
Perfect, that did it :-)

**Comment by tkrebs** [comment]
Nice :)
