### ISSUE TITLE
Email Text Editing

### ISSUE THREAD

**Issue by Buckley97** [tkrebs/ep3-bs#205]
Hi there,

I would like to know how to change the text of the emails for activation email, booking confirmation email and cancellation email. In particular I would like to change the underlined text.

<img width="565" alt="booking confirmation" src="https://user-images.githubusercontent.com/43447311/53580008-9a25f480-3b72-11e9-8612-b3c0924a0962.PNG">

**Comment by tkrebs** [comment]
The emails are assembled from lots of different variables in these two services:

https://github.com/tkrebs/ep3-bs/blob/master/module/Booking/src/Booking/Service/Listener/NotificationListener.php

https://github.com/tkrebs/ep3-bs/blob/master/module/User/src/User/Service/MailService.php

**Comment by tkrebs** [comment]
#169
