### ISSUE TITLE
Platzordnung auf Registrierungsmaske

### ISSUE THREAD

**Issue by sitze89** [tkrebs/ep3-bs#206]
Hallo zusammen,
kann ich irgendwie ein Kontrollkästchen in die Registrierungsmaske einfügen mit dem man der Platzordnung des Vereins zustimmen muss und diese dann auch zu verlinken? Hat so etwas schon jemand verwirklicht oder Tipps für mich?
LG Daniel

**Comment by tkrebs** [comment]
Wenn Grundkenntnisse in HTML und PHP vorhanden sind, könntest du den Code für die Datenschutz-Checkbox kopieren und etwas weiter unten mit geänderten Inhalten einfügen:

https://github.com/tkrebs/ep3-bs/blob/master/module/User/view/user/account/registration.phtml#L165

**Comment by sitze89** [comment]
Vielen Dank, hat funktioniert:)
