### ISSUE TITLE
Deprecated: idn_to_utf8(): INTL_IDNA_VARIANT_2003 

### ISSUE THREAD

**Issue by twix76** [tkrebs/ep3-bs#209]
I recently installed the last Version of ep-3 (1.6.3). I am using PHP Version 7.2.8!

I got the following error code.

Deprecated: idn_to_utf8(): INTL_IDNA_VARIANT_2003 is deprecated in /var/www/cust/6685/www/www.tc.grosshoeflein.at/htdocs/platzreservierung/vendor/zendframework/zendframework/library/Zend/Validator/EmailAddress.php on line 545

Deprecated: idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated in /var/www/cust/6685/www/www.tc.grosshoeflein.at/htdocs/platzreservierung/vendor/zendframework/zendframework/library/Zend/Validator/EmailAddress.php on line 532

Is there any solution for my problem?

Br,
Chris

**Comment by tkrebs** [comment]
Thank you for the report. Yes, there is an update available for the underlying Zend Framework, which I have implemented in the latest version 1.6.3c. You can download it here:

https://bs.hbsys.de/download?locale=en-US
