### ISSUE TITLE
Dialog auf Safari/IOS/Iphone lässt sicht nicht schließen,...

### ISSUE THREAD

**Issue by balbi21** [tkrebs/ep3-bs#21]
Während auf dem Desktop PC/Browser die Dialog-Boxen (Buchen, Veranstaltung etc.) durch einen klick neben den Dialog wieder zugeht und man das System weiter nutzen kann, funktioniert dies auf einem Iphone (IOS9, Safari) nicht, der Dialog (z.B. Anzeige eines Events) bleibt zentriert offen und man kann nur noch die Seite über die Adresszeile des Browsers wechseln - aber man kommt nicht mehr in das System zurück, weder klick auf den Button, noch auf den Dialog oder neben den Dialog können diesen schließen...?

MfG - Björn

**Comment by tkrebs** [comment]
Leider habe ich gerade kein iOS-Gerät zur Hand um das zu Testen; ich habe allerdings einen X-Button zum expliziten Schließen der Dialogboxen (im Entwicklungszweig) eingebaut. Ich hoffe, das funktioniert dann auch unter iOS:

![ep3-bs-close-x](https://cloud.githubusercontent.com/assets/2473984/11571425/937a9e80-99fc-11e5-8997-1e91138f894e.png)

**Comment by balbi21** [comment]
Das funktioniert :-)
