### ISSUE TITLE
Fatal error: Uncaught Zend

### ISSUE THREAD

**Issue by Tommypz** [tkrebs/ep3-bs#210]
Fatal error: Uncaught Zend\Session\Exception\InvalidArgumentException: Invalid save handler specified ("files"); must be one of [] or a class implementing SessionHandlerInterface in /var/www/virtual/tommys-zeltverleih.de/htdocs/Buchungssytem/vendor/zendframework/zend-session/src/Config/SessionConfig.php:473 Stack trace: 

#0 /var/www/virtual/tommys-zeltverleih.de/htdocs/Buchungssytem/vendor/zendframework/zend-session/src/Config/SessionConfig.php(218): Zend\Session\Config\SessionConfig->performSaveHandlerUpdate('files')

#1 /var/www/virtual/tommys-zeltverleih.de/htdocs/Buchungssytem/vendor/zendframework/zend-session/src/Config/SessionConfig.php(103): Zend\Session\Config\SessionConfig->setPhpSaveHandler('files') 

#2 /var/www/virtual/tommys-zeltverleih.de/htdocs/Buchungssytem/vendor/zendframework/zend-session/src/Config/StandardConfig.php(172): Zend\Session\Config\SessionConfig->setOption('save_handler', 'files') 

#3 /var/www/virtual/tommys-zeltverleih.de/htdocs/Buchungssytem/vendor/zendframework/zend-session/src/Config/SessionCo in /var/www/virtual/tommys-zeltverleih.de/htdocs/Buchungssytem/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 941

Nach der Installertion dieses Problem

System
PHP 7.1
Debian 8

**Comment by tkrebs** [comment]
Ist das data/session/-Verzeichnis für PHP beschreibbar, sprich sind die UNIX-Dateiberechtigungen korrekt gesetzt?

Oder wurde in der config/autoload/local.php eine vom Standard abweichende 'session_config' hitnerlegt?

**Comment by Tommypz** [comment]
Hallo

Ja data/session ist beschreibbar 

und config/autoload/local.php nein

**Comment by tkrebs** [comment]
Hmmm ... handelt es sich um das "fertige Paket" von der Website oder ist es eine Composer-Installation?

**Comment by Tommypz** [comment]
Kann ich dich Privat erreichen?
