### ISSUE TITLE
Ansicht bei Teilbelegung

### ISSUE THREAD

**Issue by monoseo** [tkrebs/ep3-bs#211]
Gibt es eine Möglichkeit teilbelegte Plätze (z. B. 2 von 4) irgendwie im Kalender anzuzeigen? Momentan stehen die Plätze als „frei“ und der User weiß nicht, ob sich bereits jemand eingetragen hat.

**Comment by tkrebs** [comment]
Beim Anklicken eines derart freien Feldes sollte die Teilbelegung im sich öffnenden Fenster angezeigt werden.

**Comment by monoseo** [comment]
Genau, allerdings taucht diese Information leider in der Übersicht selbst nicht auf. 

Kurz zum Hintergrund: Bei uns sollen Volleyballplätze reserviert werden. Die Spieler, die alleine sind, sollen direkt in der Übersicht sehen, ob sich bereits Mitspieler für ein Feld interessieren und noch Mitspieler suchen. Bis jetzt müsste man ja immer auf jedes Feld klicken, um etwas zu finden.

**Comment by tkrebs** [comment]
Falls ihr jemanden mit grundlegenden PHP-Kenntnissen habt:

Die Daten sind technisch vorhanden und können relativ leicht abgefragt:

https://github.com/tkrebs/ep3-bs/blob/master/module/Calendar/src/Calendar/View/Helper/Cell/Render/Cell.php#L38

Und ausgegeben werden:

https://github.com/tkrebs/ep3-bs/blob/master/module/Calendar/src/Calendar/View/Helper/Cell/Render/Free.php#L15

**Comment by monoseo** [comment]
Quick and durty gelöst mit:

Cell.php (neue Zeile 54):
`$freeSpaces = intval($capacity) - intval($quantity);`

Free.php (anpassen Zeile 11):
`    public function __invoke($user, $userBooking, array $reservations, array $cellLinkParams, Square $square, $freeSpaces)`

Free.php (anpassen Zeile 15):
`	    $labelFree = $square->getMeta('label.free', $this->view->t('Frei (' . $freeSpaces . ')'));`

Damit wird in der Zeile „Frei“ noch eine Zahl angezeigt, wie viele freie Plätze offen sind.

**Comment by thepontifexus** [comment]
@monoseo : Danke für die Lösung! 
In Deiner Beschreibung fehlt allerdings noch in Cell.php, Zeile 72, dass Du die neue Variable auch zurückgibst:
return $view->calendarCellRenderFree($user, $userBooking, $reservationsForCell, $cellLinkParams, $square, $freeSpaces);

Dann funktionierts :-)
