### ISSUE TITLE
Problem bei Registrierung

### ISSUE THREAD

**Issue by Buddy0110** [tkrebs/ep3-bs#214]
Hallo,

bei mir kommt bei einer möglichen Registrierung folgende Fehlermeldung. Habe schon vieles probiert aus dieser Community, nur bis jetzt hat leider nicht geholfen. Auch eine Anfrage beim Hoster ergab keine Lösung.

Bitte um Hilfe: http://reservierung.bplaced.net/platzbuchung/public/user/registration

Danke!

**Comment by tkrebs** [comment]
Als Übergangslösung kann folgende Datei und Zeile geändert werden:

https://github.com/tkrebs/ep3-bs/blob/524dd2b38700f8e8e9a432aa187243f53b1a80ef/module/User/src/User/Form/RegistrationForm.php#L259

zu

```php
$bcrypt->setSalt('Hier mindestens 16 zufällige Zeichen einsetzen');

**Comment by Buddy0110** [comment]
Du bist der Beste! Endlich klappt es! Großer Dank an Dich!
