### ISSUE TITLE
Suche in der Benutzerverwaltung

### ISSUE THREAD

**Issue by mjmpeace** [tkrebs/ep3-bs#217]
Die Suche mit den eingebauten Abfragen ist zwar nett, aber ich möchte eine Abfrage machen, bei der mir wirklich ALLE BENUTZER auf einmal angezeigt werden, egal welchen Status oder welche Berechtigung der Benutzer hat. Wie geht das?

**Comment by tkrebs** [comment]
Zum Beispiel mit

(uid > 0)

oder

(erstellt > 01.01.2000)

**Comment by mjmpeace** [comment]
Danke - da bin ich nicht drauf gekommen - manchmal ist man etwas Betriebsblind.
