### ISSUE TITLE
Wartungsarbeiten deaktivieren

### ISSUE THREAD

**Issue by todd125** [tkrebs/ep3-bs#219]
Wenn die Wartungsarbeiten aktiviert sind ist ein LogIn nicht möglich, wodurch man diese nicht wieder deaktiveren kann. ein Zugriff direkt auf ".../public/user/login" funktioniert ebenfalls nicht. Wie lässt sich die Option deaktiveren?

**Comment by tkrebs** [comment]
Die Login-Seite ist von den Wartungsarbeiten ausgenommen und sollte funktionieren.

Falls sie bei dir nicht funktioniert liegt eventuell noch ein anderes Problem vor, z. B. mit mod_rewrite?

**Comment by todd125** [comment]
Fehler gefunden. ".../user/login" ist verfügbar, aber ".../public/user/login" nicht
