### ISSUE TITLE
Tagesübergreifende Buchungen..

### ISSUE THREAD

**Issue by zaeng** [tkrebs/ep3-bs#22]
Hi, man kann leider keine tagesübergreifenden Buchungen (z.B. Von 20.00 bis 11.00h) ermöglichen, da das System dann mit den Zeiten durcheinanderkommt. Als Anregung: alle Zeiten auf Internetzeit umrechnen, dann stimmen auch alle Berechnungen und Fehler werden vermieden.

**Comment by tkrebs** [comment]
Hi, eine Buchung besteht intern aus einer oder mehreren "Reservierungen", welche jeweils an einem bestimmten Datum (= Tag) eine Zeitspanne (a - b Uhr) abdecken. Technisch ist es also problemlos möglich, eine Buchung mit zwei Reservierungen (z.B. von 20:00 - 0:00 Uhr und von 0:00 - 11:00 Uhr) zu erstellen. Tatsächlich jedoch gibt es derzeit keine Möglichkeit in der Bedienoberfläche, solche Fälle anzulegen... :)
