### ISSUE TITLE
Zeichenlänge bei Plätzen ändern

### ISSUE THREAD

**Issue by DanielM1991** [tkrebs/ep3-bs#220]
Servus,

wie kann ich die Zeichenlänge bei den Namen der Plätze ändern? Wenn der Name zu lang wird, erhalte ich folgende Meldung:

Statement could not be executed (22001 - 1406 - Data too long for column 'name' at row 1)

Danke und viele Grüße
Daniel M.

**Comment by tkrebs** [comment]
Das müsste über die Datenbank-Struktur (z. B. via phpMyAdmin) geändert werden.

**Comment by DanielM1991** [comment]
Hat über die Datenbank geklappt. Danke für den Hinweis!
