### ISSUE TITLE
Kann man das System an die Authentifizierung des WebServers koppeln?

### ISSUE THREAD

**Issue by MrCoffee77** [tkrebs/ep3-bs#221]
Hallo,

wir überlegen, ob wir ep3 für unsere Raum-Verwaltung nutzen wollen. Ich würde dabei gerne für das Login auf die Authentifizierung des WebServers zurückgreifen. Da ich schon die Übersicht nicht öffentlich haben möchte. Kann man das koppeln?

**Comment by tkrebs** [comment]
Man könnte beim Erstellen bzw. Ändern eines Benutzers gleichzeitig dessen Passwort in der .htpasswd eintragen bzw. ändern. Das wäre technisch nicht allzu aufwendig.

Standardmäßig bietet das Buchungssystem diese Funktion aber nicht.
