### ISSUE TITLE
Zweite Spalte bei Plätzen

### ISSUE THREAD

**Issue by DanielM1991** [tkrebs/ep3-bs#222]
Servus,

bevor ich mir mein ganzes Reservierungssystem Schrotte, hier mal die Frage, wie ich hinter die Platzbezeuchnung eine 2. Spalte bekomme. Als zwischen Platz und Uhrzeit. 
Info: Ich habe bei mir die Plätze in den Zeilen und die Uhrzeiten als Spalten eingestellt. 

Danke im Voraus 
Viele Grüße
Daniel M.

**Comment by tkrebs** [comment]
Die Kalendertabelle und deren Spalten und Zeilen kann auf oberster Ebene relativ leicht über die Template-Dateien bearbeitet werden. Je nach Darstellungsmodus entweder hier:

https://github.com/tkrebs/ep3-bs/blob/master/module/Calendar/view/calendar/calendar/index.landscape.phtml ("Landscape Mode")

oder hier

https://github.com/tkrebs/ep3-bs/blob/master/module/Calendar/view/calendar/calendar/index.portrait.phtml ("Portrait Mode")
