### ISSUE TITLE
Platzinfos auch beim Anklicken des Platzes einblenden

### ISSUE THREAD

**Issue by DanielM1991** [tkrebs/ep3-bs#224]
Hallo zusammen,

derzeit erhält man die Platzinfos nur, wenn auf ein Freies Feld geklickt wird. 
Super wäre es, wenn man die Platzinformationen auch erhält, wenn man auf den Platznamen direkt klickt. 

Gibt es hierfür eine Quick und Dirty Lösung?

Danke und Grüße
DanielM

**Comment by tkrebs** [comment]
Du könntest das Template für freie Plätze
https://github.com/tkrebs/ep3-bs/blob/master/module/Square/view/square/square/index.free.phtml
mit dem Template für belegte Plätze
https://github.com/tkrebs/ep3-bs/blob/master/module/Square/view/square/square/index.occupied.phtml
vergleichen und die Zeilen mit den gewünschten Informationen einfach rüberkopieren.

**Comment by DanielM1991** [comment]
Danke für die schnelle Antwort. 
Wird damit nicht erreicht, dass die Information auch bei belegten Plätzen angezeigt wird? 
Ich meinte, dass man den Namen des Platzes anklicken kann. Im Screenshot z.B. Platz "A".

<img width="439" alt="Bildschirmfoto 2019-06-16 um 21 52 40" src="https://user-images.githubusercontent.com/43386779/59568837-13454b00-9081-11e9-81cd-257371191aa2.png">

**Comment by tkrebs** [comment]
Ach so, verstehe. Dafür gibt es m. E. derzeit leider keine einfache Lösung.
