### ISSUE TITLE
Display player name in a cell

### ISSUE THREAD

**Issue by theolam** [tkrebs/ep3-bs#225]
Hello,

When I am logged in as administrator,  I have the ability to see the player name in a cell. Is there a way for the logged-in user to see it (player name), instead of the "Occupied" message ?

Thanks
Ps. Two attachments included

<img width="596" alt="Screenshot 2019-06-19 at 13 39 02" src="https://user-images.githubusercontent.com/7641063/59758907-9f30c000-9297-11e9-988e-9a9698bb76f4.png">
---

<img width="445" alt="Screenshot 2019-06-19 at 13 41 04" src="https://user-images.githubusercontent.com/7641063/59759039-e9b23c80-9297-11e9-8f6c-8e7e62b7615f.png">

**Comment by tkrebs** [comment]
In **Administration > Settings > Squares > Edit** you can set the visibility of names in the calendar to none (default), public or (as requested) to other logged in users.

**Comment by theolam** [comment]
I do not find the "Settings" option somewhere. 
Attached Suggested Choices Are Given

<img width="223" alt="Screenshot 2019-06-19 at 17 55 12" src="https://user-images.githubusercontent.com/7641063/59776802-19733b80-92bc-11e9-8329-ee7394ef8b16.png">


<img width="1065" alt="Screenshot 2019-06-19 at 17 54 50" src="https://user-images.githubusercontent.com/7641063/59776725-f2b50500-92bb-11e9-958d-f562009453e9.png">


<img width="807" alt="Screenshot 2019-06-19 at 17 58 31" src="https://user-images.githubusercontent.com/7641063/59776724-f2b50500-92bb-11e9-9567-c56704954abc.png">

**Comment by tkrebs** [comment]
It's **Configuration > Square > Edit** then, my bad.

**Comment by theolam** [comment]
thanks. 
Congratulations on your work, as well as on the quick feedback. Respect!
