### ISSUE TITLE
Filemanager rödelt sich tot

### ISSUE THREAD

**Issue by azich01** [tkrebs/ep3-bs#229]
ich würde gerne über den filemanager Bilder mit einbinden, aber wenn ich den Filemanager starte rödelt der sich tot und zeigt keine Ordner an.
Welche Berechtigungen müssen dafür angepasst werden ?
Hat irgend Jemand einen Tipp oder kennt die Lösung ?

![2019-08-02 14_00_13-CompatWindow](https://user-images.githubusercontent.com/52746565/62368977-6e96a400-b52e-11e9-9158-121f83683a98.jpg)

**Comment by tkrebs** [comment]
Die Verzeichnisrechte des Buchungssystems sind hier beschrieben:
https://bs.hbsys.de/documentation/de/installation/einrichtung#docs
(Punkt 4)

Ansonsten hilft auch ein Blick in die Netzwerkanalyse der Browser-DevTools (F12). Dort kann nachvollzogen werden, welche Anfrage welche Art Fehler produziert.

**Comment by azich01** [comment]
Die Berechtigungen habe ich alle kontrolliert, auch nochmal rekursiv erneuert.
Ist der Filemanager eventuell eine Java-Application, die nicht mehr unterstützt wird ?
bei DevTools weiß ich nicht so genau wonach ich schauen soll.


![Netzwerk](https://user-images.githubusercontent.com/52746565/62462392-97fe3c80-b787-11e9-8cfe-0b7c7cdcfedf.jpg)

**Comment by azich01** [comment]
Das apache2 Log sagt folgendes:
[Tue Aug 06 15:56:40.045741 2019] [php7:warn] [pid 4895] [client 192.168.1.164:57500] PHP Warning:  require(vendor/zendframework/zendframework/library/Zend/Stdlib/Exception/ExceptionInterface.php): failed to open stream: No such file or directory in /var/www/leihgeraete.de/public/vendor/filemanager/connectors/php/user.config.php on line 43, referer: http://leihgeraete.gerberarchitekten.de/public/vendor/filemanager/?langCode=de-DE
[Tue Aug 06 15:56:40.045784 2019] [php7:error] [pid 4895] [client 192.168.1.164:57500] PHP Fatal error:  require(): Failed opening required 'vendor/zendframework/zendframework/library/Zend/Stdlib/Exception/ExceptionInterface.php' (include_path='.:/usr/share/php') in /var/www/leihgeraete.de/public/vendor/filemanager/connectors/php/user.config.php on line 43, referer: http://leihgeraete.gerberarchitekten.de/public/vendor/filemanager/?langCode=de-DE

zendframework ist aber installiert

**Comment by tkrebs** [comment]
Offenbar gab es hier Umstrukturierungen, sodass die Pfade im Filemanager nicht mehr korrekt sind:

https://github.com/tkrebs/ep3-bs/blob/master/public/vendor/filemanager/connectors/php/user.config.php#L43

**Comment by azich01** [comment]
OK, der Link ist von 2015 , die Datei in dem Link ist gleich mit der die ich habe. Gibt es denn jetzt eine Lösung, oder ein aktuelleres Datenpaket ?

Oder einfach hinnehmen das der Filemanager nicht mehr funktioniert ?

**Comment by azich01** [comment]
OK, die Pfade haben sich geändert , was anscheinend in den letzten 5 Jahren niemanden aufgefallen ist.
Die neuen Pfade in /public/vendor/filemanager/connectors/php/user.config.php in Zeile 43-45 sind -
    require 'vendor/zendframework/zend-stdlib/src/Exception/ExceptionInterface.php';
    require 'vendor/zendframework/zend-stdlib/src/Exception/InvalidArgumentException.php';
    require 'vendor/zendframework/zend-stdlib/src/ArrayObject.php';

für die Nachwelt
