### ISSUE TITLE
Oops ... da ist wohl etwas schief gelaufen Option service.calendar.days does not exist

### ISSUE THREAD

**Issue by ebuckpc** [tkrebs/ep3-bs#23]
Was mache ich bei der Installation falsch?

Oops ... da ist wohl etwas schief gelaufen
Option service.calendar.days does not exist

**Comment by bedv** [comment]
Hi, bist du die ganze Setup Routine durchgegangen??
Hatte auch das selbe Problem, Setup nochmal ganz von vorne, jetzt gehts!!
(auch alle Tables in der DB löschen!!)
