### ISSUE TITLE
Anzeigen von Preisen

### ISSUE THREAD

**Issue by mjmpeace** [tkrebs/ep3-bs#230]
Ich habe für einen Zeitraum einen Preis eingegeben. Aber ich bekomme nirgendwo als normaler Benutzer die Preise angezeigt. Was muss ich tun, damit die Preise angezeigt werden?

**Comment by tkrebs** [comment]
Im Preis-Editor gibt es am unteren Ende eine Auswahlbox als Einstellungsmöglichkeit, wann und wem die Preise angezeigt werden sollen. Möglicherweise steht diese auf "Für niemanden"?

**Comment by mjmpeace** [comment]
Die Einstellungen waren korrekt. Weder mit der Einstellung alle noch der Einstellung angemeldete Besucher wird etwas angezeigt. Auch Testweise ausschalten und wieder einschalten brachte keine Änderung.

**Comment by tkrebs** [comment]
Treffen die Preisregeln denn ganz sicher für den getesteten Zeitraum und für die getesteten Plätze zu? Eventuell hilft es bei komplexen Preisregeln, testweise einen Basispreis für alle Zeiträume und Plätze festzulegen, um zu schauen, ob es funktioniert.

Zudem werden die Preise nicht angezeigt, wenn man als Admin oder eventuell Mitarbeiter angemeldet ist.

**Comment by mjmpeace** [comment]
Ich habe extra für mich einen Testbenutzer mit keinen besonderen Rechten angelegt, um das zu testen.
![Preise](https://user-images.githubusercontent.com/46706899/62714205-6511ae00-b9fe-11e9-9e09-bc0c961ded33.JPG)
![Buchung](https://user-images.githubusercontent.com/46706899/62714207-6511ae00-b9fe-11e9-8f62-fe6f5bf8d119.JPG)

**Comment by mjmpeace** [comment]
Ups sehe gerade - falscher Platz :-(

**Comment by mjmpeace** [comment]
Auch nach Ändern der Einstellung auf alle Plätze (wir haben nur 2) tut sich nichts. Es wird beim normalen Benutzer kein Preis angezeigt. Wie muss das aussehen?

**Comment by mjmpeace** [comment]
![Preis anzeigen](https://user-images.githubusercontent.com/46706899/62715058-051c0700-ba00-11e9-8ce0-697e6de44df3.JPG)
Nachdem ich einmal erst für Montag bis Sonntag einen Preis festgesetzt habe für die Zeit von 7:00 bis 23:00 wird jetzt der Preis angezeigt. Das heißt, man muss erstmal für alle Zeiten einen Preis festlegen. Danach dann kann ich für bestimmte Tage und Zeiten andere Preise festlegen. Ist das so richtig?

**Comment by tkrebs** [comment]
Genau, man kann nach unten hin immer spezifischer werden und allgemeinere Regeln überschreiben.

**Comment by mjmpeace** [comment]
Prima - jetzt klappt die Preisangabe komplett. Das war schnelle Hilfe. Leider kann man im Moment ja nur einen Preis angeben. Daher werde ich erstmal, was meistens der Fall sein wird, die Preise für die Mitglieder angeben. Wird es da irgendwann eine Möglichkeit geben, das mit einer Differenzierung zu versehen? Vorschlag dazu: Die Benutzer werden in Gruppe Mitglieder bzw. Nichtmitglieder einsortiert bei der Aktivierung (machen wir im Moment manuell durch Verwaltung). Dann müsste man zwei Preisgruppen bilden dürfen, so dass dann je nach Gruppenzugehörigkeit des Benutzers der korrekte Preis angezeigt wird.
