### ISSUE TITLE
Ok. Danke für die schnelle Antwort.

### ISSUE THREAD

**Issue by azich01** [tkrebs/ep3-bs#232]
Ok. Danke für die schnelle Antwort.
Werde mich mal dran versuchen....

_Originally posted by @Joysdesign in https://github.com/tkrebs/ep3-bs/issues/83#issuecomment-348790556_

**Comment by azich01** [comment]
Konnte das Notizfeld in der Buchungsmaske hinzugefügt werden ?

**Comment by tkrebs** [comment]
https://github.com/tkrebs/ep3-bs/issues/83#issuecomment-640941277
