### ISSUE TITLE
Universal-Gestaltung

### ISSUE THREAD

**Issue by azich01** [tkrebs/ep3-bs#236]
Hallo, 
Ein Buchungssystem für Tennisplätze ist ja an sich nicht schlecht, aber wäre es nicht sinnvoller
so ein System universaler zu gestalten damit es vielfältiger eingesetzt werden kann ?
Solche Buchungssysteme sind echt rar, meist sündhaft teuer und ich denke mal wenn ep3-bs universaler gestaltet wäre, könnte es ein echter Renner werden.

Gruß
Andreas

**Comment by tkrebs** [comment]
Prinzipiell haben wir den Universal-Ansatz auch in letzter Zeit verstärkt verfolgt, indem z. B. Bezeichnungen und Texte systemweit ausgetauscht werden können. Die Wurzeln des Tennisplatz-Buchungssystems sind aber natürlich weiterhin und in den Programmtiefen vorhanden, weshalb wir schon länger ein größeres "Universal"-Update im Auge haben. Bislang scheiterte dies allerdings an der verfügbaren Zeit.

**Comment by azich01** [comment]
Ich habe die Texte über die Übersetzungsdateien de-DE ausgetauscht. Leider fehlt da eine en-EN , damit auch die englische Version angepasst werden kann.
