### ISSUE TITLE
display player name while the game is over

### ISSUE THREAD

**Issue by theolam** [tkrebs/ep3-bs#237]
Hi,
I was wondering if it was possible to display the player's name while the game was over.
For example in the picture below, I have booked 6pm-7pm but my name is not displayed.

Could you give me the Playername object to put it in place 'Past' ?

      if ($walkingDate <= $now) {
            if (! ($user && $user->can('calendar.see-past'))) {
                return $view->calendarCell($this->view->t('Past'), 'cc-over');
            }
        }

![pic-1](https://user-images.githubusercontent.com/7641063/63359789-fe817e00-c375-11e9-9578-11015f238513.jpg)

Thx!!

**Comment by tkrebs** [comment]
You can get the player object from the booking object by

```php
$booking->getExtra('user')
```

Or from any reservation object by

```php
$reservation->getExtra('booking')->getExtra('user')

**Comment by luke8800gts** [comment]
Is there a configuration option for this? If not, would it be possible to get one?
