### ISSUE TITLE
Layout Bug unter IOS

### ISSUE THREAD

**Issue by balbi21** [tkrebs/ep3-bs#24]
Auf einem Iphone 6+ führen "viele" Plätze zu diesem Layout-Bug:

![img_8089](https://cloud.githubusercontent.com/assets/4647867/13003323/4eda768c-d175-11e5-94cd-6477eb181827.PNG)

**Comment by wagpat** [comment]
Mir ist dieses Problem auch aufgefallen wenn Veranstaltungen eingetragen sind. (iPhone 5S)

![img_0119](https://cloud.githubusercontent.com/assets/10882283/14408618/a312143a-fefc-11e5-8d10-680a61c4e009.PNG)

**Comment by tkrebs** [comment]
Das wird in der nächsten Version korrigiert sein.

**Comment by geopicture** [comment]
Gratulation zu dieser sehr guten WebApp! Gibt es schon ein voraussichtliches release date für die nächste Version? Vielen Dank für die viele Arbeit, die in diesem Projekt steckt. LG

**Comment by tkrebs** [comment]
Ein konkretes Datum gibt es noch nicht, es wird aber vermutlich nächsten Monat soweit sein.
