### ISSUE TITLE
The RandomLib fallback pseudorandom generator is not installed.

### ISSUE THREAD

**Issue by mikehomme** [tkrebs/ep3-bs#241]
Hello,

Great product. I've installed it before on a very similar (almost identical) server before without any problems. I'm running Amazon Linux, MySQL 5.7 and PHP 5.6.

Running the setup seems to work as far as the database table creation is concerned, however, after completing the form and submitting it to create the Admin user I'm receiving this error:

**The RandomLib fallback pseudorandom generator is not installed. Please install it to support secure random numbers.**

Any obvious reason for this?

Thanks for any heads up.

Thanks.

**Comment by mikehomme** [comment]
I figured this one out. 

mcrypt wasn't installed although it was showing in phpinfo()?

Either way this command resovled the error:

`sudo yum install php56-mcrypt`

Thanks

**Comment by tkrebs** [comment]
Glad you figured it out and thanks for the update. This will certainly help if someone finds this issue by search.
