### ISSUE TITLE
Info zu Maileinstellungen

### ISSUE THREAD

**Issue by Stefan-Ha** [tkrebs/ep3-bs#246]
Da ich fast einen halben Tag rumprobiert habe bis die Mails zur Registrierung klappen, hier die Info was am Ende bei mir funktioniert hat.

Nutze unter MS Azure eine VM mit Ubuntu 18.04.3 LTS

Maileinstellungen unter /config/local.php => damit es geht Port 587 (TLS) statt 465 (SSL) ist der "Trick" :-)

 18	    'mail' => array(
 19         'type' => 'smtp', // 'sendmail' or 'smtp' or 'smtp-tls'
 20         'address' => 'name@domain.de',
 21
 22         'host' => 'smtp.xyz.de', // for 'smtp' type only, otherwise remove or leave as is
 23         'user' => 'name@domain.de', // for 'smtp' type only, otherwise remove or leave as is
 24         'pw' => 'passwort', // for 'smtp' type only, otherwise remove or leave as is
 25
 26         'port' => '587', // for 'smtp' type only, otherwise remove or leave as is
 27         'auth' => 'plain', // default: plain ; for 'smtp' type only, change this to 'login' if you have problems with SMTP authentication
 28     ),

Um am Server Maileinstellungen testen hat mir folgender Link geholfen: https://www.stevenrombauts.be/2018/12/test-smtp-with-telnet-or-openssl/

**Comment by tkrebs** [comment]
Vielen Dank für die Infos, das wird sicherlich einigen Nutzern helfen!

**Comment by haGibear** [comment]
Perfekt, danke @Stefan-Ha !

**Comment by StefanHeid** [comment]
Das Tool ist echt klasse. Aber leider komme ich mit der Mail Konfiguration nicht zurecht. Ich habe alle Tipps in den verschiedenen Comments versucht. Ich bekomme immer folgenden Fehler: "An exception was raised while creating "Zend\Mail\Protocol\Smtp\Auth\Plain", no instance returned"
