### ISSUE TITLE
Admin PW vergessen

### ISSUE THREAD

**Issue by adjustGirl** [tkrebs/ep3-bs#247]
Ich habe das PW vergessen als Admina. Die normale PW vergessen funktioniert da aber nicht. Was ist zu tun?

**Comment by lexushamburg** [comment]
Da das Passwort in der Datenbank nicht im Klartext gespeichert ist, hilft ein kleiner Umweg.
Eine Möglichkeit:
Registriere Dich neu im laufenden Buchungssystem mit einer bisher noch nicht vorhandenen Mail Adresse. Merke Dir das Passwort, was Du dabei vergibst.

Logge Dich über phpMyAdmin in die Datenbank ein.
Gehe zur Tabelle bs_user und suche den eben regisitrierten Benutzer.
Kopiere das Feld "pw" komplett und füge es in das "pw" Feld des Admin ein.

Jetzt soltest Du Dich wieder mit dem Benutzernamen des Admin und dem neuen Passwort (des vorher registrierten neuen Benutzers) einloggen können.

**Comment by adjustGirl** [comment]
Danke. Aber zum Glück ist mir das PW wieder eingefallen. ;)
