### ISSUE TITLE
Basisverzeichnis umbenennen

### ISSUE THREAD

**Issue by Frage2019** [tkrebs/ep3-bs#248]
Hallo!
Nachdem ich das Buchungssystem in einem nicht öffentlichen Verzeichnis neu aufgebaut habe, wollte ich das neue Buchungssystem gegen das alte Buchungssystem austauschen. Der Plan war, das Basisverzeichnis des alten Buchungssystems umzubenennen, um anschließend das Basisverzeichnis des neuen Buchungssystems auf den Namen des alten Buchungssystems umzubenennen, so dass am Ende der Link zum neuen Buchungssystem für den Anwender unverändert bleibt.
Leider musste ich feststellen, dass das Buchungssystem nur dann funktioniert, wenn das Basisverzeichnis so benannt ist, wie es beim Setup gewesen ist. Sobald das Basisverzeichnis anders heißt, kommt noch noch ein weißer Hintergrund.
Gibt es einen pragmatischen Ansatz, wie man zwei bestehende Buchungssysteme gegeneinander austauschen kann?

**Comment by adjustGirl** [comment]
Das hatte ich auch mit ner Subdomain

**Comment by tkrebs** [comment]
Dem Buchungssystem ist es eigentlich egal, in welchem Verzeichnis es liegt, das Umbenennen der Verzeichnisse (auch nach dem Setup) müsste also funktionieren. Dass eine weiße Seite erscheint, könnte viele verschiedene Ursachen haben (z. B. Caches, UNIX-Dateiberechtigungen, Webserver-Einstellungen, ...). Das ist schwer aus der Ferne zu sagen.

**Comment by Frage2019** [comment]
Vielen Dank für die Info! ... Der Hinweis hat mir sehr geholfen. Da das Umbenennen der Verzeichnisse am Ende immer zu einer weißen Seite geführt hat, habe ich jetzt die komplette Verzeichnis- und Dateistruktur des Buchungssystems einfach vom Entwicklungsverzeichnis in das Zielverzeichnis kopiert. Diese Methode hat einwandfrei funktioniert. Sehr schön! :-)
