### ISSUE TITLE
Ooops, ... Must Call beginTransaction() before you can rollback

### ISSUE THREAD

**Issue by cipmos** [tkrebs/ep3-bs#25]
Hallo!

Nach dem Klick auf "Buchung abschließen" kommt immer die Fehlermeldung

 "Oops ... da ist wohl etwas schief gelaufen
Must call beginTransaction() before you can rollback"

Woran liegt das und wie kann dieses Problem behoben werden?

Viele Grüße

**Comment by tkrebs** [comment]
Für eine genaue Diagnose des Problems fehlen hier leider Details, aber aus dem Zusammenhang mit Ihrem anderen Problem #26 ergibt sich die naheliegende Erklärung, dass auch hier eine etwas ungünstige Konfiguration Ihres Webservers der Grund sein könnte.
