### ISSUE TITLE
Gesprengtes Layout

### ISSUE THREAD

**Issue by DanielM1991** [tkrebs/ep3-bs#250]
Hallo zusammen,

ich habe seit neuestem ein gesprengtes Layout. Von mir wurde am Code nichts geändert, kann es am Hoster liegen? 

Es wird folgende Meldung angezeigt:

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/ud08_303/html/vendor/zendframework/zendframework/library/Zend/Stdlib/ArrayObject.php on line 426

Ich hoffe hier kann mir jemand weiter helfen. 

Dank und Grüße
Daniel M

**Comment by hschiebold** [comment]
Taucht ab PHP 7.3 auf. Siehe https://github.com/zendframework/zend-stdlib/issues/97

**Comment by tkrebs** [comment]
#372
