### ISSUE TITLE
Datumsbereiche ausschließbar?

### ISSUE THREAD

**Issue by Stefan-Ha** [tkrebs/ep3-bs#251]
Kann man im Einstellungsdialog: Verhalten/Folgende Tage verstecken auch Datumsbereiche ausschließen? Unsere Anlage kann nur in den Sommer von Mai - Sept. gebucht werden. Wenn es geht bitte Info zur Syntax. Danke!

Gruß

Stefan

**Comment by mjmpeace** [comment]
In den Einstellungen unter Verhalten kann man Tage angeben, welche nicht angezeigt werden sollen - auch mit konkretem Datum. Damit müsste das gewünschte zu erreichen sein.
