### ISSUE TITLE
Möglichkeit, insgesamt nur eine Woche anzuzeigen

### ISSUE THREAD

**Issue by LukaMarcel** [tkrebs/ep3-bs#255]
Hallo, da wir gerne nur für eine Woche Buchungen anbieten würden,
suche ich eine Möglichkeit, nur eine Woche im Kalender einstellen zu können, die auch direkt auf der Startseite "dargestellt" wird und nicht erst im Kalender ausgewählt werden muss.
Ist das möglich?

**Comment by DanielM1991** [comment]
Hallo,
über den Link "https://deinedomain/?date=2020-01-30" kannst du ein Datum per Link vorgeben. 
Andere Möglichkeiten sind mir nicht bekannt.
