### ISSUE TITLE
Must call beginTransaction() before you can rollback

### ISSUE THREAD

**Issue by max841** [tkrebs/ep3-bs#256]
Hallo,
gibt es eine Möglichkeit diese Fehlermeldung abzustellen.
Die Buchung funktioniert trotzdem.

Gruß Max

Exception details

Type

    Zend\Db\Adapter\Exception\RuntimeException

Mitteilung

    Must call beginTransaction() before you can rollback

File

   .../bsystem/vendor/zendframework/zendframework/library/Zend/Db/Adapter/Driver/Pdo/Connection.php:334

**Comment by tkrebs** [comment]
Schau mal hier:

https://github.com/tkrebs/ep3-bs/issues/53

**Comment by max841** [comment]
Vielen Dank für die Rückantwort.
Habe den Fehler gefunden. 
Einfach unter / config / autoload / local.php die Email Einstellungen setzen.
