### ISSUE TITLE
"Abo", als nicht registrierter Benutzer

### ISSUE THREAD

**Issue by LukaMarcel** [tkrebs/ep3-bs#258]
Hallo,
ich habe in meinem Kalender einige Plätze gebucht, damit sie von Benutzern nicht gebucht werden könne. Jedoch steht nun als nicht registrierter Besucher dort "Abo", welches Irreführend für meinen Zweck ist.
Gibt es eine Möglichkeit, das Wort zu ersetzen?
![image](https://user-images.githubusercontent.com/6438316/73435364-c3ce3980-4348-11ea-979c-e2e2ac6148d2.png)

Danke für jegliche Tipps!

**Comment by tkrebs** [comment]
Das Wort "Abo" kann generell über die Übersetzungsdatei beliebig geändert werden:

https://github.com/tkrebs/ep3-bs/blob/master/data/res/i18n/de-DE/booking.php

Besser noch als es direkt in dieser Datei zu ändern, ist die Datei booking.php in folgendes Verzeichnis zu kopieren und dort zu bearbeiten:

https://github.com/tkrebs/ep3-bs/tree/master/data/res/i18n-custom/de-DE

Dann wird sie bei einem etwaigen Update nämlich nicht überschrieben.
