### ISSUE TITLE
 Using array_key_exists() on objects is deprecated

### ISSUE THREAD

**Issue by klaus79** [tkrebs/ep3-bs#259]
Hallo ich bekomme leider immer eine Fehlermeldung 
( Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /var/www/html/ep3/vendor/zendframework/zend-i18n/src/Translator/Loader/PhpArray.php on line 52)
debian 9
Apache 
php 7.4
ist da hilfe möglich

**Comment by tkrebs** [comment]
Das Buchungssystem ist derzeit nicht mit PHP 7.4 kompatibel. Siehe https://github.com/tkrebs/ep3-bs/issues/265#issuecomment-614566473 für die Hintergründe.
