### ISSUE TITLE
Oops ... Unable to send mail: mail(): Policy restriction in effect. The fifth parameter is disabled on this system

### ISSUE THREAD

**Issue by cipmos** [tkrebs/ep3-bs#26]
Hallo!

Nach Abschluss einer Stornierung kommt diese Fehlermeldung:

"Oops ... da ist wohl etwas schief gelaufen
Unable to send mail: mail(): Policy restriction in effect. The fifth parameter is disabled on this system"

Eine Mail kommt trotzdem.

Woran liegt das und wie kann man das beheben?

Viele Grüße

**Comment by tkrebs** [comment]
Der Satz "Policy restriction in effect" beschreibt das Problem recht gut. Auf Ihrem Webserver wurden (eher ungewöhnliche) Einstellungen vorgenommen, welche den reibungslosen Betrieb des Buchungssystems beeinträchtigen.

**Comment by cipmos** [comment]
Vielen Dank für die schnelle Antwort! :-)
