### ISSUE TITLE
update auf vers. 1.6.3 nach php 7.3 update 

### ISSUE THREAD

**Issue by Markus030** [tkrebs/ep3-bs#261]
Gibt es eine Anleitung für DAUs? Habe update nach Anleitung gemacht. Jetzt Fehler: 

Deprecated: You are retrieving the service locator from within the class Calendar\Controller\CalendarController. Please be aware that ServiceLocatorAwareInterface is deprecated and will be removed in version 3.0, along with the ServiceLocatorAwareInitializer. You will need to update your class to accept all dependencies at creation, either via constructor arguments or setters, and use a factory to perform the injections. in /homepages/21/d34459434/htdocs/buchungentc/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php on line 258

Außerdem Layout zerschossen. Was tun? tcc.clubconsult.eu

**Comment by mpongo12** [comment]
Servus,
ich hab das gleiche problem (Issue #242).

- Für das Problem mit dem Zend Framework habe ich den workaround mit E_USER_DEPRECATED (https://stackoverflow.com/questions/35933113/php-deprecated-you-are-retrieving-the-service-locator-from-within-the-class-zft) benutzt.
- Bezüglich Layouts hab ich keine Ahnung. Hab jetzt mal nur den Schritt von 1.6 auf 1.6.2 getestet (also genau einen Schritt der Anleitung in data/docs), nutze das zip file (=> keine dependencies, die nachinstalliert werden müssen & -data/cache/ ist auch leer und wieder ist das Layout im Eimer...

Hast du es hinbekommen oder auch zurückgerollt? tcc.clubconsult.eu schaut ja jetzt nach einem vernünftigen Layout, zumindest im im Wartungsmodus, aus.

**Comment by Markus030** [comment]
Salut,
danke für die Antwort, aber ich komme immer noch nicht klar damit. Dafür kenne ich mich einfach nicht gut genug mit php aus. Ich bräuchte einfach eine Art Kochrezept, welcher Code genau in welcher Datei ergänzt oder ausgetauscht werden muss.
Ja im Wartungsmodus sieht es gut aus aber schau mal hier : https://tcc.clubconsult.eu/public/user/login
Hoffe noch immer, dass ich nicht das ganze Ding neu installieren muss... Wäre schade, die ganzen Texte usw. wieder neu anpassen zu müssen.

**Comment by Markus030** [comment]
Hallo, ich komme leider immer noch nicht klar. Kann mir jemand helfen? Habe mit meinem laienhaften Mitteln viel probiert aber das wird nichts. Sogar eine völlige Neuinstallation mit neuer Datenbank scheiterte. Hier die Fehlermeldungen: 

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /homepages/21/d34459434/htdocs/buchungentc/vendor/zendframework/zend-stdlib/src/ArrayObject.php on line 426

Deprecated: You are retrieving the service locator from within the class Calendar\Controller\CalendarController. Please be aware that ServiceLocatorAwareInterface is deprecated and will be removed in version 3.0, along with the ServiceLocatorAwareInitializer. You will need to update your class to accept all dependencies at creation, either via constructor arguments or setters, and use a factory to perform the injections. in /homepages/21/d34459434/htdocs/buchungentc/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php on line 258

Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /homepages/21/d34459434/htdocs/buchungentc/vendor/zendframework/zend-i18n/src/Translator/Loader/PhpArray.php on line 52

Zu sehen hier: tcc.clubconsult.eu

BITTE HILFE!

**Comment by tkrebs** [comment]
Die "Warning"- und "Deprecated"-Hinweise können einfach ausgeschaltet werden, indem in der Datei `config/init.php` in Zeile `13` der Debug-Modus deaktiviert wird:

```php
define('EP3_BS_DEV_TAG', false);
```

**Comment by tkrebs** [comment]
Die zuletzt genannten Fehlermeldungen sollten in Version 1.7.0 nun behoben sein.
