### ISSUE TITLE
$this->dateStart in index.landscape.phtml

### ISSUE THREAD

**Issue by matkoenig** [tkrebs/ep3-bs#265]
Bin am verzweifeln. Bekomme sowohl nach der Installation des fertigen Pakets bzw. Github nach dem Setup folgende Fehlermeldung:

__clone method called on non-object

D:\Users\Admin\Documents\Programmierung\Xampp\htdocs\ep3\module\Calendar\view\calendar\calendar\index.landscape.phtml:18

$this->dateStart scheint Null bzw. initial zu sein.

XAMPP auf Windows 10 ist frisch installiert. Irgendwelche Ideen, woran es liegt?

**Comment by tkrebs** [comment]
Die aktuelle XAMPP-Version wird mit PHP 7.4 ausgeliefert. Das dem Buchungssystem zugrunde liegende Zend Framework ist damit aber nicht kompatibel. Vorerst funktioniert das Buchungssystem also nur mit bis zu PHP 7.3, bis wir eine Lösung für das Problem gefunden haben.

**Comment by matkoenig** [comment]
Dann mache ich mal einen Downgrade auf 7.3. Vielen Dank für die schnelle Rückmeldung.
