### ISSUE TITLE
Buchungsmöglichkeiten einschränken

### ISSUE THREAD

**Issue by peterfuehrer** [tkrebs/ep3-bs#266]
Gibt es eine Möglichkeit die Buchungen einzuschränken, sodass ein Benutzer z.B. für heute nicht buchen kann sondern erst ab dem morgigen Tag?

Danke!

**Comment by gitroli** [comment]
ich suche so was ähnliches: wenn ein benutzer 2h Stunden gebucht hat, darf er erst wieder buchen wenn diese 2h Stunden gespielt sind oder storniert

**Comment by gitroli** [comment]
oder vielleicht ist diese variante einfacher zu realisieren, hat der benutzer eine buchung welche in der zukunft liegt, darf er nicht buchen

**Comment by peterfuehrer** [comment]
Ja, das wäre der nächste Schritt.. 
Da wir für jedes Training eine Aufsichtsperson brauchen (Auflage des Dachverbandes), da wäre es natürlich praktisch wenn Buchungen erst in 24h vom Login des Benutzers weg möglich wären.

**Comment by tkrebs** [comment]
Da diese beiden Funktionen ebenfalls für einen von uns betreuten Verein benötigt wurden, sind sie kurzfristig eingebaut worden. Im Detail gibt es zwei neue Einstellungsmöglichkeiten pro Platz:

1. **Buchungsvorlauf** (in Minuten): Kann z. B. auf 180 ("erst in drei Stunden") oder 720 ("erst in 12 Stunden", also praktisch am nächsten Tag) gestellt werden.

2. **Buchungen einschränken**: Anzahl gleichzeitig aktiver Buchungen pro Benutzer. Steht dies z. B. auf 1, kann nur 1 Buchung vorgenommen werden und die nächste dann erst wieder, wenn der Termin vorbei oder storniert ist.

Da diese Änderungen ganz frisch sind, gibt es noch keine neue Version und kein Download-Paket auf der Website. Es reicht aber aus, die aktuellen Dateien [über GitHub herunterzuladen](https://github.com/tkrebs/ep3-bs/archive/master.zip) und einfach **nur** das modules/-Verzeichnis auszutauschen.

**Comment by gitroli** [comment]
Ich habe selber ziemlich viele Anpassungen gemacht, könntest du die entsprechenden Module genauer angeben bzw. Files welche zu tausche sind oder sind es zu viele?

**Comment by tkrebs** [comment]
Die Änderungen sind im Wesentlichen in folgenden beiden Commits zusammengefasst:

1. Buchungsvorlauf: https://github.com/tkrebs/ep3-bs/commit/2ede9edc3d69d6be6469fc330c407a22aa069bac

2. Buchung einschränken: https://github.com/tkrebs/ep3-bs/commit/819cadb1a258b5b7c534c33349930c916172e59a

**Comment by peterfuehrer** [comment]
Super! Danke! das ist genau das was ich gebraucht habe!

**Comment by suedschwede** [comment]
Wäre es möglich die Anzahl der Buchungen pro Tag zu beschränken ?

**Comment by bytefactory73** [comment]
wie aktualisiert man die datenbank nachdem man den code aktualisiert hat? ich erhalte mit dem neuen code einen fehler beim versuch einer buchung.

**Comment by tkrebs** [comment]
Wie lautet die Fehlermeldung?

(die Datenbank braucht in der Regel keine Aktualisierung nach Updates)

**Comment by bytefactory73** [comment]
ich habe das problem gefunden. in den tennisplatzdefinitionen mußte man noch die (neuen) fehlenden werte eintragen.

**Comment by tkrebs** [comment]
Danke für die weitere Verfolgung dieses Problems. Ich habe eine entsprechende Verbesserung vorgenommen, bei der die Datenbank automatisch bei Bedarf angepasst wird.

**Comment by TCRW** [comment]
Moin,

habe das auch eingebaut, hat aber den Nachteil, dass die Benutzer auch für die nächsten Tage, bzw. nächste Woche keine Buchung mehr vornehmen können.

Es kommt die Meldung: Sie können derzeit nur eine Buchung offen haben.

**Comment by git-kraeMit** [comment]
> dass lediglich 1 Stunde auf dem gleichen Platz gespielt

Das könnten wir auch gebrauchen, wir wollen erreichen, das ein Mitglied nur 1 Stunde am Stück buchen kann. Leider gibt es keine ganze Reihe von Egoisten, die das nicht kapieren wollen/können.
Danke

**Comment by bytefactory73** [comment]
ich habe in meinem fork folgende änderungen eingebaut.

1. jeder spieler kann nur 2 buchungen in der zukunft machen (das ging per platz limit)
2. zwischen 2 buchungen eines spielers muß eine lücke von X stunden sein (bei uns 3h)
3. innerhalb der kommenden 2 stunden (jetzt bis + 2h) kann jeder spieler spontan auch eine zusätzliche dritte buchung machen wenn ein platz ungenutzt ist.

Falls ihr interesse an den änderungen habt, stelle ich die gern in einem feature branch zur verfügung.

**Comment by cbits68** [comment]
Dir Optionen 2 und 3 würden mich schon interessieren. Speziell 2 finde ich sehr sinnvoll.

**Comment by git-kraeMit** [comment]
Ich fände das sehr nett, wenn Du einen Feature Branch zur Verfügung stellen würdest. Auf welcher Version basiert der?

**Comment by bytefactory73** [comment]
ok, here we go. 

Ich habe meine Changes unter:

https://github.com/bytefactory73/ep3-bs/tree/dev/bookingmods

zusammengefasst und in den "Einstellungen" unter "Verhalten" hinzugefügt:

![image](https://user-images.githubusercontent.com/9210200/82755297-f659e180-9dd2-11ea-9907-ec3dffb06a1c.png)

Die Änderungen basieren auf der original 1.6.4 Version. Sollten sich also ohne Konflikte einfach reinmergen lassen.

LG

**Comment by TomTurbo78** [comment]
Hallo,
ist das Feature jetzt schon in einem Release enthalten?
SG
Tom

**Comment by git-kraeMit** [comment]
So wie ich das sehe, brauchst Du doch nur den aktuellen GIT Stand auschecken und hast die Änderungen. Sieht für mich so aus, als ob tkrebs die Änderungen von bytefactory73 gemerged hat am 26.06.

Gruß

**Comment by TomTurbo78** [comment]
Ich möchte auf ein stabiles Release verwenden. Wie kann man erkennen, ob und in welchem Release eine Änderung enthalten ist?
