### ISSUE TITLE
Umleitungsfehler

### ISSUE THREAD

**Issue by peterfuehrer** [tkrebs/ep3-bs#268]
Habe gerade einen Fehler entdeckt, wenn ich eine Datenschutzerklärung (pdf) hochlade und diese bei der Registrierung anklicke bekomme ich egal ob bei Firefox, Chrome, oder Edge den Fehler "ERR_TOO_MANY_REDIRECTS".
Habe ich da einen Fehler in der Konfiguration?

**Comment by tkrebs** [comment]
Klingt nach einem Problem mit der Apache-Webserver-Konfiguration.

Kannst du die Datei `public/docs-client/upload/.htaccess` einmal testweise und vorübergehend umbenennen (und damit deaktivieren)?

**Comment by peterfuehrer** [comment]
danke! hat geklappt, der fehler ist nach dem umbennennen der htaccess weg, das Dokument ist erreichbar.
