### ISSUE TITLE
Fehlermeldung beim Starten vom Setup 

### ISSUE THREAD

**Issue by IrethDT** [tkrebs/ep3-bs#269]
Hallo! 

ich bin leider ganz neu auf dem Gebiet und wollte gerne für meinen Verein das Bookingsystem testen. 

Wenn ich versuche das Setup zu starten kommt nun folgende Fehlermeldung: 

Fatal error: Method Zend\View\Helper\HeadTitle::__toString() must not throw an exception, caught Error: Class 'Zend\I18n\Translator\TextDomain' not found in /home/.sites/128/site4160389/web/booking-zeiselmauer/module/Setup/view/layout/layout.phtml on line 0 

Lese/Schreibberechtigungen habe ich zwei mal kontrolliert. 

Woran könnte es liegen? 

Danke und liebe Grüße 

Martina

**Comment by tkrebs** [comment]
Existiert die Datei

`vendor/zendframework/zend-i18n/src/Translator/TextDomain.php`

und steht da was drin? Vielleicht sind beim Kopieren/Übertragen einige Dateien verloren gegangen. Dann hilft es, das `vendor/`-Verzeichnis noch mal neu hochzuladen.
