### ISSUE TITLE
Tage ausblenden

### ISSUE THREAD

**Issue by ReneMuellerCH** [tkrebs/ep3-bs#27]
Hallo
Ich habe folgende Frage:
Kann ich einen Tag (zB Sonntag) dauerhaft über den ganzen Kalender ausblenden?

Danke und Gruss
R. Müller

**Comment by tkrebs** [comment]
Dies wird im kommenden größeren Update möglich sein. In der aktuellen Version ist es leider nicht möglich.

**Comment by MrSesame** [comment]
Meine Behelfslösung, bis es soweit ist:

in module > Calendar > view > calendar > calendar > index.landscape.phtml
steht ab Zeile 22 die Ausgabe der Kalenderspalten:

`while ($walkingDate <= $this->dateEnd) {
    echo sprintf('<td class="calendar-date-col %s">',
		  ($walkingIndex > 0 ? 'responsive-pass-' . (max(1, 5 - $walkingIndex)) : ''));`

Das habe ich geändert in:

`while ($walkingDate <= $this->dateEnd) {
    echo sprintf('<td class="calendar-date-col %s">',
		  ($walkingIndex > 0 ? 'responsive-pass-' . (max(1, 7 - $walkingIndex)) : '') . date_format($walkingDate," l"));`

Jede Tages-Spalte bekommt also per "walkingDate" eine zusätzliche Klasse, und zwar den jeweiligen Wochentag auf Englisch (erster Buchstabe groß!)
siehe http://php.net/manual/en/function.date.php
Jetzt kann ich Sams- und Sonntag mit den Klassen `.Saturday` und `.Sunday` per css ansprechen und z.B. per `display: none` ausblenden.

Wobei das natürlich so seine Tücken hat, weil so die Anzahl der angezeigten Tage variieren kann, je nach Anzahl der Tage nebeneinander. Vielleicht ist grau färben die bessere Lösung :)

**Comment by tkrebs** [comment]
Das ist mittlerweile implementiert (Einstellungen > Verhalten > Folgende Tage verstecken).
