### ISSUE TITLE
Fehler bei neuer Registrierung

### ISSUE THREAD

**Issue by milack68** [tkrebs/ep3-bs#270]
Wenn sich ein neuer User registrieren möchte bekommt er nach Absenden des Formulars folgenden Fehler angezeigt:

`Could not open socket: stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known`

Auch die E-Mail zur Bestätigung wird nicht gesendet. Woran könnte das liegen? Habe php 7.3. - ein Problem?

**Comment by tkrebs** [comment]
Die Fehlermeldung ist etwas knapp, klingt aber danach, als dass die Prüfung nicht funktioniert, ob es sich bei der eingegeben E-Mail-Adresse um eine echte, im Internet erreichbare Domain handelt. Kann das sein?

Testweise könntest du folgende Zeile löschen:

https://github.com/tkrebs/ep3-bs/blob/master/module/User/src/User/Form/RegistrationForm.php#L301

**Comment by milack68** [comment]
Habe die Zeile auskommentiert - leider keine Änderung. Die Mailadressen sind auch echte, im Internet erreichbare Domains (habe es auch mit meiner gmail Adresse probiert).
Kann ich irgendwo testen, ob der Mailversand aus dem Programm heraus generell funktioniert?

**Comment by milack68** [comment]
Ich habe das Problem insofern vom Tisch, als ich den debug modus in der init.php auf true gesetzt habe. Ich versteh's zwar nicht, aber das System läuft jetzt stabil und ohne Fehlermeldungen.
