### ISSUE TITLE
__clone method called on non-object

### ISSUE THREAD

**Issue by Holger690** [tkrebs/ep3-bs#272]
Type:Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /var/www/Tennis/vendor/zendframework/zend-i18n/src/Translator/Loader/PhpArray.php on line 52
Error:
Mitteilung:
__clone method called on non-object
File
/var/www/Tennis/module/Calendar/view/calendar/calendar/index.landscape.phtml:18
Stack trace
#0 /var/www/Tennis/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(506): include()
#1 /var/www/Tennis/vendor/zendframework/zend-view/src/Helper/Partial.php(61): Zend\View\Renderer\PhpRenderer->render()
#2 [internal function]: Zend\View\Helper\Partial->__invoke()
#3 /var/www/Tennis/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(397): call_user_func_array()
#4 /var/www/Tennis/module/Calendar/view/calendar/calendar/index.phtml(14): Zend\View\Renderer\PhpRenderer->__call()
#5 /var/www/Tennis/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(506): include('/var/www/Tennis...')
#6 /var/www/Tennis/vendor/zendframework/zend-view/src/View.php(207): Zend\View\Renderer\PhpRenderer->render()
#7 /var/www/Tennis/vendor/zendframework/zend-view/src/View.php(236): Zend\View\View->render()
#8 /var/www/Tennis/vendor/zendframework/zend-view/src/View.php(200): Zend\View\View->renderChildren()
#9 /var/www/Tennis/vendor/zendframework/zend-view/src/View.php(236): Zend\View\View->render()
#10 /var/www/Tennis/vendor/zendframework/zend-view/src/View.php(200): Zend\View\View->renderChildren()
#11 /var/www/Tennis/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(105): Zend\View\View->render()
#12 [internal function]: Zend\Mvc\View\Http\DefaultRenderingStrategy->render()
#13 /var/www/Tennis/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func()
#14 /var/www/Tennis/vendor/zendframework/zend-eventmanager/src/EventManager.php(248): Zend\EventManager\EventManager->triggerListeners()
#15 /var/www/Tennis/vendor/zendframework/zend-mvc/src/Application.php(384): Zend\EventManager\EventManager->triggerEvent()
#16 /var/www/Tennis/vendor/zendframework/zend-mvc/src/Application.php(356): Zend\Mvc\Application->completeRequest()
#17 /var/www/Tennis/public/index.php(75): Zend\Mvc\Application->run()
#18 {main}

**Comment by Holger690** [comment]
Hallo
Installiert ist das System
Debian 10
PHP 7.4

**Comment by tkrebs** [comment]
Das Buchungssystem ist derzeit nicht mit PHP 7.4 kompatibel, siehe https://github.com/tkrebs/ep3-bs/issues/265#issuecomment-614566473 für die Hintergründe.
