### ISSUE TITLE
Zwei "Anzeige"-Probleme direkt nach Installation

### ISSUE THREAD

**Issue by holgerbusch** [tkrebs/ep3-bs#274]
Hallo,
zuerst muss ich mich für das Projekt bedanken. Es gibt unzählige kommerzielle Produkte am Markt und ich finde es genial, dass es hier ein auch Open Source Projekt gibt.

Leider habe ich zwei Probleme, die gerade dafür sorgen, dass das Buchungssystem bei uns gerade nicht genutzt werden kann. 
Ich habe die Installation ohne Probleme durchgeführt.
1. Nach der Installation erscheint oben am Rand die Zeile
"Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /homepages/5/d706071746/htdocs/hosting/ep3_booking/vendor/zendframework/zend-stdlib/src/ArrayObject.php on line 426"

2. Nachdem ich meine Logindaten eingetragen haben, werde ich auf user/login weitergeleitet und erhalte einen "Internal Server Error". Dabei spielt es keine Rolle ob ich korrekte oder falsche Logindaten eintrage. 
 
S, Screenshot 
![ep3-1](https://user-images.githubusercontent.com/33656326/80300632-b20cfe80-879e-11ea-844b-597a31b7737a.PNG)

Über Hilfe wäre ich dankbar. 

Liebe Grüße

**Comment by holgerbusch** [comment]
Ich habe vergessen:

Ich habe mit das ep3-bs-package-1.6.3c.zip Paket von der Webseite heruntergeladen.

**Comment by holgerbusch** [comment]
Okay, Nummer ein können wir abhaken.
Ich habe die Hinweise wie unter https://github.com/tkrebs/ep3-bs/issues/261#issuecomment-618281095 beschrieben abgeschaltet.

Aber das Loginproblem bleibt. 
Gleiches Ergebnis, wenn ich auf "Registrieren" klicke und auf /user/registration weitergeleitet werde.
Dann kommt auch der 500 internal server error.

**Comment by tkrebs** [comment]
Der "Internal Server Error" klingt nach einem Problem mit dem Apache (Webserver) Modul "mod_rewrite", siehe https://github.com/tkrebs/ep3-bs/issues/15#issuecomment-140542572 und folgend. Dort sind einige Lösungsansätze beschrieben.

**Comment by holgerbusch** [comment]
Hey, danke für den Tipp.
ich habe die RewriteBase mit einer Raut auskommentiert - aber das bringt mich nicht weiter.

In der .htaccess steht nun

<IfModule mod_rewrite.c>

    RewriteEngine On
    #RewriteBase /   # Try to uncomment this if you experience redirect problems

    RewriteCond %{ENV:REDIRECT_STATUS} ^$
    RewriteRule ^index\.php$ http://stand.ssc-soest-sued.de/ [R=301,L]

    RewriteCond %{ENV:REDIRECT_STATUS} ^$
    RewriteRule ^index\.php/(.*)$ http://stand.ssc-soest-sued.de/$1 [R=301,L]

    RewriteRule ^robots\.txt$ misc/robots.txt
    RewriteRule ^favicon\.ico$ imgs-client/icons/fav.ico

    RewriteCond %{REQUEST_FILENAME} -s [OR]
    RewriteCond %{REQUEST_FILENAME} -l [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^.*$ - [L]
    RewriteRule ^.*$ index.php [L]

</IfModule>

**Comment by Bakati** [comment]
Hi die Zeile sollte so aussehen
RewriteEngine On
RewriteBase / 

Ohne Raute Zeichen davor.

**Comment by holgerbusch** [comment]
Hey, danke dir für die Hilfe.


Es geht also nur um die eine Zeile, wo die Raute weg muss?

 

 

Lieben Gruß

Holger Busch

 

Von: Bakati [mailto:notifications@github.com] 
Gesendet: Sonntag, 26. April 2020 23:16
An: tkrebs/ep3-bs <ep3-bs@noreply.github.com>
Cc: holgerbusch <info@holgeronline.de>; Author <author@noreply.github.com>
Betreff: Re: [tkrebs/ep3-bs] Zwei "Anzeige"-Probleme direkt nach Installation (#274)

 

Hi die Zeile sollte so aussehen
RewriteEngine On
RewriteBase /

Ohne Raute Zeichen davor.

**Comment by Bakati** [comment]
Ja ich hatte das Problem auch. LG

**Comment by holgerbusch** [comment]
> Ja ich hatte das Problem auch. LG

Okay, ich werde mal versuchen das mit 1und1 zu klären. 
.... In der Hoffnung, dass es nur diese Zeile ist...

**Comment by HendrikRe** [comment]
@holgerbusch. Ich hoste mein System auch bei 1&1-Ionos, und habe trotz Ahnung von HTML/PHP das Problem bis jetzt nicht lösen können. Könntest du eventuell deine .htaccess hier posten, bzw was zu verändert hast damit es funktioniert?

**Comment by Shineson1001** [comment]
Hi @HendrikRe,
hast du die .htaccess Einstellungen schon getestet?
https://github.com/tkrebs/ep3-bs/issues/297#issuecomment-624854533

**Comment by HendrikRe** [comment]
@Shineson1001 tuts nicht, aber die .htaccess meiner Wordpress-Installation machts perfekt. Muss mal in ruhe debuggen. Trotzdem danke

**Comment by holgerbusch** [comment]
Guten Morgen zusammen,
ich habe ep3 bei 1und1 ans Laufen gebracht. 
Gleich direkt: Es werden keinerlei Änderungen seitens des Providers gemacht, wenn man einen einfachen Webhostingvertrag hat. Null. Es werden keine php-Dateien angepasst und keine Konfig des Apache. 
Ich betreue knappe 20 Joomla-Webseiten bei 1und1 und habe noch nie wirkliche Probleme gehabt. Das war meine erste "Negativerfahrung" bei 1und1 - wenn man das so nennen will. Ich bleibe trotzdem dort : )

Auch wenn es lief - ich habe mich gegen ep3 entschieden. 
Denn uns fehlte die Funktion, dass z.B. unterschiedliche Zeiten an unterschiedlichen Wochentagen gebucht werden können.
Wir sind ein Sportschützenverein und trainieren zu unterschiedlichen Zeiten an den Tagen. 
Dazu habe ich die E-Mailbenachrichtigung nicht ans Laufen bekommen. Egal wie mit oder ohne Verschlüsselung oder welchen denkbaren Port - es hat nicht geklappt. 
Da mir die Zeit weglief und ich eine funktionierende Lösung brauchte, habe ich mich für modernbooking entschieden: https://www.modernjoomla.com/joomla-extensions/modern-booking/
Das war einfach einzurichten, denn Joomla-Fragen kann ich morgens um 4 beantworten, wenn ich geweckt werde. Wer gucken möchte, wie es läuft, schreibt mich bitte kurz an. Den Link möchte ich hier nicht öffentlich posten. 

Vielleicht habe ich mich auch bei der htaccess total verhaspelt. 
Ich habe komplett neu begonnen und mit der htaccess mit folgenden Inhalt lief es auf anhieb:

<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /

    RewriteRule ^(favicon\.ico)$ imgs-client/icons/fav.ico [L]
    RewriteRule ^(robots\.txt)$ misc/$1 [L]

    RewriteCond %{REQUEST_FILENAME} -s [OR]
    RewriteCond %{REQUEST_FILENAME} -l [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^.*$ - [NC,L]

    RewriteCond %{REQUEST_URI}::$1 ^(/.+)(.+)::\2$
    RewriteRule ^(.*) - [E=BASE:%1]
    RewriteRule ^(.*)$ %{ENV:BASE}index.php [NC,L]

</IfModule>


Liebe Grüße aus Soest
Holger
