### ISSUE TITLE
Buchungen ausdrucken

### ISSUE THREAD

**Issue by Bakati** [tkrebs/ep3-bs#276]
Gibt es eine Möglichkeit, täglich alle Buchungen für alle Plätze inklusive den Spielernamen, Spielzeiten ausdrucken zu können? Wegen Corona Krise müssen wir es dokumentieren.
Danke

**Comment by peterfuehrer** [comment]
ja, der Kalender ist druckfreundlich. 
Einfach als Benutzer der die Namen angezeigt bekommt anmelden und danach so vorgehen wie bei einem normalen Ausdruck, funktioniert super. Anbei ein Beispieldruck als pdf.
[BCUW Scheibenreservierung.pdf](https://github.com/tkrebs/ep3-bs/files/4553002/BCUW.Scheibenreservierung.pdf)

**Comment by Bakati** [comment]
Toll. Vielen Dank
