### ISSUE TITLE
Exception details Fehler nach Buchung (User)

### ISSUE THREAD

**Issue by Holger690** [tkrebs/ep3-bs#278]
Guten Abens Herr Krebs,
erst mal danke für die erste Hilfe !
Ich habe nun noch ein Problem beim Buchen.
Die Einstellung ist Sofortige Anmeldung von User ohne Mail.
Die Aplikation läuft nun und ich als Admin kann Buchungen vornehmen.
Wenn nun ein User eine Buchung erstellt und auf Jetzt buchen drückt ,,Buchung abschließen,,wird die Buchung angelegt aber mit einer Exception Fehlermeldung:
Das gleiche passiert bei Buchung Stornieren.#
#Exception Details#
Type
Zend\Db\Adapter\Exception\RuntimeException
Mitteilung
Must call beginTransaction() before you can rollback
File
/var/www/tennis/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Connection.php:352
Stack trace
#0 /var/www/tennis/module/Booking/src/Booking/Service/BookingService.php(130): Zend\Db\Adapter\Driver\Pdo\Connection->rollback()
#1 /var/www/tennis/module/Square/src/Square/Controller/BookingController.php(180): Booking\Service\BookingService->createSingle(Object(User\Entity\User), Object(Square\Entity\Square), 1, Object(DateTime), Object(DateTime), Array, Array)
#2 /var/www/tennis/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(84): Square\Controller\BookingController->confirmationAction()
#3 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#4 /var/www/tennis/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#5 /var/www/tennis/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#6 /var/www/tennis/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(116): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#7 /var/www/tennis/vendor/zendframework/zend-mvc/src/DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#8 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#9 /var/www/tennis/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#10 /var/www/tennis/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /var/www/tennis/vendor/zendframework/zend-mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#12 /var/www/tennis/public/index.php(75): Zend\Mvc\Application->run()
#13 {main}

**Comment by nlbgr** [comment]
Wenn man unter config/init.php den Entwicklermodus aktiviert hat, läuft das Buchungssystem ohne Probleme. Dafür (trotz anders aussagendem Kommentar) die Zeile `define('EP3_BS_DEV_TAG', true);` auf true setzen bzw. lassen. Hat danach funktioniert.
Wenn hier false gesetzt ist, werden php-Fehlermeldungen angezeigt.

**Comment by Holger690** [comment]
Guten Abend,
die Datei define('EP3_BS_DEV_TAG', true); steht bei mir auf true
Wenn ich Sie auf false stelle kommt diese Fehlermeldung.
Oops ... da ist wohl etwas schief gelaufen
Must call beginTransaction() before you can Rollback
Die Fehlermeldungen kommen auch nur bei benutzer
Wenn ich Mitarbeiter Rechte vergebe das funktioniert alles prima.
Ist es denn Möglich eine Grundeinstellung zu definieren.
Wenn sich jemand neu registriert:
Mitarbeiter Rechte
mit eingeschränkten Rechten?
Vielen Dank vorab für die Hilfe
Gruß
Holger Rudershausen

**Comment by Shineson1001** [comment]
Hi,
ja, die Anwendung ist sehr empfindlich bei der Fehlerbehandlung .. auch bei unkritischen Problemen wird der Benutzer nichts-sagende Meldung verunsichert.

Ich gehe davon aus, dass die Buchung ordnungsgemäß bei dir gespeichert wird, oder?
Wenn ja, dann weiß ich auch nicht was das "Connection->rollback()" aufsich hat. ... zum Glück wurde der Datenbank-Befehl nicht "beginTransaction()" initialisiert .. sonst würde wahrscheinlich die Buchung wieder entfernt werden. :-)

**Comment by Holger690** [comment]
Guten Abend,
nun habe ich das Problem, das eine Buchung mit normalem Benutzer nicht abgeschlossen wird.
Das Fenster Buchung Abschließen blockiert.
Als Mitarbeiter funktionieren die Buchungen
Können Sie mir hier helfen?

**Comment by tkrebs** [comment]
Das hängt möglicherweise mit deinen E-Mail-Versand-Problemen zusammen.

Wenn du den E-Mail-Versand a) per Konfiguration korrigierst oder b) wie in https://github.com/tkrebs/ep3-bs/issues/286#issuecomment-623447502 beschrieben entfernst, sollte auch dieses Problem verschwinden.
