### ISSUE TITLE
Wiederkehrende Termine (wöchentlich)

### ISSUE THREAD

**Issue by ReneMuellerCH** [tkrebs/ep3-bs#28]
Hallo
Ich habe folgenden Fehler bei Eingabe eines wiederholenden Termins (wöchentlich):
"Invalid date range passed for reservation creation"
Was ist da falsch?

Danke und Gruss
R. Müller

**Comment by tkrebs** [comment]
Das klingt nach einem Fehler bei der Eingabe des Start- und Enddatums. Bitte stellen Sie sicher, dass die Datum-Angaben korrekt geschrieben sind (bzw. mit dem Datepicker ausgewählt wurden), und dass das Startdatum nicht **nach** dem Enddatum liegt.
