### ISSUE TITLE
Massen-Import von Benutzern?

### ISSUE THREAD

**Issue by bytefactory73** [tkrebs/ep3-bs#281]
Gibt es einen Weg per csv Tabelle alle Vereinsmitglieder in einem Rutsch zu registrieren/anzulegen?

Wir würden die Registrierung gern gesperrt lassen und alle Benutzer selbst anlegen.

Danke

**Comment by Shineson1001** [comment]
Hi,
ich glaube diese Funktion gibt es nicht ... ich würde das per SQL-Statements löschen

Beispiel für einen neuen Benutzer:
`INSERT INTO bs_users (alias, status, email, pw, login_attempts, login_detent, last_activity, last_ip, created) VALUES('meinvorname meinnachname', 'disabled', 'meiltest0123@web.de', '$2y$06$4DtpRP3v8x1Bmkb8e846/uWlWnry8eQFGV0E4aH.EseR8FWc15Mei', NULL, NULL, NOW(), '127.0.0.1', NOW());`

**Comment by GregLoichot** [comment]
It could be very useful. 
You cannot import directly in database because the password must be encrypted. 

Please add mass import 👍

**Comment by feslfan** [comment]
Could the import work and the users have to just reset their password?

**Comment by tkrebs** [comment]
#370
