### ISSUE TITLE
Fehlermeldung in Anzeige der Buchung --> BookingController.php

### ISSUE THREAD

**Issue by fgiesecke** [tkrebs/ep3-bs#282]
Hallo,
ich habe den aktuellen Stand vom GIT eingespielt und erhalte nun im Backend eine Fehlermeldung wenn ich mir Buchungen ansehe.
Warning: Invalid argument supplied for foreach() in /html/tennisplatz/ep3-bs-package-1.6.3c/module/Backend/src/Backend/Controller/BookingController.php on line 219

Die Meldung taucht nicht bei allen Buchungen auf, das Muster konnte ich noch nicht richtig ermitteln.
![2020-05-01_09-22-48](https://user-images.githubusercontent.com/7612848/80789899-ac902980-8b8d-11ea-9313-26b1ad7e82b3.png)

Ein Blick in den Code hat mich spontan auch nicht auf den Fehler gestoßen, vielleicht hat jemand von euch das schon erlebt?

LG
Florian

**Comment by tkrebs** [comment]
Die in der Fehlermeldung angegebene Zeile Code soll die Namen weiterer Mitspieler ausgeben:

https://github.com/tkrebs/ep3-bs/blob/master/module/Backend/src/Backend/Controller/BookingController.php#L219

Offenbar gibt es dann aber bei Buchungen ohne weitere Mitspieler Probleme. Ich schaue es mir an.

**Comment by tkrebs** [comment]
Ist korrigiert
