### ISSUE TITLE
Placeholder löschen

### ISSUE THREAD

**Issue by DanielM1991** [tkrebs/ep3-bs#284]
Hallo zusammen, 

ich habe in der Datenbank _bs_users_ sämtliche Placeholder gelöscht. Jedoch werden sie mir weiterhin beim manuellen eintragen einer Buchung angezeigt. Wo könnten die noch drin hängen? 

Ich möchte für diese Saison nicht alle Placeholder aus 2019 angezeigt bekommen, sondern bei Bedarf eben neue Anlegen. 

Vielen Dank schon mal!

**Comment by Shineson1001** [comment]
Hi Daniel,
werden die Benutzer in den Einstellungen->Benutzer auch noch angezeigt?

**Comment by DanielM1991** [comment]
Hallo, 
nein, dort sind sie nicht mehr vorhanden. 

Grüße
Daniel

**Comment by Shineson1001** [comment]
Kommen die Namen evtl. von der Browser Autovervollständigung? Wird hinter dem Namen die interne User-ID in runden Klammern angezeigt?

**Comment by DanielM1991** [comment]
Nein, definitiv nicht aus dem Browser-Verlauf. Die User-ID wird auch noch angezeigt. Verständlich ist es für mich nicht :-)

**Comment by Shineson1001** [comment]
Hi,
evtl. kommen die Daten aus dem Ordner "/data/cache" .. den einfach mal leeren.

**Comment by DanielM1991** [comment]
Ich habe gerade mal am FTP nachgeschaut. Der /Data/Cache ist bzw. war auch leer...
Hast du vielleicht noch einen Tipp?

**Comment by cbits68** [comment]
sind vielleicht noch Buchungen/Stornierungen  aus der Vergangenheit auf die Platzhalter vorhanden, oder hast Du die auch alle gelöscht?

**Comment by DanielM1991** [comment]
Die Buchungen habe ich auch gelöscht. Also ALLE Buchungen und ALLE Placeholder. Ich hab jetzt  als IT'ler nicht viel Ahnung von Datenbanken weiß aber, dass ich die definitiv aus der DB gelöscht habe. Mir fällt dazu nichts mehr ein...

**Comment by cbits68** [comment]
Hallo Daniel,
als IT'ler mit Datenbankerfahrung würde ich wie folgt vorgehen.
1. direkt in der Datenbank über Suche sicherstellen, dass die Einträge auch wirklich nincht mehr in der DB sind (entweder auf dem Server über phpMyAdmin falls installiert, oder über den PC mittels HeidiSQL)
2. Wenn die Suche tatsächlich ergibt dass die Einträge nicht mehr in der DB sind, bleibt nur noch die Möglichkeit dass diese in einem Cache zwischengespeichert sind. Das kann auf dem Server sein, im Browsercache auf dem Client oder , falls genutzt, auf einem Proxyserver im Netzwerk.

Ich habe es bei mir mal getestet und Platzhalter erstellt und gelöscht (über das Backend). Die waren danach bei mir auch tatsächlich nicht mehr bei einer Buchung angezeigt.

Gruß
Andreas

**Comment by DanielM1991** [comment]
Vielen Dank für den Tipp! 

Gleich mal gesucht und fest gestellt, dass ich tatsächlich so viele registrierte Benutzer habe! Meiner Ansicht nach, hätten das weniger sein müssen. 

Somit lag der Fehler bei mir. Die Placeholder sind tatsächlich gelöscht, wenn Sie in der DB gelöscht werden.
