### ISSUE TITLE
Buchungsfehler beim normalen Benutzer

### ISSUE THREAD

**Issue by Holger690** [tkrebs/ep3-bs#285]
Hallo Herr Krebs
Habe die init.php angepasst ,,define('EP3_BS_DEV_TAG', true);
Jedoch keinen Erfolg
Oops ... da ist wohl etwas schief gelaufen
Must call beginTransaction() before you can rollback

Bitte informieren Sie uns bei exotischen oder nicht nachvollziehbaren Fehlermeldungen, 
damit wir das Problem schnell beheben können. 

Zurück zur Startseite 

Exception details
Type
Zend\Db\Adapter\Exception\RuntimeException
Mitteilung
Must call beginTransaction() before you can rollback
File
/var/www/tennis/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Connection.php:352
Stack trace
#0 /var/www/tennis/module/Booking/src/Booking/Service/BookingService.php(130): Zend\Db\Adapter\Driver\Pdo\Connection->rollback()
#1 /var/www/tennis/module/Square/src/Square/Controller/BookingController.php(180): Booking\Service\BookingService->createSingle(Object(User\Entity\User), Object(Square\Entity\Square), '2', Object(DateTime), Object(DateTime), Array, Array)
#2 /var/www/tennis/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(84): Square\Controller\BookingController->confirmationAction()
#3 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#4 /var/www/tennis/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#5 /var/www/tennis/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#6 /var/www/tennis/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(116): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#7 /var/www/tennis/vendor/zendframework/zend-mvc/src/DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#8 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#9 /var/www/tennis/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#10 /var/www/tennis/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /var/www/tennis/vendor/zendframework/zend-mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#12 /var/www/tennis/public/index.php(75): Zend\Mvc\Application->run()
#13 {main}

**Comment by Holger690** [comment]
init.php angepasst ,,define('EP3_BS_DEV_TAG', false);
Dann kommt die Fehlermeldung:
Oops ... da ist wohl etwas schief gelaufen
Must call beginTransaction() before you can rollback

Können Sie mir hier bitte weiterhelfen  ?
Gruß
H.Rudershausen

**Comment by tkrebs** [comment]
Siehe https://github.com/tkrebs/ep3-bs/issues/278
