### ISSUE TITLE
Buchung Stornieren 

### ISSUE THREAD

**Issue by Holger690** [tkrebs/ep3-bs#286]
Beim Buchung Stornieren kommt folgender Fehler:
Oops ... da ist wohl etwas schief gelaufen
5.7.0 Must issue a STARTTLS command first. b191sm4689048wmd.39 - gsmtp 

Wie kann ich dieses beheben ?

**Comment by Shineson1001** [comment]
Hi,
da passt was mit den Maileinstellungen nicht ... leider sind die sehr indiviuell, sprich von Mail-Provider zu Mail-Provider sehr unterschiedlich. 

Man braucht die richtige Kombination aus Verschlüsselungstyp, Protokoll und Serverport. Die genauen Infos bekommt man vom Provider.

**Comment by Holger690** [comment]
Kann ich diese Funktion abschalten ?
Denn ich benutze das System nur zur Platzbuchung und benötige keine Mail Reservierung mit Bestätigungsmail.

**Comment by Shineson1001** [comment]
Hi,
Mails kommem IMHO nur beim Registrieren und beim Buchen ins Spiel.
Prüf mal die Einstellungen:
"Einstellungen"->"Namen und Texte"->[ ] Sende Benutzer-E-Mails wie Buchungs- oder Stornierungsbestätigungen als Kopie an diese Adresse

"Einstellungen"->"Verhalten"->"Aktivierung" auf "Per Verwaltung"

**Comment by tkrebs** [comment]
Die E-Mails werden im Wesentlichen in zwei Dateien versendet:

Buchungen und Stornierungen:
https://github.com/tkrebs/ep3-bs/blob/master/module/Booking/src/Booking/Service/Listener/NotificationListener.php

Registrierung, Aktivierungen, Passwort-Vergessen, Einstellungen:
https://github.com/tkrebs/ep3-bs/blob/master/module/User/src/User/Controller/AccountController.php

Dort gibt es jeweils im Code verstreut `...mailService->send(...`-Zeilen. Du kannst prinzipiell in deinem Editor danach suchen und diese entfernen.

Ich habe zudem eine Einstellung zum Abschalten des E-Mail-Versands als Verbesserungswunsch notiert.

**Comment by schwarzekatze005** [comment]
Lassen sich die Stornierungen, die von einem Verwalter durchgeführt werden, auch via E-Mail Notification an den Benutzer verschicken?

**Comment by cbits68** [comment]
siehe #174 
macht eigentlich nicht wirklich Sinn, denn nur der Verwalter kennt den Grund für die Löschung/Stornierung und die bekommst Du nicht in eine automatische Mail an den Buchenden ...

**Comment by dc-de** [comment]
es macht zwar keinen sinn aber wo im code kann ich das wie aktivieren das doch vom Verwalter gemachte Stornierungen als Email raus gehen?
