### ISSUE TITLE
Update to Zend Framework 3 (Laminas) ?

### ISSUE THREAD

**Issue by cbits68** [tkrebs/ep3-bs#287]
Hi, ist es schon geplant die Zend Framework Umgebung (2.5) mal auf einen aktuelleren Stand zu bringen? Zumal ja das ZF Projekt jetzt auf Laminas umbenannt wurde.
Bei der Installation oder beim Update über Composer bekomme man ja bereits einige Hinweise, welche Komponenten "outdated" sind und nicht mehr genutzt werden sollten.
Auch einige Layout Probleme im Frontend, sowie im Backend scheinen Ihre Ursache ja in einer schlechteren Kompatibilität mit php Version 7.X zu haben.
Auch soll die Geschwindigkeit mit der 3er Version gegenüber ZF 2.X um bis zu 4 Mal schneller sein.
Wäre sicher interessant das mal zu testen, oder hat Jemand von Euch schon eine angepasste composer.lock für die ZF 3? Zumal ich davon ausgehe, dass dann ggf. auch einige Stellen im php Code überarbeitet werden müssten :-(

Gruß
Andreas

**Comment by tkrebs** [comment]
Die nächste Generation des Buchungssystems befindet sich bereits in Entwicklung und basiert dann auch tatsächlich auf Laminas, allerdings auf deren Middleware-Architektur [Mezzio](https://docs.mezzio.dev/mezzio/), nicht mehr auf MVC. Dabei muss so viel umgeschrieben werden, dass es also streng genommen kein einfaches Update der ZF-Umgebung im aktuellen Buchungssystem ist.

**Comment by cbits68** [comment]
Das habe ich mir auch schon gedacht und mich gefragt.,ob sich der Zwischenschritt auf ZF 3 dann überhaupt lohnt, bzw. sinnvoll wäre.
Sicher nur dann, wenn der Aufwand der Umstellungen nur marginal wären. 
Ich hoffe nur, dass bei der neuen Version mit Laminas dann nicht die Datenbank neu erstellt muss und damit alle Benutzer sich neu registrieren müssten. Wenn es aber nicht so einfach mit einer DB Konvertierung geht, ist es dann halt so...
Danke für die Info!

**Comment by tkrebs** [comment]
Es wird auf jeden Fall ein Übertragungswerkzeug geben, um die Benutzer, Buchungen und (Platz-)Einstellungen in das neue System zu übernehmen.

Der Aufwand der ZF3-Umstellung dürfte sich ggf. für Betreiber lohnen, die zwingend auf PHP 7.3+ umsteigen müssen oder wollen. Die Entwicklung konzentriert sich aber gerade ausschließlich auf die neue Version.

**Comment by tkrebs** [comment]
#372
