### ISSUE TITLE
Entfernen der telefonischen Buchungsoption

### ISSUE THREAD

**Issue by cbits68** [tkrebs/ep3-bs#289]
Hallo,
ich würde gern das Feld Telefonische Buchung komplett (inklusive Telefonicon) )ausblenden.
In welcher php Datei kann man das "auskommentieren", so dass es nicht mehr angezeigt wird? 

Gruß
Andreas

**Comment by cbits68** [comment]
laut HTML Code handelt es sich um
<div id="topbar-phone" class="responsive-pass-4">
                    <p>
                        <span class="light-gray">Telefonische Buchung</span><br>
                        <span class="large-text">
                            <a href="tel:nicht verfügbar" class="unlined white">
                                nicht verfügbar                            </a>
                        </span>
                    </p>
                </div>
und ggf. den darauf folgenden Separator
<div id="topbar-separator" class="responsive-pass-4"></div>

**Comment by tkrebs** [comment]
Entweder per CSS (empfohlen, da flexibler) in dieser Datei:

https://github.com/tkrebs/ep3-bs/blob/master/public/css-client/default.css

Oder aus dem Template entfernen in dieser Datei:

https://github.com/tkrebs/ep3-bs/blob/master/module/Base/view/layout/layout.phtml#L70

**Comment by cbits68** [comment]
Danke Tobias,
ich habe erst mal Variante 2 gewählt. Funktioniert!

Gruß
Andreas

**Comment by GitHias** [comment]
Ich würde die Option nur nach Login sichtbar machen, habe aber Probleme auf den User im Base Module zuzugriefen, kann mir da jemand einen Tip geben?
