### ISSUE TITLE
No Admin button in pannel

### ISSUE THREAD

**Issue by serakos** [tkrebs/ep3-bs#29]
Hi,
First I would like to thank you for your nice S/W.
I have already install Version 1.5 and after the set up I go to the main page
1) I don't have the administration button for administer modules although in the MySQL the user has admin status.
2) when I try to register a new user for booking  I get the following error 
"Oops ... something went wrong here
You cannot use Zend\Crypt\Symmetric\Mcrypt without the Mcrypt extension"

Please Help

**Comment by tkrebs** [comment]
Hi, it seems the webserver you have installed the system on does not have the **PHP mcrypt extension** installed. I suppose this is the reason for both problems. If you have a local webserver, you can install/enable this extension yourself. Otherwise you need to contact your webspace provider.

**Comment by serakos** [comment]
It is already installed!!!

**Comment by serakos** [comment]
OK I enabled mycrypt extension and i can register now BUT STILL the
administration BUTTON is not VISIBLE.
Can you please help me?
Thanks

**Comment by serakos** [comment]
Sorry Mate finally I managed to make it Work!!! Thank you !!

**Comment by tkrebs** [comment]
I am happy you managed it. I close this issue then.
