### ISSUE TITLE
Base module not found

### ISSUE THREAD

**Issue by larsrich** [tkrebs/ep3-bs#290]
Hallo!
Leider habe ich das Problem, dass ich mir die Fehlermeldung base module not found angezeigt wird.
Die im bereits geschlossenen Issue genante Datei ist vorhanden und die Änderung der Leseberechtigung habe ich auch ausprobiert.
Hat jemand noch eine andere Idee / Lösung?
Vielen Dank schonmal!

**Comment by tkrebs** [comment]
Diese Meldung erscheint, wenn die Datei `module/Base/Charon.php` von PHP nicht lesbar ist:

https://github.com/tkrebs/ep3-bs/blob/master/public/index.php#L44

**Comment by larsrich** [comment]
Danke für die schnelle Antwort!
Die Datei hat entsprechende Rechte, die Fehlermeldung erscheint leider immer noch.

**Comment by luke8800gts** [comment]
Ich hatte den selben Fehler. In meinen Fall war der directory root falsch eingestellt. Da können die Rechte noch soviel stimmen ;)
