### ISSUE TITLE
Verlinkungen funktionieren nur für "IP-Adresse/public/index.php"

### ISSUE THREAD

**Issue by murreni** [tkrebs/ep3-bs#291]
Hallo,

ich habe das Programm soweit installiert. Ein Problem habe ich allerdings.
Die Verlinkungen auf der Weboberfläche funktionieren nur, sofern ich die Seite so aufrufe:
**IPAdresse/public/index.php/**

Wenn ich dann aber auf das Logo oben links klicke lande ich hier:
**IPAdresse/public/**

aber von dieser Seite aus funktionieren die Links z.B. zur Anmeldung  nicht.

kann mir jemand sagen, was ich einstellen muss, damit
**IPAdresse/public/** inkl. der Verlinkungen funktioniert?

Vielen Dank

**Comment by mumulusul** [comment]
in der Hosting Settings, Document root / domain/public ändern ....??

**Comment by murreni** [comment]
Danke für die Antwort, könntest du das ein wenig genauer erklären. ich bin ziemlich neu in dem Thema.
Wo finde ich die Hosting Setting?

**Comment by Shineson1001** [comment]
Hi @murreni,
das Root-Verzeichnis von deinem (Virtual-)Host muss das "public"-Verzeichnis sein ... d.h. /public/ darf gar nicht in der Browser-Adresse auftauchen.

**Comment by murreni** [comment]
Alles klar. Habe ich verstanden und geändert. Public erscheint nun nicht mehr.
Aber an dem Grundproblem hat sich nichts geändert.
wenn ich nun meine **"IP-Adresse"** aufrufe, öffnet sich sich die Website ganz normal. Sobald ich aber irgendeinen Link auf der Seite anklicke, dann erscheint die Fehlermeldung: "Not Found - The requested URL was not found on this server. 
Wenn ich nun **"IP-Adresse/index.php/"** eingebe, dann funktionieren alle Links.
Meine Frage ist nun, was muss ich ändern, damit bei aufrufen der **"IP-Adresse"** die Links funktionieren und keine Fehlermeldung erscheint?

**Comment by Shineson1001** [comment]
Hi @murreni,

ich vermute das ReWriting läuft noch nicht. Aktiviert wird die Funktion über ein .htaccess Datei im Ordner "public" .. wenn deine Installation aus den Dateien von diesem git-Repo bestehen, dann prüfe mal ob die Datei da ist bzw. von ".htaccess_original" zu ".htaccess" umbenannt wurde.

Wenn die Datei da ist, dann wird die vom Webserver noch nicht berücksichtig. Damit z.B. der Apache die Datei berücksichtigt, muss man man die Konfiguration vom Web anpassen: https://httpd.apache.org/docs/2.4/mod/core.html#allowoverride

Oder du entfernt die .htaccess Datei und aktivierst die ReWrite-Funktion direkt in der Web-Konfiguration.

Beispiel für die Standard-Konfig vom Apache Webserver  .. Um diesen Abschnitt erweitern
```
<Directory /var/www/html/public>
        RewriteEngine On
        RewriteRule ^robots\.txt$ misc/robots.txt
        RewriteRule ^favicon\.ico$ imgs-client/icons/fav.ico
        RewriteCond %{REQUEST_FILENAME} -s [OR]
        RewriteCond %{REQUEST_FILENAME} -l [OR]
        RewriteCond %{REQUEST_FILENAME} -d
        RewriteRule ^.*$ - [L]
        RewriteRule ^.*$ index.php [L]
</Directory>
```

**Comment by murreni** [comment]
Super. Hat geklappt :-) Du hast mir den Abend gerettet. 
Vielen Dank!

**Comment by murreni** [comment]
Könntest du mir bitte noch kurz erklären, wie das mir der .htaccess funktioniert?

### "Oder du entfernt die .htaccess Datei und aktivierst die ReWrite-Funktion direkt in der Web-Konfiguration."

ich wollte das ganze nun auf einen IONOS Server ziehen und da habe ich leider keine Möglichkeit die apache configs zu ändern. Wo muss ich die ReWrite Funktion aktivieren?

Danke und Gruß
murrnei

**Comment by Shineson1001** [comment]
Hi @murreni,
im Grunde kopiert man das ep3 Projekt in den Webspace und legt dann das Root-Verzeichnis der (Sub-)Domain auf den `public`-Ordner.
Im `public`-Ordner liegt die .htaccess Datei, dort kommen bzw. sind die ReWrite-Regeln enthalten.

So sieht grob der Inhalt meiner .htaccess Datei aus
```
<IfModule mod_rewrite.c>
RewriteEngine On

RewriteRule ^robots\.txt$ misc/robots.txt
RewriteRule ^favicon\.ico$ imgs-client/icons/fav.ico

RewriteCond %{REQUEST_FILENAME} -s [OR]
RewriteCond %{REQUEST_FILENAME} -l [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^.*$ - [NC,L]

RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
```
