### ISSUE TITLE
Änderung der Textlables

### ISSUE THREAD

**Issue by murreni** [tkrebs/ep3-bs#292]
Hallo,

ist es möglich, z.B. dem Label "Telefonische Buchung" einen anderen Text zuzuordnen?
Welche Datei müsste ich da editieren?

Danke und Gruß

**Comment by Shineson1001** [comment]
Hi,
der Begriff kommt hier 
https://github.com/tkrebs/ep3-bs/blob/aaa44d34d908803528f1ce52a31b59d4cd877c58/data/res/i18n/de-DE/base.php#L69
und hier vor
https://github.com/tkrebs/ep3-bs/blob/aaa44d34d908803528f1ce52a31b59d4cd877c58/data/res/i18n/de-DE/backend.php#L250

**Comment by murreni** [comment]
Dankeschön :-)
