### ISSUE TITLE
Straßennamen aus der Mannheim Innenstadt werden nicht akzeptiert

### ISSUE THREAD

**Issue by SpectroEric** [tkrebs/ep3-bs#293]
Richten das System gerade in Mannheim ein. Funktioniert sehr gut. 
Uns ist nur aufgefallen, dass Adressen aus der Mannheimer Innenstadt nicht akzeptiert werden.
Diese sind immer ein Buchstabe und eine Zahl.
https://de.wikipedia.org/wiki/Quadratestadt#Benennungsschema

![mannheimstraße](https://user-images.githubusercontent.com/7069352/81062878-15054080-8ed7-11ea-8cce-769964f1d6e3.PNG)

**Comment by mumulusul** [comment]
dann schreib bitte Straße E4 :-)

**Comment by SpectroEric** [comment]
Behebt das Problem der länge. Aber nicht, dass scheinbar keine Ziffern zugelassen sind.
![mannheimstraße1](https://user-images.githubusercontent.com/7069352/81064054-454dde80-8ed9-11ea-85db-23158d5c7fe3.PNG)
![mannheimstraße2](https://user-images.githubusercontent.com/7069352/81064051-44b54800-8ed9-11ea-9f8c-eaabb68dc04f.PNG)

**Comment by mumulusul** [comment]
e-vier ??

**Comment by SpectroEric** [comment]
Habe das Problem bei mir folgendermaßen gefixed:
https://github.com/tkrebs/ep3-bs/blob/aaa44d34d908803528f1ce52a31b59d4cd877c58/module/User/src/User/Form/RegistrationForm.php#L481 durch 
`'pattern' => '/^([ \.\'\-\x{00c0}-\x{01ff}a-zA-Z\d])+$/u',`
ersetzen (\d wurde in die eckige Klammer gesetzt)
und 
https://github.com/tkrebs/ep3-bs/blob/aaa44d34d908803528f1ce52a31b59d4cd877c58/module/User/src/User/Form/RegistrationForm.php#L474 die 3 durch eine 2 ersetzt also             
` 'min' => 2,`

**Comment by tkrebs** [comment]
Danke für die Info und Korrektur, ich habe die Änderungen in das Repo übernommen.

Dass es derart kurze Straßennamen in Mannheim gibt, wusste ich nicht. Wieder etwas gelernt. 👍🏻
