### ISSUE TITLE
JavaScript-Aktivierung

### ISSUE THREAD

**Issue by HendrikRe** [tkrebs/ep3-bs#294]
Zuerst einmal vielen Dank für deine Mühe und generell die Einstellung, so ein Projekt auf GitHub verfügbar zu machen. Nach einigen Problemchen, die ich zum Glück mit Beiträgen zu anderen Issues lösen konnte scheint soweit alles zu laufen. Wenn aber ein normaler Nutzer versucht, einen Platz zu buchen, erscheint folgende Meldung: "JavaScript muss in Ihrem Webbrowser aktiviert sein um fortzufahren. Im Zweifelsfall benutzen Sie einfach einen anderen Webbrowser (z.B. Mozilla Firefox).". Dabei habe ich JavaScript aktiviert, und konnte auch in den anderen Issue-Threads keine Lösung finden. Über eine Antwort würde ich mich freuen

**Comment by HendrikRe** [comment]
Ich habe nochmal einen Blick darauf geworfen, das Problem tritt nur in folgendem Fall auf: Die Kapazität eines Platzes steht auf >2 und die Angabe der Mitspieler ist verpflichtend. In diesem Fall erhalte ich die JavaScript-Meldung. Ist die Kapazität =1, läuft alles normal

**Comment by tkrebs** [comment]
Kannst du einmal die Entwicklerwerkzeuge öffnen (i. d. R. `F12` oder _Rechtsklick -> Untersuchen_) und im Tab _Konsole_ nach roten Fehlermeldungen Ausschau halten.

**Comment by HendrikRe** [comment]
Ja klar. Da erhalte ich neben einigen Deprecations(Durch das Framework) folgendes:
`customization.min.js:1 Uncaught ReferenceError: $ is not defined
    at customization.min.js:1
    at customization.min.js:1
(anonymous) @ customization.min.js:1
(anonymous) @ customization.min.js:1
rzQTAloLJ7U8sdHKA0xxIoPPiYo.js:70 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
b.open @ rzQTAloLJ7U8sdHKA0xxIoPPiYo.js:70
b.open @ rzQTAloLJ7U8sdHKA0xxIoPPiYo.js:70
send @ jquery.min.js:4
ajax @ jquery.min.js:4
n._evalUrl @ jquery.min.js:4
Ha @ jquery.min.js:3
append @ jquery.min.js:3
b @ default.min.js:1
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
K @ jquery.min.js:2
c @ rocket-loader.min.js:1
l @ rocket-loader.min.js:1
t.simulateStateAfterDeferScriptsActivation @ rocket-loader.min.js:1
callback @ rocket-loader.min.js:1
t.run @ rocket-loader.min.js:1
P @ rocket-loader.min.js:1
callback @ rocket-loader.min.js:1
t.run @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
load (async)
u @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
t.run @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
load (async)
u @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
t.run @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
load (async)
u @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
t.run @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
load (async)
t.runOnLoad @ rocket-loader.min.js:1
x @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
`

**Comment by HendrikRe** [comment]
Dazu noch, ich betreibe das System gerade ohne .htaccess. Mit htaccess erhalte ich dauernd Internal Server Errors (HTML 500). Auch kein Erfolg mit auskommentieren und den anderen Issue-Threads

**Comment by HendrikRe** [comment]
Okay, ich habe das Problem selber gelöst. Ich poste hier mal den Grund, falls jemand anders auch das Problem haben sollte. Scheinbar lag es an CloudFlare, welches als "Firewall" zwischen Server und Nutzer steht. Ich vermute, dass ein Kompressionsalgorithmus von CloudFlare, welcher js, HTML, PHP und CSS komprimieren soll dawischen gefunkt hat
