### ISSUE TITLE
Fehler bei der Installation über Github

### ISSUE THREAD

**Issue by cbits68** [tkrebs/ep3-bs#295]
Ich habe gerade mal versucht neu über Github zu installieren.
git clone erfolgreich!
Composer installiert und Anhängigkeiten aktualisiert!
php Dateien nach INSTALL Anleitungen umbenannt und Datenbank + Maileinstellung eingetragen.
.htaccess ebenso.
Nach Aufruf von setup.php sieht alles gut aus, bis nach der Angabe zur Erstellung des Adminusers. 

Danach kommt die Fehlermeldung
Oops ... da ist wohl etwas schief gelaufen
An exception was raised while creating "Booking\Manager\ReservationManager"; no instance returned

Die Installation zuvor über das fertige Paket lief fehlerfrei.
Habe ich etwas vergessen, oder mache ich etwas falsch?
Datenbanktabellen wurden erstellt.

Gruß
Andreas

**Comment by cbits68** [comment]
Ich habe jetzt mal das komplette modules Verzeichnis mit dem aus dem aktuellen master überschrieben. Jetzt läuft das System ohne Fehlermeldung.
Der Fehler scheint irgendwie mit der Installation des Composers und dem Update der Abhängigkeiten zu tun zu haben.
Installiert habe ich
wget https://getcomposer.org/download/1.10.6/composer.phar
chmod +x ./composer.phar
./composer.phar install
./composer.phar update

lief auch alles soweit sauber durch, bis auf die Hinweise anstelle der zendframework Pakete die entsprechenden laminas Pakete zu nutzen.

**Comment by gabrielkumar** [comment]
Hallo cbits68,
ich habe gerade genau das selbe Problem :(
Jedoch bekomme ich es nicht hin es zu lösen.
Ich benutze den PHP Composer der direkt vom Webanbieter auf der Konfigurationsseite bereitgestellt wird.
Was genau hast du verändert, dass es funktioniert?
Ich würde mich sehr über eine Rückmeldung freuen! :)

**Comment by cbits68** [comment]
Gern,
nachdem das setup.php "durchgelaufen" war und die Fehlermeldung erschient ( nach 5 Installationsversuchen und immer dem selben Fehler) habe ich einfach das aktuelle ep3-bs-master.zip von hier runtergeladen, es lokal auf meinem PC entpackt und dann das module Verzeichnis per sftp (ich nutze dafür FileZilla) auf dem Server überschrieben.
Danach konnte ich das System, wie gewohnt, über den Browser aufrufen und mich mit dem generierten Admin Account anmelden.
Habe inzwischen die Erstkonfiguration und meine Anpassungen durch geführt und bisher läuft es ohne Fehler. Werde aber gleich noch mal alles Testen (Registrierung, Buchungen, Stornierungen, .)
Die Tabellen wurden aber durch das Setup sauber in der Datenbank angelegt, soweit ichsehen konnte.
Gruß
Andreas

**Comment by gabrielkumar** [comment]
Danke für deine schnelle Antwort!
Leider hat das bei mir alles nicht funktioniert. Ich werde einen neuen Beitrag verfassen und hoffe, dass ich das Problem bis nächste Woche beheben kann.

Aber trotzdem einen sehr großen Dank an dich!!! :)
Gruß
Gabriel

**Comment by tkrebs** [comment]
Danke euch beiden für die Meldung und Untersuchung dieses Fehlers.

Auslöser war, dass das Setup noch nicht die kürzlich neu hinzugefügten Felder für die Buchungseinschränkungen kannte und gesetzt hat.

In der aktuellen Version 1.6.4 ist das korrigiert.
