### ISSUE TITLE
Installation erfolgreich aber dann stimmt die Zuordnung nicht mehr

### ISSUE THREAD

**Issue by Michi-Ger** [tkrebs/ep3-bs#297]
Hallo, vielleicht kann mir jemand helfen.
Wir haben unseren Webspace bei 1&1 Ionos. Ich habe das paket hochgeladen und die Subdomain auf den Ordner public gelegt. Dann die Installation gestartet und diese lief auch korrekt durch. Doch als ich mir die Installierte Seite ansehen wollte, zeigte mir mein Browser nur eine Defaultsite von 1&1 an. Ich habe nochmal alle einstellungen in der htaccess usw. überprüft, aber nichts bzw. keinen Fehler entdeckt. Jetzt habe ich die Subdomain auf das Root Verzeichnis (also eine Ebene höher) gelegt. Allerdings funktionieren jetzt keinerlei Links mehr. Ich kann nun nur die Seite ansehen wenn ich meinesubdomain/public/ aufrufe. Dann funktioniert es.

meine htaccess:

<IfModule mod_rewrite.c>

    RewriteEngine On
    #RewriteBase /   # Try to uncomment this if you experience redirect problems

    #RewriteCond %{ENV:REDIRECT_STATUS} ^$
    #RewriteRule ^index\.php$ http://bookings.example.com/ [R=301,L]

    #RewriteCond %{ENV:REDIRECT_STATUS} ^$
    #RewriteRule ^index\.php/(.*)$ http://bookings.example.com/$1 [R=301,L]

    RewriteRule ^robots\.txt$ misc/robots.txt
    RewriteRule ^favicon\.ico$ imgs-client/icons/fav.ico

    RewriteCond %{REQUEST_FILENAME} -s [OR]
    RewriteCond %{REQUEST_FILENAME} -l [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^.*$ - [L]
    RewriteRule ^.*$ index.php [L]

</IfModule>

Vielen Dank.

Michael

**Comment by tkrebs** [comment]
Zum Thema Webserver-Einrichtung bei 1&1 gibt es hier schon jede Menge Beiträge, eine allgemeine Lösung, die bei allen gleichermaßen funktioniert, scheint es nicht zu geben.

Eventuell hilft auch die in der Version 1.6.4 gerade frisch hinzugekommene .htaccess-Alternative:

https://github.com/tkrebs/ep3-bs/blob/master/public/.htaccess_alternative

**Comment by Shineson1001** [comment]
Hi @Michi-Ger,

ich habe gerade auch eine Installation auf einem mein.ionos.de Server gemacht. Die Installation funktioniert gänzlich ohne .htaccess ...

Ist der Name bei die "htaccess" oder ".htaccess"?

**Comment by tkrebs** [comment]
Danke für die Info, ich hoffe, das hilft auch anderen bei 1&1.

**Comment by S-MD** [comment]
Ja, bin auch bei 1&1 und hatte auch den Fehler 500.
Ich kann bestätigen dass er auch bei mir mit der neuen htacces behoben ist.
