### ISSUE TITLE
An exception was raised while creating "Booking\Manager\ReservationManager

### ISSUE THREAD

**Issue by gabrielkumar** [tkrebs/ep3-bs#298]
Hallo,
die Installation hat bis zum Schritt des löschens der Setup.php Datei gut geklappt. Jetzt kommen jedoch folgende Meldungen:

> Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /var/www/vhosts/web11615.web4a.de/buchung-tcroth.de/vendor/zendframework/zend-i18n/src/Translator/Loader/PhpArray.php on line 52

und

> Oops ... da ist wohl etwas schief gelaufen
An exception was raised while creating "Booking\Manager\ReservationManager"; no instance returned

Ein anderer User hatte das Selbe Problem, aber seine Lösung hat bei mir leider nicht funktioniert.

Ich hoffe jemand kann mir weiterhelfen!

Vielen Dank
Gabriel

![Unbenannt](https://user-images.githubusercontent.com/64897211/81182304-e908be80-8fad-11ea-8e5d-11b308b29664.PNG)
![Unbenannt1](https://user-images.githubusercontent.com/64897211/81182320-ee660900-8fad-11ea-919e-3157f37ec009.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/64897211/81182323-ef973600-8fad-11ea-9fb2-04719ecf3a19.PNG)
![Unbenannt3](https://user-images.githubusercontent.com/64897211/81182327-ef973600-8fad-11ea-9d6f-7e24f25e33f1.PNG)

**Comment by tkrebs** [comment]
Der Fehler bzgl. `Booking\Manager\ReservationManager` wurde kürzlich korrigiert:

https://github.com/tkrebs/ep3-bs/issues/295#issuecomment-624683003

Die `Deprecated`-Meldungen können unterdrückt werden, indem der Debug-Modus deaktiviert wird:

https://github.com/tkrebs/ep3-bs/blob/fb4a742ffa186511ee9eb65934a6637c6ab488ad/config/init.php.dist#L13
