### ISSUE TITLE
Upload Veranstaltungen

### ISSUE THREAD

**Issue by wagpat** [tkrebs/ep3-bs#30]
Hallo,
wie ist es möglich mehrere Veranstaltung mittels (Excel-)File hochzuladen?

LG patrick

**Comment by tkrebs** [comment]
In der aktuellen Version gibt es leider keine Importfunktion. Die einzige Möglichkeit wäre hier der  (etwas umständliche) CSV-Import direkt in die Datenbank (z.B. per phpMyAdmin).

**Comment by tkrebs** [comment]
https://github.com/tkrebs/ep3-bs/issues/370
