### ISSUE TITLE
Fatal error: Uncaught Zend\Session\Exception\InvalidArgumentException: 

### ISSUE THREAD

**Issue by Holger690** [tkrebs/ep3-bs#300]
Hallo Herr Krebs,
Habe die aktuelle Version 1.6.4 installiert.
Webserver gestartet.
Setup aktiviert
Datenbank angelegt-i.o
Benutzerdaten eingetragen -i.o
Admin Password angegeben -i.o
Installation war fertig
System Startet mit Fatal error:
#Können Sie mir helfen was da falsch geht?
Fatal error: Uncaught Zend\Session\Exception\InvalidArgumentException: Invalid save_path provided; not writable in /var/www/tennis/vendor/zendframework/zend-session/src/Config/StandardConfig.php:232 Stack trace: #0 /var/www/tennis/vendor/zendframework/zend-session/src/Config/SessionConfig.php(233): Zend\Session\Config\StandardConfig->setSavePath('/var/www/tennis...') #1 /var/www/tennis/vendor/zendframework/zend-session/src/Config/StandardConfig.php(114): Zend\Session\Config\SessionConfig->setSavePath('/var/www/tennis...') #2 /var/www/tennis/vendor/zendframework/zend-session/src/Service/SessionConfigFactory.php(67): Zend\Session\Config\StandardConfig->setOptions(Array) #3 /var/www/tennis/vendor/zendframework/zend-session/src/Service/SessionConfigFactory.php(85): Zend\Session\Service\SessionConfigFactory->__invoke(Object(Zend\ServiceManager\ServiceManager), 'Zend\\Session\\Co...') #4 [internal function]: Zend\Session\Service\SessionConfigFactory->createService(Object(Zend\ServiceManager\ServiceManager), 'zendsessionconf...' in /var/www/tennis/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 941

**Comment by Shineson1001** [comment]
Hi @Holger690,

es fehlen anscheinend Schreibrechte.

>  Invalid save_path provided; not writable

Evtl. nochmal die Installationsanleitung durchgehen: https://github.com/tkrebs/ep3-bs/blob/fb4a742ffa186511ee9eb65934a6637c6ab488ad/data/docs/install.txt#L11
