### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by NMTGTFR** [tkrebs/ep3-bs#301]
Lieber Tobias,

vorab vielen Dank für deine Software!!! Falls ich Dir bei einem responsiven Design helfen darf, melde dich gerne.

Ich verwende ebenfalls die Version 1.6.4. Die Installation funktioniert (auf den ersten Blick) bei 1&1 (IONOS);
Folgenden Fehler konnte ich schnell beheben:
> `Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /homepages/34/d83429358/htdocs/platzres/vendor/zendframework/zend-stdlib/src/ArrayObject.php on line 426`

Das Frontend wird nun korrekt ausgegeben. Doch alle sämtliche Funktionen und Links scheinen nicht zu funktionieren. Nach einem Klick lädt die Seite neu und es erscheint immer
> ![image](https://user-images.githubusercontent.com/64959185/81282611-af8e8c80-905b-11ea-829c-4f32ac61bf0c.png)

Was kann ich tun oder habe ich falsch gemacht?

**Comment by NMTGTFR** [comment]
Lokal läuft es – aber irgendwas mache ich bei 1&1 nicht richtig. :/

**Comment by NMTGTFR** [comment]
Evtl hilft folgendes aus der setup.php, die ich noch mal eingespielt habe?

Exception details
Type
RuntimeException
Mitteilung
System has already been setup
File
/homepages/34/d83429358/htdocs/platzres/module/Setup/src/Setup/Controller/Plugin/ValidateSetup.php:29
Stack trace

```
#0 [internal function]: Setup\Controller\Plugin\ValidateSetup->__invoke('index')
#1 /homepages/34/d83429358/htdocs/platzres/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(318): call_user_func_array(Object(Setup\Controller\Plugin\ValidateSetup), Array)
#2 /homepages/34/d83429358/htdocs/platzres/module/Setup/src/Setup/Controller/IndexController.php(15): Zend\Mvc\Controller\AbstractController->__call('validateSetup', Array)
#3 /homepages/34/d83429358/htdocs/platzres/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(84): Setup\Controller\IndexController->indexAction()
#4 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#5 /homepages/34/d83429358/htdocs/platzres/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#6 /homepages/34/d83429358/htdocs/platzres/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#7 /homepages/34/d83429358/htdocs/platzres/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(116): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#8 /homepages/34/d83429358/htdocs/platzres/vendor/zendframework/zend-mvc/src/DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#9 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#10 /homepages/34/d83429358/htdocs/platzres/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#11 /homepages/34/d83429358/htdocs/platzres/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /homepages/34/d83429358/htdocs/platzres/vendor/zendframework/zend-mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#13 /homepages/34/d83429358/htdocs/platzres/public/setup.php(66): Zend\Mvc\Application->run()
#14 {main}
```

**Comment by tkrebs** [comment]
Schau mal hier:

https://github.com/tkrebs/ep3-bs/issues/297#issuecomment-624688532

Versuch insbesondere einmal, die erwähnte Datei `public/.htaccess_alternative` einzusetzen.

**Comment by NMTGTFR** [comment]
Super. Die htacess-Einstellungen von @Shineson1001 bei #297 haben mir geholfen!!! Merci!

**Comment by tkrebs** [comment]
Super! 👍🏻
