### ISSUE TITLE
Buchung beginnend um XX:30

### ISSUE THREAD

**Issue by FantasticFry** [tkrebs/ep3-bs#302]
Ich habe folgende Einstellungen bei der Platzreservierung eingestellt.
Zeitblock: 60min
min. buchbar: 30min

Wie es aussieht kann der normale aktivierte Benutzer mit diesen Einstelluingen keine Buchung machen die um XX:30 beginnt sondern immer nur zur vollen Stunde. Man kann aber sehr wohl bspw. 1,5h Stunden buchen, d.h. Buchung endet um XX:30, aber es ist nicht möglich eine zu machen die um XX:30 beginnt.
Es geht nur wenn man erweiterte Nutzungsrechte hat und Buchungen verwalten darf.

Wir würden den Zeitblock ungern auf 30min einstellen, da der Kalender sonst sehr lang wird. Wäre es möglich aber die Buchung entsprechend zur halben Stunde dennoch zu ermöglichen?

**Comment by tkrebs** [comment]
Technisch gesehen können auch Buchungen beginnend um xx:30 vorgenommen werden. Es ist eine Einschränkung der Kalenderdarstellung, dass eben nur ganze Zeitblöcke angeklickt werden können.

Abhilfe würde hier eine zusätzliche Startzeit-Auswahl analog der Endzeit-Auswahl schaffen. Die gibt es aber derzeit nicht.

**Comment by Busfreak** [comment]
Ich hatte das gleiche Problem und habe es folgendermaßen gelöst:

In /public/js-client/controller/square/index.free.js die Funktion at.on("change") ändern, dass sie Beginn UND Ende im Link ersetzt:
            at.on("change", function() {
				var atParts = at.val().split("-");
				var atStart = atParts[0];
				var atEnd = atParts[1];
                var hrefBook = buttonBook.attr("href");
                var hrefReload = buttonReload.attr("href");

				buttonBook.attr("href", hrefBook.replace(/\&ts\=[0-9][0-9]:[0-9][0-9]/, "&ts=" + atStart).replace(/\&te\=[0-9][0-9]:[0-9][0-9]/, "&te=" + atEnd));
				buttonReload.attr("href", hrefReload.replace(/\&ts\=[0-9][0-9]:[0-9][0-9]/, "&ts=" + atStart).replace(/\&te\=[0-9][0-9]:[0-9][0-9]/, "&te=" + atEnd));
				buttonReload.click();
             });

In /module/Square/src/Square/View/Helper/TimeBlockChoice.php die select-Liste um die halbstündigen Startzeiten erweitern
        /* Render alternate time select */

        $view = $this->getView();
        $html = '';

        $html .= '<select id="sb-alternate-times" style="display: none; margin-right: 16px;">';

        $walkingTimeStartParts = explode(':', $dateTimeStart->format('H:i'));
        $walkingTimeStart = $walkingTimeStartParts[0] * 3600 + $walkingTimeStartParts[1] * 60;

        $walkingDateTime = clone $dateTimeStart;
        // zusätzliche Zeiten für die halbe Stunde
        $walkingDateTime2 = clone $dateTimeStart;
		$dateTimeStart2 = clone $dateTimeStart;
		$dateTimeStart2->modify('+' . $bookable . ' sec');
        $walkingIndex = 0;

        if ($square->getMeta('pseudo-time-block-bookable', 'false') == 'true') {
            $bookable = $square->need('time_block');
        }

        while ($walkingDateTime < $dateTimeCheck) {
            $walkingDateTime->modify('+' . $bookable . ' sec');
            $walkingDateTime2->modify('+' . $bookable . ' sec');
            $walkingIndex++;

            $walkingTimeEndParts = explode(':', $walkingDateTime->format('H:i'));
            $walkingTimeEnd = $walkingTimeEndParts[0] * 3600 + $walkingTimeEndParts[1] * 60;

            $quantity = 0;

            foreach ($reservations as $reservation) {
                $booking = $reservation->needExtra('booking');

                if ($booking->need('status') != 'cancelled' && $booking->need('visibility') == 'public') {
                    if ($booking->need('sid') == $square->need('sid')) {
                        if ($reservation->needExtra('time_start_sec') < $walkingTimeEnd &&
                            $reservation->needExtra('time_end_sec') > $walkingTimeStart) {
                            $quantity += $booking->need('quantity');
                        }
                    }
                }
            }

            if ($capacity > $quantity) {
                if ($quantity && ! $capacityHeterogenic) {
                    break;
                }
            } else {
                break;
            }

            if ($walkingDateTime == $dateTimeEnd) {
                $attr = 'selected="selected"';
            } else {
                $attr = null;
            }

            // Start und Endzeit in Auswahlliste
			$value = $dateTimeStart->format('H:i') . "-" . $walkingDateTime->format('H:i');
//            $value = $walkingDateTime->format('H:i');

            $html .= sprintf('<option value="%s" %s>%s</option>',
                $value, $attr, $view->timeRange($dateTimeStart, $walkingDateTime, '%s to %s'));

            if ($dateTimeStart2 != $walkingDateTime2) {
				// Zwischenzeiten einfügen
				$value = $dateTimeStart2->format('H:i') . "-" . $walkingDateTime2->format('H:i');

				$html .= sprintf('<option value="%s" %s>%s</option>',
					$value, NULL, $view->timeRange($dateTimeStart2, $walkingDateTime2, '%s to %s'));
			}
        }

        $html .= '</select>';


In /module/Square/view/square/square/index.free.phtml die angepasste js-Datei einbinden:
//        echo $this->ajaxAwareScript('js/controller/square/index.free.min.js');
        echo $this->ajaxAwareScript('js-client/controller/square/index.free.js');

**Comment by Busfreak** [comment]
Ich hatte das gleiche Problem und habe es so gelöst:

- in /public/js-client/controller/square/index.free.js die Funktion at.on("change") ändern, dass sie Beginn UND Ende im Link ersetzt
- in /module/Square/src/Square/View/Helper/TimeBlockChoice.php die select-Liste um die halbstündigen Startzeiten erweitern
- in /module/Square/view/square/square/index.free.phtml die angepasste js-Datei einbinden

Funktioniert bei meinen Einstellungen sehr gut:
- Zeitblock = 60
- Zeitblock (min. buchbar) = 30
- Zeitblock (max. buchbar) = 120

Wie es sich bei anderen Blockgrößen verhält, habe ich nicht getestet.

[spätere Startzeit.txt](https://github.com/tkrebs/ep3-bs/files/4616208/spatere.Startzeit.txt)

**Comment by FantasticFry** [comment]
Hat geklappt, danke schön

**Comment by dschousef** [comment]
Auch ich hatte denselben Gedanken bzw. Wunsch und bin sehr froh, dass es Busfreak bereits gelöst hat. Hab es eingebaut und funktioniert!
Vielen Dank @Busfreak !!!
