### ISSUE TITLE
Header Email statt Telefonische Buchung welche Datei ändern?

### ISSUE THREAD

**Issue by gabrielkumar** [tkrebs/ep3-bs#303]
Hallo,
das Buchungssystem funktioniert jetzt top. Vielen Dank!

Wir wollen jedoch keine telefonische Buchung machen. Eine derartige Änderung ist in den Einstellungen im Buchungssystem nicht vorgesehen. Deswegen hab ich mich auf die Suche nach der passenden Datei (index.html php und so weiter) gemacht und wollte dies einfach umbenennen. Der Quellcode im Browser zeigt die Datei an, die ich aber nirgendwo finden kann.

Ich hoffe jemand kann mir helfen und sagen wo ich die Datei finde.
Vielen lieben Dank!!!! :)

**Comment by murreni** [comment]
schau mal hier:

https://github.com/tkrebs/ep3-bs/issues/292#issuecomment-623987742

**Comment by gabrielkumar** [comment]
Perfekt danke!
