### ISSUE TITLE
Info-Seite als Startseite einrichten

### ISSUE THREAD

**Issue by murreni** [tkrebs/ep3-bs#305]
Hallo zsammen,

Kann mir jemand sagen, wie man die Infoseite als Startseite festlegen kann?

Danke und Gruß

**Comment by Busfreak** [comment]
Das hier ist die Startseite:
module/Frontend/view/frontend/index/index.phtml

Dort habe ich eine Bedingung eingebaut, die den Kalender nur dann anzeigt, wenn ein User eingelogged ist, sonst einen allgemeinen Text.

Du könntest so z.B. die Infoseite mit
$this->partial('service/service/info.phtml')
einbinden.

<?php if ($this->user): ?>
    <?= $this->calendar ?>
<?php else: ?>
    <?= $this->partial('service/service/info.phtml') ?>
<?php endif; ?>

**Comment by Busfreak** [comment]
Hab's für mich auch umgesetzt:
https://github.com/Busfreak/ep3-bs/blob/master/module/Frontend/view/frontend/index/index.phtml
