### ISSUE TITLE
Regelwerk-PDF löschen

### ISSUE THREAD

**Issue by HendrikRe** [tkrebs/ep3-bs#307]
Hallo,

Ich habe heute versucht, ein PDF-Regelwerk zu löschen, finde dazu aber keinen Button etc. Habe auch schon die Datenbank durchkämmt, aber in keinem Table derartige Einträge gefunden. Ist das ein genereller Fehler oder übersehe ich hier etwas?

**Comment by Shineson1001** [comment]
Hi @HendrikRe,
in der Tabelle `bs_squares_meta` gibt es bei den Plätzen, bei denen es ein PDF gibt, die 2 Einträge:
key = 'rules.document.file'
key = 'rules.document.name'

**Comment by HendrikRe** [comment]
Das kommt davon wenn ionos plötzlich phpmyadmin cached... schrecklich
