### ISSUE TITLE
weiteres Logo in Kopfzeile

### ISSUE THREAD

**Issue by frankgayer** [tkrebs/ep3-bs#309]
Hallo,

ich versuche ein weiteres Logo neben die Telefonnummer zu bekommen. In der CSS bin ich auf die Topbar gestossen, weiß aber nicht wie ich es einbinde. Habt Ihr mir einen Tipp ?

**Comment by tkrebs** [comment]
Das Logo muss in Form von HTML-Code in die [Templates](https://github.com/tkrebs/ep3-bs/blob/master/module/Base/view/layout/layout.phtml) eingearbeitet werden und anschließend mit CSS harmonisch dargestellt werden.
