### ISSUE TITLE
Problem beim öffnen der Seite bei IONOS

### ISSUE THREAD

**Issue by tennstar1** [tkrebs/ep3-bs#310]
Hallo, ich habe das System bei bplaced ohne Schwierigkeiten als Test laufen und habe es nun samt Datenbank zu 1&1 übertragen und die local.php angepasst. Wenn ich ep3 nun mit der "Domain/ep3/public/user/Login" aufrufe passiert Garnichts. Lasse ich "public/user/Login" weg öffnet sich das System aber nicht wie gewohnt sondern das Fenster zum einloggen wird links und rechts großflächig angezeigt und es wird bereits zum einloggen "admin" vorgegeben. Der Kalender und alles andere ist wie gewohnt. Am oberen Rand erscheint die Fehlermeldung:

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /homepages/20/d34594934/htdocs/ep3/vendor/zendframework/zend-stdlib/src/ArrayObject.php on line 426
Was mache ich verkehrt?
Hier noch die Domain: https://tg-parkstein.de/ep3
Hat jemand eine Idee, ich bin leider nicht so fit, dass ich es selber in die Reihe bringe!
Vielen Dank erstmal
Gruß tennstar

**Comment by Shineson1001** [comment]
Hi @tennstar1 ,
die Warnung sollte man schon mal so weg bekommen: https://github.com/tkrebs/ep3-bs/issues/261#issuecomment-618281095

Dann würde ich das Buchungssystem in eine eigene Sub-Domain installieren, um den "public"-Ordner als Web-Root-Verzeichnis angeben zu können.

**Comment by cbits68** [comment]
@tennstar1 Du machst nix falsch, die Provider nutzen aber nicht unbedingt die selben Versionen von Apache, php, …
Den Fehler ignorieren (ausblenden) kannst Du von Shineson1001 oben verlinkt.

Das mit der Subdomain hatte ich auch erst vor, allerdings benötigt man dafür ein entsprechendes SSL Wildcard Zertifikat um auch Subdomains per SSL/https verschlüsseln zu können.
Bei meinem Provider Strato kostet das Wildcard Paket 6€ pro Monat. werde ich dann wohl irgendwann auch mal dazu buchen.

Gruß
Andreas

**Comment by Shineson1001** [comment]
Hi @cbits68,
man bekommt, und er hat, ein Wildcard Zertifikat. Von daher ist die Sub-Domain kein Problem und ich würde der Installationsanleitung folgen: https://github.com/tkrebs/ep3-bs/blob/fb4a742ffa186511ee9eb65934a6637c6ab488ad/data/docs/install.txt#L47

**Comment by tennstar1** [comment]
Hallo Andreas, danke für Deinen Hinweis!

Werde jetzt mal bei 1%1 nachfragen wie es sich hier verhält. 
Wobei ich ja glaube, dass das nicht das Problem ist, die Seite öffnet ja, nur halt nicht mit der Vorgabe "/user/login", das "Anmelden" Fenster fehlt und man kann sich nicht einloggen.
Ich betreibe eine zweite Seite (nicht ep3) auch mit einer Subdomain bei 1&1 und die funktioniert auch ohne Pobs. und bei bplaced läuft sie auch als Subdomain einwandfrei.
Der Fehler muss wo anders liegen weil ja nur das einloggen über "user/login" nicht möglich ist.

Hol mir jetzt eine Domain von bplaced und werde die Seite dort betreiben.

Vielen Dank nochmals für euere Hilfe!
Gruß tennstar

**Comment by tennstar1** [comment]
Hab jetzt bei 1&1 eine Subdomain aktiviert (kostenlos) und damit gestartet.
Dasselbe verhalten, Seite startet ohne Anmeldefenster und man kann sich auch nicht einloggen.
Hier wird dann die Fehlermeldung 
"Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request."
angezeigt.
Hab die Installation mal gelassen, vielleicht fällt einem von euch ja noch etwas ein.
Werde es jetzt wieder mit bplaced probieren!
Danke für Eure Hilfe

**Comment by Shineson1001** [comment]
Hi @tennstar1, 
teste mal die angepasste .htaccess Datei
https://github.com/tkrebs/ep3-bs/issues/297#issuecomment-624854533

**Comment by tennstar1** [comment]
Hallo Shineson1001,
jetzt funktioniert die Seite überhaupt nicht mehr Wird sie nochmal neu aufsetzen.
Danke

**Comment by tennstar1** [comment]
Ich muss mich jetzt nochmal melden, ich hab jetzt nochmal die Installation die auf einem bplaced Account blendend funktioniert heruntergeladen und mit der Datenbank auf einen neuen bplaced Account installiert.
Nach dem Start erhalte ich nun ein Fenster mit folgenden Inhalt:
> Exception details
Type
Error
Mitteilung
__clone method called on non-object
File
/users/ep3/www/module/Calendar/view/calendar/calendar/index.landscape.phtml:18
Es folgen dann noch viele einzelnen Zeilen mit fehlgeschlagenen Aufrufen

Kann jemand damit etwas anfangen und hat eine Lösung
Danke
tennstar

**Comment by mharzl** [comment]
Hi, kann mich zwar nicht mehr auf die Fehlermeldung erinnern, bei der Installation auf 1&1 hat mir dann ein Kommentar in .htaccess doch einige Probleme verursacht:

RewriteBase /   # Try to uncomment this if you experience redirect problems ==> hat nicht funktioniert

RewriteBase / ==> funktioniert

Bin kein Experte in dem Bereich, hat mich aber doch gewundert

**Comment by tennstar1** [comment]
Hallo @mharzl,
Danke für Deine Antwort, dieses Problem hat sich bereits gelöst.
Dank Shineson1001 hat sich dieses Problem geändert und es lag tatsächlich an der htacess.
Wenn Du Deine Installation bei IONOS hast würde mich Deine EMail Einstellungen brennend interessieren, denn bei funktioniert alles nur die EMails werden nicht verschickt. Hierfür bekomme ich die Fehlermeldung:
> "Oops ... da ist wohl etwas schief gelaufen-Must call beginTransaction() before you can rollback"
Es würde mich interessieren wie Du das gelöst hast!
Gruß tennstar1

**Comment by mharzl** [comment]
Hallo, bitte sehr
    'mail' => array(
        'type' => 'sendmail', // or 'smtp' or 'smtp-tls'
        'address' => 'unsere Mail Adresse',

        'host' => '?', // for 'smtp' type only, otherwise remove or leave as is
        'user' => '?', // for 'smtp' type only, otherwise remove or leave as is
        'pw' => '?', // for 'smtp' type only, otherwise remove or leave as is

        'port' => 'auto', // for 'smtp' type only, otherwise remove or leave as is
        'auth' => 'plain', // for 'smtp' type only, change this to 'login' if you have problems with SMTP authentication
    ),

**Comment by tennstar1** [comment]
Das meinte ich nicht, ich wollte eigentlich wissen ob unter Type noch etwas verändert werden muss und welcher Port, Pop od. smtp und was unter auth. tls od. ssl eingetragen werden muß.

**Comment by mharzl** [comment]
Hi, die o.a. Config funktioniert bei uns für System Mails (Anmeldung etc.). Da mussten wir so nichts ändern. Die Option " Sende Benutzer-E-Mails wie Buchungs- oder Stornierungsbestätigungen als Kopie an diese Adresse" haben wir nicht aktiviert. Wenn bei dir dort der Fehler auftritt stimmt vielleicht auf Applikations- oder Datenebene was nicht.

**Comment by tennstar1** [comment]
@ mharzl Danke für Deine Antwort,
Fehler lag in den 6 Zeilen ini_set in der INIT.php! Dank @Shineson1001 hab ich das jetzt hinbekommen und alles läuft perfekt! Warum das so ist kann ich nicht sagen, scheint aber IONOS spezifisch zu sein, da die seit April einen neuen Standard für den Mailversand eingeführt haben.
Hier ist die Lösung!
[https://github.com/tkrebs/ep3-bs/issues/315](url)
Gruß
tennstar
