### ISSUE TITLE
Buchungsverlängerung um 30 oder 60 min während aktuellen Spiels

### ISSUE THREAD

**Issue by Robox49** [tkrebs/ep3-bs#311]
Hi,

vielen Dank erstmal für das coole Buchungstool. Dies ist in der aktuellen Coronazeit eine große Hilfe für unsere Tennisabteilung. Ich hätte eine Frage zur Buchung.
Derzeit sind bei uns nur Buchungen von 30 oder 60 min erlaubt. Wenn man dann noch länger spielen möchte, muß man sich bis zur 60. min eingeloggt haben und die nachfolgende Stunde buchen. Ab Min 61 hat ansonsten das Buchungstool die neue volle Stunde schon begonnen und man kann diese leider nicht mehr buchen.  Ist es möglich, dem Code etwas hinzuzufügen, daß man auch in eine bereits laufende Stunde ( die natürlich nicht für einen anderen Spieler reserviert ist ) reinbuchen kann ?
Als Alternative dachte ich mir, könnte man ansonsten das Buchungstool zeitlich gesehen um z.B. 30 min "nachgehen lassen", so daß die interne Uhrzeit des Buchungstool immer um 30 min nachgeht und man dann genügend Zeit hätte, während eines laufenden Spiels die Buchung zu verlängern. 
Da ich leider kein PHP kann würde ich mich um ein paar Tips hier sehr freuen  wie ich das im Skript ändern / anpassen kann.
Danke & Grüße

Robin

**Comment by Busfreak** [comment]
Entweder macht das einer von euch mit dem Status "Verwaltung", der kann die ursprüngliche Buchung einfach verlängern, oder jeder eurer Spieler bekommt den Status "Mitarbeiter" und die Berechtigung "Sieht auch vergangene Buchungen". Damit kann man auch "in der Vergangenheit" buchen.

Das ist vielleicht einfacher, als die Serverzeit zu ändern :-)

**Comment by roloresnag** [comment]
Änderung von init.php im Verzeichniss /Config
Zeile 21 Ist: ini_set('date.timezone', 'Europe/Berlin');
ändern auf: ini_set('date.timezone', 'Europe/London');
gibt 1 Stunde Extra Zeit.
Nach Test´s ohne das System zu schrotten.
Evtl. in den Buchungsstatistiken um 1 Stunde falsch in der Datenbank abgelegt.

**Comment by Robox49** [comment]
Hi, vielen Dank für eure Hilfe, werde das mit der GMT-Zeit mal ausprobieren, das scheint der einfachste Weg zu sein.
