### ISSUE TITLE
Anmeldeproblem

### ISSUE THREAD

**Issue by 97RS** [tkrebs/ep3-bs#314]
Hallo,

erst mal Danke für diese tolle Anwendung.
Dies hilft uns als Verein in Zeiten der Corona Krise extrem., :-)

Nun zum Problem:
Wenn man sich als User anmelden will, wird auf einmal beim Klicken auf den Anmeldebutton ein Download eine "login" Datei ausgeführt.
Eine Anmeldung ist nun nicht mehr möglich.
Für eine schneller Lösung wäre ich euch sehr dankbar!

Ich habe gerade festgestellt, dass der Admin User sich anmelden kann, ein normaler Nutzer aber nicht (login Datei wird runtergeladen).

**Comment by 97RS** [comment]
Ich habe gerade festgestellt, dass der Admin User sich anmelden kann, ein normaler Nutzer aber nicht (login Datei wird runtergeladen).

**Comment by tkrebs** [comment]
Das klingt nach einer fehlerhaften oder unvollständigen Konfiguration des Apache-Webservers. Möglicherweise ist PHP oder das Modul "mod_rewrite" nicht verfügbar.

**Comment by Shineson1001** [comment]
Hi @97RS,
wie sieht denn der Inhalt der heruntergeladenen Datei aus? Ist das php- oder html-Code?
