### ISSUE TITLE
Übertragene Seite startet mit Fehlermeldung

### ISSUE THREAD

**Issue by tennstar1** [tkrebs/ep3-bs#315]
Ich bräuchte bitte nochmals Euere Hilfe!
Ich habe eine funktionierende und bereits konfigurierte Installation von ep3 auf bplaced laufen.
Leider auf einem falschen Account. Ich habe sie nun heruntergeladen, auf einen eigenen Account hochgeladen, die Datenbank importiert und sie startet auch, aber leider mit der Fehlermeldung am oberen Rand:

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /users/ep3/www/vendor/zendframework/zend-stdlib/src/ArrayObject.php on line 426

Deprecated: array_key_exists() [function.array-key-exists]: Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /users/ep3/www/vendor/zendframework/zend-i18n/src/Translator/Loader/PhpArray.php on line 52

In der Seite wird ein Fenster angezeigt welches diesen Inhalt mit einem anschließend aufgeführten Strak Trace von 16 Zeilen hat:
Oops ... da ist wohl etwas schief gelaufen
__clone method called on non-object

Bitte informieren Sie uns bei exotischen oder nicht nachvollziehbaren Fehlermeldungen,
damit wir das Problem schnell beheben können.
Zurück zur Startseite
Exception details

Type Error
Mitteilung

    __clone method called on non-object

File

    /users/ep3/www/module/Calendar/view/calendar/calendar/index.landscape.phtml:18

Es wäre super wenn mir jemand helfen könnte diesen Fehler zu finden und abzustellen, ich bin hiermit leider überfordert!
Hier ist der Link zur Seite: http://ep3.bplaced.net

Vielen Dank im voraus für Euere Mühe
Gruß tennstar

**Comment by Shineson1001** [comment]
Hi @tennstar1 ,
die Warnung sollte man schon mal so weg bekommen: #261 (comment)

.. und als PHP-Version solltest du Version **7.2** auswählen.

**Comment by tennstar1** [comment]
Hallo @Shineson1001,
hab ich schon probiert, die Meldung ist dann weg aber das große Anmeldefenster erscheint auch nicht und alle Anmeldungen in den kleinen Fenstern werden mit einem weißen Bildschirm und einem Error 404 quittiert!
Ich kann nicht verstehen, dass die Kopie von einem funktionierenden System auf dem gleichen Server nicht zum laufen kommt!
7.2 wird morgen mal probieren
einstweilen Danke für Deine Mühe

**Comment by Shineson1001** [comment]
Hi @tennstar1, 
und teste mit der .htaccess Datei im "public"-Ordner

```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteRule ^robots\.txt$ misc/robots.txt
    RewriteRule ^favicon\.ico$ imgs-client/icons/fav.ico
    RewriteCond %{REQUEST_FILENAME} -s [OR]
    RewriteCond %{REQUEST_FILENAME} -l [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^.*$ - [L]
    RewriteRule ^.*$ index.php [L]
</IfModule>
```

.. und es gilt immer noch diese Abschnitt der Installationsanleitung
https://github.com/tkrebs/ep3-bs/blob/fb4a742ffa186511ee9eb65934a6637c6ab488ad/data/docs/install.txt#L47

**Comment by cbits68** [comment]
Hallo @Shineson1001,
um zu verstehen, warum eine Kopie beim selben Provider nicht funktioniert, müsstest Du das Setup.php untersuchen. Möglicherweise werden hier neben Datenbank und Maileinstellungen, auch Parameter (wie z.B. absolute Pfade) bei der Installation ausgelesen und in der Konfiguration abgespeichert.
Kopierst Du dann das Verzeichnis einfach auf einen anderen Account beim selben Provider, passen ggf. diese hart verdrahteten Parameter in der Konfigurationen nicht mehr.
Wenn Du bsp. auf einem PC das Programmverzeichnis einer Software auf einen anderen PC mit der gleichen Windows Version kopierst, funktionier das ja meist auch nicht, weil das Setup Programm die Registry Einträge setzt, welche Dir dann fehlen. Kann man natürlich auch per Hand nachziehen, wenn man weiß, welche das sind ...

**Comment by Shineson1001** [comment]
Hi @cbits68, 
man muss einfach nur einen Schritt nach dem anderen machen ... d.h. sich an den Fehlermeldungen entlang hangeln, bis es läuft ... jetzt sind wir aus meiner Sicht erst beim 2. und 3. Schritt ... und versuchen die "Infrastruktur" ans Laufen zu bekommen ... danach kommen die Einstellungen wie Datenbank-Einstellungen.

**Comment by Shineson1001** [comment]
@tennstar1,
Bei der Meldung stimmt was mit den Datenbank-Einstellungen nicht ... prüfe mal die Einstellungen in der local.php
![grafik](https://user-images.githubusercontent.com/22273771/81613842-6b92e300-93df-11ea-8758-ac9b5163a9bc.png)

Wenn die Datei local.php von deiner alten Installation übertragen wurde, dann sind die Datenbankeinstellungen bestimmt nicht mehr gültig und müssen auf dein neues Konto angepasst werden.

**Comment by tennstar1** [comment]
Hallo @Shineson1001,@cbits68,
Danke für Euere Hilfe!
Der entscheidende Hinweis war "php 7.2"
Die Seite auf der es läuft arbeitet mit 7.2 und die neue Seite 7.4, das war´s!
Deshalb konnte ich auch die Seite (ca. 10 mal) nicht neu installieren, d.h. das System läuft einfach nicht mit 7.4.
Ein GANZ GROSSES Danke noch an Euch zwei für Euere Mühe und Geduld!
Gruß tennstar
PS: Habt Ihr das System schon mal auf Xampp zum kaufen gebracht und wenn ja was müsste ich tun?

**Comment by cbits68** [comment]
Schön, dass es läuft. Ich habe PHP 7.3 eingestellt, die läuft auch bis auf kleinere Fehler, die man aber über Deaktivierung der debug Funktion ignorieren kann.
XAMPP habe ich mit ep3 noch nicht probiert.

**Comment by Shineson1001** [comment]
Hi @tennstar1,
XAMPP direkt habe ich noch nicht benutzt .. aber dahinter steckt auch nur der Apache mit u.a. php und MariaDB Modul; von daher sehe ich da kein Problem, wenn php 7.2 zum Einsatz kommt.

**Comment by tennstar1** [comment]
Hallo,

hab es heute probiert, funzt leider nicht auf die schnelle. 

Muss mal im Internet suchen, bringt beim Start folgende Fehlermeldung.

The PHP  <http://php.net/manual/de/book.intl.php> intl extension is required but not installed. Please contact your web hosting provider to get this one fixed.

Gruß tennstar1

 

Von: Shineson1001 <notifications@github.com> 
Gesendet: Dienstag, 12. Mai 2020 15:48
An: tkrebs/ep3-bs <ep3-bs@noreply.github.com>
Cc: tennstar1 <tennstar@gmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [tkrebs/ep3-bs] Übertragene Seite startet mit Fehlermeldung (#315)

 

Hi @tennstar1 <https://github.com/tennstar1> ,
XAMPP direkt habe ich noch nicht benutzt .. aber dahinter steckt auch nur der Apache mit u.a. php und MariaDB Modul; von daher sehe ich da kein Problem, wenn php 7.2 zum Einsatz kommt.

**Comment by Shineson1001** [comment]
Hi @tennstar1,
nur interessehalber ... wieso installierst du die Software in so viele unterschiedliche Umgebungen?

**Comment by tennstar1** [comment]
Hallo Shineson1001,

ich betreue zwei Tennisklubs und habe dort bei beiden ep3 laufen!

Meine erste Installation bei bplaced war nur rein zum Testen!

Bei 1&1 wo eine Seite liegt bekomme ich es trotz Umstellung auf php 7.2 nicht zum Laufen, deshalb habe ich es zunächst nochmal zusätzlich auf einem eigenen Account bei bplaced platziert weil es hier gut funktioniert und verlinke dorthin.

Werde mal bei 1&1 probieren mit der php Version noch ein bisschen runter zu gehen, denn es gibt dort den gleichen Fehler wie bei bplaced und 7.4.

Auf meinem PC und XAMPP wollte ich es rein Test technisch installieren, leider startet es nicht da irgend ein intl extension fehlen würde.

Es wird folgende Meldung angezeigt:

„The PHP  <http://php.net/manual/de/book.intl.php> intl extension is required but not installed. Please contact your web hosting provider to get this one fixed“

Es ist für aus Sicherheit technischen Gründen gut, für den Fall der Fälle immer ein neues frisches und laufendes System in der Hinterhand zu haben um mal kurzfristig reagieren zu können!

Solltest Du bezüglich XAMPP etwas mehr wissen oder erfahren wäre es schön wenn Du mich das wissen lassen würdest.

Danke nochmals

Gruß tennstar1

 

Von: Shineson1001 <notifications@github.com> 
Gesendet: Dienstag, 12. Mai 2020 22:21
An: tkrebs/ep3-bs <ep3-bs@noreply.github.com>
Cc: tennstar1 <tennstar@gmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [tkrebs/ep3-bs] Übertragene Seite startet mit Fehlermeldung (#315)

 

Hi @tennstar1 <https://github.com/tennstar1> ,
nur interessehalber ... wieso installierst du die Software in so viele unterschiedliche Umgebungen?

**Comment by tennstar1** [comment]
Hallo Shineson1001
ich hab jetzt zweimal mit IONOS telefoniert und nachgefragt warum meine Seite bei bplaced aber nicht bei ihnen läuft. Ergebnis negativ, man konnte oder wollte nichts sagen. Man hat mir in einer Mail verschiedene Links für Seite mit php Infos geschickt.
Ich hab mir das heute zum wiederholten mal angeschaut und dabei die Installationen bei den beiden Providern verglichen. Hier ist mir aufgefallen als ich mir den Quellcode habe anzeigen lassen, dass es bei der einen Inst. einen Ordner User gibt und bei dem anderen , die nicht funktioniert gibt´s den nicht. Ich hab nun dann mit dem Ftp die Installation, wo mir im Quellcode der Ordner User angezeigt wird nachgeschaut und wurde hier aber nicht fündig. Auch die php Datei mit dem angezeigten Quellcode konnte ich nicht finden.
Wird dieser Ordner User nur virtuell erzeugt oder müsste der vorhanden sein, auch der Quellcode
der beiden Startdateien war unterschiedlich. Ich kann mir leider keinen Reim darauf machen!
Vielleicht kannst Du mich bitte aufklären.
VG tennstar1

**Comment by Shineson1001** [comment]
Hi @tennstar1,
von den Dateien und Ordnern her sollten die Installationen nahezu identisch sein. Nur die Datenordner, in denen während der Benutzeraufrufe Daten zwischengespeichert werden unterscheiden sich.

Die "Ordner"-Namen, die man in der URL sieht, sind in der Regel keine physischen Ordner auf dem Server. Die könnte man durchaus als "virtuell" bezeichnen; dienen aber einfach nur dem Routing im Webserver, um die Funktion im php Code zu adressieren.

Das Buchungssytem bei IONOS ans Laufen zu bekommen ist aber auch kein großer Akt. Wo klemmt es denn?

**Comment by Shineson1001** [comment]
Hi @tennstar1,
nutzt du die XAMPP-Testinstallation unter Windows oder Linux bzw. hast du die mittlerweile am Laufen?

**Comment by tennstar1** [comment]
Hallo Shineson1001,
die xampp istall. habe ich noch auf dem Server und hab auch schon eine Xampp Install. zerschossen.
Scheint nicht so leicht zu sein, hab auch keine wirklich gute Anweisung gefunden welches int. Extension wo und wie installiert werden muss. Ich habe WIN 10 installiert.
Bei IONOS ist es halt immer noch dasselbe es kommt immer noch die alte Fehlermeldung.

> Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /users/ep3/www/vendor/zendframework/zend-stdlib/src/ArrayObject.php on line 426

Könnte sein, dass es vielleicht an der htaccess liegt, die dann die vielleicht speziellen Belange von IONOS berücksichtigt. Was anderes kann ich mir fast nicht mehr vorstellen.

**Comment by Shineson1001** [comment]
Hi @tennstar1,
Alle "Warning"-Meldungen von php bekommt man mit dieser Einstellung weg:
Datei: config/init.php
von
`define('EP3_BS_DEV_TAG', true);`
auf 
`define('EP3_BS_DEV_TAG', false);`
stellen

**Comment by tennstar1** [comment]
Hallo Shoson1001,
ist mir klar, löst aber nicht das Problem weil die Seite dann zwar normal dargestellt wird, jedoch ohne das Anmeldefenster und bei Anmeldung od. Registrierung kommt das Fenster "404 - Not Found".

**Comment by Shineson1001** [comment]
Hi @tennstar1,

dann wird die `.htaccess` Datei im Ordner `public` nicht verarbeitet ... existiert die Datei?

Eine XAMPP Einrichtung läuft auch .. hier die nötigen Schritte.

1. XAMPP laden und installieren (https://www.apachefriends.org/xampp-files/7.3.17/xampp-windows-x64-7.3.17-0-VC15-installer.exe). Es reicht als Auswahl: MySQL und phpMyAdmin
2. ep3 Paket in c:\xampp\htdocs
3. ep3: config\autoload\local.php mit den Datenbank-Verbindungsdaten ausstatten
4. httpd.conf öffnen und alles was `c:/xampp/htdocs` zu `c:/xampp/htdocs/public` ändern
5. php.ini öffnen und nach `intl` suchen. Kommentarzeichen vor dem `extension` Eintrag wegnehmen
6. Datenbank für ep3 per phpMyAdmin erstellen (Kollation: utf8_general_ci)
7. Apache Dienst stoppen und wieder starten
8. Webseite http://localhost/setup.php aufrufen

**Comment by Shineson1001** [comment]
Hi @tennstar1,
> ist mir klar, ...

wieso änderst du denn das dann nicht direkt und dauerhaft!? ... in deinen Installationen bestehen mehrere Probleme/Fehler, die man auch nach und nach ohne große Probleme wegbekommt .. nur irgendwie fangen wir immer wieder ganz vorne an.

> 404 - Not Found

Der Fehler hat gar nichts mit den "Warning"-Meldungen zu tun .. sondern mit der noch "krummen" Verzeichnisstruktur bzw. der .htaccess Datei

**Comment by tennstar1** [comment]
Guten Morgen Shineson1001,
Danke für Deine Antworten, hab schon vermutet, dass dies an der htaccess Datei liegt.
Kann aber leider selbst nicht beurteilen was hier nicht stimmt und wahrscheinlich für IONOS speziell angepasst werden muss.
Hier mal die momentan installierte:

> <IfModule mod_rewrite.c>

    RewriteEngine On
    #RewriteBase /   # Try to uncomment this if you experience redirect problems

    #RewriteCond %{ENV:REDIRECT_STATUS} ^$
    #RewriteRule ^index\.php$ http://bookings.example.com/ [R=301,L]

    #RewriteCond %{ENV:REDIRECT_STATUS} ^$
    #RewriteRule ^index\.php/(.*)$ http://bookings.example.com/$1 [R=301,L]

    RewriteRule ^robots\.txt$ misc/robots.txt
    RewriteRule ^favicon\.ico$ imgs-client/icons/fav.ico

    RewriteCond %{REQUEST_FILENAME} -s [OR]
    RewriteCond %{REQUEST_FILENAME} -l [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^.*$ - [L]
    RewriteRule ^.*$ index.php [L]

</IfModule>
Hast Du eine Lösung?
Für die Infos bzgl. XAMPP vielen Dank, werd ich heute mal ausprobieren!
Nochmals vielen Dank für Deine Mühe

**Comment by tennstar1** [comment]
@Shineson1001,
hab grad XAMPP ausprobiert, Hab nur Kommentarzeichen in der php.ini entfernt und meine bestehende ep3 Installation ist sofort gelaufen! 👍😀

**Comment by Shineson1001** [comment]
Hi @tennstar1,
seht gut, dass XAMPP jetzt läuft.
... bei der IONOS Installation ... die Datei muss `.htaccess` heißen, also mit führendem Punkt (.).

Mit dem Inhalt sollte es funktionieren.
```
<IfModule mod_rewrite.c>
RewriteEngine On

RewriteRule ^robots\.txt$ misc/robots.txt
RewriteRule ^favicon\.ico$ imgs-client/icons/fav.ico

RewriteCond %{REQUEST_FILENAME} -s [OR]
RewriteCond %{REQUEST_FILENAME} -l [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^.*$ - [NC,L]

RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
```

**Comment by tennstar1** [comment]
@Shineson1001, erstmal DANKE,
habs probiert, beim einloggen mit "https://tg-parkstein.de/ep3/public/user/login" öffnet sich die Hauptdomain, beim einloggen ohne /user/login alter Zustand!

**Comment by Shineson1001** [comment]
Hi @tennstar1,
1. Lege eine Subdomain unter "Domains & SSL" -> "Subdomain erstellen" an
2. Verbinde die neue Subdomain mit dem Verzeichnis: "Hosting-Übersicht" -> Webspace-Einstellungen: "Verzeichnis mit Domain verbinden"
3. Neue Subdomain auswählen und `/ep3/public` wählen und speichern.

**Comment by tennstar1** [comment]
Hallo @Shineson1001 ,
hatte ich schon mal gemacht, die Subdomain wird bei IONOS angezeigt, wenn ich sie aber aufrufe bekomme ich die Meldung "keine sichere Verbindung möglich"
Ich kann mich aber erinnern, dass ich vor mehreren Tagen diese Subdomain schon mal aufrufen konnte!

**Comment by Shineson1001** [comment]
Hi @tennstar1,

das ist ein Nebenschauplatz .. das liegt u.a. an dem Counter auf der Seite .. der bindet ein gif-Bild ohne http**s** ein ... ist aber erstmal unwichtig ...

**Comment by tennstar1** [comment]
Hab den Counter durch einen https:// fähigen ersetzt, das gleiche Ergebnis. "keine sichere Verbindung möglich"
Außerdem wird die eingestellte Subdomain immer wieder gelöscht, werd wohl nochmal bei IONOS nachfragen müssen.

**Comment by Shineson1001** [comment]
Hi @tennstar1,

ok. die Meldung "keine sichere Verbindung möglich" ist aber kein Problem vom Buchungssystem und kann auch erstmal ignoriert und später korrigiert werden. Normalerweise kann man die Seite von jedem Browser trotzdem öffnen lassen. ... aktuell kann ich aber keinen https Fehler mehr feststellen. Spontan fällt mir kein Grund ein wieso IONOS eine Subdomain löschen sollte.

**Comment by tennstar1** [comment]
Hallol @Shineson1001 👍😃
alles läuft!
Hab mich jetzt nochmal in Ruhe hingesetzt und alles gelöscht und mein bereits funktionierendes System übertragen.
Die Subdomain  die angelegt hatte habe ich gelöscht, den Daten Ordner umbenannt, einen neue Subdomain angelegt, die local.php angepasst, die init php wegen des Fehlers angepasst, dann die von Dir gemailte .htacess eingebaut und vor allem beim Import der Datenbank SQL darauf geachtet, dass das Datensystem auf UTF8-general_ci eingestellt war.
Dies wurde mir besonders bewußt als Du mir die inst Anweisung für XAMPP geschickt hast.
So nun erst das System mit der Subdomain gestartet und alles war hell und hat funktioniert!
Alle Einträge und Anmeldungen waren bereits vorhanden.
Ich DANKE DIR nochmals sehr, sehr herzlich für Deine Geduld und Deine Mühe.
VG tennstar1

**Comment by Shineson1001** [comment]
Hi @tennstar1,
ja wunderbar, dass es jetzt läuft. Manchmal zahlt sich die Hartnäckigkeit aus.
Danke für die ausführliche Rückmeldung.

**Comment by tennstar1** [comment]
Hallo @Shineson1001,
jetzt muß ich mich doch nochmal melden.
Es hat sich jetzt im nachhinein herausgestellt, dass das System doch einen Fehler hat!
1. Man kann sich registrieren und einloggen
2. Es wird aber keine Registrierungsmail versandt
3. Man kann buchen, aber es erscheint dann eine Fehlermeldung
    "Oops ... da ist wohl etwas schief gelaufen-Must call beginTransaction() before you can rollback"
    und es wird keine Buchungsbestätigung versandt.
4. Die Buchung wird aber erfolgreich angezeigt
Es scheint mit dem Mailversand irgendetwas nicht zu stimmen!
Ansonsten läuft´s eigentlich normal
Hast Du einen Lösungsvorschlag?
Gruß tennstar1

**Comment by Shineson1001** [comment]
Hi @tennstar1,
wie sehen die Mail-Einstellungen in der Datei `local.php` aus? Bei `type` sollte `sendmail` bei IONOS ausreichen .. und eine gültige Absender E-Mail Adresse unter `address`

**Comment by tennstar1** [comment]
Hallo @Shineson1001,
folgende Eintragungen sind dort gespeichert!

>    'mail' => array(
        'type' => 'sendmail', // or 'smtp' or 'smtp-tls'
        'address' => 'info@tg-parkstein.de',

        'host' => '?', // for 'smtp' type only, otherwise remove or leave as is
        'user' => '?', // for 'smtp' type only, otherwise remove or leave as is
        'pw' => '?', // for 'smtp' type only, otherwise remove or leave as is

        'port' => 'auto', // for 'smtp' type only, otherwise remove or leave as is
        'auth' => 'plain', // for 'smtp' type only, change this to 'login' if you have problems with SMTP authentication
    ),
    'i18n' => array(
        'choice' => array(

**Comment by Shineson1001** [comment]
Hi @tennstar1,
handelt es sich um die IONOS-, XAMPP- oder die bplaced Installation?

**Comment by tennstar1** [comment]
Hallo @Shineson1001  es handelt sich um die IONOS inst.
XAMPP funktioniert!

**Comment by Shineson1001** [comment]
Hi @tennstar1,
die Mail-Einstellungen sind ok .. schwer zu sagen woran es liegt. Die Fehlermeldungen sind leider (allgemein vom ep3-System) nicht sehr aussagekräftig. Man muss viel interpretieren und in dem Fall fällt mich auch spontan nichts ein.

**Comment by tennstar1** [comment]
Werde morgen noch mal bei IONOS anrufen und nachfragen warum sendmail nicht funktioniert!
Eigentlich kann ich es nicht verstehen weil das gleiche System mit den gleichen Einstellungen, sehr stabil und funktionell auf Xampp und bplaced läuft.
Wollte noch fragen wie man die smtp Einstellungen aktiviert, vielleicht geh´s ja damit!

**Comment by Shineson1001** [comment]
Hi @tennstar1.

du kannst mal einen kleinen Mailtest mit dem Skript machen.
Einfach einen Datei mailtest.php im "public"-Ordner anlegen; mit diesem Inhalt und dann im Browser aufrufen. Mailadressen voher anpassen.
```
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
ini_set('log_errors', 1);
ini_set('ignore_repeated_errors', 1);
ini_set('html_errors',  1);
ini_set('ignore_user_abort', 1);

error_reporting(E_ALL);

$empfaenger = 'abc@test.org';
$betreff = 'Der Betreff';
$nachricht = 'Nur ein Test';
$header = array(
    'From' => 'yxz@abc.de',
    'Reply-To' => 'yxz@abc.de',
    'X-Mailer' => 'PHP/' . phpversion()
);

echo mail($empfaenger, $betreff, $nachricht, $header);
?>
```

Die Ausgabe im Browser sollte "1" sein. Und darauf achten, dass nur gültige IONOS-Mail-Adressen als `From` und `Reply-To` verwendet werden.

**Comment by tennstar1** [comment]
Hallo @Shineson1001,
Danke für Deine Antwort und Deine Anregung.
Ich habe den Test gemacht und der war positiv, es kam eine 1 zurück!
Folgende Antwort habe ich von IONOS auf meine Anfrage bzgl. Sendmail bekommen:

> Mit der Fehlermeldung können wir leider nichts anfangen, da diese keinerlei Informationen preisgibt.

An der Subdomain wird es nicht liegen, da auch diese Mailserver nutzt.

Meine Vermutung ist, dass das Programm nicht RFC konform ist.

Hier wurde am 01.04.2020 die Änderung von unseren Administratoren eingeführt.

Die definierten Standards aus RFC5321 und RFC5322.

Ich kann hiermit nichts anfangen, Du vielleicht?
Habs mittlerweile auch schon mit smtp probiert, war auch negativ.
Aber ich weiß nicht ob man, außer die dementsprechenden Daten einzutragen, noch etwas ändern muß.

**Comment by Shineson1001** [comment]
Hi @tennstar1,
evtl. steht in der Logdatei unter `data/log/errors.txt` eine brauchbare Fehlermeldung.

**Comment by tennstar1** [comment]
Hallo @Shineson1001 ,
die Datei ist geschätzt 2 km lang :-) sowie ich das übersehen kann steht dort immer dir gleiche Fehlermeldung die ich ausgeblendet habe

> [23-May-2020 13:24:15 Europe/Berlin] PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /homepages/20/d34594934/htdocs/tgpbs/vendor/zendframework/zend-stdlib/src/ArrayObject.php on line 426

**Comment by Shineson1001** [comment]
Hi @tennstar1,
die Meldung hat nichts mit dem Versenden von Mails zu tun.

**Comment by tennstar1** [comment]
Hallo @Shineson1001,
hatte sie auf "false" gesetzt, dann stimmt das Themeplate. Wenn ich auf "true" setze zereist es mir das Themeplate, d.h. das Anmeldefenster ist riesengroß funktioniert aber.
Von IONOS hab ich gerade folgende Mitteilung bekommen:

> Ihre E-Mail wurde von unserem SMTP-Server abgelehnt, weil diese nicht die definierten Standards aus RFC 5321 und RFC5322 einhält.
Diese Änderung der Anforderungen wurde von unseren Administratoren am 01.04.2020 eingeführt.
Die Ursache ist vermutlich, dass die E-Mail Kopfzeilen unvollständig sind oder mehrere Einträge des gleichen Feldtyps enthalten.
Die Kopfzeilen Ihrer E-Mail müssen die Felder "Date:", "From:", "Sender:" und "To:" enthalten.
Darüber hinaus dürfen die Kopfzeilen nicht mehr als genau einen, der folgenden Feldtypen beinhalten: "Date:", "From:", "Sender:", "To:", "CC:", "BCC:", "Subject:"
Hinweis: Die Feldtypen To:, CC: und BCC: können selbstverständlich mehrere Empfänger enthalten.

Ich kann leider nichts damit anfangen, weil ich nicht weiß wo man dieses einsehen oder ändern könnte.

**Comment by tennstar1** [comment]
Hallo @Shineson1001,
ich hab jetzt noch mal ein bisschen rum probiert und hab nun folgendes festgestellt.
Wenn ich INIT auf "true" setze habe ich wie bei obigen Link sichtbar ein zerschossenes Themepl.
aber die Mailfunktion passt und es werden Mails sowohl bei der Registrierung und beim buchen versandt!
Wenn die INIT auf "false" gesetzt ist schaut die Seite normal aus, die Buchung wird angezeigt aber es werden keine Mails versandt und das Fenster:

> Oops ... da ist wohl etwas schief gelaufen
Must call beginTransaction() before you can rollback

erscheint!
Scheint ein Teufelskreis zu sein! Kann mit jetzt überhaupt keinen Reim mehr drauf machen!

**Comment by Shineson1001** [comment]
Hi @tennstar1,
ein ganz schönes gefummel .. :-)
teste mal diesen Inhalt in der INIT Datei.
```
<?php

/**
 * Testing and development mode
 *
 * If true, errors are displayed.
 * If false, errors are silently logged into the error file.
 *
 * If false, certain caches will be enabled.
 *
 * Should be true during initial testing and false when actually using the system.
 */
define('EP3_BS_DEV_TAG', true);

/**
 * Timezone of the people using the system
 *
 * An overview of available timezones can be found here:
 * http://php.net/manual/en/timezones.php
 */
ini_set('date.timezone', 'Europe/Berlin');

/**
 * The following settings are more technical and can usually be ignored.
 */

ini_set('error_reporting', E_ALL & ~E_USER_DEPRECATED);
ini_set('error_log', getcwd() . '/data/log/errors.txt');

ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);
ini_set('log_errors', 1);
ini_set('ignore_repeated_errors', 1);
ini_set('html_errors',  0);
ini_set('ignore_user_abort', 0);

ini_set('default_charset', 'UTF-8');
```

**Comment by tennstar1** [comment]
Hallo @Shineson1001, Du bist der beste!
Die letzten 6 "ini_set" Zeilen machen den Unterschied!
Diese waren in meiner vorhanden:

> ini_set('display_errors', EP3_BS_DEV_TAG ? 1 : 0);
ini_set('display_startup_errors', EP3_BS_DEV_TAG ? 1 : 0);
ini_set('log_errors', EP3_BS_DEV_TAG ? 0 : 1);
ini_set('ignore_repeated_errors', 1);
ini_set('html_errors',  EP3_BS_DEV_TAG ? 1 : 0);
ini_set('ignore_user_abort', EP3_BS_DEV_TAG ? 1 : 0);

wenn du die mit den von Dir gesandten vergleichst ist das ein himmelgroßer Unterschied!
Wo die bei mir im System gespeicherten herkommen weiß ich nicht, aber die müssen ja bei der Installation erzeugt worden sein und waren definitiv der Auslöser der Mail- und Anzeige Fehler!
Wie bist Du jetzt zu dieser INIT Einstellung gekommen!
Ich Danke Dir nochmals recht herzlich für Deine Geduld und Deine Hilfe!! :-))
Gruß
tennstar1

**Comment by tennstar1** [comment]
Guten Morgen @Shineson1001 ,
also jetzt läuft wirklich sehr gut und ist so wie es sein soll!
Wenn ich nun mit meinem momentan aktiven ep3 System auf bplaced mit allen Daten, sprich Anmeldungen und Reservierungen umziehen möchte zu IONOS, funktioniert das wenn ich die komplette Datenbank von bplaced nach IONOS importiere. Es müssten doch die mühsam erarbeiteten Einstellungen erhalten bleiben.
Gruß
tennstar1

**Comment by Shineson1001** [comment]
Hi @tennstar1,
ich helfe wo immer ich kann und gerne. Das ep3 System hat sehr spezielle Systemvoraussetzungen.
Die Fehlerbehandung ist; ich sage's nur ungern, weil ich das Projekt richtige geil finde; richtig schlecht. ... Wenn ein Fehler auftritt, dann bekannt man nicht den eigentlich auslösenden Grund, sondern irgendein "drumherum"-Ereignis genannt. Man muss den eigentlichen Fehler um 3 Ecken interpretieren.

**Comment by tkrebs** [comment]
Die hier beschriebenen Fehlermeldungen sollten in der aktuellen Version 1.7.0 behoben sein.

**Comment by mjmpeace** [comment]
@tennstar1 ich habe im Moment nach dem Serverwechsel die Gleichen Probleme.

Der Mailtest erbrachte Erfolg. Also funktioniert das grundsätzlich. Die init habe ich angepasst, aber immer noch der Fehler.
Kannst du helfen?
