### ISSUE TITLE
Feature request: Wiederkehrende Veranstaltungen

### ISSUE THREAD

**Issue by geopicture** [tkrebs/ep3-bs#32]
Wäre es möglich, in der nächsten Version die Funktion einzubauen, wiederkehrende Veranstaltungen anlegen zu können?
Sprich die gleiche Eingabemöglichkeit wie bei Abo-Reservierungen, nur eben für Veranstaltungen.
Vielen Dank

**Comment by tkrebs** [comment]
Die neue Version enthält ein grundlegend neues System, mit welchem beliebige Einträge in den Kalender möglich werden. Regelmäßige Veranstaltungen werden dann möglich sein (inklusive Teilnahmemöglichkeiten).

**Comment by geopicture** [comment]
Perfekt!
