### ISSUE TITLE
System sendet keine Registrierungs-Email

### ISSUE THREAD

**Issue by frankgayer** [tkrebs/ep3-bs#321]
Hallo,

ich habe ein System neu installiert und eben einen Testuser angelegt. Ich erhalte eine Nachricht dass ich eine Email für die Aktibierung erhalten soll. Diese Email bekomme ich, auch wenn ich diese erneut anfordere, nicht. Woran kann das liegen ?

**Comment by maegnes** [comment]
Am besten über SMTP verschicken. Sonst kann es sein, dass die Mails nicht ankommen.

DIe Daten zum SMTP-Account unter config/autoload/local.php eintragen.

Falls es die local.php noch nicht gibt die local.php.dist in local.php umbenennen.

**Comment by frankgayer** [comment]
Danke für den Tip. Ich ging davon aus dass nach der Konfiguration unter Verwaltung das alles so eingestellt ist

**Comment by frankgayer** [comment]
Dazu muss ich dann aber host, user und pw füllen. Das habe ich ja nur wenn ich das für mich selbst mache aber nicht wenn ich das für andere eionrichte. Gibt es da keinen anderen Weg ?

**Comment by maegnes** [comment]
Dann muss "der andere" Dir halt Zugangsdaten zu einem SMTP-Postfach mitteilen. Hatte vorhin das gleiche Problem, dass keine Mails ankamen. Nach dem Eintragen der SMTP Daten funktioniert es wunderbar.

**Comment by frankgayer** [comment]
mit sendmail geht es auch, muss also nicht smtp sein. Natürlich sollte man die Emailadresse anpassen. Hatte aber in der Doku keinen Hinweis gefunden dass man das noch Einstellen muss

**Comment by maegnes** [comment]
@frankgayer Ticket dann bitte schließen. Sonst wird es zu unübersichtlich. :)
