### ISSUE TITLE
Sortierung Benutzer

### ISSUE THREAD

**Issue by chrisschauer75** [tkrebs/ep3-bs#324]
Wie kann man (vielleicht im Code) die Sortierung der Benutzer ändern?
Ich hab leider nichts geunden.

Derzeit ist die Sortierung nach Namen.
Ich hätte gerne die Sortierung nach Nr., wenn es leicht geht. :-)

![image](https://user-images.githubusercontent.com/65334696/81907220-b2433180-95c7-11ea-9140-e84138dc2cac.png)

Danke für etwaige Hinweise.

**Comment by cbits68** [comment]
Hallo chrisschauer75,
vielleicht kann man später sogar mal einen Parameter für die Filterung einbauen, den man dass im Backend auswählen kann (z.B.  Sortierung nach ID, Vorname, Nachname, ?) und ggf. auch noch die Felder, die man anzeigen lassen will (Telefonnummer, …)
Vorerst behelfe ich mir so, dass ich mir die Daten in eine Excel Tabelle kopiere. dort kann ich dann nach ID, Name oder Staus sortieren. Wenn man ein wenig geübt ist und die Tabellenstruktur kennt, kann man die entsprechenden Daten auch direkt per SQL aus der Datenbank exportieren, dann hat man sogar alle Benutzerdaten zur Verfügung.
Gruß
Andreas

**Comment by Busfreak** [comment]
Du musst nur in
/module/Backend/src/Backend/Controller/UserController.php
in Zeile 39 die Sortierung von 'alias ASC' in 'uid ASC' ändern ;-)

**Comment by chrisschauer75** [comment]
Perfekt! Genau das habe ich gesucht! 
VIELEN DANK!
