### ISSUE TITLE
Anzeige von Belegt / Frei ohne Anmeldung

### ISSUE THREAD

**Issue by Holger690** [tkrebs/ep3-bs#329]
Hallo Herr Krebs,
erstmal vielen Dank für den tollen Support
Die Software läuft nun schön stabile (auch ohne Mail Bestätigung ) super!
Gibt es die Möglichkeit das man ohne Anmeldung schon sehen kann ob die Plätze Gebucht - Frei - für den Zeitraum sind und Gebucht in Grün ?
Vielen Dank im voraus.
Gruß
Holger Rudershausen

**Comment by MarcoFuerte** [comment]
so etwa ? 
![greenfree](https://user-images.githubusercontent.com/62291350/82055734-d92d6080-96b8-11ea-90cd-fb5cda37c5ae.png)

**Comment by MarcoFuerte** [comment]
Dannn einfach das default.min.css editieren .. zeile 334 

a.cc-free:link,
a.cc-free:visited {
 opacity:1.0;
 color:#333;
 background-color:#3EC822;

**Comment by Holger690** [comment]
default.min.css alles grün wenn frei hat funktioniert.
Aber in default.css zeile 14 finde ich nicht ,,a.cc-own:visited { background-color: #8BB243;
Liegt diese in einem anderen Ordner?

**Comment by Holger690** [comment]
Was auch nicht funtioniert, ist das Belegt angezeigt wird wenn keiner angemeldet ist

**Comment by MarcoFuerte** [comment]
Hallo Holger ... 

die default.min.css    lieg im Ordner : /public/css/
die default.css    liegt im Ordner : /public/css-client/

**Comment by MarcoFuerte** [comment]
> Was auch nicht funtioniert, ist das Belegt angezeigt wird wenn keiner angemeldet ist

Als bei mir gehts ... musst mal de cache leeren
