### ISSUE TITLE
Delay to book next hour

### ISSUE THREAD

**Issue by GregLoichot** [tkrebs/ep3-bs#330]
Hi, 

Let’s say player 1 and 2 play on court 1 from 8 am to 9 am, and the court 1 is free from 9 am to 10 am.
In the club, players cannot book an other court until their game is completed. So, in the example they cannot book until 9:00am.
BUT, if they want to play (and because the court is free) from 9 to 10, they cannot because at 9:00:01 they will be only able to book for 11 am (because the hour from 9 to 10 has already started !).

So, is it possible to add a « delay », so our players could book from 9 to 10, until 9:05 am (let’s say) ?

Best,
Greg

**Comment by tkrebs** [comment]
Technically sure, by directly modifying the code. There is however no such configuration option available by default.

**Comment by GregLoichot** [comment]
Yes, an option would be useful :)

**Comment by luke8800gts** [comment]
Please this would be utterly useful; so that also spontaneous games(starting past the full hour) can be recorded

**Comment by tkrebs** [comment]
There is a commit in the development branch that allows bookings up to half a "bookable time block" after it already started (if the minimum booking range is set to 0 = unrestricted):

https://github.com/tkrebs/ep3-bs/commit/256334a57e835f6f86e17914f20c1c62b5fa09b2

You can download the latest development package from GitHub:
https://github.com/tkrebs/ep3-bs/archive/develop.zip

It is sufficient to replace the `module` directory.

**Comment by Busfreak** [comment]
Oh, sorry @tkrebs 
ich hatte deinen Commit nicht bemerkt.
Sind ja beides auch unterschiedliche Anforderungen, leider an der gleichen Stelle umzusetzen.
Wie sollen wir damit umgehen?
