### ISSUE TITLE
ZEITZONE ?

### ISSUE THREAD

**Issue by MarcoFuerte** [tkrebs/ep3-bs#331]
Hallo zusammen, 
kan mir jemand sagen wo ich die Zeitzone einstellen kann ? 
Info 
Server steht in Deutschland - Tennisplatz ist auf den Kanaren (-1h) .. 
z.b. : Serverzeit 20:00  Lokale Zeit 19:00 -- diese eine Stunde kann der Kunde nicht buchen. 

Hat mir jemand eine Tip ... wo ich dem Programm aktuelle Zeit -1h beibringen kann ... 

Danke

**Comment by Shineson1001** [comment]
Hi @MarcoFuerte 
schau mal in die Datei `config/init.php`
=>ini_set('date.timezone', 'Europe/Berlin');
Liste von Zeitzonen in Afrika: https://www.php.net/manual/de/timezones.africa.php

**Comment by MarcoFuerte** [comment]
Hallo Shineson1001 ....
kennst du das wenn du den Wald vor lauter Bäumen nicht mehr siehst :-)   

DANKE !!!!
