### ISSUE TITLE
Fehler nach Bestätigung der E-Mailadresse

### ISSUE THREAD

**Issue by onkelkirsch** [tkrebs/ep3-bs#335]
Hallo!

Ich erhalte eine Fehlermeldung nach Bestätigung der E-Mailadresse für neue Benutzer. Diese lautet:

Zend\View\Renderer\PhpRenderer::render: Unable to render template "user/account/activation"; resolver could not resolve to a file

Die Anmeldung funktioniert danach trotzdem. Jedoch wäre die Fehlermeldung für die Benutzer irritierend... 

Ansonsten ein Top System!! :-)

Könnt Ihr weiterhelfen? 

VG Sascha

**Comment by onkelkirsch** [comment]
Hier noch die weitere Meldung:

#0 /www/htdocs/w0190089/tc-gresaubach.de/buchung/vendor/zendframework/zend-view/src/View.php(207): Zend\View\Renderer\PhpRenderer->render(NULL)
#1 /www/htdocs/w0190089/tc-gresaubach.de/buchung/vendor/zendframework/zend-view/src/View.php(236): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#2 /www/htdocs/w0190089/tc-gresaubach.de/buchung/vendor/zendframework/zend-view/src/View.php(200): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#3 /www/htdocs/w0190089/tc-gresaubach.de/buchung/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(105): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#4 [internal function]: Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#5 /www/htdocs/w0190089/tc-gresaubach.de/buchung/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#6 /www/htdocs/w0190089/tc-gresaubach.de/buchung/vendor/zendframework/zend-eventmanager/src/EventManager.php(248): Zend\EventManager\EventManager->triggerListeners('render', Object(Zend\Mvc\MvcEvent))
#7 /www/htdocs/w0190089/tc-gresaubach.de/buchung/vendor/zendframework/zend-mvc/src/Application.php(384): Zend\EventManager\EventManager->triggerEvent(Object(Zend\Mvc\MvcEvent))
#8 /www/htdocs/w0190089/tc-gresaubach.de/buchung/vendor/zendframework/zend-mvc/src/Application.php(356): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#9 /www/htdocs/w0190089/tc-gresaubach.de/buchung/public/index.php(75): Zend\Mvc\Application->run()
#10 {main}

**Comment by tkrebs** [comment]
Gibt es diese Datei bei dir?

https://github.com/tkrebs/ep3-bs/blob/master/module/User/view/user/account/activation.phtml

**Comment by onkelkirsch** [comment]
So in der Form nicht, aber so ähnlich...
Der Pfad lautet ./buchung/module/User/view/user/account und die Datei heißt activation-resend.phtml

**Comment by onkelkirsch** [comment]
Hier der Inhalt:

<?php

$this->setup(array(
    'title' => 'Resend activation email',
    'panel' => 'centered-panel',
    'messages' => array(
        'success' => $this->activationResendMessage,
    ),
    'back' => true,
    'links' => array(
        'Login' => $this->url('user/login'),
    ),
));

?>

<div>
    <h1><?= $this->t('Resend activation email') ?></h1>

    <div class="separator-small"></div>

    <p>
        <?= $this->t('If you did not receive an activation email from us after registration, you can request a new one here.') ?>
        <?= $this->t('Therefore, please type the email adress you used for registration.') ?>
    </p>

    <div class="separator separator-line"></div>

    <div class="padded">

        <?php

        $form = $this->activationResendForm;
        $form->setAttribute('method', 'post');
        $form->setAttribute('action', $this->url('user/activation-resend'));
        $form->prepare();

        ?>

        <?= $this->form()->openTag($form) ?>

        <table class="default-table">
            <tr>
                <td class="default-form-label-row">
                    <?= $this->formLabel($form->get('arf-email')) ?>
                </td>
                <td>
                    <?= $this->formElement($form->get('arf-email')) ?>
                </td>
            </tr>

            <?= $this->formRowSubmit($form, 'arf-submit') ?>
        </table>

        <?= $this->form()->closeTag() ?>

    </div>
</div>

**Comment by onkelkirsch** [comment]
`<?php

$this->setup(array(
    'title' => 'Resend activation email',
    'panel' => 'centered-panel',
    'messages' => array(
        'success' => $this->activationResendMessage,
    ),
    'back' => true,
    'links' => array(
        'Login' => $this->url('user/login'),
    ),
));

?>

<div>
    <h1><?= $this->t('Resend activation email') ?></h1>

    <div class="separator-small"></div>

    <p>
        <?= $this->t('If you did not receive an activation email from us after registration, you can request a new one here.') ?>
        <?= $this->t('Therefore, please type the email adress you used for registration.') ?>
    </p>

    <div class="separator separator-line"></div>

    <div class="padded">

        <?php

        $form = $this->activationResendForm;
        $form->setAttribute('method', 'post');
        $form->setAttribute('action', $this->url('user/activation-resend'));
        $form->prepare();

        ?>

        <?= $this->form()->openTag($form) ?>

        <table class="default-table">
            <tr>
                <td class="default-form-label-row">
                    <?= $this->formLabel($form->get('arf-email')) ?>
                </td>
                <td>
                    <?= $this->formElement($form->get('arf-email')) ?>
                </td>
            </tr>

            <?= $this->formRowSubmit($form, 'arf-submit') ?>
        </table>

        <?= $this->form()->closeTag() ?>

    </div>
</div>`

**Comment by onkelkirsch** [comment]
Kommando zurück, die Datei wurde beim Upload in der Tat nicht übertragen. Habe Sie nochmals kopiert und jetzt läufts. 

VIELEN DANK! :-)
