### ISSUE TITLE
Warning: "continue" targeting switch is equivalent to "break".

### ISSUE THREAD

**Issue by frankgayer** [tkrebs/ep3-bs#336]
Hallo,

ich bekomme seit heute morgen diese Fehlermeldung auf der Seite. Ich habe nichts im Code geändert. Wer kann dazu etwas beiftragen ?

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /www/htdocs/w00e1827/sve.t.bespannservice.de/vendor/zendframework/zend-stdlib/src/ArrayObject.php on line 426

**Comment by Shineson1001** [comment]
Hi @frankgayer,
setzte den Wert in den Datei `init.php` auf `false` .. dann werden die Warnungen unterdrückt.
https://github.com/tkrebs/ep3-bs/blob/fb4a742ffa186511ee9eb65934a6637c6ab488ad/config/init.php.dist#L13

**Comment by frankgayer** [comment]
leider hat sich herausgestellt dass es an der php Version der Datenbank lag. Mit 7.4 kam dieses Problem und das Format des Kalenders war auch völlig verschoben. Mit der 7.1 ist wieder alles OK. 

Meine Frage stellt sich hier, ob ich die Codierung updaten sollte auf die 1.64

**Comment by cbits68** [comment]
Siehe Dokumentation ...
[Zend Framework 2](http://framework.zend.com/) (2.5).
It is compatible with PHP version up to and including 7.2 - uot not PHP 7.3+. We are currently working on an upgrade of the underlying Zend Framework to make it compatible with PHP 7.3+.

Zendframework wird durch Laminas abgelöst.
Daher muss irgendwann Zendframework abgelöst werden, um auch PHP 7.3#+ kompatibel zu sein. Ist aber eine Menge Arbeit, daher wird es wohl noch etwas dauern ...

**Comment by frankgayer** [comment]
Ich wollte das sowieso updaten aber ich bin mir nicht sicher ob ich die neuen Dateien nur uploaden muss oder ob ich noch etwas anderes machen muss ?

**Comment by murreni** [comment]
hatte auch gerade das Problem. 
Ein Abändern von **continue** in **break** in zeile 426 der php Datei schafft Abhilfe

**Comment by frankgayer** [comment]
Nutzt aber nichts wenn der Code nicht kompatibel mit der verwendeten php Version ist. Meine Frage ist leider damit von oben nicht beantwortet

**Comment by murreni** [comment]
ahh. ok. mit php 7.3 hat bei mir geklappt

**Comment by Shineson1001** [comment]
Hi @frankgayer,

ep3 ist für php 7.2 entwickelt worden ... 7.3 geht auch, aber mit Warnungen. Gibt auch für die ep3-Version 1.64. ... oder welche Frage von dir ist noch offen?

**Comment by frankgayer** [comment]
Genau diese Frage war noch offen. Danke

**Comment by tkrebs** [comment]
#372

**Comment by tkrebs** [comment]
Behoben in Version 1.7.0
