### ISSUE TITLE
MD5 checksum

### ISSUE THREAD

**Issue by GS-OM** [tkrebs/ep3-bs#339]
I've downloaded ep3-bs-package-1.6.4.zip and calculated the MD5-checksum. It isn't the same as you described in the download field. Can I trust the download package?

**Comment by tkrebs** [comment]
It should be fine, but the safest option is always to clone the repository directly from GitHub. You just need to install the dependencies with Composer yourself, otherwise it's the same.

**Comment by bandemer** [comment]
md5 checksum for version 1.7 on download page is not correct.
md5sum gives 6fbdbbc83cd633a69809befc21a2c0c8
If you cannot provide a valid md5 checksum, then please remove it.

**Comment by tkrebs** [comment]
Thank you for the hint. I have reviewed and updated the md5 checksum generation workflow.
