### ISSUE TITLE
Stornierung jederzeit ermoeglichen

### ISSUE THREAD

**Issue by Elektrostephan** [tkrebs/ep3-bs#34]
Hallo,
ich möchte das System für eine Modellbaugeschichte verwenden, dazu wäre es nötig das die Buchungen der Teilnehmer jederzeit wieder stornierbar sind. Wie kann ich das ändern?

So nebenbei noch, ist es möglich die Pflichtfelder bei der Registriereung auszuschalten? Mir würde Vorname und Name reichen, wäre jetzt aber auch nicht so schlimm.

Gruß und Danke schonmal, Stephan

**Comment by Elektrostephan** [comment]
Die Möglichkeit der Buchung bis zum Ende der Zeit wäre auch noch gut.

**Comment by tkrebs** [comment]
Hallo Stephan,

die Stornierungsdauer kann in der Verwaltung der "Plätze" angegeben werden. Mit einem Wert von 0 sollte die Stornierung jederzeit möglich sein.

Die Pflichtfelder können leider derzeit nur über Anpassungen im Quellcode ausgeschaltet werden. Ich habe mir aber notiert, eine Abschaltfunktion für das nächste Update einzubauen.

Zum letzten Punkt: Meinst du eine Buchung bis zum Ende des Tages? Eventuell funktioniert hier, in der Platz-Verwaltung bei den maximal buchbaren Zeitblock auf einen hohen Wert (z.B. 24 Stunden) einzustellen.

**Comment by Elektrostephan** [comment]
Bei der Stornierungsdauer mit Wert 0 ist gar keine Stornierung möglich.

Die "Plätze" sind eingeteilt in 10 Minuten Blöcken, wo sich die Teilnehmer dann ein 10Min.-Zeitfenster reservieren können. Wenn das einer wegen defekt zb nicht nutzen kann, sollte er das Zeitfenster stornieren können und jemand anderes sich dafür eintragen können. 
Sobald der Block schon angefangen hat, ist er nicht mehr buchbar.

**Comment by tkrebs** [comment]
Die Stornierungsfrist ist in der Datenbank in Sekunden hinterlegt. Wenn du den Wert "range_cancel" in der "squares"-Tabelle manuell auf 1 setzt (= 1 Sekunde) ist es praktisch stornierbar bis zum Beginn der Buchung.

**Comment by Elektrostephan** [comment]
Ok, hat funktioniert.
Das man jetzt während dem Block nicht buchen/stornieren kann, ist jetzt auch nicht so schlimm, notfalls mache ich das oder ernenne andere noch zum Mitarbeiter. Man kann halt nicht immer alles haben :-)
Sollte jetzt so aber schon funktionieren.

Danke nochmal und Gruß
Stephan

**Comment by tkrebs** [comment]
Ich habe trotzdem noch die Möglichkeit eingebaut, Dezimalzahlen direkt in das Eingabefeld einzugeben. :)

**Comment by sitze89** [comment]
Hallo, gibt es hierzu schon eine Möglichkeit die Buchung auch während der gebuchten Zeit zu stornieren? Lg

**Comment by Sahel2021** [comment]
> Hallo, gibt es hierzu schon eine Möglichkeit die Buchung auch während der gebuchten Zeit zu stornieren? Lg

Ich möchte das nochmal aufrufen und fragen, ob das geht? Also eine bereits angebrochene Stunde/Buchung wieder freigeben?
