### ISSUE TITLE
(Doku] Wartungsarbeiten deaktivieren

### ISSUE THREAD

**Issue by vogt31337** [tkrebs/ep3-bs#340]
Hi,

ich habe es gerade geschafft aus dem System rauszuwerfen, wenn wartungsarbeiten aktiviert sind und man den admin user ausloggt, gibt es keine einfache möglichkeit sich wieder einzuloggen.

Ich habe dann händisch in der Datenbank das passende Feld verändert und konnte mich wieder einloggen.

Das sollte dringend mit in die Doku!

**Comment by mumulusul** [comment]
mit https://deineDomäne/user/login  kommst wieder rein ,,,,
