### ISSUE TITLE
Wie kann ich abfragen wer welches Produkt mitgebucht hat?

### ISSUE THREAD

**Issue by andyproko** [tkrebs/ep3-bs#341]
Ich habe für unser Platzbuchungssystem "Produkte" definiert für Gästemarken. Es gibt drei verschieden Gästemarken. Wie kann ich als Verwalter abfragen:
a. Wer eines der Produkte mitgebucht hat?
b. Welches der angebotenen Produkte?
Es sollte uns ermöglichen monatliche Rechnungen zu erstellen (die Rechnungen werden manuell erstellt).

**Comment by cbits68** [comment]
Hallo andyproko,
eine Abfrage nach Produkt gibt es im Backend meines Wissens nach nicht. könnte man ggf. aus der DB auslesen.
Im Backend kannst Du aber über die Buchungs-Verwaltung z.B. den Filter  (rechnungsstatus = ausstehend) (rechnungssumme > 0) schauen, was noch offen ist. Dort siehst Du dann die entsprechenden Buchungen. Wenn Du einzelne davon öffnest siehst Du auch das gebuchte Produkt zu der jeweiligen Buchung.
Mir ist allerdings aufgefallen, dass bei einer Stornierung des Platzes, das gebuchte Produkt nicht mit storniert wird. Ich setze es dann aktuell den Rechnungsstatus per Hand auf "Storniert".
Ich wollte eigentlich noch ein Zusatzprodukt Flutlicht erstellen, was ab einer bestimmten Uhrzeit automatisch dazu gebucht werden muss. Dazu müsste man aber an den Code ran und dafür habe ich frühestens im Winter wieder Zeit ;-) Jetzt wird endlich wieder Tennis gespielt  :-)

**Comment by andyproko** [comment]
@cbits68 danke dir .. hatte beide Optionen auch schon gefunden. Hoffte auf eine elegantere Lösung. Meine Abfrage zur Berücksichtigung einer Buchung inkl. Gästemarke in meinem Fall ist die Kombination von (rechnungssumme > 0) und (status = einzelbuchung).
