### ISSUE TITLE
Bemerkungsfeld bei einfacher Buchung

### ISSUE THREAD

**Issue by MartinAltVK** [tkrebs/ep3-bs#342]
Gibt es die Möglichkeit, einem registrierten Benutzer (kein Verwalter oder Admin) die Möglichkeit zu geben, eine Bermerkung oder Kommentar bei einer Buchung zu hinterlegen?
Dies evt. auch vordefiniert über eine DropDown Box ?

**Comment by tkrebs** [comment]
Im Entwicklungszweig ist vorige Woche eine Einstellung
"Erlaube optionale Anmerkungen bei der Buchung"
pro Platz hinzugekommen:

https://github.com/tkrebs/ep3-bs/commit/11493eb974eedb2f559145d98bcecf83b372a3aa

Diese bewirkt ein Freitext-Eingabefeld für optionale Anmerkungen beim Buchen.
