### ISSUE TITLE
Abobuchungen für jeden sichtbar machen

### ISSUE THREAD

**Issue by MaxDev98** [tkrebs/ep3-bs#343]
Hallo zusammen,

gibt es eine Möglichkeit, ausgewählte Abobuchungen mit Namen öffentlich einsehbar zu machen?
Etwa wenn der Platz täglich für Trainigsstunden reserviert ist?

Sodass statt "Abo" ein Text der Wahl angezeigt wird? z.B. "Training XY"
Somit ist es möglich, dass Kunden zu dieser Zeit gezielt vorbeikommen, da gerade ein Training stattfindet. "Abo" ist in diesem Fall unpassend.

Grüße
Max

**Comment by cbits68** [comment]
Das ist dann eher eine Veranstaltung, wenn ich das richtig verstehe. diese ist dann auch ohne Login sichtbar und man kann sogar eine Beschreibung hinterlegen, wenn diese angeklickt wird.
Leider sind Veranstaltungen der zeit nicht wiederkehrend  einstellbar. Wäre eine Idee für ein Enhancement?

**Comment by MaxDev98** [comment]
Das wäre natürlich die noch bessere Lösung 👍

**Comment by tkrebs** [comment]
#316
