### ISSUE TITLE
User Registrierung

### ISSUE THREAD

**Issue by uli2004** [tkrebs/ep3-bs#347]
Ich habe mir heute das Paket heruntergeladen und entsprechend installiert.
Der Kalender startet auch, nur - wie kann sich ein User registrieren?
Im /public/ Ordner fehlt das Verzeichnis /user , auf das der Registrierungslink verweist.

Was habe ich falsch gemacht oder vergessen?

Viele Grüße

**Comment by jacotec** [comment]
Du hast die .htaccess wohl nicht entsprechend der Anleitung umbenannt ... oder mod_rewrite funzt nicht.

**Comment by uli2004** [comment]
Danke dir, das war es. Funktioniert jetzt nach Anpassung der .htaccess, leider aber nicht sonderlich zuverlässig. Manchmal kommt noch ein 404..
Nach dem neu laden der Seite und 2 Versuchen geht's dann meistens.

**Comment by tkrebs** [comment]
Beim Thema Apache mod_rewrite gibt es eigentlich nur die beiden Extreme: Entweder funktioniert es oder nicht. Unzuverlässigkeit oder gelegentliches Funktionieren tritt hierbei nicht auf, das dürfte also dann noch andere Gründe haben.

**Comment by uli2004** [comment]
Nein, es lag nur an der .htaccess, läuft nun alles wie gewollt. 
Ich musste den Pfad auf die index.php explizit angeben, RewriteBase genügte nicht bzw. führte nur zur halben Funktionalität - seitdem läuft es ohne Probleme.

**Comment by tkrebs** [comment]
Sehr gut! 👍
