### ISSUE TITLE
Fehler: __clone method called on non-object

### ISSUE THREAD

**Issue by rs-tennis** [tkrebs/ep3-bs#349]
Hallo,
ich nutze als Hoster 1&1(IONOS), habe dort PHP7.2 und MySQL5.7
Habe gestern versucht ep-3 Buchungssystem 1.6.4 als fertiges Paket zu installieren.
Beim ersten Versuch die Reservierungs-Software zu nutzen kam ich auf obige Fehlermeldung.
Hier die Website: https://djk-irchenrieth.de/Platzreservierung/public/
Woran könnte das liegen?

**Comment by Shineson1001** [comment]
Hi @rs-tennis,
riecht aber nicht nach der php Version 7.2 .. sondern eher nach 7.4. Prüfe die Einstellungen nochmal und lass dir zur Sicherheit die php Informationen über die `phpinfo` Funktion ausgeben.
https://www.php.net/manual/en/function.phpinfo

**Comment by rs-tennis** [comment]
Hallo Shineson1001,
stimmt, nach Umstellung auf 7.2 hat es geklappt.
Danke für den Hinweis.
