### ISSUE TITLE
Höhe der 'calendar-toolbar'

### ISSUE THREAD

**Issue by SBasti2020** [tkrebs/ep3-bs#350]
Hallo,

ich habe soweit das Buchungssystem einrichten können.

Allerdings fällt auf, dass die 'calendar-toolbar' (weiße Felder der Datumauswahl und Login-Felder) sehr hoch sind. Sie nehmen beinahe die gesamte Bildschirmhöhe ein. Zur Kalenderansicht bedarf es dann einiger Scroll-Umdrehungen...
![calendar-toolbar](https://user-images.githubusercontent.com/66257603/83412361-3d228980-a41a-11ea-81ff-a4bd693c2b41.JPG)
Auch in der Smartphone-Ansicht ist die 'calendar-toolbar' extrem hoch.

Bei fertig eingerichteten Buchungssystemen anderer Tennisclubs ist die calendar-toolbar eigentlich immer schon schlank und gut an die Höhen der Datumauswahl und der Login-Felder angepasst.

Kann die Höhe ggf. manuell nachjustiert werden? Wenn ja, wie/wo?

Vielen Dank für die Hilfe im Voraus!
Gruß
SBasti2020

**Comment by Shineson1001** [comment]
Hi @SBasti2020,
Das Layout wird wahrscheinlich aufgrund von irgendwelchen Fehler- oder Warnmeldungen kaputt gemacht ... der Screenshot scheint aber unvollständig zu sein und die wichtigen Informationen nicht zu zeigen.

**Comment by SBasti2020** [comment]
Hi Shineson1001,

Danke für deine schnell Antwort.

Genau, bei dem Screenshot wurde absichtlich der obere Teil abgeschnitten, da dort bereits der Name des Sportvereins mit Logo ausgegeben wird ... dachte zunächst, dass ich das nicht mit reinposte.

Aber du hast recht, ganz oben wird folgende Fehlermeldung angezeigt:
`Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /homepages/25/d86587185/htdocs/wordpress/tennisplatzreservierung/vendor/zendframework/zend-stdlib/src/ArrayObject.php on line 426`

Wie kann das Problem behoben werden?

Ich vermute hinter dem Problem dieselbe Ursache wie #351 .


Gruß
SBasti2020

**Comment by Shineson1001** [comment]
Hi @SBasti2020,
ok ... die Warnungen sollten nicht mehr angezeigt werden, wenn du in der Datei config/init.php den Wertt auf `false` setzt.
https://github.com/tkrebs/ep3-bs/blob/fb4a742ffa186511ee9eb65934a6637c6ab488ad/config/init.php.dist#L13

**Comment by tkrebs** [comment]
Behoben in Version 1.7.0
