### ISSUE TITLE
Schriftfarbe in 'calendar-toolbar' und 'calendar'

### ISSUE THREAD

**Issue by SBasti2020** [tkrebs/ep3-bs#351]
Hallo,

nach der Standardeinrichtung des Buchungssystems fällt auf, dass die Schriftfarbe der Beschriftungen in sämtlichen panels z.B. calendar-toolbar' und 'calendar', aber auch in allen Feldern beispielsweise der Einstellungen offenbar weiß ist. Da die panels/Felder ebenfalls weiß sind, ist die Schrift nicht lesbar!

--> Beschriftung calendar-panel nicht lesbar:
![calendar-toolbar_Beschriftung](https://user-images.githubusercontent.com/66257603/83412918-3f391800-a41b-11ea-9e2a-d3a761ac80eb.JPG)

--> markiert:
![calendar-toolbar_Beschriftung_markiert](https://user-images.githubusercontent.com/66257603/83412990-5e37aa00-a41b-11ea-984e-88a765984e50.JPG)

--> Beschriftung Kalender nicht lesbar:
![calendar_Beschriftung](https://user-images.githubusercontent.com/66257603/83413144-a2c34580-a41b-11ea-8cb6-616cc98a133a.JPG)

--> markiert:
![calendar_Beschriftung_markiert](https://user-images.githubusercontent.com/66257603/83413161-a9ea5380-a41b-11ea-879b-cda6f3733dd1.JPG)

Lässt sich die Schriftfarbe respektive der Hintergrund denn ändern?
Habe ich was bei der Einrichtung falsch gemacht?

Vielen Dank im Voraus
Gruß
SBasti2020

**Comment by Shineson1001** [comment]
Hi @SBasti2020, 
es scheint, als ob der Screenshot nicht alle wichtigen Infos zeigt ... da fehlt doch oben was!? Werden da php Warnungen oder Fehler ausgegeben? .. wenn ja, dann muss man sich erst mal darum kümmern.

**Comment by tkrebs** [comment]
Die weiße Schriftfarbe resultiert wie auch das zerschossene Layout aus PHP-Meldungen.
Das Thema kann also gemeinsam in #350 fortgeführt werden.
