### ISSUE TITLE
Unterschiedliche Öffnungs-/Platzzeiten

### ISSUE THREAD

**Issue by DasMaulwurf** [tkrebs/ep3-bs#354]
Kann man evtl für jeden Wochentag bestimmte Öffnungszeiten hinterlegen (z.B. Mo-Fr. 14:00 - 20:00 Uhr, Sa-So. 10:00 - 21:00)?
Aktuell behelfe ich mir durch blockierte Zeitfenster (z.B. Mo-Fr. 10:00 - 14:00 Uhr).

Vielen Dank für jeden Input!

**Comment by Shineson1001** [comment]
Verwandschaft #327

**Comment by tkrebs** [comment]
Guter Hinweis, wir sollten dieses Thema in #327 weiter verfolgen.
