### ISSUE TITLE
Plötzlich "Configuration required" 

### ISSUE THREAD

**Issue by Elektrostephan** [tkrebs/ep3-bs#36]
Bekomme auf der Seite plötzlich die Meldung:
Please provide database configuration prior to first usage in file config/autoload/local.php
in der Datei stehen die Daten noch drin.

Was kann ich da tun?

**Comment by tkrebs** [comment]
In der neuesten Version hat sich das Format der Konfigurations-Datei leicht verändert:

https://github.com/tkrebs/ep3-bs/blob/master/config/autoload/local.php.dist

Kopier die Datei am besten einfach und übertrage die Zugangsdaten aus der alten local.php manuell.

**Comment by Elektrostephan** [comment]
Hat leider nichts gebracht. 
Die Teilnehmer hatten sich die letzten Tage registriert und wie mir heute gesagt wurde, geht es seit 2 Tagen nicht mehr.

**Comment by tkrebs** [comment]
Diese Fehlermeldung kommt generell dann, wenn sich das System nicht (mehr?) mit der Datenbank verbinden kann.

**Comment by Elektrostephan** [comment]
Ich habe es dann einfach nicht mehr zum laufen gebracht, seltsam da ich ja nichts verändert habe und plötzlich ging nichts mehr. Hätte es gerne eim Einsatz gehabt, ob das so für unsere Zwecke taugt, bin jetzt am Wochenende nochmal auf einem Treffen und versuche es garade auf einem Raspberry zum laufen zu bringen.
Installation geht, Startseite auch, Tag auswählen auch noch , aber alles andere sagt er immer, nicht gefunden: 
The requested URL /buchung/public/user/login was not found on this server.
oder zb
The requested URL /buchung/public/square was not found on this server.


Hab das auch nochmal online neu installiert, Setup alles gut, danach kommt:
Fatal error: Uncaught exception 'Zend\Session\Exception\InvalidArgumentException' with message ''session.save_path' is not a valid sessions-related ini setting.' in ....../vendor/zendframework/zendframework/library/Zend/Session/Config/SessionConfig.php:90 Stack trace: #0 ....../vendor/zendframework/zendframework/library/Zend/Session/Config/StandardConfig.php(236): Zend\Session\Config\SessionConfig->setStorageOption('save_path', '/home/webpages/...') #1 .....

Bin jetzt langsam am verzweifeln hier.

**Comment by tkrebs** [comment]
Dass die Seite nicht gefunden wird, liegt an der Apache-Erweiterung mod_rewrite, siehe hier (insbesondere der vorletzte Beitrag): #12 

Das zweite Problem wurde hier bereits behandelt (auch hier wieder der vorletzte Beitrag): #10
