### ISSUE TITLE
Teams  Buchungszeit erhöhen

### ISSUE THREAD

**Issue by Schmadda** [tkrebs/ep3-bs#361]
Hallo,
vielen Dank schon mal vorab für die Hilfe und die super Software. Klasse Arbeit.

Ich beschreibe mal unserer Problem: Wir möchten , das die Mannschaftführer die Spiele der Saison eintragen. Ich habe nun einen User pro Mannschaft angelegt. 

Ist es möglich, bestimmten User längere Buchungszeiten zu hinterlegen?

Wie haben die anderen dies gelöst? 
Die Platzhalter Variante ist gut, allerdings muss ich dann alle Spiele eintragen. Will ich eigentlich nicht.

Gruß Markus

**Comment by Shineson1001** [comment]
Hi @Schmadda,
wir legen die Medenspiele als Event an; macht unser Admin für alle Mannschaften.
Um eine beliebig lange Buchungszeit angeben zu können, kann man dem Benutzer den "Status"-Wert "Mitarbeiter" geben und zB die Berechtigungen:
- Darf Buchungen verwalten
- Darf Einzelbuchungen erstellen
- Darf Einzelbuchungen stornieren
- Darf Einzelbuchungen löschen
- Darf Abos erstellen
- Darf Abos stornieren
- Darf Abos löschen

Dann sieht der Buchungsdialog so aus
![grafik](https://user-images.githubusercontent.com/22273771/84743034-a6290600-afb1-11ea-98b7-cf63f35cd2f6.png)

Die Rechten muss jeder auf seine Bedürfnisse anpassen.

**Comment by JonesHH** [comment]
Wir haben auch die Punktspiele als Events angelegt.
Allerdings habe ich mir mit Excel die SQL-Statements generiert und dann
die Events über meine DB-Admin-Oberfläche direkt angelegt.

**Comment by Schmadda** [comment]
Hi ,
@Shineson1001 
Das mit den Rechten der Mitarbeiter-Rolle habe ich schon ausprobiert. Leider kann dieser Account auch auf andere Konten buchen. Und wenn ich das richtig verstanden habe, kann dieser bei einer Falschbuchung auf ein anderes Konto dieses nicht mehr löschen. Möchte ich nicht.

@JonesHH 
 Das mit den SQL-Statements muss ich mir mal genauer durchlesen, wie das funktioniert. Habe ich hier schon mal gelesen, allerdings noch sehr wenig Ahnung davon.

Das die Medenspiele als Event aufgeführt werden, scheint ja eher hier die Lösung zu sein. Werde ich mal durchspielen.

Vielen Dank euch beiden nochmals für die Antworten.

**Comment by JonesHH** [comment]
Hi,
habe unter
https://github.com/tkrebs/ep3-bs/issues/363
mal meine Excel zur Verfügung gestellt.

gruss
jones
