### ISSUE TITLE
Notizen bei vergangenen Abo-Buchungen ändern

### ISSUE THREAD

**Issue by manuelloizi** [tkrebs/ep3-bs#364]
Hallo,
das System ist spitze und nach ein paar Adaptionen perfekt für mich bzw. unseren Verein geeignet.
Ein riesen Danke dafür!

Ein kleines feature hätte ich aber noch gerne umgesetzt.

Ich möchte mit dem Admin Account bei bereits vergangenen Abo-Buchungen die Notizen ändern können.
Zum Beispiel kann man dann ein Trainings Abo reservieren und jeweils am nächsten Tag die tatsächlichen Teilnehmer erfassen. Wäre auch im Zuge der COVID-19 Richtlinien sinnvoll.
Gibt es dafür irgendeine Möglichkeit.

Ich habe bereits im Code ein bisschen gesucht und auch hingebracht, dass das Notizen Feld nicht mehr als disabled erscheint. (Anpassung in edit.js und edit.min.js)
Allerdings werden die Änderungen dann nicht gespeichert.

Bitte um Unterstützung.

DANKE

**Comment by tkrebs** [comment]
Admin-Benutzer können die Notizen vergangener Buchungen bearbeiten.

Beim Bearbeiten von Abo-Buchungen muss dafür "Die gesamte Buchung" gewählt werden. Denn die alternative Auswahl "Nur diese eine Reservierung" bearbeitet eine konkrete zeitliche Reservierung. Technisch betrachtet sind die Notizen aber den Buchungen zugeordnet, nicht den Reservierungen, daher ist das Notizfeld nicht änderbar.

**Comment by manuelloizi** [comment]
Ich bin derzeit nicht im Büro. Ich kehre zurück am  29.06.2020.


Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [tkrebs/ep3-bs] Notizen bei vergangenen Abo-Buchungen ändern (#364)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2020 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
DVR: 0572934, UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------
