### ISSUE TITLE
Blacklist-emails not working, also with other code, is there a option to enable?

### ISSUE THREAD

**Issue by derRichter** [tkrebs/ep3-bs#365]
Die Liste /data/res/blacklist-emails.txt wird offensichtlich nicht ausgewertet oder die ganze Trashmail-Blacklist-Funktion ist nicht aktiviert?

Weder reine Domains mit Angabe "domain.tlv" oder "@domain.tlv" usw. funktionieren.
Auch habe ich mal den Code umgebaut auf:
`					
$domain = substr(trim($value), strpos($value, '@')+1);
if(strpos($blacklistContent, $domain)){
echo "false";
return false;
} else {
echo "true";
return true;
}
`

Also die funktion preg_match durch strpos ersetzt, aber es scheint so als würde der ganze Callbackblock unter "\module\User\src\User\Form\RegistrationForm.php" oder "EditEmailForm" würde gar nicht ausgeführt?!

Muss man das irgendwo aktivieren?

**Comment by derRichter** [comment]
wird hier eigentlich auch was bearbeitet oder sind das alles hier nur sinnlose Notizzettel?

**Comment by tkrebs** [comment]
Womit rechtfertigst du deinen Anspruch, von der Community eines kleineren, kostenlosen Open-Source-Systems innerhalb von einem Tag eine Antwort zu bekommen?

**Comment by derRichter** [comment]
Die Frage ist aufgrund der extrem vielen unbearbeiteten Einträgen auf alle Fälle berechtigt und zudem hatten wir angerufen und um bezahlten Support gefragt, aber das hat auch keinen interessiert, daher kommt die Annahme, dass das Projekt eher nicht supported wird ...


    Am Dienstag, 23. Juni 2020, 11:24:05 MESZ hat Tobias Krebs <notifications@github.com> Folgendes geschrieben:  
 
 


Womit rechtfertigst du deinen Anspruch, von der Community eines kleineren, kostenlosen Open-Source-Systems innerhalb von einem Tag eine Antwort zu bekommen?

**Comment by hendrikreuhl** [comment]
> wird hier eigentlich auch was bearbeitet oder sind das alles hier nur sinnlose Notizzettel?

@derRichter solche Ansprüche stellt man an ein OpenSource-Projekt nicht! 
GitHub ist eine Community zum gemeinsamen Arbeiten an Projekten, das Issue-Feed dient nicht dazu in diesem Ton "Anfragen" zu stellen

**Comment by derRichter** [comment]
so einen blödsinn habe ich auch schon lange nicht mehr gehört.
Den Anspruch eine Antwort zu bekommen wenn der Haupt-Maintainer eh schon
zweimal online war?
Wir betreiben selbst zwei OpenSource-Projekt und da gibts auch sofort ne
Antwort. Zumal es tausende OpenSource-Projekte gibt die Geld für Support
gerne nehmen, worauf hier schon wieder nicht eingegangen ist.
Es geht hier wohl eher um Kompetenz und Lust, wie man ja schon an den
ausweichenden Antworten sieht.

Mir egal, ich hab das Problem eh schon besser gelöst sowie unzählige andere
Bugs korrigiert, aber wem das alles nicht interessiert der sollte das auch
gar nicht erst online stellen ...

>

**Comment by tkrebs** [comment]
@derRichter Wir haben deine Kritik zur Kenntnis genommen. Auf diesem Niveau möchte sich aber hier niemand weiter unterhalten oder rechtfertigen. Da du das ursprüngliche Problem ja laut eigener Aussage mittlerweile gelöst hast, schließe ich dieses Issue daher.

Der Vollständigkeit halber, falls jemand mit einem ähnlichen Problem auf dieses Issue stößt:

Der Blacklist-Filter ist immer aktiv und muss nicht manuell aktiviert werden. In meinem Test der aktuellen Version 1.6.4 hat der Filter auch funktioniert. Möglicherweise ist die Datei `data/res/blacklist-emails.txt` von PHP nicht lesbar, vgl.:

https://github.com/tkrebs/ep3-bs/blob/master/module/User/src/User/Form/RegistrationForm.php#L315
