### ISSUE TITLE
Event nur als Hinweis: Buchung soll weiterhin möglich sein

### ISSUE THREAD

**Issue by JonesHH** [tkrebs/ep3-bs#366]
Hi,
im Rahmen der Corona-Nachverfolgung (bzw. auch zur Organisation, dass
nicht zu viele Spieler zu denZeiten kommen) soll es bei uns möglich sein,
zu Trainingzeiten die Spieler eintragen zu können.
D.h., die Trainingszeiten sollen „nur“ als Hinweis dienen, dass der Platz
für Training der einzelnen Mannschaften reserviert ist.
Zu den einzelnen Trainingsstunden soll es aber trotzdem möglich sein,
die Spieler eintragen zu können.
Hat das jemand schon mal implementiert bzw. einen Ansatz gefunden?

gruss
jones

**Comment by tkrebs** [comment]
Wie wäre es damit, die Platzinfo-Texte über und/oder unter den Platzdetails beim Buchen anzuzeigen? Möglicherweise auch in einer kräftigeren Signalfarbe, damit es unübersehbar ist?
