### ISSUE TITLE
Fehlermeldung beim Login: "/user/login was not found"

### ISSUE THREAD

**Issue by Explorer72** [tkrebs/ep3-bs#368]
Hallo,
ich habe eben ep-3 installiert und die Datenbank und den Admin user angelegt.
Wenn ich mich jetzt anmelden will kommt die Meldung:
"The requested URL /user/login was not found on this server."
Ich kann auch kein /user/login in der Verzeichnisstruktur finden.
Hat jemand eine Idee woran das liegen könnte.
Danke.
Marcus

**Comment by tkrebs** [comment]
Das liegt am Apache-Modul "mod_rewrite", welches serverseitig installiert und eingerichtet sein muss.

Dazu gibt es bereits zahlreiche Issues, z. B.

#15 
#12 

mit verschiedenen Lösungsansätzen. Falls du nach der Lektüre dieser Issues noch Probleme haben solltest, verwende bitte o. g. Issues.
