### ISSUE TITLE
Fehler nach Buchung als "normaler" User

### ISSUE THREAD

**Issue by dvsfit** [tkrebs/ep3-bs#369]
Hallo,

bekomme bei Buchungen als "normaler" User immer Fehlermeldungen. Buchung geht trotz Fehlermeldung aber durch. 

Infos zum System:
- Apache Webserver
- PHP 7.1.33
- ZIP-File von der Homepage (1.6.4), jedoch mit der .htaccess_original von github, da ich mit den .htaccess keine Links verwenden konnte, Register etc.
- Installation gemäß Anleitung, sprich alle Berechtigungen etc wurden gesetzt

Problem war schon direkt nach dem Setup, beim ersten Testlauf vorhanden.

Fehlermeldung mit define('EP3_BS_DEV_TAG', true);

Warning: Invalid argument supplied for foreach() in /var/www/html/bs/module/Booking/src/Booking/Service/Listener/NotificationListener.php on line 84

![image](https://user-images.githubusercontent.com/67462178/85847674-24528d00-b7a8-11ea-9e80-faa619299e3d.png)

Wenn define('EP3_BS_DEV_TAG', false);

![image](https://user-images.githubusercontent.com/67462178/85847721-37fdf380-b7a8-11ea-8c8f-7430e95306a7.png)

**Comment by tkrebs** [comment]
Danke für die Meldung, ich habe soeben eine Korrektur vorgenommen (https://github.com/tkrebs/ep3-bs/commit/a16fce5e97ff917319ce0f56f7fe1f2d553ee0e5).

Wenn du die [geänderte Datei](https://github.com/tkrebs/ep3-bs/blob/a16fce5e97ff917319ce0f56f7fe1f2d553ee0e5/module/Booking/src/Booking/Service/Listener/NotificationListener.php) in deiner Installation austauschst, müsste der Fehler verschwinden.

**Comment by dvsfit** [comment]
Danke für die schnelle Antwort, der foreach() fehler ist nun weg.

Folgender Fehler nun: 

> Exception details
Type
Zend\Db\Adapter\Exception\RuntimeException
Mitteilung
Must call beginTransaction() before you can rollback
File
/var/www/html/bs/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Connection.php:352
Stack trace
#0 /var/www/html/bs/module/Booking/src/Booking/Service/BookingService.php(130): Zend\Db\Adapter\Driver\Pdo\Connection->rollback()
#1 /var/www/html/bs/module/Square/src/Square/Controller/BookingController.php(180): Booking\Service\BookingService->createSingle(Object(User\Entity\User), Object(Square\Entity\Square), 1, Object(DateTime), Object(DateTime), Array, Array)
#2 /var/www/html/bs/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(84): Square\Controller\BookingController->confirmationAction()
#3 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#4 /var/www/html/bs/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#5 /var/www/html/bs/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#6 /var/www/html/bs/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#7 /var/www/html/bs/vendor/zendframework/zend-mvc/src/DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#8 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#9 /var/www/html/bs/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#10 /var/www/html/bs/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /var/www/html/bs/vendor/zendframework/zend-mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#12 /var/www/html/bs/public/index.php(75): Zend\Mvc\Application->run()
#13 {main}

**Comment by tkrebs** [comment]
Der zweite Fehler könnte folgende Ursache und Lösung haben:

https://github.com/tkrebs/ep3-bs/issues/256#issuecomment-580409789

**Comment by dvsfit** [comment]
Leider habe ich immer noch den gleichen Fehler.. Mail Config habe ich gecheckt wie in  https://github.com/tkrebs/ep3-bs/issues/256#issuecomment-580409789 erwähnt. 
Dann hab ich noch https://github.com/tkrebs/ep3-bs/issues/246 gefunden und nach dem Muster das gleiche probiert. 

Getestet habe ich nun mit einem internen Mailserver (Exchange), sowie externen.. 
Auf dem gleichen Server läuft ebenfalls noch ein anderes System, welches problemlos Mails über SMTP verschicken kann.

Gibt es evlt. noch andere Fehlerquellen die mit der Fehlermeldung zusammenhängen könnten?

**Comment by tkrebs** [comment]
In der Vergangenheit waren immer Mail-Einstellungen für die Fehlermeldung verantwortlich:

https://github.com/tkrebs/ep3-bs/issues?q=beginTransaction%28%29

Daher fallen mir sonst leider keine weiteren Problemlösungsansätze ein.

**Comment by dvsfit** [comment]
Wenn ich das ganze mal mit 'smtp-tls' probiere, bekomme ich folgende Fehlermeldung:

`Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /var/www/html/bs/vendor/zendframework/zend-mail/src/Protocol/Smtp.php on line 215`
