### ISSUE TITLE
Währung von USD auf € umstellen?

### ISSUE THREAD

**Issue by juergen2912** [tkrebs/ep3-bs#37]
Hallo, wie stelle ich die Währung von US auf Euro um. Ich habe sowohl in den Dateien als auch in der Datenbank gesucht, finde aber keinen Hinweis (Anfänger....)

**Comment by tkrebs** [comment]
In der Datei

`/config/autoload/local.php`

kann die Währung in folgender Zeile umgestellt werden:

`'currency' => 'EUR',`

**Comment by juergen2912** [comment]
VIELEN DANK!
