### ISSUE TITLE
Bevor du ein neues Issue schreibst ...

### ISSUE THREAD

**Issue by tkrebs** [tkrebs/ep3-bs#375]
- [ ] Schau nach, ob dein Thema nicht schon behandelt wurde: Benutze die Suche oder den Bereich [Projects](https://github.com/tkrebs/ep3-bs/projects).
- [ ] Schau nach, ob dein Thema nicht in der [Dokumentation](http://bs.hbsys.de/documentation) beschrieben ist.

- [ ] Beschreibe dein Anliegen **präzise**. Füge Details, Beispiele und Screenshots hinzu, falls vorhanden.

**Comment by ivenho** [comment]
Hi läuft das ep3 Buchungssystem nur auf MySQL Datenbanken oder auch auf Maria DB 10.4?

**Comment by aulicus** [comment]
Hallo Herr Krebs, keine Frage, keine Beanstandung, nur: Danke für das tolle Programm.
mfg
Gilbert Hoffmann

**Comment by Raiti1402** [comment]
Guten Tag,
in der Mobilen Version der EP3 Buchungssystem taucht folgende Fehlermeldung auf. Was kann ich tun um diesen Fehler zu beheben.
[Deprecated: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/vhosts/whwc9twq.web58.alfahosting-server.de/platzreservierung-online.de/src/Zend/Uri/src/UriFactory.php on line 96](https://www.platzreservierung-online.de/public/platzreservierung-online.de)
Vielen Dank
R.Tischer
