### ISSUE TITLE
Vermutlich kein Fehler sondern eigene Blödheit

### ISSUE THREAD

**Issue by klaus29** [tkrebs/ep3-bs#379]
Habe 2 x ep3 installiert, einmal vom zip und einmal mit composer. Immer derselbe Fehler: nach dem Aufruf der URL zeigen sich zwar die Time-Slots, aber sobald man buchen möchte oder sich anmelden möchte, erscheint ein Link, der ins Leere läuft:

The requested URL /ep3-bs/public/square was not found on this server. (beim Anklicken eines Slots)
he requested URL /ep3-bs/public/user/registration was not found on this server. (beim Login-Versuch)

Irgendwo stehe ich auf dem Schlauch. Ich habe auch die Ordnerstruktur mit der Anleitung verglichen: alles korrekt. Kann es sein, dass ep3 nicht mit php7.2 funktioniert?

**Comment by cbits68** [comment]
7.2 ist kein Problem. Hast Du mal die Config vom Webserver (vermutlich apache?) gecheckt? Thema mod_rewrite. Ggf musst Du die .htaccess anpassen, wenn Du keine Einstellungen an der httpd.conf vornehmen kannst.

**Comment by klaus29** [comment]
Ganz herzlichen Dank. Das war's (heftig gegen den eigenen Kopf schlag)
