### ISSUE TITLE
Veranstaltugen

### ISSUE THREAD

**Issue by andi1957** [tkrebs/ep3-bs#38]
Hallo,

wir benützen das System für drei Plätze. Beim Eintragen von Veranstaltungen ist eine auswahl aber nur von entweder einem oder alle Plätze möglich. Gibt es hier die Möglichkeit das zu ändern damit man auch zwei Plätze auswählen kann.
lg

**Comment by tkrebs** [comment]
Die Datenbank kann nur einen konkreten Platz oder nichts (= alle) speichern, daher gibt es derzeit leider keine solche Möglichkeit.
