### ISSUE TITLE
2 Fragen

### ISSUE THREAD

**Issue by Maxi1909** [tkrebs/ep3-bs#381]
Guten Tag, 

Ich hätte mal 2 Fragen: 

Zum einen --> wie kann ich den Admin Benutzer zurücksetzen bzw. das PW neu vergeben ohne Neuinstallation ? 

Zum anderen, wenn ich mein Logo einfügen möchte, ersetzte ich die Datei in public/imgs-client/layout/logo.png, jedoch passiert rein gar nichts. Woran könnte das liegen ? 

Danke im Vorraus.  

LG

**Comment by mumulusul** [comment]
1. in der Datenbank kannst du das Admin Passwort ändern,   du nimmst $2y$06$VCDc018koev4b83Q9rO4QuZmYXg8.46n7Ncwc8/Br05Zgtq0wBVmm      lautet:   test123
2. Browser Cache löschen ??

**Comment by tkrebs** [comment]
Das scheint es gelöst zu haben.
