### ISSUE TITLE
Mitspieler in Buchungs-Verwaltung anzeigen

### ISSUE THREAD

**Issue by Reiji-kun** [tkrebs/ep3-bs#382]
Guten Tag

Gibt es eine Möglichkeit, wie man die Mitspieler in einem zusätzliche Feld anzeigen lassen kann?

![Booking](https://user-images.githubusercontent.com/67977278/86831160-daff1900-c096-11ea-943e-b8b2b73deb83.JPG)

Vielen Dank für die Hilfe

**Comment by Shineson1001** [comment]
Hi @Reiji-kun,

teste mal folgende Änderungen:
Datei `BookingsFormat.php`
Oberhalb dieser Zeile einfügen
https://github.com/tkrebs/ep3-bs/blob/26e43b55607dbf94e6926643f287bc7ad5ce7a6a/module/Backend/src/Backend/View/Helper/Booking/BookingsFormat.php#L21
`        $html .= '<th>' . $view->t('Players') . '</th>';`



Datei `BookingFormat.php`
Oberhalb dieser Zeile einfügen
https://github.com/tkrebs/ep3-bs/blob/26e43b55607dbf94e6926643f287bc7ad5ce7a6a/module/Backend/src/Backend/View/Helper/Booking/BookingFormat.php#L52
```
        $booking = $reservation->needExtra('booking');
        $playerNames = $booking->getMeta('player-names');
        $outputPlayerNames = null;
        if ($playerNames) {
            $playerNames = @unserialize($playerNames);
            if ($playerNames) {
                foreach ($playerNames as $playerData) {
                    $nameData = $playerData['value'];
                    if ($nameData !== "") {
                        if ($outputPlayerNames === null) {
                            $outputPlayerNames = $nameData;
                        } else {
                            $outputPlayerNames .= sprintf('<br />%1$s', $nameData);
                        }
                    }
                }
            }
        }

        $html .= sprintf('<td><b>%s</b></td>', $outputPlayerNames);
```

**Comment by Reiji-kun** [comment]
Ciao Shineson1001 

Funktioniert einwandfrei. Vielen Dank
