### ISSUE TITLE
Der Code zum ändern Ihres Passowrtes ist ungültig oder abgelaufen

### ISSUE THREAD

**Issue by juergen2912** [tkrebs/ep3-bs#39]
Hallo, wenn jemand auf 'Passowrt vergessen' geht und in der mail auf den link zu Eingabe eines neuen Passwortes klickt, kommt obige Fehlermeldung. Bei der Aktivierung des eigenen Accounts per link passiert das Gleiche. Systemmails, Buchungen,.... funktioniert alles wunderbar. 
Bin bei Hosteurope und habe dort einen Standardzugang mit php und mysql. Bei anderen Anwendungen (z.B. Joomla) gibt es keinerlei Probleme.
Kann mir jemand einen Tipp geben?
Danke und Gruß
Jürgen

**Comment by tkrebs** [comment]
Kannst du die URL zum Aktivieren einmal aus der E-Mail hierher kopieren/einfügen (aus Sicherheitsgründen bitte ohne den Domain-Teil)?

**Comment by juergen2912** [comment]
http://buchung.superverein.de/public/user/password-reset?id=34&code=RXBFOXZPNGQ%3D

Jetzt habe ich mich gerade über den 1und1-webmailer eingeloggt und konnte nach klicken des links ein neues Passwort eingeben und erst dann kam:
"Oops ... da ist wohl etwas schief gelaufen
Der Code zum Ändern Ihres Passwortes ist ungültig oder abgelaufen. Bitte lassen Sie sich eine neue E-Mail zusenden."

Der link in der gleichen mail, geöffnet mit Outlook auf dem Handy lautet: ........id=34&amp;code=........,
da kommt dann sofort der Fehler.....

**Comment by juergen2912** [comment]
Okay, da bin ich zu unwissend, der handylink mit Leerzeichen dazwischen, weil er sonst gleich ausieht wie der erstgenannte : ...id = 34 & amp ; code = .....

**Comment by juergen2912** [comment]
Nochmal ich, das "&" in der mail wird in der outlook-mail also als HTML-Zeichen & a m p ; geschrieben....

**Comment by tkrebs** [comment]
Steht nach dem Anklicken des Links in der Adresszeile des Browsers

id=34&amp;code=...

oder

id=34&code=...

**Comment by juergen2912** [comment]
Die sind doch beide identisch, oder? Wird aus dem einen Zeichen "&" vielleicht das HTML-& gemacht???

**Comment by tkrebs** [comment]
Stimmt, ich habe es korrigiert.

**Comment by juergen2912** [comment]
Wenn gleich die Fehlermeldung kommt, dann sieht es aus wie in Version 1,
Wenn ich ein neues Passwort eingeben kann, sieht es aus wie in version 2, allerdings kommt dann die gleiche Fehlermeldung beim versuch zu speichern...
