### ISSUE TITLE
Empfehlungen für geeigneten Hoster

### ISSUE THREAD

**Issue by helmi90** [tkrebs/ep3-bs#391]
Hi allerseits!

Ich möchte für meinen Verein ein neues Buchungssystem aufsetzen und bin über dieses super Projekt hier gestolpert. Habe es auch schon lokal getestet und die Vereinsleitung und ich finden es großartig.
Nun möchte ich für die nächste Saison eine Website für den Verein erstellen und auf einer Subseite das ep3-Buchungssystem einrichten.

Habt Ihr Hoster-Empfehlungen für mich, bei denen Ihr aus eigener Erfahrung wisst, dass **das System reibungslos läuft**? Die Kosten sollten sich auf **nicht mehr als ~5€ pro Monat** belaufen und ich nach einmaliger Einrichtung möglichst wenig Wartungsaufwand haben. Fällt euch da was ein? 😃

Wäre für jede Hilfe dankbar!

Liebe Grüße

**Comment by cbits68** [comment]
Ich kann Dir Strato empfehlen, da läuft unsere Verinshomepage mit Joomla CMS und das ep3 Buchungssystem auf einer Domain (ohne Dubdomain) perfekt. Keine Probleme bei der Installation wie z. B. bei 1&1,...
Preislich dürfte es auch passen.

Gruß
Cbits

**Comment by cbits68** [comment]
Achso, wenn Du mal schauen magst https://tc-rotweiss-grossbeeren.de

**Comment by tkrebs** [comment]
Die Website und Demo des Buchungssystems wird bei [all-inkl.com](https://all-inkl.com/) gehostet, mit denen ich nun schon seit vielen Jahren sehr zufrieden bin.

**Comment by helmi90** [comment]
Vielen Dank für eure Empfehlungen!

@cbits68:
Hast du eines dieser Pakete? https://www.strato.de/server/linux-vserver/mini-vserver/

Bin (offensichtlich) kein Experte, aber ich denke mir folgendes: Bei einem VPS hat man doch den Vorteil, dass man ALLES genau so installieren kann, wie man es braucht (also zb. auch genau die kompatible PHP-Version 7.2 statt 7.3). Oder kann es sein, dass beispielsweise die intl-Erweiterung oder irgendetwas nicht installiert werden kann aufgrund irgendwelcher Einschränkungen? Und wenn ich das mal zum Laufen gebracht habe, dann sollte das Ganze eigentlich keine Wartung benötigen. Außerdem wäre ein Preis ab 1€ pro Monat der Hammer.

Bei all-inkl.com hätte ich auch die 5€ pro Monat nicht überschritten und sogar Domains und E-Mail dabei, was natürlich super wäre. Könnte es dort dann nicht sein, dass mit einem automatischen Update das Ganze nicht mehr rund läuft (zb von Zend auf Laminas)?


Liebe Grüße

**Comment by cbits68** [comment]
Hallo helmi90,
Ich habe bei Strato ein Hosting Paket (PowerWeb Basic), da ich dort mehrere Domains mit Websites & eMail hoste.
Die V-Server gab es damals noch nicht, ist aber sicher eine Alternative, wenn man individuelle Projekte hosten möchte und root access benötigt. Allerdings muss Du Dich dann quasi um Alles selbst kümmern (apache, mysql, ...) Die Plesk Onyx Verwaltungsoberfläche ist allerdings auch sehr komfortabel.
Beim Hosting Starter Paket (4€/Monat) hast Du aber auch Alles dabei, was Du benötigst. Auch die PHP Version kannst Du über das Kundenportal einstellen (aktuell sind 7.2, 7.3 und 7.4 verfügbar, sowie PHP Boost). Bei der Installation von ep3 lief bei mir Alles problemlos (auch über github). Es gab auch keine Probleme mit der apache Konfiguration, so dass keine Anpassungen der .htaccess erforderlich waren.
Ich habe gehört, dass Strato gerade sein RZ umbaut und sich einige Kunden über Performance Probleme beschweren. Ich selbst habe bisher keine Probleme gehabt, weder mit Joomla, noch mit ep3. Betreibe aber auch keine Shop Lösung o.Ä., wo das sicher dann ärgerlich sein kann.
Ob ep3 mit Web Framework Zend oder Laminas läuft, sollte imho für die Auswahl des Providers nicht entscheidend sein.
Letztendlich bekommst Du ep3 sicher bei fast allen Hosting Providern zum laufen. Ggf. sind bei der Installation dann einige Punkte anzupassen, damit es dann auch läuft (z.B. mode rewrite, ...) Bei Strato musste ich eben nichts anpassen und nur die DB und eMail Zugangsdaten eintragen.

Gruß

**Comment by chrisschauer75** [comment]
Ich verwende hoststart.at schon seit Jahren.
Relativ bililg, bietet alles was das Herz begehrt und der Support ist auch sehr flott!

**Comment by helmi90** [comment]
Vielen Dank für eure hilfreichen Empfehlungen!

Ich tendiere nach dem Vergleich der drei von euch genannten Anbieter aktuell am ehesten zu Hoststar (Preis und Funktionsumfang scheinen wirklich super zu sein), werde mir das aber alles nochmal genau durch den Kopf gehen lassen, nachdem das System erst 2021 laufen muss.


Danke nochmal! 👍😃

**Comment by helmi90** [comment]
Habe das System bei hoststar.at aufgesetzt und es läuft einwandfrei. Danke nochmal für eure Hilfe! 👍
