### ISSUE TITLE
Benutzer Export mit PW

### ISSUE THREAD

**Issue by Bakati** [tkrebs/ep3-bs#396]
Hallo an alle
Könnte man die Benutzer inkl. Passwörter so exportieren das man in eine Joomla3 Seite importieren Kann? Und wenn ja wie? 
Vielen Dank
LG

**Comment by cbits68** [comment]
Die Passwörter sind in beiden Datenbanken verschlüsselt abgelegt. Selbst wenn der Algorithmus der selbe ist, wird sicher der Schlüssel unterschiedlich sein.
Alle anderen Felder könnte man sicher über Import/Export abgleichen.
Die beste Lösung wäre dann voraussichtlich eine SSO mit einem LDAP oder Active Directory Verzeichnis via Schnittstelle. Bei Joomla kann ich mir vorstellen, dass es das gibt. Auch die Joomla Benutzerverwaltung lässt sich z. B. mit Community Builder abgleichen.
Müsste man aber programmieren. Export Import wird mit ep3 nicht funktionieren.

**Comment by Bakati** [comment]
Hi, sorry spät aber vielen Dank für Deine Antwort.
LG
