### ISSUE TITLE
Registrierung Text

### ISSUE THREAD

**Issue by Bakati** [tkrebs/ep3-bs#397]
Guten morgen,
wo könnte ich diesen Text bei Registrierun ändern?  Auf english denke ich gefunden zu haben aber auf Deutsch?

_**_"Sie haben es sicher schon vermutet: Um unser Angebot nutzen zu können, also um freie Plätze online buchen zu können, müssen Sie sich vorher ein eigenes Benutzerkonto auf Ihren Namen und Ihre E-Mail Adresse erstellen. Die Registrierung ist natürlich kostenlos und unverbindlich. "_**_
Vielen Dank im Voraus

**Comment by tkrebs** [comment]
Schau mal hier:

https://github.com/tkrebs/ep3-bs/blob/53253348939c192949319b6c5bb39c0416f89515/data/res/i18n/de-DE/user.php#L222

**Comment by Bakati** [comment]
Danke sehr. Genau das.
