### ISSUE TITLE
Hilfe - ich habe meine Installation  zerschossen

### ISSUE THREAD

**Issue by mjmpeace** [tkrebs/ep3-bs#399]
Der Fehler lautet:

Warning: ini_set(): A session is active. You cannot change the session module's ini settings at this time in /kunden/238965_27580/webseiten/halle/vendor/zendframework/zendframework/library/Zend/Session/Config/SessionConfig.php on line 88

Fatal error: Uncaught Zend\Session\Exception\InvalidArgumentException: 'session.name' is not a valid sessions-related ini setting. in /kunden/238965_27580/webseiten/halle/vendor/zendframework/zendframework/library/Zend/Session/Config/SessionConfig.php:90 Stack trace: #0 /kunden/238965_27580/webseiten/halle/vendor/zendframework/zendframework/library/Zend/Session/Config/StandardConfig.php(266): Zend\Session\Config\SessionConfig->setStorageOption('name', 'ep3-bs-session') #1 /kunden/238965_27580/webseiten/halle/vendor/zendframework/zendframework/library/Zend/Session/Config/StandardConfig.php(114): Zend\Session\Config\StandardConfig->setName('ep3-bs-session') #2 /kunden/238965_27580/webseiten/halle/vendor/zendframework/zendframework/library/Zend/Session/Service/SessionConfigFactory.php(60): Zend\Session\Config\StandardConfig->setOptions(Array) #3 [internal function]: Zend\Session\Service\SessionConfigFactory->createService(Object(Zend\ServiceManager\ServiceManager), 'zendsessionconf...', 'Zend\\Session\\Co...') #4 /kunden/238 in /kunden/238965_27580/webseiten/halle/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php on line 946

Wer kann mir helfen? Was muss ich löschen, damit das System wieder läuft.
Ich habe aus Versehen eine Sicherung komplett hochgeladen, was ich gar nicht wollte.
Hilfe ist dringend notwendig.

**Comment by tkrebs** [comment]
Ich würde zunächst einmal die Verzeichnisse

`vendor/`

und

`module/` (Achtung bei eigenen Anpassungen)

löschen (oder testweise umbenennen) und neu hochladen.

Wenn es danach immer noch defekt ist, würde ich die Konfigurationsdateien im Verzeichnis `config/` überprüfen. Insbesondere die Datei `config/autoload/global.php`.

Ansonsten könnte noch das Leeren der Verzeichnisse `data/cache/` und `data/session/` helfen.

**Comment by mjmpeace** [comment]
Data/cache und Data/session allein nützt nichts, ich lasse jetzt das Verzeichnis aus der Datensicherung wieder herstellen.

**Comment by mjmpeace** [comment]
Restore erfolgreich. Danke.
