### ISSUE TITLE
How to set event modals to absolute paths

### ISSUE THREAD

**Issue by mattymurphy** [tkrebs/ep3-bs#4]
I see currently the link is square/data

I am curious how to set that to a absolute path?

Matt

**Comment by tkrebs** [comment]
Are you referring to a link within the PHP code base?
Generally, you can add a third parameter to the url methods like so to force it create an absolute path:
$this->url('square/data', array(...), array('force_canonical' => true))

**Comment by mattymurphy** [comment]
Here is what i'm trying to do... I know this is wrong... I'm a newb so sorry if this is pure ignorance. 

$nextDayUrl = $this->url('http://absolutepath.com/module/Frontend/view/frontend/', array('force_canonical' => true), [], ['query' => ['date' => $dateStartClone->format('Y-m-d')]]);

$todayUrl = $this->url('http://absolutepath.com/module/Frontend/view/frontend/', array('force_canonical' => true), [], ['query' => ['date' => $this->dateNow->format('Y-m-d')]]);

Thanks tkrebs

**Comment by mattymurphy** [comment]
Figured it out! Sillyness on my part.
