### ISSUE TITLE
Oops ... something went wrong here Invalid date range passed for reservation creation

### ISSUE THREAD

**Issue by makriria** [tkrebs/ep3-bs#40]
Hello there,

I am trying your system. When I try to book as admin almost 10 hours and I select to repeat weekly I get this message 'Oops ... something went wrong here Invalid date range passed for reservation creation'
Should I be able to book as admin all Mondays for example for one user? 

Thank you.

**Comment by tkrebs** [comment]
Sorry no one answered this back then. Ashamedly closing it now.

**Comment by nuukee** [comment]
Hi Tobias,
I am facing the same problem right now. Was there ever a solution?
Thanks, Sven

**Comment by nuukee** [comment]
Ok sorry, found it out,
If you do a repeat booking without specifying an end date you'll get the non-descript error message from above.
Thanks anyway :-)
