### ISSUE TITLE
Installation: The PHP intl extension is required but not installed. Please contact your web hosting provider to get this one fixed.

### ISSUE THREAD

**Issue by Kraemer92** [tkrebs/ep3-bs#402]
Guten Morgen,

ich versuche bereits seit einem Tag die Installation des Buchungssystem durchzuführen. Die in der Dokumentation vorgeschriebenen Anpassungen hatte ich erledigt, doch leider erhielt ich beim Aufruf des public Folders im Browser die Fehlermeldung:

The PHP intl extension is required but not installed. Please contact your web hosting provider to get this one fixed.

Daraufhin habe ich mich mit dem Support meines Webspace in Verbindung gesetzt und die haben mir das intl extension installiert. Leider erhielt ich immer noch die Hinweismeldung, egal ob [kraemer.sw.gw](http://kraemer.sw.gw) oder kraemer.sw.gw/setup.php aufgerufen wurde. 

Heute habe ich es erneut versucht und siehe da, der Aufruf der setup.php hat funktioniert. Die Datenbank wurde beschrieben und ich hab alle weiteren Konfigurationen vorgenommen und meinen Benutzer erstellt. Anschließend habe ich die setup.php vom Webspace gelöscht und wollte mich einloggen. 

Leider erhalte ich beim Aufruf von [kraemer.sw.gw](http://kraemer.sw.gw) immer noch die Hinweismeldung mit dem fehlenden intl Extension.

Da aber die setup.php funktionierte, gehe ich davon aus, dass alle notwendigen Module vorhanden und installiert sind.

Der Webspace-Support hat mir auch eine phpinfo.php auf den Webspace gelegt und die zeigt auch das Vorhandensein von intl an. [kraemer.sw.gw/phpinfo.php](http://kraemer.sw.gw/phpinfo.php)

Woran könnte es denn jetzt noch hapern?

Besten Dank,
Tobias Krämer

**Comment by Shineson1001** [comment]
Hi @Kraemer92,
besteht die Möglichkeit auf php 7.2 zu wechseln?

**Comment by mjmpeace** [comment]
Bei mir musste das erst aktiviert werden vom Provider, da man an der Konfiguration des PHP ja nichts selber machen kann.

**Comment by Kraemer92** [comment]
> Bei mir musste das erst aktiviert werden vom Provider, da man an der Konfiguration des PHP ja nichts selber machen kann.

Hallo mjmpeace,

ich hatte ja bereits geschrieben, dass ich den Kunden-Support kontaktiert habe und dieser hat mir das entsprechende Extension installiert und aktiviert. Dies lässt sich ja auch unter http://kraemer.sw.gw/phpinfo.php einsehen.

> eht die Möglichkeit auf php 7.2 zu wechseln?

Hallo Shineson1001,

da muss ich mal nachhaken ob ein Update möglich wäre. Denke mal ein Webspace-Betreiber sollte immer ein Augenmerk darauf haben, alle Module auf dem neusten Stand zu halten. Wundert mich gerade auch etwas, dass "nur" 7.0.3 läuft.
Ein Versuch ist es allemal wert.

**Comment by Shineson1001** [comment]
Hi @Kraemer92,
schwer zu sagen ob der Wechsel hilft ... kann aber auf keinen Fall schaden ... Support gibt es seit ca. 3 Jahren nicht mehr für die Version. Aktuelle wäre 7.4 .. die ist aber (noch) nicht empfohlen für das ep3-System. Versuche mal an die Version 7.2 zu kommen.
Zur Not richte ich mir einen kleine Testumgebung mit php 7.0.3 ein um das mal gegen-zu-prüfen.

**Comment by Kraemer92** [comment]
Hi Shineson1001,

ich habe es mal weitergegeben und bin gespannt, ob man die PHP-Version aktualisiert.

Was mich nur stutzig macht: Ich konnte anfangs weder die index.php noch die setup.php aufrufen und erhielt ständig die Meldung: "The PHP intl extension is required but not installed. Please contact your web hosting provider to get this one fixed."

Daraufhin hab ich den Webspace-Support angeschrieben und die haben mir relativ schnell mit einer Bestätigung der Installation und Aktivierung des Extensions geantwortet. Ich konnte danach auch tatsächlich die setup.php aufrufen und die Installation erfolgreich fertigstellen. Somit hatte es ja eigentlich bereits funktioniert. Nur erhalte ich jetzt wieder dieselbe Meldung wenn ich versuche die index.php aufzurufen und das verwundert mich doch sehr.
