### ISSUE TITLE
Falsche Website-Adresse in Systemmails

### ISSUE THREAD

**Issue by dvsfit** [tkrebs/ep3-bs#403]
Hallo,

in Systemmails z.B. Buchungsbestätigungen oder Stornierungen ist die Website-Adresse/Domain falsch, ist in meinem Fall sogar eine nicht mehr aktuelle IP-Adresse.

![image](https://user-images.githubusercontent.com/67462178/93101467-97ceb100-f6aa-11ea-8436-3d883062ecfe.png)

Wie kann ich die aktualisieren oder ggf. ganz aus den Emails entfernen? In der NotificationListener.php bin ich leider nicht fündig geworden.

Danke

**Comment by tkrebs** [comment]
Die URL an dieser Stelle kommt aus der Datenbank-Tabelle "bs_options", genauer von dem Eintrag "service.website".

**Comment by dvsfit** [comment]
Danke für die Info. Hat soweit geklappt! Hab den Eintrag direkt in der Datenbank geändert.

> Auch zu bearbeiten über Verwaltung › Einstellungen › Namen und Texte › Ihre Webseite.

Ändert in der Datenbank, jedenfalls bei mir, anscheinend nur den key 'client.website'

**Comment by koehntopp** [comment]
Nur als Kommentar - ich kann bestätigen dass die Einstellungen die DB Einträge nicht setzen.
Bin von der Test-URL auf Produktiv gewechselt, nach Anpassung in der DB passt alles.
