### ISSUE TITLE
Nur Buchung für sich selbst

### ISSUE THREAD

**Issue by FD-ITE** [tkrebs/ep3-bs#406]
Hallo!

Ich möchte gerne, dass bei einer Platzbuchung keine weiteren Spieler gebucht werden können, sprich, man kann sich nur selbst anmelden. 
Ich habe etwas die Ordner durchforstet um beispielsweise beim Buchungsfenster das Dropdownmenü komplett zu entfernen und den auswählbaren Wert auf 1 festzusetzen, wurde aber nicht fündig. 

Kann mir hier jemand weiterhelfen wo ich was verändern muss?

**Comment by Shineson1001** [comment]
Hi @FD-ITE,
reicht es evtl. aus, wenn man in den Platz-Einstellungen den Wert für "Kapazität" auf 1 setzt?

**Comment by FD-ITE** [comment]
Hallo @Shineson1001, 
wenn ich die Kapazität auf "1" setze, dann kann sich ja nur ein einziger sich für den Platz anmelden und danach ist er voll. 
Es sollen sich aber mehrere anmelden dürfen bis der Platz komplett voll ist.

**Comment by Shineson1001** [comment]
Hi @FD-ITE,
ok .. dann habe ich nicht verstanden was du genau meinst bzw. was das Ziel der Anpassung/Einstellung sein soll.
Ich bräuchte mehr Details ...

**Comment by FD-ITE** [comment]
Ich habe einen Raum/Platz mit beispielsweise 10 Kapazitäten. Jetzt kann ein Benutzer von diesen 10 Kapazitäten 3 belegen (mit optionalen/geforderten Angaben der anderen Teilnehmer). Und genau da ist der springende Punkt. Ich möchte, dass ein Benutzer nur eine Kapazität belegen kann und keine weiteren.

**Comment by Shineson1001** [comment]
Hi,
ok, ich glaube jetzt habe ich es grob verstanden. Es geht um eine bestehende Buchung, in die sich weitere Spieler nachträglich einbuchen können. Jedoch soll man nur sich und noch noch andere dazubuchen dürfen. Richtig?

**Comment by Busfreak** [comment]
Hallo @FD-ITE 

guck mal hier:
https://github.com/tkrebs/ep3-bs/blob/26e43b55607dbf94e6926643f287bc7ad5ce7a6a/module/Square/view/square/booking/customization.phtml#L31

Da wird das Auswahlfeld für weitere Spieler angezeigt.

**Comment by FD-ITE** [comment]
Entschuldigung für die späte Antwort. Ich kam die letzte Zeit nicht zum Austesten. 

@Shineson1001 Es geht nicht um eine bestehende Buchung. Für den Verwalter oder Admin soll sich nichts ändern. Es soll sich nur für Benutzer das Feld ändern, indem er seine zusätzlichen Spieler auswählen kann. Hier soll er nur "1" auswählen können und nicht die Anzahl bis zur freien Kapazität. 

@Busfreak Danke für den Verweis. Er war zwar nicht ganz richtig, hat mich aber auf die richtige Spur gebracht. Vielen Dank dafür!

Unter "\module\Square\src\Square\View\Helper\QuantityChoice.php" gibt es eine For-Schleife, die hochzählt und anhand dessen gibt mir das Programm meine Anzahloptionen. Hier als Endbedingung eine "1" eingetragen und es hat funktioniert.
