### ISSUE TITLE
Alle vorhandenen Buchungen bulk löschen

### ISSUE THREAD

**Issue by wollflea** [tkrebs/ep3-bs#407]
Hallo zusammen,
ich musste eine zweite Instanz des Buchungssystems nur für Hallenplätze aufsetzen und habe natürlich der Einfachheit halber die vorhandene Installation inklusive der Datenbank 1:1 kopiert.
Jetzt möchte ich gerne sämtliche nicht benötigten Buchungen entfernen, damit ich die nicht benötigten Freiluftplätze ebenfalls entfernen kann.
Da dieses Vorhaben über das Backend nur sehr umständlich (einzeln) umsetzbar ist: Gibt es eine einfache Möglichkeit, das bulk-mäßig per SQL/phpMyAdmin zu lösen?
Vielen lieben Dank für Eure Hilfe!
Wolfgang

**Comment by cbits68** [comment]
Nach meinem Verständnis musst Du über phpMyAdmin doch nur die entsprechenden Tabellen leeren.
bs_bookings_..., bs reservations_... und bs_events_...

Ich habe das bei mir auch nach Abschluß der Saison geplant, damit ich nächstes Jahr wieder mit einer aufgeräumten DB starten kann.
Gruß
Cbits

**Comment by wollflea** [comment]
Hallo Cbits, das hat geklappt. Man muss allerdings die _meta-Tabellen sowie die bs_bookings_bills auch truncaten und sich über Fremdschlüssel-Referenzen hinwegsetzen... ;-)
Vielen Dank!

**Comment by cbits68** [comment]
Super :-) ja, da sind auch Datensätze vorhanden, die raus müssen.
Lediglich die bs_reservations_meta ist bei mir leer.
Viel Erfolg dann in der Wintersaison. Wir haben leider nur Außenplätze, aber dann habe ich auch mal ein halbes Jahr Ruhe ;-)

**Comment by wollflea** [comment]
Vielen herzlichen Dank! Werde das Thema dann erst mal schließen! ;-)
