### ISSUE TITLE
Bei verschiedenen Benutzern werden Termine aus der Vergangenheit als frei angezeigt

### ISSUE THREAD

**Issue by mnicolaij** [tkrebs/ep3-bs#409]
Bei einem User, der verschiedene Termine gebucht hat, wird der Kalender richtig angezeigt, bei anderen Benutzern werden im Kalender vergangene Tage als frei angezeigt. Hat jemand eine Idee?

Viele Grüße
Monika

**Comment by mnicolaij** [comment]
ich sehe gerade, dass ist nur bei Benutzern, die den Status  "Mitarbeiter".

**Comment by mnicolaij** [comment]
Sorry, hat jemand eine Idee?

**Comment by tkrebs** [comment]
Das ist das normale Verhalten.

Mitarbeiter bekommen, je nach konkreten Berechtigungen, eine andere bzw. erweiterte Darstellung der Kalenders.

**Comment by mnicolaij** [comment]
danke für die Ingo

**Comment by mnicolaij** [comment]
natürlich danke für die Info
