### ISSUE TITLE
Buchungsliste(n) unvollständig

### ISSUE THREAD

**Issue by andyproko** [tkrebs/ep3-bs#411]
Wenn ich als Beispiel die Buchung von diesem Sommer für einen Benutzer abfrage, dann bekommen ich eine unvollständige Liste zurück. In der Regel der erste 6-8 Wochen. Es ist auch nicht eine bestimmte Anzahl von Einträgen wo man annehmen könnte, dass e.g. nach 20 Einträgen abgeschnitten wird.
Die Liste wird viel länger wenn ich die Buchungen ohne Filter abfrage, aber immer noch unvollständig.
Die Logs weisen auch keinen Fehler auf.

Würde ich für einen Benutzer immer monatsweise abfragen scheint es ich bekäme dann die Informationen die ich haben will.
Aber das wäre offensichtlich etwas langwierig.

Für Hilfe wäre ich dankbar.

**Comment by cbits68** [comment]
ggf. direkt über Datenbankexport?
Ich habe mir mal die bs_reservations als csv exportiert, aus Startzeit und Endzeit die Stunden berechnen lassen  und dann eine Auswertungen mittels Pivot in Excel gemacht. Ist aber halt ohne Benutzer, rein für statistische Auswertung über die Auslastung ...

**Comment by andyproko** [comment]
Rein technische Lösungen wie DB Export, monatsweise Auflistung der Buchungen, usw. helfen und wäre etwas für technische Experten. Habe selbst das auch schon gemacht.
Aber in meinem Fall habe ich weitere Admins die ihre relevanten Informationen selbst exportieren bzw. auflisten möchten.
Z.B. der Sportwart der seine Verbandsspiel Buchungen listen möchten, desgleichen der Jugendwart der seine Turniere und Veranstaltungen auflisten möchte.
Dass alles im wesentlichen wegen Corona Dokumentationsauflagen sowie vereinsinterne Abrechnungen.

**Comment by cbits68** [comment]
Das kann ich gut nachvollziehen ... Bei mir ist die Auswertung über die Buchungsverwaltung im Backend leider auch nicht vollständig.
Für mich sieht es nach einem Limit (gewollt oder ungewollt) aus, Ist der gewählte Zeitraum zu lang oder umfasst zu viele Einträge, bricht er offenbar an einer Stelle ab.
Lass ich mir z.B. Buchungen vom 1.05. bis 1.10 (5 Monate) anzeigen, ist die letzte angezeigt Einzelbuchung von Ende August.
Lasse ich mir Buchungen vom 1.06.  bis 1.10. (4 Monate) Anzeigen, ist die letzte angezeigt Einzelbuchung von Anfang September.
Erst der Report vom 1.7. bis heute  (3,5 Monate) zeigt mir auch die letzten Buchungen an.

Es ist auch egal, wie ich den Filter setze! Insofern vermute ich, dass die Auswertung im Backend nach eine Anzahl von X Tagen (oder Buchungen) abbricht und dann nur die bis dahin ausgelesenen Datensätze anzeigt.

Gruß
CBITS

**Comment by andyproko** [comment]
Hat mir jetzt doch keine Ruhe gelassen. Habe etwas gefunden ...
im Verzeichnis: module/Backend/src/Backend/Controller
in der Datei: BookingController.php, ab Zeile #38 in der aktuellen Version:

        ```
if (($dateStart && $dateEnd) || $search) {
            $filters = $this->backendBookingDetermineFilters($search);

            try {
                **_$limit = 1000;_**

                if ($dateStart && $dateEnd) {
                    $reservations = $reservationManager->getInRange($dateStart, $dateEnd, $limit);
                    $bookings = $bookingManager->getByReservations($reservations, $filters['filters']);
                } else {
                    $bookings = $bookingManager->getBy($filters['filters'], null, $limit);
                }
.................
```
ich habe den Wert für $limit mal von 1000 auf 10000 erhöht ... jetzt bekomme ich all die Buchungen die ich gesucht habe.
Auch wenn ich die Abfrage für all Einzelbuchungen in diesem Sommer abschicke, das sind ca. 1900.

Bin zufrieden. Allerdings wäre eine Bestätigung gut, dass ich die Richtige Stelle gefunden habe und keine sonstigen Nachteile zu befürchten sind.

**Comment by andyproko** [comment]
@tkrebs Danke für die Erklärung und Bestätigung. Wäre gut diesen Wert heutigen Standards anzupassen, bzw. zu dokumentieren.
