### ISSUE TITLE
Installation on Debian Buster?

### ISSUE THREAD

**Issue by speedy-10** [tkrebs/ep3-bs#414]
As it turns out the PHP in Debian Buster is too new for ep3-bs.

Do you know, when this will be available?

Regards Speedy-10

**Comment by cbits68** [comment]
Only with the new Release, which has to be rebuild on a new framework. So there is no fixed date for supporting php 7.2+.
To run it with 7.3 is possible but only with some restrictions and after customizing.
If you want to use ep3 on productive environment, I recomment to setup a distribution with php 7.2.

**Comment by speedy-10** [comment]
Thanks for answering so fast.
