### ISSUE TITLE
Installation nicht möglich

### ISSUE THREAD

**Issue by LukaMarcel** [tkrebs/ep3-bs#415]
Hallo, nach der Installation kommt immer wieder folgender Fehler:

![image](https://user-images.githubusercontent.com/6438316/96301037-dc75a100-0ff6-11eb-8a76-22a221c9584b.png)

Was ist das Problem?
Danke für die Hilfe!

**Comment by dmscholz** [comment]
Aus den Antworten von ähnlichen issues hier vielleicht ein Ansatz, der weiterhilft: 

https://github.com/tkrebs/ep3-bs/issues/377#issuecomment-652289178
> in Config/global.php --> 'save_path' => getcwd() . '/data/session/', auskommentieren

Die erste Warnung könnte auch an der PHP version liegen, hast du PHP 7.2? Auf neueren PHP Versionen (7.3+) läuft es nicht ganz reibungslos und da kommen dann manchmal die "deprecation" warnings.

**Comment by LukaMarcel** [comment]
Problem gelöst, danke!
