### ISSUE TITLE
Keine E-Mail Benachrichtigung bei Stornierungen, wie aktivieren?

### ISSUE THREAD

**Issue by dc-de** [tkrebs/ep3-bs#418]
Keine E-Mail Benachrichtigung bei Stornierungen durch Mitarbeiter /Verwalter
Hallo, ich weiß das wurde schongefragt aber nicht voll beantwortet.
mir ist bewusst das das eigentlich nicht vorgesehen ist aber wie lässt sich das trotzdem aktivieren?
Eine benachrichtigung hirbei ist wichtig für uns!

Danke schonmal an das Team für die Hilfe! :+1:

**Comment by dc-de** [comment]
Es ist echt dringend! Ich bitte um hilfe!
Danke

**Comment by tkrebs** [comment]
PHP-Kenntnisse vorausgesetzt, kann das an folgender Stelle eingebaut werden:

https://github.com/tkrebs/ep3-bs/blob/26e43b55607dbf94e6926643f287bc7ad5ce7a6a/module/Backend/src/Backend/Controller/BookingController.php#L395

Dort wird der Buchungsstatus auf "cancelled", also storniert, gesetzt. Das ist die richtige Stelle für eine E-Mail-Benachrichtigung, z. B. mit dem `UserMailerService`:

https://github.com/tkrebs/ep3-bs/blob/master/module/User/src/User/Service/MailService.php

Ohne Anpassung im Code (und/oder ohne entsprechende Grundkenntnisse) ist das nicht möglich.

**Comment by dc-de** [comment]
super vielen dank! das sollte ich hin bekommen werde es mal testen :+1:

**Comment by dc-de** [comment]
Hab eine simple Lösung nun dafür:

```
$booking->set('status', 'cancelled');
$booking->setMeta('cancellor', $sessionUser->get('alias'));
$booking->setMeta('cancelled', date('Y-m-d H:i:s'));
$bookingManager->save($booking);

/* send cancellation confirmation email */
$bookingService = $serviceManager->get('Booking\Service\BookingService');
$bookingService->cancelSingle($booking);
return $this->redirectBack()->toOrigin();
```
Funktioniert einwandfrei. :)
Vielen Dank nochmal

**Comment by DanielM1991** [comment]
Ich bin jetzt in der Anpassung auf einen Bug gestoßen. 
Wenn (bei uns) eine Reservierungen gelöscht wird, legt sich ein Fenster (siehe Screenshot) über unser Reservierungssystem. In dem Fenster auf vorderster Ebene kann ich auch weiter Reservierungen eintragen/löschen, das Fenster dass sich aber beim Anklicken einer Reservierung öffnet, erscheint zwischen beiden Ebenen und ist daher nicht mehr sichtbar. 

Wenn die Ansicht über F5 aktualisiert wird, ist alles wieder normal. Kann man bspw. einen Refresh der Seite in das Skript mit einbauen um das temporär zu lösen?

<img width="1438" alt="Bildschirmfoto 2020-12-18 um 08 57 37" src="https://user-images.githubusercontent.com/43386779/102589471-574e5b80-410f-11eb-958b-38fd8b1c08b2.png">

**Comment by dc-de** [comment]
Moin Daniel,
das hat leider absolut nichts mit diesem issue zutun der außerdem schon geschlossen ist da es eine lösung dafür gibt siehe letzten comment. mach doch einfach einen neuen issue dafür auf.
