### ISSUE TITLE
PHP3 Komatibilität?

### ISSUE THREAD

**Issue by git-kraeMit** [tkrebs/ep3-bs#419]
Hallo,
Provider wie IONOS kündigen aktuell die Unterstützung für PHP 7.2.

Gibt es Pläne die Unterstützung für PHP >= 7.3 zu implementieren?

Danke für eine Antwort & Gruß
kraeMit

**Comment by tkrebs** [comment]
Wir betreiben das Buchungssystem selbst auch auf einem IONOS-Server mit auslaufender PHP-7.2-Unterstützung, daher steht das Thema ganz oben auf der Prioritätsliste.

Wie in anderen Beiträgen bereits besprochen (z. B. https://github.com/tkrebs/ep3-bs/issues/287) ist die Kompatibilität aufgrund des zugrunde liegenden und stark genutzten Zend Framework 2, welches ebenfalls sein EOL erreicht hat, nicht ganz einfach und das überarbeitete Buchungssystem wird sich dementsprechend mehr oder weniger stark von der aktuellen Version unterscheiden und direkt auf PHP 8 basieren.

**Comment by git-kraeMit** [comment]
Herzlichen Dank für Deine schnelle Antwort!
Wird sich dann das Software Nutzungsmodell ändern?

Gruß

**Comment by tkrebs** [comment]
Nein, es bleibt Open-Source und es wird einen Migrationsassistenten zum neuen System geben (den wir ja auch selbst benötigen).

**Comment by git-kraeMit** [comment]
Bedankt!!

**Comment by tkrebs** [comment]
Dank eines aufmerksamen Benutzers des Buchungssystems gibt es nun eine Version 1.7.0 mit provisorischem PHP-7.4-Support.

**Comment by gitbub-mkr** [comment]
Cool! Vielen Dank!
