### ISSUE TITLE
French translation (contribution)

### ISSUE THREAD

**Issue by FlossyWeb** [tkrebs/ep3-bs#42]
Hi there,

I've translated the web application to make it an english/german/french app.
You can see it live there : http://flossyweb.com/tennis/public/
Note that the third flag, which is the french one, fits in the top-right corner block,. Also I've made french the default language in this demo, because it is intended for french users.

If you're interested I would be glad to send you the files related to this translation.

Thanks anyway for the great work you've done here.

**Comment by tkrebs** [comment]
Hi, french translations are very welcome. You can send me the language files per email (info@bs.hbsys.de) or per GitHub pull request.

Thank you!

**Comment by makriria** [comment]
I am working on a greek translation. I will send it to you when it is done

**Comment by FlossyWeb** [comment]
Hi @tkrebs,

The code I'm working on is accessible here : https://github.com/FlossyWeb/BookingSystem , I also packed only related files there : http://flossyweb.com/tennis/french_pack.zip so that you can pick directly the i18n translated files and a french flag icon.

**Comment by tkrebs** [comment]
Thank you very much, I have merged them into the master branch. **Good work!**
