### ISSUE TITLE
Setup funktioniert nicht

### ISSUE THREAD

**Issue by hansiburli** [tkrebs/ep3-bs#424]
Ich habe alle Schritte im install.txt befolgt, bekomme aber beim Aufruf von setup.php eine Fehlerseite.

Fatal error: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, Zend\I18n\Translator\TextDomain given in D:\xampp\htdocs\ep3-bs\vendor\zendframework\zend-i18n\src\Translator\Loader\PhpArray.php:52 Stack trace: #0 D:\xampp\htdocs\ep3-bs\vendor\zendframework\zend-i18n\src\Translator\Loader\PhpArray.php(52): array_key_exists('', Object(Zend\I18n\Translator\TextDomain)) #1 D:\xampp\htdocs\ep3-bs\vendor\zendframework\zend-i18n\src\Translator\Translator.php(709): Zend\I18n\Translator\Loader\PhpArray->load('de-DE', 'D:\\xampp\\htdocs...') #2 D:\xampp\htdocs\ep3-bs\vendor\zendframework\zend-i18n\src\Translator\Translator.php(618): Zend\I18n\Translator\Translator->loadMessagesFromPatterns('default', 'de-DE') #3 D:\xampp\htdocs\ep3-bs\vendor\zendframework\zend-i18n\src\Translator\Translator.php(442): Zend\I18n\Translator\Translator->loadMessages('default', 'de-DE') #4 D:\xampp\htdocs\ep3-bs\vendor\zendframework\zend-i18n\src\Translator\Translator.php(356): Zend\I18n\Translator\Translator->getTranslatedMessage('Error', 'de-DE', 'default') #5 D:\xampp\htdocs\ep3-bs\vendor\zendframework\zend-mvc\src\I18n\Translator.php(73): Zend\I18n\Translator\Translator->translate('Error', 'default', 'de-DE') #6 D:\xampp\htdocs\ep3-bs\vendor\zendframework\zend-i18n\src\View\Helper\Translate.php(38): Zend\Mvc\I18n\Translator->translate('Error', 'default', NULL) #7 [internal function]: Zend\I18n\View\Helper\Translate->__invoke('Error') #8 D:\xampp\htdocs\ep3-bs\vendor\zendframework\zend-view\src\Renderer\PhpRenderer.php(397): call_user_func_array(Object(Zend\I18n\View\Helper\Translate), Array) #9 D:\xampp\htdocs\ep3-bs\module\Base\src\Base\View\Helper\Setup.php(15): Zend\View\Renderer\PhpRenderer->__call('translate', Array) #10 [internal function]: Base\View\Helper\Setup->__invoke(Array) #11 D:\xampp\htdocs\ep3-bs\vendor\zendframework\zend-view\src\Renderer\PhpRenderer.php(397): call_user_func_array(Object(Base\View\Helper\Setup), Array) #12 D:\xampp\htdocs\ep3-bs\module\Setup\view\error\500.phtml(4): Zend\View\Renderer\PhpRenderer->__call('setup', Array) #13 D:\xampp\htdocs\ep3-bs\vendor\zendframework\zend-view\src\Renderer\PhpRenderer.php(506): include('D:\\xampp\\htdocs...') #14 D:\xampp\htdocs\ep3-bs\vendor\zendframework\zend-view\src\View.php(207): Zend\View\Renderer\PhpRenderer->render(NULL) #15 D:\xampp\htdocs\ep3-bs\vendor\zendframework\zend-view\src\View.php(236): Zend\View\View->render(Object(Zend\View\Model\ViewModel)) #16 D:\xampp\htdocs\ep3-bs\vendor\zendframework\zend-view\src\View.php(200): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel)) #17 D:\xampp\htdocs\ep3-bs\vendor\zendframework\zend-mvc\src\View\Http\DefaultRenderingStrategy.php(105): Zend\View\View->render(Object(Zend\View\Model\ViewModel)) #18 [internal function]: Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent)) #19 D:\xampp\htdocs\ep3-bs\vendor\zendframework\zend-eventmanager\src\EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #20 D:\xampp\htdocs\ep3-bs\vendor\zendframework\zend-eventmanager\src\EventManager.php(248): Zend\EventManager\EventManager->triggerListeners('render.error', Object(Zend\Mvc\MvcEvent)) #21 D:\xampp\htdocs\ep3-bs\vendor\zendframework\zend-mvc\src\View\Http\DefaultRenderingStrategy.php(123): Zend\EventManager\EventManager->triggerEvent(Object(Zend\Mvc\MvcEvent)) #22 [internal function]: Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent)) #23 D:\xampp\htdocs\ep3-bs\vendor\zendframework\zend-eventmanager\src\EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #24 D:\xampp\htdocs\ep3-bs\vendor\zendframework\zend-eventmanager\src\EventManager.php(248): Zend\EventManager\EventManager->triggerListeners('render', Object(Zend\Mvc\MvcEvent)) #25 D:\xampp\htdocs\ep3-bs\vendor\zendframework\zend-mvc\src\Application.php(384): Zend\EventManager\EventManager->triggerEvent(Object(Zend\Mvc\MvcEvent)) #26 D:\xampp\htdocs\ep3-bs\vendor\zendframework\zend-mvc\src\Application.php(356): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent)) #27 D:\xampp\htdocs\ep3-bs\public\setup.php(66): Zend\Mvc\Application->run() #28 {main} thrown in D:\xampp\htdocs\ep3-bs\vendor\zendframework\zend-i18n\src\Translator\Loader\PhpArray.php on line 52

**Comment by Shineson1001** [comment]
Hi @hansiburli,
welche Version von php setzt du ein?

**Comment by hansiburli** [comment]
> 
> 
> Hi @hansiburli,
> welche Version von php setzt du ein?

8.0, is die zu hoch?

**Comment by Shineson1001** [comment]
ja .. auf jeden Fall .. teste mal die Version 7.2 .. 7.3 geht schon nicht bzw. macht Probleme

**Comment by tkrebs** [comment]
Dieser Fehler sollte in der neuen Version 1.7.0 mit PHP-7.4-Kompatibilität behoben sein.
