### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Caserena1** [tkrebs/ep3-bs#430]
Wenn ich alles installiert habe, bekomme ich unterstehende Fehlermeldung?

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/xxxx/domains/xxx.de/public_html/booking/vendor/zendframework/zend-stdlib/src/ArrayObject.php on line 426

Auch die Einteilung ist anders, also das was man sieht. Ich könnte eine link einstellen.

**Comment by Bergruebe** [comment]
Den Fehler habe ich auch, allerdings geht es nach einem Neuladen der Seite ohne Probleme. Dann wird der Kalender richtig angezeigt.
Nur leider tritt der Fehler öfters auf.

[Hier wurde der Fehler schon mal angesprochen](https://github.com/tkrebs/ep3-bs/issues/336#issue-620073341) allerdings wurde es da mit einer anderen PHP Version behoben. 
Ich setzt grade die PHP Version 7.3 ein, und die ep3 Version 1.7.0 (meines Wissens der neuste Stand)

**Comment by tkrebs** [comment]
Der Fehler wurde im heute aktualisierten, [letzten Stand](https://bs.hbsys.de/download) behoben.
