### ISSUE TITLE
Buchungen nur Werktags - "Wochenanzeige" im Kalender fehlerhaft

### ISSUE THREAD

**Issue by andyproko** [tkrebs/ep3-bs#431]
Wir planen evtl diesen Sommer das Buchungssystem beizubehalten und wollen Online Buchungen nur Werktags und zu Kernzeiten zulassen. Die Einstellungen dafür sind soweit vorhanden (Buchungen e.g. 16 bis 20 Uhr) ausschl.. Samstag und Sonntag.

Wenn ich aber 5 Tage im Kalender anzeigen will, werden nur 4 Tage angezeigt. Wenn ich dann tageweise weiter scrolle, werden nur 3 Tage, dann 2 Tage angezeigt (weil Sa, So ausgeblendet werden). Zum Wochenende schließlich Freitag und Montag. Erst wenn ich Montag erreicht habe, werden wieder die nächsten 4 Tage angezeigt.

Meine Erwartung wäre, dass bei der Anzeige von 5 Tagen und der heutige Tag Mittwoch ist, dass Mittwoch, Donnerstag, Freitag, Montag, Dienstag im Kalender gezeigt wird.

**Comment by tkrebs** [comment]
Teste mal die aktuelle Entwicklungsversion:

https://github.com/tkrebs/ep3-bs/archive/develop.zip
(es reicht der Austausch des `modules`-Verzeichnisses)

Dort gab es vor ein paar Monaten eine Korrektur hinsichtlich der Datumausnahmen.

**Comment by andyproko** [comment]
@tkrebs Habs probiert und funktioniert nicht wie erwartet.
Ein grundsätzliches Problem ist, dass mehr als 4 Tage im Kalender nicht angezeigt werden. Was so gesehen auch OK ist weil je nachdem wieviele Plätze der Verein hat das in Darstellungsprobleme resultieren kann :-)

Die Darstellung im Kalender folgt wohl der Logik:
1. Wieviele Tage anzeigen, e.g. 4
2. Tagesspezifische Information abholen
3. Falls ein Tag/Datum ausgeblendet ist, dann nicht anzeigen

Mein Wunsch wäre solche Tage/Datum zu überspringen. Wobei mach auch anders argumentieren kann.

Wenn ich als eingestellt habe:
- 4 Tage im Kalender anzeigen
- mit 6 Plätzen aktiv
- Samstag, Sonntag ausgeblendet

- Dienstag als Beginnwochentag: Dienstag, Mittwoch, Donnerstag, Freitag wird angezeigt
- Mittwoch als Beginnwochentag: Mittwoch, Donnerstag, Freitag wird angezeigt
- Donnerstag als Beginnwochentag: Donnerstag, Freitag wird angezeigt
- Freitag als Beginnwochentag: Freitag, Montag wird angezeigt

**Comment by andyproko** [comment]
Unser Ziel ist es die Stecktafel im Sommer an Werktagen in einem bestimmten Zeitraum durch Online Buchung für einen Teil der Plätze zu ersetzen.
Plan ist es jetzt die Buchung 24h im voraus zu erlauben.
Somit brauche ich nur 2 Tage anzeigen - also Problem mit Kalender nicht mehr relevant.

Was in einem solchen Szenario hilfreich wäre, ist die Möglichkeit zu haben wiederholende Sperrzeiten eingeben zu können (e.g. Samstag, Sonntag) und diese als solche im Kalender auch anzuzeigen. Evtl. auch mit Zusatz-Info zum Sperrtermin, wie z.B. "Bitte am Wochenende Stecktafel benutzen" .... Feature request :-)
