### ISSUE TITLE
Wöchentliche Buchung

### ISSUE THREAD

**Issue by Bergruebe** [tkrebs/ep3-bs#432]
**Auch ich muss mich erstmal für dieses tolle System bedanken!**
<hr>
Ich versuche mit dem Programm eine online Buchungslösung für Yogakurse umzusetzen, was natürlich anders als Tennisplätze funktioniert. 😉 
In der Woche finden insgesamt sechs Kurse statt, für jeden Kurs habe ich jetzt jeweils ein "Platz" angelegt und Buchungen nur für den Montag erlaubt (für die gesamte Woche).
Das sieht natürlich nicht ganz so gut aus, und ist auch leicht verwirrend für die Buchenden:

![image](https://user-images.githubusercontent.com/68869895/105477548-4c549100-5ca2-11eb-84bc-a0b0d50825ee.png)

Meine Idee war jetzt, in der Übersetzung "Montag" mit "Woche beginnend am" zu ersetzen. Habt ihr vielleicht elegantere Lösungen oder gibt es die Möglichkeit die Tag mit Kalenderwochen zu ersetzen?

Viele Grüße Bergrübe

**Comment by tkrebs** [comment]
Die Übersetzung zu ändern ist hinsichtlich Kosten/Nutzen sicherlich eine solide Möglichkeit.

Technisch "korrekter", aber PHP-Kenntnisse voraussetzend, wäre die Anpassung im entsprechenden Code-Baustein:

https://github.com/tkrebs/ep3-bs/blob/master/module/Calendar/src/Calendar/View/Helper/DateRow.php

**Comment by Shineson1001** [comment]
Hi @Bergruebe,

würden diese Einstellungen passen?
![grafik](https://user-images.githubusercontent.com/22273771/105578711-5b127500-5d82-11eb-94c1-e8aa18fa4b06.png)

**Comment by Bergruebe** [comment]
@Shineson1001 Interessante Idee! Wie genau hast du geschafft, verschiedene Zeiten je Wochentag anzugeben?
Wenn ich das richtig verstehe, hast du ja nur einen "Platz" mit dem Namen Kurse angelegt.

Das würde nämlich auch gleich ein weiteres Problem lösen, dass ich (mit der Montags-/Wochenlösung) nur maximal vier Tage nach vorne schauen kann, da sonst der Error kommt: `Too many days are hidden from calendar`
`File /hp/cd/aa/sa/www/ep3/module/Calendar/src/Calendar/Controller/CalendarController.php:79`

**Comment by Shineson1001** [comment]
Hier die Einstellungen
![grafik](https://user-images.githubusercontent.com/22273771/105608806-88bce580-5da5-11eb-9a03-8524a2cf0525.png)

![grafik](https://user-images.githubusercontent.com/22273771/105608813-8d819980-5da5-11eb-8864-4bc97380bb31.png)

![grafik](https://user-images.githubusercontent.com/22273771/105608815-91152080-5da5-11eb-8b45-d62173d3e9c2.png)

![grafik](https://user-images.githubusercontent.com/22273771/105608819-93777a80-5da5-11eb-8b54-1c9b22f65129.png)

![grafik](https://user-images.githubusercontent.com/22273771/105608820-96726b00-5da5-11eb-89ed-e6d75f9f4647.png)

**Comment by Bergruebe** [comment]
Ok, vielen Dank! Auf die Idee einen User "Geschlossen" anzulegen, kam ich noch nicht!

**Comment by Shineson1001** [comment]
Du kannst ja mal berichten, ob du mit den Einstellungen weiterkommst.

**Comment by Bergruebe** [comment]
Ich muss leider sagen, dass das Projekt bei mir grade auf Eis liegt.
Deine Idee @Shineson1001 finde ich nicht schlecht, nur dass der verfügbare Platz nicht effizient genutzt wird. (da bin ich eventuell etwas zu perfektionistisch 😉)

Wenn ich es Zeitlich schaffe das Thema wieder aufzugreifen, und eine Lösung finde, werde ich sie hier posten.
Bis dahin schließe ich erstmal wieder diesen Issue.
