### ISSUE TITLE
Neuinstallation Version 1.7.0 mit php 7.4

### ISSUE THREAD

**Issue by Shineson1001** [tkrebs/ep3-bs#433]
Hallo,

ich habe eine frische Testinstallation mit der aktuellen ep3 Version erstellt und bekomme nach dem Ausfüllen der "Insert database records"-Setup Seite eine Meldung und kann die Einrichtung nicht abschließen.

Hier ein paar Infos zum System:
Betriebssystem: Ubuntu 20.04
php-Version: 7.4.3
Apache-Version: 2.4.38

![grafik](https://user-images.githubusercontent.com/22273771/105557599-e6e9ba00-5d0c-11eb-9d4c-e438a67e2032.png)

Einrichtungsschritte:
![grafik](https://user-images.githubusercontent.com/22273771/105557076-a9d0f800-5d0b-11eb-8523-6f95f092ba54.png)
![grafik](https://user-images.githubusercontent.com/22273771/105557099-b35a6000-5d0b-11eb-9e53-74b1264f06d3.png)
![grafik](https://user-images.githubusercontent.com/22273771/105557146-ca00b700-5d0b-11eb-8c30-876113504203.png)
![grafik](https://user-images.githubusercontent.com/22273771/105557155-cf5e0180-5d0b-11eb-99fa-6e195b023386.png)
![grafik](https://user-images.githubusercontent.com/22273771/105557163-d258f200-5d0b-11eb-811a-870d012b7acf.png)

Nach dem [Speichern] kommt die Meldung
![grafik](https://user-images.githubusercontent.com/22273771/105557212-eef52a00-5d0b-11eb-82b2-2afd422b18a1.png)

Tabellenstruktur:
![grafik](https://user-images.githubusercontent.com/22273771/105557696-1f899380-5d0d-11eb-8fc5-692d257e124e.png)

Ich habe habe das Feld bs_squares->allow_notes testweise mal mit dem Default-Wert '1' anlegen lassen
=> 'allow_notes' tinyint(1) NOT NULL DEFAULT '1',
.. dann kann man die Installation abschließen.
![grafik](https://user-images.githubusercontent.com/22273771/105558062-09c89e00-5d0e-11eb-8a0c-8ceeb749af4f.png)

**Comment by tkrebs** [comment]
Vielen Dank für die Hinweise, ist korrigiert:

https://github.com/tkrebs/ep3-bs/commit/139e2165f812f3463592d21670d2e00131bf6773

**Comment by Shineson1001** [comment]
Hi @tkrebs,
Besten Dank für deine Arbeit. Gestern habe ich auch meine Produktivumgebung auf 1.7.0 und php 7.4 umgestellt. Läuft sehr gut.
