### ISSUE TITLE
Änderung der E-Mail-Adresse in der local.php

### ISSUE THREAD

**Issue by dschousef** [tkrebs/ep3-bs#435]
Hi! Folgendes kleines Problem habe ich:
Ich habe die E-Mail-Adresse des Systems sowohl in den Einstellungen für "Namen und Texte" als auch in der local.php geändert. In den vom System verschickten E-Mails erscheint aber in der Von-Zeile immer noch die alte Adresse, Nur in der "Antwort an"-Zeile erscheint die neue. Ich vermute, dass die Adresse für die Von-Zeile aus der local.php gelesen wird. Liege ich da richtig? Hat ggf. jemand eine Ahnung, warum die Änderung in der local.php nicht zieht?
Vielen Dank für eure Tipps und Ideen!

**Comment by cbits68** [comment]
Hast Du mal unter data/cache die module-config-cache.ep3-bs.php gelöscht? Oder steht da bei Dir unter sendmail auch schon die neue Adresse drin?
Gruß
CBITS

**Comment by dschousef** [comment]
Danke, das war's! Diese Datei gab's in meiner lokalen XAMPP-Installation nicht, deshalb konnte mein Suchlauf nach der alten Adresse dort nichts finden. Hab die neue Adresse jetzt in dieser Datei auf dem Server eingetragen und jetzt passt's!
Danke nochmal und Gruß
dschousef

**Comment by cbits68** [comment]
gern geschehen ;-) Wenn Du Änderungen am System (Einstellungen) vornimmst empfiehlt es sich generell den cache zu löschen. Die Dateien im Cache werden dann automatisch mit der geänderten Konfiguration neu erstellt. Da liest er dann wohl u.A. auch Parameter aus der lokale-php aus. Das betrifft z.B. auch Änderungen bei der Sprache, Datenbank und dem Mailversand.

**Comment by dschousef** [comment]
Alles klar, gut zu wissen, Danke!
