### ISSUE TITLE
ep3-bs Update Version auf 1.7

### ISSUE THREAD

**Issue by tennstar1** [tkrebs/ep3-bs#436]
Hallo,
in der Downloaddatei für das o.a. Update auf 1.7 fehlt die Datei VENDOR daher lässt sich das Paket nicht eigenständig installieren.

Ist das Absicht oder ein Versehen und muss dann die alte Vendor Datei benutzt werden?

Es sollen ja Dateien im zendframework geändert worden sein und dieses ist ja in der Datei Vendor!

Gruß tennstar

**Comment by tkrebs** [comment]
GitHub und die [Release-Downloads](https://github.com/tkrebs/ep3-bs/releases) enthalten nur den Quellcode des Buchungssystems ohne Drittanbieter-Abhängigkeiten. Diese müssen mittels Composer selbst installiert werden.

Das [Download-Paket auf der Website](https://bs.hbsys.de/download) ist hingegen vollständig und enthält bereits die o. g. Abhängigkeiten.

Ich habe hierzu sicherheitshalber auch noch mal einen Hinweis auf der Release-Seite platziert.

**Comment by tennstar1** [comment]
Vielen Dank für den Hinweis!
