### ISSUE TITLE
Stornierungsmail bei Stornierung durch Verwaltung

### ISSUE THREAD

**Issue by MacHoliday** [tkrebs/ep3-bs#445]
Hallo.
Erstmal DANKE für das grandiose Buchungssystem! Ich bin gerade dabei es im Verein einzurichten und einzuführen.  ;-)

Mir ist jetzt allerdings beim Testen aufgefallen, dass für Buchungen von beliebiegen Usern, die von der Verwaltung storniert werden, keine Stornierungs-E-Mails an den User, der die Buchung durchgeführt hat, versendet werden.
Also, 
- User bucht einen Platz ==> Bestätigungsemail wird versendet
- Verwaltung storniert (nicht löschen) Platzbuchung von User ==> Bestätigungsemail wird NICHT versendet, weder an User noch an die Verwaltung.

- Bucht und Storniert der User die Buchung selber => Bestätigungsemail wird versendet

Ist das Verhalten so gewollt/bekannt oder nur bei mir so? Kann man das ggf. anpassen, dass auch die E-Mail bei Stornierung durch die Verwaltung rausgeht?

Vielen Dank für eure Antworten.
MFG
Andreas

**Comment by DanielM1991** [comment]
Servus Andreas,

das ist im aktuellen Release nicht implementiert, soll aber im nächst größeren Release berücksichtigt werden. 
Es gibt aber eine Bastel-Lösung die bei mir auch funktioniert.

Schau mal hier: https://github.com/tkrebs/ep3-bs/issues/418


Grüße
Daniel M

**Comment by MacHoliday** [comment]
Servus Daniel,
Danke für die schnelle Antwort. Funzt und genau das, was ich gesucht habe (und nicht gefunden haben weil ich nicht den Closed Issues gesucht habe... Sorry. ;-) )
Grüße
Andreas

**Comment by DanielM1991** [comment]
Gerne! 
Hab selbst nochmal kurz suchen müssen weil es dazu schon diverse Issues gibt..
