### ISSUE TITLE
Possible issue in validators

### ISSUE THREAD

**Issue by makriria** [tkrebs/ep3-bs#45]
Hello there

I made some changes in my forked repository. While trying to remove some user profile fields from interface I reach line 384 in file
/module/Backend/src/Backend/Form/User/EditForm.php

'ef-street' => array(

Should it be 

 'euf-street' => array(

line all the others in this page?

Kind regards.

**Comment by tkrebs** [comment]
Yes, you are right. Thank you for reporting. I have fixed that.
