### ISSUE TITLE
Syntax Error nach Update auf 1.7

### ISSUE THREAD

**Issue by frankgayer** [tkrebs/ep3-bs#450]
Hallo,

ich habe heute das Update 1.7 hochgeladen und dabei die beiden Ordner Vendor und Module ersetzt. 
Jetzt erhalte ich auf der Webseite diesen Fehler:

Warning: Unterminated comment starting line 580 in /www/htdocs/w00e1827/sve.t.bespannservice.de/vendor/zendframework/zend-http/src/Response.php on line 580

Parse error: syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST) in /www/htdocs/w00e1827/sve.t.bespannservice.de/vendor/zendframework/zend-http/src/Response.php on line 586

Kann mir jemand sagen was hier das Problem ist ?

**Comment by cbits68** [comment]
Welche PHP Version hast Du denn jetzt laufen?
Das Update auf 1.7 hat bei mir gut funktioniert, allerdings mache ich das auch über git und nicht per manuellem Upload.
Bei mir läuft es mit PHP 7.4 bisher fehlerfrei ...

**Comment by cbits68** [comment]
schon komisch ... Du stellst ein issue ein und nach über 10 Tagen kannst Du nicht mal eine Frage beantworten, um Dir zu helfen? Ich bin dann mal hier raus ...

**Comment by frankgayer** [comment]
Ich finde das nicht komisch, denn ich habe in der Zwischenzeit genau das gemacht ! Das Update der PHP auf 7.4 von der 7.1, dann habe ich das Update eingespielt und getestet ob alles wie gewohnt funktioniert. Da ich das nicht mal kurz tagsüber machen konnte bin ich erst am Wochenende dazu bekommen. Seit Samstag scheint alles rund zu laufen. Danke für die Aufklärung

**Comment by cbits68** [comment]
freut mich, dass es jetzt läuft ;-)
