### ISSUE TITLE
Fehler bei Überspringen von Tagen

### ISSUE THREAD

**Issue by FD-ITE** [tkrebs/ep3-bs#451]
Hallo!

Seit 2020 haben wir das Buchungssystem in Betrieb mit der Einstellung des Kalenders, Samstag und Sonntag nicht anzuzeigen. Jetzt besteht seit Anfang März 2021 das Problem, dass zwar die Wochenenden nicht angezeigt werden, dafür die nachkommenden Tage als frei markiert sind obwohl diese nicht frei sind. Kommt man dann in die neue Woche, wird diese mit den Buchungen richtig dargestellt. 

Als Beispiel: Am Montag, 08.03.21, wird noch alles korrekt dargestellt, ob ein Platz belegt ist oder nicht. Am Freitag, 12.03.21, wird bereits die nächste Woche angezeigt, jedoch als komplett "Frei" obwohl bereits Plätze gebucht sind. Geht man auf den Montag, 15.03.21, erscheinen die gebuchten Termine ohne Probleme. 

Es muss an der Funktion liegen, Tage auszublenden. Ich habe mir mal die komplette Woche anzeigen lassen, da gab es keine Probleme bei der Darstellung. Kaum lasse ich wieder das Wochenende überspringen, tritt oben genannter Fehler wieder auf. 

Kann mir jemand weiterhelfen, wie ich das wieder richtig darstellen lassen kann mit den ausgeblendeten Tagen?

Vielen Dank im Voraus!

**Comment by tkrebs** [comment]
Welche Version des Buchungssystems setzt ihr ein bzw. wann habt ihr das letzte mal geupdated?

**Comment by FD-ITE** [comment]
Die Version ist die 1.6.4

**Comment by tkrebs** [comment]
Schau mal hier:

https://github.com/tkrebs/ep3-bs/issues/390

Und hier:

https://github.com/tkrebs/ep3-bs/issues/299

Es gab eine Korrektur, die das Problem bei den meisten Anwendern gelöst hat und Teil der aktuellen Version 1.7.0 ist.

Ansonsten das Thema bitte bei den o. g. Issues weiterführen.
