### ISSUE TITLE
Can't find how to change the background color

### ISSUE THREAD

**Issue by Khairulazib** [tkrebs/ep3-bs#452]
Hello, i can't find where to change the background color of the system, i already edit public/css-client/default.css still no changes. Can someone tell me where to edit the background color and layout of the system? I'm new to Zend framework, thanks

**Comment by tkrebs** [comment]
The file `public/css-client/default.css` is the right place for this and should work. This is pure CSS. No need to know Zend Framework.

Have you tried reloading without caches (Shift + Reload; or a private browser tab) after you saved your changes?

Also, make sure your CSS rules have the same or higher [specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) than the ones you want to override.

**Comment by Khairulazib** [comment]
okay, thank you. Can be change already.

**Comment by tkrebs** [comment]
👍
