### ISSUE TITLE
Einbau eines Java Tracking Codes im ep3 Buchungssystem?

### ISSUE THREAD

**Issue by cbits68** [tkrebs/ep3-bs#459]
Hallo,
Es geht um ein Website Tracking mit Matomo (ehemals Piwik).
Ich möchte es gern verwenden, um eine Nutzungsauswertung des ep3 Buchungssystems zu erstellen und auch um zu sehen, mit welchen Endgeräten und Browserversionen die Mitglieder das System nutzen.
Dazu muss ein JavaScript-Tracking-Code eingebaut werden, der dann bei jedem Seitenaufruf die statistischen Daten übermittelt.
sieht dann etwa so aus:

<script type="text/javascript">
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="https://matomoserver/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '2']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>

Wo kann man das Script sinnvoller Weise am besten einbauen, damit es dann auch bei allen Seitenaufrufen im ep3 durch läuft?

Lieben Gruß
CBITS

**Comment by Shineson1001** [comment]
Hi @cbits68,
spontan würde ich das Skript an das Ende der layout.phtml setzen.
https://github.com/tkrebs/ep3-bs/blob/6d4bc8b016c7712c36af902c9a8df469bd0c59e2/module/Base/view/layout/layout.phtml#L108

**Comment by cbits68** [comment]
Hi @Shineson1001
Danke, ich habe es mal dort eingefügt und das Script wird jetzt auch entsprechend bei den Seitenaufrufen ausgeführt, wie ich im Seitenquelltext sehen kann.
Momentan sehe ich noch keine Daten im Matomo Backend, aber das kann auch etwas dauern ...

**Comment by Shineson1001** [comment]
Hi @cbits68,
ob das Skript korrekt und fehlerlos aufgerufen wird, kann man am einfachsten mit den Browser-integrierten Web-Entwickler Werkzeugen prüfen. Im Firefox öffnet man die z.B. mit STRG-SHIFT+I
Im Reiter "Netzwerkanalyse" kann man zum Beispiel jeden Aufruf nachverfolgen. Oder in den Reitern "Konsole" oder "Debugger" werden einem eventuelle Skriptfehler ausgegeben.

**Comment by cbits68** [comment]
Ja, habe ich auch so gemacht. Passt! Inzwischen sind auch die Trackingdaten in der Matomo Datenbank :-)
In der Konsole hatte ich nur einen Fehler, allerdings scheint der aber aus den bereits vorhandenen Javascrip Aufrufen mit jQuery's zu kommen. Offenbar ist es besser mit asynchronen Requests zu arbeiten als mit synchronen. Hat aber für mich aktuell keine Auswirkungen...

jquery.min.js:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
