### ISSUE TITLE
Question about date format

### ISSUE THREAD

**Issue by makriria** [tkrebs/ep3-bs#46]
Hello tkrebs,

trying to create a greek interface I face an issue. In module/Backend/src/Backend/Controller/BookingController.php at lines about 150 (for applying default values in form) I see that english language shows 'Nov 26, 2016' while german shows '26.11.2016'
I can not understand where this difference comes from. For greek, the value there is '26 Νοε 2016' that is considered invalid on submit. When selecting a value from datepicker it works correctly. The problem is only in default value. Can you describe me how you get 26.11.2016 in german?

Kind regards,
Michael.

**Comment by tkrebs** [comment]
Hello makriria,

the date string is generated by Zend Framework's DateFormat view helper, which in turn uses the PHP intl extension to create a correctly formatted date in the current locale.
