### ISSUE TITLE
User soll vergangene Buchungen sehen

### ISSUE THREAD

**Issue by hulot113** [tkrebs/ep3-bs#463]
Hallo, hätte gerne, dass der normale Benutzer auch die vergangenen Termine sehen kann.
Schön wäre z.B. wenn dieser auch Rechte bekommen könnte so ähnlich wie der Mitarbeiter.
Jemand ne Idee?

**Comment by cbits68** [comment]
Warum legst Du dann nicht jeden Benutzer als Mitarbeiter an und verpasst Ihm die Rechte, die er braucht? (Buchungen, Versnstaltungen & Abo's )
Mitarbeiter kannst Du ja auch unterschiedlich berechtigen. Ich habe z.B. Trainer, die auch Veranstaltungen und Abo's buchen dürfen und welche die nur Buchungen verwalten dürfen und auch vergangene Buchungen sehen können.

**Comment by hulot113** [comment]
Ok, wenn ich nur die Rechte für vergangene Buchungen markiere passt das.
Wenn ich das Recht Sieht Namen und Details markiere, ist das mit dem Buchen nicht mehr ganz so schön einfach. Da muss er dann seinen Namen erst auswählen. Kann man das Feld mit dem eigenen Namen vorbelegen lassen?

**Comment by cbits68** [comment]
musst Du probieren/testen. Ich musste z.B. das Recht Buchungen verwalten vergeben, damit die Benutzer überhaupt noch buchen können. Ich bin mir aber nicht sicher  ob diese dann auch Buchungen anderer Benutzer verwalten können.
