### ISSUE TITLE
You cannot use Zend\Crypt\Symmetric\Mcrypt without the Mcrypt extension

### ISSUE THREAD

**Issue by JaEmiX** [tkrebs/ep3-bs#47]
Hi, kann mir da jemand helfen Ich bin nicht so in der Materie, darum auch logischerweise kein Profi und weiß nicht was das zu bedeuten hat. Wäre cool wenn mir da jemand helfen könnte.

**Comment by JaEmiX** [comment]
habs gefixed :) 

einfach das Mcrypt aufspielen üder die Konsolle (SSH-Verbindung).

**Comment by tkrebs** [comment]
Sehr gut, dann kann das ja geschlossen werden! :)
