### ISSUE TITLE
Die 1 aus der Mitspieler Liste entfernen - geht das?

### ISSUE THREAD

**Issue by tennstar1** [tkrebs/ep3-bs#476]
Hallo,
obwohl das System jetzt während der Corona Pandemie so eingestellt ist, dass die Mitspieler zwingend einzutragen sind, versucht immer wieder jemand das zu umgehen indem er keine auswählt und die 1 stehen lässt.

Gibt es die Möglichkeit die 1 aus den Auswahlliste zu entfernen sodass diese erst mit 2 Teilnehmern beginnt und damit die Buchung ohne Eingabe des Teilnehmers nicht vollzogen werden kann?

Vielleicht hat dies ja der eine oder andere auch schon festgestellt und geändert.

Vielen Dank für Euere Mühe!

Gruß tennstar1

**Comment by cbits68** [comment]
siehe #273

**Comment by tennstar1** [comment]
Hallo cbits68,
Danke für Deine Hilfe, hatte zwar danach gesucht aber leider nicht gefunden! 👍
