### ISSUE TITLE
Editor für Info und Hilfeseite - hier Hintergrund ist dunkel

### ISSUE THREAD

**Issue by mjmpeace** [tkrebs/ep3-bs#479]
![Außenanlage](https://user-images.githubusercontent.com/46706899/119687494-8cda3c00-be47-11eb-8f53-149110433f33.JPG)
![Infoseite Editor Halle](https://user-images.githubusercontent.com/46706899/119687497-8d72d280-be47-11eb-841a-e920f7fec2fd.JPG)
Der Editor bei meinem Hallensystem ist ok und gut benutzbar. Beim Außenplatzsystem nicht - siehe die zwei Screenshots. Wo muss ich da ansetzen, das bei der dunkle Editor so wird wie der andere Editor mit hellem Hintergrund?

**Comment by ChristianBlenk** [comment]
Der Editor ist leider nur spärlich mit Formatierungsbefehlen bestückt. Ich würde das ganze als Word erstellen und dann via Copy&Paste in den Editor kopieren. Dann solltest Du das Problem nicht mehr haben.

**Comment by mjmpeace** [comment]
Das mag zwar ein Workaround sein - beantwortet aber nicht die Frage - mir geht es darum, warum der Hintergrund dunkel ist. Das muss ja in irgendeiner CSS stecken. Aber wo?

**Comment by ChristianBlenk** [comment]
Wirst du so nicht finden. Schau in der Datenbank. Dort ist der Style in der Infoseite selber gespeichert. 
Was passiert denn nach STRG+A und DEL im Editor?

**Comment by mjmpeace** [comment]
Dann ist die gesamte Fläche dunkelgrau - wie oben zu sehen. Wenn ich wüsste, woher dieser Hintergrund kommt, könnte ich die Datei vergleichen mit der im Hallensystem, wo es korrekt ist.

**Comment by ChristianBlenk** [comment]
Schau mal in die default.min.css im body-tag

![image](https://user-images.githubusercontent.com/84763400/119877529-73112580-bf29-11eb-95a8-87e91012dbf7.png)

**Comment by mjmpeace** [comment]
Soweit war ich auch schon - aber es funktioniert nicht!

**Comment by mjmpeace** [comment]
Der Hintergrund wird durch ein jpg erzeugt. Der Name ist bg.jpg
Gefunden durch "Untersuchungsfunktion" in Chrome. Die Datei, die weiss erzeugt, konnte nicht geladen werden. Dann wird per default die dunkelgraue bg.jpg aus der ursprünglichen Einstellung verwendet. Ladefehler liegt an einem falschen Pfad in der css. Wenn ich das genau herausgefunden habe, wie es geht, schreibe ich hier und schließe den Thread dann.

**Comment by FabianHardt** [comment]
Die gesuchte Einstellung sollte sich in der Datei _public/css/tinymce/default.min.css_ finden.
Hier kann die Eigenschaft _background_ gesetzt werden.
Original sieht der Inhalt der Datei so aus:

`@import "../default.css";body{padding:8px;color:#333;background:#FFF}`

**Comment by mjmpeace** [comment]
Das habe ich auch gedacht - aber ich habe wohl irgend etwas verbogen. Das noch viel lustigere ist, dass der Editor in der englischen Version so funktioniert wie gewünscht. Nur in der deutschen Variante nicht - das habe ich noch gar nicht bemerkt - weil ich es nicht genutzt hatte,

**Comment by mjmpeace** [comment]
Der Eintrag aus der datenbank lässt sich auch über den Button rechts außen oben Quellcode aufrufen, aber es führt nicht zum Ziel, weil eine "graue Hintergrunddatei geladen wird. Woher die kommt, habe ich bis jetzt noch nicht gefunden, aber ich komme weiter.
Der Aufruf des Editors erfolgt über .../public/backend/config/info
Ich verstehe im Moment den Fehler so, dass er aus einer Datei kommt, die mit der Übersetzung ins Deutsche zu tun haben muss.
