### ISSUE TITLE
Allgemeine Texte ändern

### ISSUE THREAD

**Issue by chrismeitzler** [tkrebs/ep3-bs#48]
Hallo,

vielleicht eine blöde Frage, aber wie/wo kann ich die Standardtexte ändern? Z.B. bei der Registrierung?

**Comment by tkrebs** [comment]
Eine Möglichkeit wäre es, [die deutschen Übersetzungen](https://github.com/tkrebs/ep3-bs/tree/master/data/res/i18n/de-DE) bei Bedarf [mit eigenen Texten](https://github.com/tkrebs/ep3-bs/tree/master/data/res/i18n-custom/de-DE) zu überschreiben.

**Comment by chrismeitzler** [comment]
Super, vielen Dank! Das habe ich irgendwie übersehen.
