### ISSUE TITLE
Alle wöchentlichen Buchungen erscheinen als "Konflikt"

### ISSUE THREAD

**Issue by koehntopp** [tkrebs/ep3-bs#482]
Wir haben für Training und Mannschaften wöchentlich Plätze gebucht. In der Übersicht erscheinen die Konsequent als "Konflikt", ohne dass es erkennbare Terminüberschneidungen gibt.

Was machen wir da falsch?

![Bildschirmfoto 2021-05-30 um 11 25 02](https://user-images.githubusercontent.com/7113567/120099088-d7a2cf00-c139-11eb-8e54-ad927e7f3964.png)

**Comment by cbits68** [comment]
Wie sieht es denn mit den Kapazitäten pro Platz aus? Wenn da keine andere Buchung zeitgleich ist, dann kann es eigentlich nur sein, dass Ihr Mehr Spieler gebucht habt, als der Platz Kapazität hat.

**Comment by koehntopp** [comment]
Danke - das war das Problem!
