### ISSUE TITLE
Bestimmte Tage zum Buchen anbieten

### ISSUE THREAD

**Issue by berlinerbaer87** [tkrebs/ep3-bs#484]
Hallo,
gibt es eine möglichkeit nur bestimmte Tage zum buchen anzubieten zum beispiel nur Montag und Donnerstag,
weil das unsere Trainigstage sind

Liebe Grüße

**Comment by mjmpeace** [comment]
Unter Verhalten lassen sich Tage verstecken.

**Comment by berlinerbaer87** [comment]
Vielen Dank funktioniert wunderbar
