### ISSUE TITLE
Admin bucht für anderen Benutzer - sollte dieser Benutzer nicht eine EMail erhalten?

### ISSUE THREAD

**Issue by andyproko** [tkrebs/ep3-bs#485]
Mir war es so als ab wenn der Admin (Verwaltung) für einen Benutzer einen Platz bucht, dass dieser darüber eine EMail erhält.
Kann es sein, dass mit dem Update auf 1.7 dies nicht mehr der Fall ist?

Ich benutze speziellen Benutzer, e.g. Platz sperren wegen Platzpflege, ohne EMail Addresse, und erwarte entsprechendes Verhalten. 
Aber wenn eine EMail vorhanden ist, dann sollte die auch verwendet werden.

Ich habe mal in NotificationListener.php reingeschaut. Die einzigen Hinweise zu EMail verschicken sind "notification.bookings=true" für den Benutzer und "client.contact.email.user-notifications=true" für die Verwaltung.
Aber ich sehe nicht, dass ich darüber Kontrolle hätte.

**Comment by cbits68** [comment]
Der Versand von Mails an Benutzer, wenn Verwalter oder Mitarbeiter für diesen buchen oder stornieren ist im Standard nicht implementiert.
Es lässt sich aber im Code entsprechend umsetzen. siehe z.B. #418 für Stornierungen durch den Admin.

**Comment by andyproko** [comment]
@cbits68 ... danke dir .. werde es mal ausprobieren.

**Comment by andyproko** [comment]
EMail bei Stornierung durch Admin war wichtiger. Habe es gemäß Hinweis oben gelöst
