### ISSUE TITLE
Kalendernavigation

### ISSUE THREAD

**Issue by gitchristi** [tkrebs/ep3-bs#488]
Ich habe ein Problem mit der Kalendernavigation. Da wir in unserem Verein nur einmalig im Monat ein Training anbieten können, muss ich für jedes Jahr eine recht lange Liste an versteckten Tagen im Kalender pflegen (in unserem Fall alle Tage ausser Donnerstag und alle Donnerstage, die nicht der 4. Donnerstag im Monat sind). Durch ein paar minimale Codeanpassungen im CalendarController.php (in Zeile 59 und 78, Limits vergrößert) habe ich das Auswerfen von 2 RunTimeExceptions unterbinden können. Bei der Gelegenheit wäre anzumerken, dass die Meldung in Zeile 79 irreführend ist. Anstelle von "Too many days are hidden from calendar" sollte dort "Too many days to render in calendar" stehen.

Es sind in meinem Kalender jetzt nur noch 12 Tage im Jahr sichtbar. Leider funktioniert das Navigieren mit den Pfeiltasten im Kalender nicht mehr 100%ig. Die Vorwärtsnavigation (Pfeil rechts) funktioniert, es wird der jeweils nächste nicht versteckte Tag angezeigt. Ebenso funktioniert der "Heute" Knopf, der mich zum, vom aktuellen Datum aus gesehen, nächsten gültigen Termin bringt. Problematisch ist die Rückwärtsnavigation. Der Knopf mit dem Pfeil nach links funktioniert nicht. Daher würde ich ihn gern ausblenden. Kann jemand sagen, an welcher Stelle im Code man das bewerkstelligen kann. 

Danke. 
Christian

**Comment by FabianHardt** [comment]
Dies sollte recht einfach gehen in _module\Frontend\view\frontend\index\datepicker.phtml_.
Hier einfach die Zeile `<td><a href="<?= $previousDayUrl ?>" class="default-button symbolic symbolic-button"><div class="arrow-left"></div>&nbsp;</a></td>` löschen oder auskommentieren.

**Comment by gitchristi** [comment]
Vielen Dank Fabian, das hat mir einen Menge Sucherei erspart.
