### ISSUE TITLE
Mailversand an Hotmail-Adressen und Outlook - Adressen funktioniert nicht

### ISSUE THREAD

**Issue by mjmpeace** [tkrebs/ep3-bs#490]
Seit etwa 2 Monaten bekomme ich keine Mails aus dem System mehr heraus an Adressen @hotmail.com und Adressen mit @outlook.de oder @outlook.com 
Die Einträge in der local.php sind auf tls gesetzt mit Port 587
Andere Mailadressen funktionieren einwandfrei. Eine Registrierung mit einer Outlook.com-Adresse und anschließend damit gebucht, hat die Mail zu mir zwar gesandt, aber im Outlook-Postfach kommt nichts an. Es dauert dann einige Zeit, bis ich eine Fehlermail bekomme, dass die Mail nicht gesendet werden kann.
Der Provider hat schon einen Eintrag vorgenommen in der Domain, damit das klappen soll, aber auch das hat nicht geholfen.
Hat jemand eine Idee, was man ändern muss und wo? Es muss an der Kommunikation der Mailserver untereinander liegen.
Schicke ich die Mail mit meiner verwendeten Adresse im System aus Outlook vom PC läuft es einwandfrei.

**Comment by cbits68** [comment]
das passiert immer mal wieder bei hotmail, AOL & Co.
Die passen Ihre Filter/BlackLists an und wenn Deine Domain bzw. das SMTP Gateway Deines Providers dort drin steht, weil von dort gerade Spam, Pishing oder Ähnliches versendet wurden, dann nehmen die eine längere Zeit von dort keine Mails mehr an.
Von Deinem Outlook aus nutzt Du beim Mailversand ggf. ja auch andere Wege als über den SMTP Relay Deines Providers.

**Comment by mjmpeace** [comment]
Antwort meines Providers:
Da Sie die Mails derzeit direkt über Ihren Managed Server versenden und dieser nur TLS 1.0 unterstützt, kann es vorkommen, dass die Ziel-Mailserver diese Version von TLS nicht mehr akzeptieren und die Verbindung ablehnen. Wir empfehlen daher die Mails über unsere SMTP-Relays zu versenden. Diese unterstützen auch TLS 1.1 und 1.2.

Das bedeutet, ich müsste das anders konfigurieren im System in der Datei Mailservice.php - wie geht das?

**Comment by cbits68** [comment]
Du musst in der local.php einen anderen smtp server für den Mailversand eintragen.
Standardmäßig nutzt das Systerm sendmail für den Mailversand. Das scheint aber bei Dir offenbar nicht das aktuelle Verschlüsselungsprotokoll (TLS 1.2) zu nutzen.
Viele Provider (auch Strato) haben den Support für die älteren Protokolle (1.0 und 1.1) gerade abgeschaltet.
Ich musste meinen Eltern z.B. am Wochenende gerade neue Smartphones einrichten, da ältere Geräte bei imap und pop auch nur bis TLS 1.1 unterstützen. Mail auf den alten iPhones ging daher auch seit einigen Wochen nicht mehr.

**Comment by cbits68** [comment]
Alternativ kannst Du natürlich auch versuchen auf Deinem managed Server sendmail mit openssl so zu konfigurieren, dass es auch TLS 1.2 kann.

**Comment by mjmpeace** [comment]
> Du musst in der local.php einen anderen smtp server für den Mailversand eintragen.
> Standardmäßig nutzt das Systerm sendmail für den Mailversand. Das scheint aber bei Dir offenbar nicht das aktuelle Verschlüsselungsprotokoll (TLS 1.2) zu nutzen.
> Viele Provider (auch Strato) haben den Support für die älteren Protokolle (1.0 und 1.1) gerade abgeschaltet.
> Ich musste meinen Eltern z.B. am Wochenende gerade neue Smartphones einrichten, da ältere Geräte bei imap und pop auch nur bis TLS 1.1 unterstützen. Mail auf den alten iPhones ging daher auch seit einigen Wochen nicht mehr.

Das habe ich alles ausprobiert - es klappt nicht - die Mails werden abgewiesen von den Microsoft-Servern. Aber nur dort. Kein anderer Provider hat damit Schwierigkeiten. Was ich nicht genau verstehe bei dem System ist folgendes:
Wenn ich die gleichen Einträge wie in Outlook mache und mit Outlook klappt das versenden, wieso klappt es nicht aus dem Buchungssytem? gibt es irgendwo anders noch Einstellungen, die verbogen werden müssen, damit eben nicht der Mail-Service des Webservers verwendet wird sondern die Mails so versendet werden wie aus Outlook über den Mailserver des Providers.
Im Ordner "Mail" des Frameworks gibt es ja noch diverse Dateien mit Einstellungen, ist dort irgendwo das Problem zu finden? Wer kann helfen?

**Comment by mjmpeace** [comment]
Schade, dass mir hier nicht geholfen wird. Ich habe jetzt gefunden, dass im Verzeichnis
/.../vendor/zendframework/zendframework/library/Zend/Mail/Protocoll
die Dateien den Hinweis enthalten, dass Default der Host 127.0.0.1 genommen wird. Das muss ich ändern, aber in welcher Datei genau, denn der Eintrag in der local.php zeigt keine Wirkung. Das bedeutet man muss es hier irgendwo ändern, weil die Anweisung aus der local.php ignoriert wird.

**Comment by mjmpeace** [comment]
Ich ergänze dazu: nach dem Wechsel auf einen modernen 64bit Server klappt der Versand. Aber der Header der Mails lässt erkennen, dass der Versand der Mails letztendlich direkt vom Webserver und nicht vom ausgewählten SMTP Server erfolgt aufgrund der Einstellungen im Zenframework.

**Comment by cbits68** [comment]
Bist Du sicher, dass Du in der local.php SMTP noch konfiguriert hast, oder hast Du vielleicht jetzt sendmail für den Mailversand konfiguriert?
Sendmail mach nämlich genau das...

**Comment by mjmpeace** [comment]
Da steht smtp-tlsVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: anborn ***@***.***> Datum: 27.02.22  15:01  (GMT+01:00) An: tkrebs/ep3-bs ***@***.***> Cc: mjmpeace ***@***.***>, State change ***@***.***> Betreff: Re: [tkrebs/ep3-bs] Mailversand an Hotmail-Adressen und Outlook -
  Adressen funktioniert nicht (#490) 

Bist Du sicher, dass Du in der local.php SMTP noch konfiguriert hast, oder hast Du vielleicht jetzt sendmail für den Mailversand konfiguriert?

Sendmail mach nämlich genau das...

**Comment by cbits68** [comment]
Aber selbst bei SMTP steht doch die Absenderadresse des Clients (in dem Falle Dein Server) im Header der Mail vor dem SMTP Gateway. 
Kannst mir ja mal den Header kopieren und per Mail senden...
