### ISSUE TITLE
Wöchentliche Buchung für zwei Plätze wird unterschiedlich angezeigt

### ISSUE THREAD

**Issue by MarcusThiel** [tkrebs/ep3-bs#494]
Moin, ich habe hier das etwas seltsame Problem (das ich in einer älteren ep3 Installation nicht hatte) das ich zum Blocken die gleiche Buchung für zwei Plätze gemacht habe, allerdings wird sie unterschiedlich angezeigt, einmal auf Platz 1 korrekt und einmal auf Platz 2 als "Abo" .... woran kann das liegen, eingetragen ist der selbe Text wie auf Platz 1.
<img width="507" alt="Bildschirmfoto 2021-07-08 um 21 21 15" src="https://user-images.githubusercontent.com/86321305/124981658-1af43580-e036-11eb-910f-d917ca79509e.png">

**Comment by MarcusThiel** [comment]
übrigens eingetragen als Admin, als das Photo entstanden ist war ich "privat" eingeloggt.

**Comment by cbits68** [comment]
schau mal bei den Einstellungen von Platz 2. Da hast Du wahrscheinlich bei der Sichtbarkeit von Namen "Keine" eingetragen.

**Comment by MarcusThiel** [comment]
Danke, das war es !!!
