### ISSUE TITLE
An exception was raised while creating "DateFormat"; no instance returned

### ISSUE THREAD

**Issue by Airtracer** [tkrebs/ep3-bs#5]
Hallo Tobias,

ich krieg hier noch graue Haare:
Nach der Installation lief soweit alles glatt, bis dann folgende Meldung erscheint:

"Oops ... da ist wohl etwas schief gelaufen
An exception was raised while creating "DateFormat"; no instance returned"

Ich habe den anderen, älteren Thread gelesen, der hilft mir aber nicht weiter, weil ich nicht glaube, dass es an der sog. "php_intl" liegen kann, da meine Datenbank auf einem Apache Server bei Strato  liegt und ich im phpadmin zig hundert Sprachen zur Auswahl habe...
Daher finde ich auch keine php.ini auf meinem Server.

Hier die Daten meines Servers:

Datenbank-Server

Server: rdbms via TCP/IP
Server-Typ: MySQL
Server Version: 5.5.42-log - Source distribution
Protokoll-Version: 10
Benutzer: UXXXXXXX@oomforafor.store
Server Zeichensatz: UTF-8 Unicode (utf8)

Webserver
Apache/2.2.29 (Unix)
Datenbank-Client Version: libmysql - 5.0.96
PHP-Erweiterung: mysqli Dokumentation

Meine local.php wie folgt:
<?php
/**
- Local application configuration
  *
- Insert your local database credentials here
- and provide the email address the system should use.
  */

ini_set('date.timezone', 'Europe/Berlin');

return array(
    'mail' => array(
        'type' => 'sendmail',
        'address' => 'info@aeroclub-hof.de',
    ),
    'db' => array(
        'user' => 'UXXXXX',
        'pass' => 'aXXXXX',
        'dsn' => 'mysql:dbname=DBXXXXXXX;host=rdbms.strato.de',
    ),
    'i18n' => array(
        'locale' => 'de-DE',
        'currency' => 'EUR',
    ),
);

Gibts denn keine andere Variante der Datenbank das korrekte Datum/Zeitzone mitzuteilen???
Z.B. ohne die Zeitzonen Funktion sondern über eine andere Date-Time Funktion???

Danke,

Thomas

**Comment by tkrebs** [comment]
Hallo Thomas,

es liegt tatsächlich an der fehlenden PHP-Erweiterung intl. Die wird nicht für die Datenbank, sondern für die Übersetzung(en) des Systems benötigt. Und die kann man bei SharedHosting-Anbietern in den seltensten Fällen selber nachinstallieren.

Eventuell lockere ich die Abhängigkeit in der nächsten Version. Derzeit ist sie aber leider zwingend notwendig.

Viele Grüße
Tobias Krebs

**Comment by Airtracer** [comment]
Hallo Tobias,

danke für die Infos...
Es ist frustierend:
Jetzt habe ich endlich die passende Buchungssoftware für unsere Zwecke gefunden (Flugzeugreservierung) und als NIcht-php-ler soweit erfolgreich auf dem Server instalöliert und jetzt liegts einzig und allein am Datumsformat... *Schreikrampf krieg - Nacht um die Ohren geschlagen*

Ich hoffe bloß, dass Du bald daran was änderst, weil das geht sicherlich auch einfacher mit der Datumseinstellung siehe Wordpress, was ja auch auf meinem Server in der 2. Datenbank läuft...

Grüße,
Thomas

**Comment by Airtracer** [comment]
Hallo Tobias,

ich habe mal per php info meinen Server ausgelesen. bzgl. date-Einstellungen sind folgende Daten hinterlegt:

date

date/time support	enabled
"Olson" Timezone Database Version	2015.1
Timezone Database	internal
Default timezone	MET

Directive	Local Value	Master Value
date.default_latitude	31.7667	   31.7667
date.default_longitude	35.2333	   35.2333
date.sunrise_zenith	        90.583333  90.583333
date.sunset_zenith	        90.583333  90.583333
date.timezone	                no value	   no value

Frage:
Lässt sich der letzte, relevante Wert auch ohne php_intl einstellen?
Schließlich ist date/time Support eingeschaltet!

Gruß,
Thomas

**Comment by tkrebs** [comment]
Ich fürchte, die Fehlermeldung ist etwas irreführend. Auch wenn sie von "DateFormat" spricht, geht es eigentlich überhaupt nicht um die Einstellung der Zeit / Zeitzone, sondern schlichtweg darum, dass ein Bestandteil der intl-Erweiterung für die weitere Funktionsweise fehlt.

**Comment by tkrebs** [comment]
Ich habe gerade nochmal nachgesehen, die intl-Erweiterung ist leider zwingend notwendig, und zwar von Seiten des zugrundeliegenden Zend Framework 2. Darauf habe ich keinen Einfluss.
