### ISSUE TITLE
Show price in the Booking-Administration

### ISSUE THREAD

**Issue by MrSesame** [tkrebs/ep3-bs#50]
Hey,
I'm trying to include the price indication of a booking into the table in the Booking-Administration:
file: module > Backend > src > Backend > View > Helper > Booking > BookingFormat.php

**In the Booking-Administration table you can see:**
- "No." = booking ID --> `$booking->need('bid'));`
- "Name" = user name --> `$booking->getExtra('user')->get('alias');`
- "Day" / "Date" / "Time" ...
- "room" = room name --> `$this->squareManager->get($booking->get('sid'))->get('name');`

Any suggestions how I can add a column with the price? I guess, I need to add BillManager somehow... Or BillTable?

Thankful for any hints :)
btw: ep-3 rocks!

**Comment by tkrebs** [comment]
You need the BillManager [like here](https://github.com/tkrebs/ep3-bs/blob/master/module/User/src/User/Controller/AccountController.php#L405).

Once you have all the bill objects, you just need to sum them up [like here](https://github.com/tkrebs/ep3-bs/blob/master/module/User/view/user/account/bills.phtml#L42).
