### ISSUE TITLE
Help me  / Option service.calendar.days does not exist

### ISSUE THREAD

**Issue by Mamkie1980** [tkrebs/ep3-bs#506]
How do I do step 3.? 3. Setup the database by calling the setup.php  If you can help me, I am new to this.

and how do I solve the problem ¨Option service.calendar.days does not exist¨

**Comment by cbits68** [comment]
I think it would be very helpfull, if you post a little bit more information ;.)
Your information regarding your issue is like " my car is not driving, i just got my driving license. how do I solve the problem " engine is not starting"
you should at least post information about:
your environment you try to install ep3-bs on, like database, php version, the webhoster or your config if you use an own server, ...
the steps you have processed until the error occures, ...

otherwise the answer will be, try to start the engine of your car again, by turning the key. ;-)

**Comment by Mamkie1980** [comment]
The error is this:
Oops ... something went wrong here
Option service.calendar.days does not exist
Please drop us a note in case of unexpected error messages,
so that we can repair them quickly.

Back to front page
Exception details
Type
RuntimeException
Message
Option service.calendar.days does not exist
File

/Users/maonanis/Site/ep3/module/Base/src/Base/Manager/OptionManager.php:172
Stack trace
#0 /Users/maonanis/Site/ep3/module/Base/src/Base/Controller/Plugin/Option.php(20): Base\Manager\OptionManager->get('service.calenda...', false)
#1 [internal function]: Base\Controller\Plugin\Option->__invoke('service.calenda...', false)
#2 /Users/maonanis/Site/ep3/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(318): call_user_func_array(Object(Base\Controller\Plugin\Option), Array)
#3 /Users/maonanis/Site/ep3/module/Calendar/src/Calendar/Controller/CalendarController.php(20): Zend\Mvc\Controller\AbstractController->__call('option', Array)
#4 /Users/maonanis/Site/ep3/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(84): Calendar\Controller\CalendarController->indexAction()
#5 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#6 /Users/maonanis/Site/ep3/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#7 /Users/maonanis/Site/ep3/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#8 /Users/maonanis/Site/ep3/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(116): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#9 /Users/maonanis/Site/ep3/vendor/zendframework/zend-mvc/src/Controller/Plugin/Forward.php(143): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#10 /Users/maonanis/Site/ep3/module/Frontend/src/Frontend/Controller/IndexController.php(13): Zend\Mvc\Controller\Plugin\Forward->dispatch('Calendar\\Contro...', Array)
#11 /Users/maonanis/Site/ep3/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(84): Frontend\Controller\IndexController->indexAction()
#12 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#13 /Users/maonanis/Site/ep3/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#14 /Users/maonanis/Site/ep3/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /Users/maonanis/Site/ep3/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(116): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#16 /Users/maonanis/Site/ep3/vendor/zendframework/zend-mvc/src/DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#17 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#18 /Users/maonanis/Site/ep3/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#19 /Users/maonanis/Site/ep3/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#20 /Users/maonanis/Site/ep3/vendor/zendframework/zend-mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#21 /Users/maonanis/Site/ep3/public/index.php(66): Zend\Mvc\Application->run()
#22 {main}

----------------------
Step 3 I don't know how to do it, if you can help  / 3. Setup the database by calling the setup.php 

My settings

/Users/maonanis/Site/ep3/config/autoload/local.php 

<?php
/**
 * Local application configuration
 *
 * Insert your local database credentials here
 * and provide the email address the system should use.
 */

return array(
    'db' => array(
        'database' => 'ep3-bs',
        'username' => 'root',
        'password' => 'Mamkie1980+',

        'hostname' => 'localhost',
        'port' => null,
    ),
    'mail' => array(
        'type' => 'smtp', // or 'smtp' or 'smtp-tls'
        'address' => 'tennisalameda@gmail.com',
            // Make sure 'bookings.example.com' matches the hosting domain when using type 'sendmail'

        'host' => 'smtp.gmail.com', // for 'smtp' type only, otherwise remove or leave as is
        'user' => 'tennisalameda@gmail.com', // for 'smtp' type only, otherwise remove or leave as is
        'pw' => 'Mamkie1980', // for 'smtp' type only, otherwise remove or leave as is

        'port' => '587', // for 'smtp' type only, otherwise remove or leave as is
        'auth' => 'true', // for 'smtp' type only, change this to 'login' if you have problems with SMTP authentication
    ),
    'i18n' => array(
        'choice' => array(
            'en-US' => 'English',
            'de-DE' => 'Deutsch',

            // More possible languages:
            // 'fr-FR' => 'Français',
            // 'hu-HU' => 'Magyar',
        ),

        'currency' => 'EUR',

        // The language is usually detected from the user's web browser.
        // If it cannot be detected automatically and there is no cookie from a manual language selection,
        // the following locale will be used as the default "fallback":
        'locale' => 'de-DE',
    ),
);

the database is in phpmyadmin

**Comment by cbits68** [comment]
Ok, looking at your lokal.php setting, i dont belive that the database credentials are correct. You have to fill in database user, password and port to the database you have to setup prior to start the setup.
I think you entered credentials for the root user on OS Level and not the database user.

YOU CANNOT START THE ENGINE OF YOUR CAR WITH THE WRONG KEY

**Comment by cbits68** [comment]
And it will not Start without an engin! Please create the database first with MySQL or mariadb.
The you can configure access to the db  in local.php

**Comment by mjmpeace** [comment]
I had the same problem. Sometimes not all tables in the sql database ist correkt created. I would give the advice to start the installation with a clean new DB again.

**Comment by Mamkie1980** [comment]
I already solved it, thanks
