### ISSUE TITLE
Help me / How do I configure gmail

### ISSUE THREAD

**Issue by Mamkie1980** [tkrebs/ep3-bs#509]
How do I configure gmail mail in local.php file?, I have not been able to configure it.

My local.php

<?php
/**
 * Local application configuration
 *
 * Insert your local database credentials here
 * and provide the email address the system should use.
 */

return array(
    'db' => array(
        'database' => 'ep3-bs',
        'username' => 'root',
        'password' => '********',

        'hostname' => 'localhost',
        'port' => null,
    ),
    'mail' => array(
        'type' => 'smtp', // or 'smtp' or 'smtp-tls'
        'address' => 'tennisalameda@gmail.com',
            // Make sure 'bookings.example.com' matches the hosting domain when using type 'sendmail'

        'host' => 'smtp.gmail.com', // for 'smtp' type only, otherwise remove or leave as is
        'user' => 'tennisalameda@gmail.com', // for 'smtp' type only, otherwise remove or leave as is
        'pw' => '********', // for 'smtp' type only, otherwise remove or leave as is

        'port' => '587', // for 'smtp' type only, otherwise remove or leave as is
        'auth' => 'plain', // for 'smtp' type only, change this to 'login' if you have problems with SMTP authentication
    ),
    'i18n' => array(
        'choice' => array(
            'en-US' => 'English',
            'de-DE' => 'Deutsch',

            // More possible languages:
            // 'fr-FR' => 'Français',
            // 'hu-HU' => 'Magyar',
        ),

        'currency' => 'EUR',

        // The language is usually detected from the user's web browser.
        // If it cannot be detected automatically and there is no cookie from a manual language selection,
        // the following locale will be used as the default "fallback":
        'locale' => 'en-US',
    ),
);

**Comment by cbits68** [comment]
Google only offers encrypted connection to smtp.gmail.com. For Port 587 TLS (smtp-tls) is required. 
You should not post your credentials to access your mail account on google here ;-)

**Comment by tkrebs** [comment]
As cbit68 wrote: If the posted passwords are your actual passwords, please change them immediately!
I also removed them from your post, though they are still visible in editing history.

**Comment by Mamkie1980** [comment]
Dankeschön
