### ISSUE TITLE
Wartungsmodus verlassen?

### ISSUE THREAD

**Issue by jensluebbehusen** [tkrebs/ep3-bs#512]
Liebe Community,

leider bin ich gerade "gefühlt zu blöd". Ich habe das System auf Wartung gesetzt um einige Dinge zu verändern und jetzt gibt es kein Log-In-Button mehr. Eine direkte URL habe ich in der Doku nicht gefunden, oder übersehen...

Bitte um Hilfe!

**Comment by dmscholz** [comment]
Hey, versuch mal `/public/user/login` oder nur `/user/login` aufzurufen (#264)

**Comment by jensluebbehusen** [comment]
Danke!!! Das hat geholfen!
