### ISSUE TITLE
Logo in email

### ISSUE THREAD

**Issue by wxx13** [tkrebs/ep3-bs#515]
Hallo, 
ich würde gerne ein Vereinslogo in der Buchungs E-Mail mitsenden.
Hat jemand eine Idee wo ich das bewerkstelligen kann?

**Comment by svenatdigitalai** [comment]
Hallo,

Das ist (wenn ich das richtig sehe im Code) Stand heute nicht möglich, dafür müsste man den Code ändern.

Ich bastele für meinen Verein gerade an ein paar Erweiterungen zum Thema email, vielleicht könnte ich das damit abdecken. Wird aber noch ein paar Wochen dauern.
Gruß,
Sven
