### ISSUE TITLE
City name and housenumber

### ISSUE THREAD

**Issue by htelser** [tkrebs/ep3-bs#52]
there exist cities where a dot is in the name, like St. Andrä Wördern, but this name is not allowed, so I extended the pattern for rf-city in module/User/src/User/FormRegistrationForm.php to following

`'pattern' => '/^([ \&\'\(\)\-\x{00c0}-\x{01ff}a-zA-Z\.])+$/u',`

Also housenumbers with / are not allowed, but at least here in Austria we are using housenumbers like 23/3 and so on. So the pattern for rf-number in module/User/src/User/FormRegistrationForm.php should look like this
`'pattern' => '/^([0-9a-zA-Z\.\-\/])+$/u',`

**Comment by tkrebs** [comment]
I have added these two modifications in the develop branch, thank you!
