### ISSUE TITLE
Buchungen von 1 Jahr von eine bestimmte User löschen

### ISSUE THREAD

**Issue by Bakati** [tkrebs/ep3-bs#523]
Hallo an alle,
da eine User sehr viele Buchungen hat möchte ich von 2020 alle Buchungen von diese User löschen. Bitte könnt ihr mir sagen Welche Tabellen und auch wenn möglich den dazugehörigen Befehl um die Datensetze zu löschen.
Vielen Dank im Voraus

**Comment by cbits68** [comment]
Ich könnte mir vorstellen, das es über Export und Import umsetzbar wäre.
Die Buchungen des Users müssten in den Tabellen bs_bookings_..., bs reservations_... und falls auch Verrechnung bei Euch erfolgt die bs_bookings_bills  gespeichert sein.
Wenn Du die Buchungen identifiziert hast, müssen diese aus der exportierten Datei (SQL) gelöscht und dann später wieder in die DB importiert werden.
Ich halte das allerdings für sehr aufwändig und auch gefährlich.
Ich mache das in der Regel so, dass ich am Ende der Saison alle Buchungen lösche und die neue Saison dann mit einer leeren Basis starte.  siehe #407
Vorher exportiere ich die Tabellen so, dass ich in Excel immer noch alle vergangenen Buchungen der letzten Saison nachvollziehen kann und auch Statistiken über Platzauslastungen, ... mittels SVERWEIS & Pivot in Excel machen kann.

Gruß
Cbits

**Comment by Bakati** [comment]
Vielen Dank. Werde genau so machen. 
Schönen Tag LG
