### ISSUE TITLE
Update von 1.6 auf 1.7.0

### ISSUE THREAD

**Issue by chrismeitzler** [tkrebs/ep3-bs#525]
Hallo,

wir nutzen aktuell leider noch die Ver. 1.6.
Muss ich für ein Update auf 1.7.0 alle Versionen der Reihe nach installieren oder kann ich auch direkt den Sprung von 1.6 auf Ver. 1.7.0 wagen?

**Comment by cbits68** [comment]
in der 1.7.0 sind ja auch die Änderungen der vorherigen Versionen enthalten .  Wichtig ist, dass Du dann die passende PHP Version nutzt. Ein Update Wagen solltest Du generell nur mit einem entsprechend Backup Deiner Installation und der Datenbank. Wenn Du nicht über github updatest, solltest Du wissen, dass selbst durchgeführte Änderungen am Code dann weg sind und ggf. manuell wieder nachgezogen werden müssen.
Viel Erfolg

**Comment by mjmpeace** [comment]
> ...über github updatest...
Ich habe Updates noch nie mit Github gemacht. Gibt es dazu irgendwo eine Hilfe zum reinlesen?

**Comment by cbits68** [comment]
zum GitHub "Mechanismus" gibt es massenhaft Doku im Internet. Der ist nicht ep3-bs spezifisch, bis auf  die "fork". Google hilft da ;-)
Wichtig ist aber, man muss die Installation  schon mit GitHub durchführen, sonst geht auch alles Andere nicht.
Das einzig aufwändigere ist, die Abhängigkeiten müssen mittels Composer selbst generiert werden, das ist bei der Paket Downloadvariante eben schon passiert und enthalten,.
Der große Vorteil ist eben, dass Du im lokalen Code Änderungen vornehmen kannst, die dann bei einem Update des master repository über GitHub nicht einfach überschrieben werden und due kannst immer sehen, was bei Dir anders ist als im master branch.
Man muss sich damit aber schon beschäftigen und es verstehen, damit es hinterher auch wirklich funktioniert ...
