### ISSUE TITLE
EoL PHP 7.4 November 2022

### ISSUE THREAD

**Issue by cbits68** [tkrebs/ep3-bs#526]
Hallo Tobias, Hi All,
eigentlich kein dringendes Issue, aber schon mal die Frage, wie die Entwicklung bis November geplant ist.
Die Sommersaison wird man ja noch gut mit der aktuellen ep3-bs Version 1.7. arbeiten können.
Nach dem 28.11.2022 ist dann PHP 7.4 auch End of life. Also wird dann auch keinen Security Support mehr haben.
Ich gehe davon aus, dass dann die Webhoster auch die 7.4 abschalten werden und nur noch 8.0 bzw. 8.1 anbieten werden.
Mich würde daher mal interessieren ob es realistisch ist, dass bis Ende November noch mit einer PHP 8 kompatiblen Version von ep3-bs zu rechnen ist.
Ich würde ungern kurz vorher erst nach Alternativen suchen müssen.
Leider konnte ich weder auf der ep3-bs Website noch hier auf github Informationen zum aktuellen Stand bzw. zur Planung der Weiterentwicklung finden.
Du hattest mir ja mal geschrieben, dass Ihr an einem "grunderneuerten" Release arbeitet, da ja auch Zend Framework nicht mehr weiterentwickelt wird, bzw. mit dem Laminas Projekt eine neue PHP Framework unter der Linux Foundation entstanden ist.
Kannst Du mir/uns ein kurzes Update geben, was geplant und wie der aktuelle Stand ist?
Falls Freiwillige zum Testen gesucht werden, bin ich gern dabei.
Spätestens Ende des Sommers muss ich ohnehin auf PHP 8 umstellen, da ich in meinem Webhosting Paket nur eine PHP Version einstellen kann und durch Update auf Joomla 4 dann auch "muss".

Gruß
Cbits

**Comment by tkrebs** [comment]
Ich denke, die Umstellung auf PHP 8 wird mit der gleichen Strategie wie bei PHP 7.4 relativ gut möglich sein.

Das wird voraussichtlich auch bei unserem Verein nötig werden. Die neue Version des Buchungssystems befindet sich zwar nach wie vor in Entwicklung, derzeit setzen wir aber auch noch die Version 1.7 ein.

**Comment by mjmpeace** [comment]
> Ich denke, die Umstellung auf PHP 8 wird mit der gleichen Strategie wie bei PHP 7.4 relativ gut möglich sein.

Was bedeutet das konkret in der Umsetzung. Ich habe zwei Baustellen inzwischen:
1. Hallenbuchungssystem ist noch nicht 1.7 und müsste ein Update bekommen, das will ich im Sommer machen, wenn die Halle wenig gebucht wird.
2. Der Webserver muss umziehen und ich bekomme dann nur noch MariaDB und habe Angst, dass dann die beiden Buchungsssysteme Probleme machen. Laut Hoster ( Domain Factory) haben wir keine speziellen Sachen, so dass das gehen müsste. Das Außenplatzbuchungsssstem ist 1.7 - hat jemand schon Erfahrung mit einem Umzug zu einem Server mit MariaDB gemacht? Klappt das?

**Comment by cbits68** [comment]
MariaDB funktioniert auch gut! Damit läuft mein lokales Testsystem. Daten kannst Du problemlos mittels SQL Export und Import übertragen.

**Comment by mjmpeace** [comment]
> MariaDB funktioniert auch gut! Damit läuft mein lokales Testsystem. Daten kannst Du problemlos mittels SQL Export und Import übertragen.

Danke - das ist gut zu hören. Dann werde ich erstmal den Serverwechsel machen. Ist überfällig, weil der Mailversand Probleme mit dem alten Server macht an bestimmte Empfänger. Ich werde mal berichten, wenn es gelaufen ist.

**Comment by cbits68** [comment]
Freue mich schon auf Deinen Bericht ;-)
Denk daran, dass dann neben der Anpassungen für den DB Zugriff in der local.php auch die php Version passen sollte.
Ich habe beim Kopieren der Daten auf einen anderen Server auch mal das cache Verzeichnis löschen müssen, da dort auch  noch der alte DB Zugang hinterlegt war.

**Comment by tkrebs** [comment]
Siehe https://github.com/tkrebs/ep3-bs/issues/563#issuecomment-1270960738
