### ISSUE TITLE
maximale Anzahl eines Produkts

### ISSUE THREAD

**Issue by ilouHD** [tkrebs/ep3-bs#527]
Hallo zusammen,

wir wollen unser Angebot bei uns im Tennisclub erweitern und wollen dafür ein Produkt (Ballmaschine) anlegen. Jetzt kann die Ballmaschine allerdings nur auf max. 1 Platz gleichzeitig gebucht werden.

Ich habe dazu jetzt ein Produkt angelegt und angegeben, dass man max. 1 auswählen kann. Wenn ich die Ballmaschine jetzt aber auf einem Platz buche und anschließend versuche, diese auch auf einem anderen Platz zu buchen, kann ich diese erneut buchen. Ist es möglich zu verhindern, dass man die Ballmaschine buchen kann, wenn diese bereits auf einem anderen Platz im Einsatz ist?

**Comment by cbits68** [comment]
Leider kannst Du aktuell Produkte nur auf einen Platz beschränken, dann ist es allerdings auch nur für diesem Platz verfügbar.
Ich würde die Ballmaschine dann eher als zusätzlichen "Platz" mit Kapazität 1 anlegen. Das hat auch den Vorteil, das Buchende im Kalender gleich sehen können, ob die Ballmaschine in der gewünschten Zeit noch frei ist.

**Comment by ilouHD** [comment]
Das dachte ich mir fast. Einen eigenen Platz dafür anzulegen war auch schon ne erste Überlegung, dann werden wir das wohl so umsetzen. Danke
