### ISSUE TITLE
Unterstützung

### ISSUE THREAD

**Issue by PaulusII** [tkrebs/ep3-bs#529]
Hallo zusammen,

wir sind ein kleiner Verein und nutzen das Buchungssystem. Die Buchungsseite läuft bei Strato.
Jetzt wird ja auch hier eine Änderung PHP notwendig. Und jetzt geht leider nichts mehr. Leider haben wir im Verein niemanden der sich damit auskennt.
Wenn jemand Interesse hat uns zu helfen, bitte melden.

Grüße Mike

**Comment by zandchyl** [comment]
Hallo Mike,

kannst du vielleicht noch ein paar Details nachliefern? Welche Version des Buchungssystem habt ihr installiert? Welche PHP Version habt ihr neu, welche vorher? Dann kann vielleicht jemand konkrete Hilfe anbieten.

Viele Grüße

Christian

**Comment by PaulusII** [comment]
OK, dann hier noch die Infos die ich zusammenbekomme. PHP ist bisher 7.3. Die kostet aber bald einiges an Geld. Wir hätten gerne 8.0 oder 8.1 wenn das geht. Aber auch mit 7.4 geht es nicht richtig.
Welche Version wir haben weiß ich nicht. Im Einsatz ist es seit Mitte 2020. 

Grüße Mike

**Comment by zandchyl** [comment]
Wir benutzen aktuell PHP 7.4 und das Buchungssystem 1.7.0. Sas läuft super und ist auch bis November 2022 vom PHP Support kein Problem. 

Bis dahin wird das Buchungssystem wohl auch fit für PHP 8.0 bzw. 8.1 gemacht.

Ich hätte vermutlich erst das Buchungssystem auf den neusten Stand gebracht, sprich 1.7.0 und dann PHP auf 7.4 umgestellt.

**Comment by PaulusII** [comment]
Danke für die schnelle Antwort.
Aber dann habe ich schon das nächste Problem. Wie mache ich das dem Umstellen auf 1.7.0.

**Comment by cbits68** [comment]
Hallo PaulusII,
ich habe auch das ep3-bs Buchungssystem für unseren Verein bei Strato gehostet.
Idealerweise habe ich das Buchungssystem über GitHub installiert und nicht das "fertige" Zip Paket genutzt.
Dadurch konnte ich recht einfach das update auf die 1.7.0 machen und damit auch bei Strato auf php 7.4 umstellen.
Ich vermute mal bei Euch wurde das Paket installiert.
Wenn keine großartigen Anpassungen an  dem Code gemacht wurden. sollte es nicht so problematisch sein die 1.7.0 darüber zu bügeln und dann die Konfigurationsdateien (DB Zugriff, Mail, ...) wieder anzupassen.
Ist aber ein wenig Fummel Arbeit und das Wichtigste ist: BACKUP, BACKUP, BACKUP!!!!

**Comment by cbits68** [comment]
Und das ALLERWICHIGSTE ist BACKUP ;-)

**Comment by cbits68** [comment]
Sowohl, das Backup der Dateien wie auch der Datenbank macht ja Strato automatisch. aber man sollte sich die Backups auch nochmal lokal sichern.

**Comment by cbits68** [comment]
Ich würde wie folgt vorgehen:
1. Webroot Verzeichnis löschen (nach Backup)
2. neue Datenbak erstellen
3. ep3-bs über GitHub installieren mit der neuen Datenbank
4. danach Konfigdateien umstellen auf die alte Datenbank und Anpassungen aus der alten init.php im config Verzeichnis nachziehen
5. dann php 7.3 auf 7.4 umstellen
6. Als admin an ep3-bs anmelden und ggf. Anpassungen machen.

**Comment by PaulusII** [comment]
Danke cbit68. Aber ich bin da wirklich blank und werde das nicht hinbekommen.
Wenn das jemand für uns erledigen könnte, wäre das super.

**Comment by cbits68** [comment]
Verstehe,. Mir fehlt leider die Zeit das für Euch zu machen, helfe aber gern bei Fragen , wenn Ihr Jemanden gefunden haben solltet. Möglichst auch eine Person, die sich dann auch künftig um Euer Buchungssystem kümmern kann, denn die nächste Umstellung steht ja voraussichtlich Ende des Jahres schon an. Strato wird laut Ankündigung auch den Support für php 7.4  im Frühjahr 2023 nur noch kostenpflichtig anbieten.

**Comment by PaulusII** [comment]
7.3 wird ja auch kostenpflichtig angeboten. Wenn man das dort abschließt, ist dann dann für eine dauerhafte Nutzung? Weißt du das zufällig.
Sollte ich jemanden finden der das für kleines Geld macht (sind ein kleiner Verein) würde ich aber gerne auf dein Angebot zurück kommen. Vielleicht überlegst du dir es ja nochmal

**Comment by cbits68** [comment]
Hier findest Du alle Infos zum Extended Support von php bei Strato:
https://www.strato.de/blog/php-extended-support-fuer-php-7-3/
Der Aufwand für die Umstellung auf die ep3-bs Version ist aber maximal 4-5 Tage, je nachdem ob derjenige der es bei Euch mal installiert hat eigene Anpassungen für Euren "kleinen Verein" gemacht hat.
Ist Bei Euch die ep3-bs 1.64 installiert, oder sogar noch eine ältere Version? Auch davon hängt der Aufwand ggf. ab um auf die 1.7.0 zu kommen.

Ich selbst kümmere mich seit vielen Jahren um die Vereinshompage unseres Vereins und auch um das Buchungssystem. Momentan steht ein großes Update für unsere Homepage auf Joomla 4 an, weshalb ich auch nur sehr wenig Zeit neben Beruf, Familie, Hund und Tennis habe ;-)

**Comment by PaulusII** [comment]
Installiert haben wir es Mitte 2020. Aber welche Version das ist, weiß ich nicht.
Wenn das mit der monatlichen 7,81€ dauerhaft gehen würde wären wir bei unter 100€ im Jahr. Das würde der Vorstand sicherlich machen. Immerhin muss ja mit jedem Wechsel immer Anpassung nötig. Die Kosten von einen externen Webdesigner sind ja auch nicht ohne.

**Comment by cbits68** [comment]
damit verschiebst Du das Problem allerdings nur und löst es nicht.
Es gibt End of Live Versionen nicht mehr bzw. nur mit extremer Zeitverzögerung Sicherheitspatches.
Da Ihr ja als Verein auch der Datenschutzgrundverordnung unterliegt und ja auch Personenbezogene Daten der Mitglieder verarbeitet, könnte es theoretisch auch dazu führen dass diese Daten durch eine Sicherheitslücke an Dritte geraten. Das kann teuer werden, insbesondere wenn Ihr bewusst veraltete Softwareversionen einsetzt, ist das sogar fahrlässig!
Ich arbeite bei einem großen IT Dienstleister und kann Dir daher sagen, das dafür sogar Geschäftsführer und Vorstände ggf. persönlich haftbar sind. Das sollte Euer Vorstand auch berücksichtigen ...

**Comment by PaulusII** [comment]
Ja, die DSGVo ist immer Thema.
Die Daten haben wir schon deutlich reduziert. Also ohne Adresse etc. Und Aufräumen tuen wir regelmäßig.
Aber du hast Recht, aber wir brauchen die Zeit. Wenn wir gleich den Sprung auf 8.1 machen könnten wäre das gut.

**Comment by cbits68** [comment]
Ich drücke Euch die Daumen, dass Ihr schnell jemanden findet. Habt Ihr nicht einen "IT Spezi" im Verein, oder Studenten/Schüler die sich da einbringen könnten?

**Comment by PaulusII** [comment]
Ich frag gerade rum. Vielleicht findet sich ja jemand.

**Comment by cbits68** [comment]
Wenn Ihr jemanden finden solltet, meldet Eich gern,
Die Person muss auch nicht programmieren können! Wichtig ist ein Grundversändniss, wie man man mit sftp  (z.B. FileZilla) auf das Strato Webrootverzeichnis zugreifen kann, und mit einem Editor (z.B. Notepad++) Dateien editieren kann.
Was das Backup und die Datenbank angeht braucht Ihr den Zugriff auf Euer Strato Paket über das Strato Kunden Login.
Bei Strato sind sehr gute Beschreibungen zu den meisten Themen im Hilfebereich hinterlegt.

Wir hatten Strato vor Jahren mal gekauft, aber inzwischen schon wieder weiter verkauft ;-) und ich habe lange hier in Berlin mein Büro Im Gebäude neben der Strato Zentrale gehabt. Bisher war ich mit den Services auch immer zufrieden. und habe meine Domains jetzt seit fast 25 Jahren dort gehostet.

**Comment by PaulusII** [comment]
Vielen Dank für dein Angebot. Jetzt schau ich Mal was ich tun kann. Klingt eigentlich interessant auch für mich. FileZilla hab ich zumindest Mal unter Anleitung verwendet. Vielleicht geht das ja z.B über Teamviewer oder sowas.
Wie kontaktiere ich dich, hier?

**Comment by cbits68** [comment]
Alternativ könnt Ihr Euch natürlich auch mal überlegen, ob Ihr nicht mal Kontakt zum THC Forsthof aufnehmen wollt. Die bieten ein Schlüsselfertiges OpenSource System an, sogar inclusive Hosting. Dann müsst Ihr Euch um die Installation den Betrieb und Updates auch zukünftig keine Gedanken machen.
https://www.thc-forsthof.de/reservierungssystem

**Comment by PaulusII** [comment]
Das klingt auch sehr interessant und ich schaue mir das gerne Mal an.
Vielen Dank für die große Unterstützung bis hierher.

**Comment by PaulusII** [comment]
Hallo cbits68,
kann man hier auch persönliche Nachrichten schreiben?
Da könnten wir die Kontakte Mal austauschen.
Grüße Mike

**Comment by cbits68** [comment]
https://tc-rotweiss-grossbeeren.de/index.php/verein/vorstand/90-beauftragte/9-andreas-born
