### ISSUE TITLE
Must call beginTransaction() before you can rollback

### ISSUE THREAD

**Issue by Errichamonda** [tkrebs/ep3-bs#53]
Hello, I have this problem while I try for a booking. The other solution I've found is written in Dutch and I can't understand even with google translate.

How can I fix this problem?

**Comment by geopicture** [comment]
Hey. I had the same Problem. After checking my mail settings it worked for me.
I changed from smtp mode back to sendmail.
reference #25

**Comment by Errichamonda** [comment]
It doesn't work for me. I've also updated ZendFramework but nothing. The error keeps popping out

**Comment by tkrebs** [comment]
Please enable the development mode in `config/application.php`:

`define('EP3_BS_DEV', true);`

This should output a more detailed error message, which you can copy here.

**Comment by Errichamonda** [comment]
Ok I've found the issue. It was my mistake. I forgot to add to the domain to my mail server. I'll leave this there if someone else have this problem.

**Comment by tkrebs** [comment]
Okay, nice!

**Comment by azich01** [comment]
i have the same problem. Where i must add the domain

regards Andreas

**Comment by helmi90** [comment]
Ich wollte in der Datenbank testweise User erstellen, von denen ich nur die E-Mail-Adresse wissen muss, sodass sie ich gezielt bereits aktivierte Mitglieder anlegen kann, welche dann über "Passwort vergessen" sich ihr Passwort nach eigenen Wünschen setzen können. Dabei habe ich ein beliebiges Passwort gewählt und auch die gleich die E-Mail-Adresse für den Alias verwendet (mit dem Gedanken, dass die User das später selber ändern sollten). Daraufhin habe ich auch genau diese "Must call beginTransaction() before you can rollback"-Fehlermeldung erhalten. Nach Änderung des Alias funktionierte alles wieder tadellos.

Also vielleicht hilft das ja jemandem: **der Alias darf scheinbar kein E-Mail-Format haben**.

**Comment by helmi90** [comment]
> ... gleich die E-Mail-Adresse für den Alias verwendet (mit dem Gedanken, dass die User das später selber ändern sollten). 

sorry, hab gerade gemerkt, dass Standard-User den Alias gar nicht selbst verändern können..
