### ISSUE TITLE
Validation Code on e-mail for each square

### ISSUE THREAD

**Issue by matos-07** [tkrebs/ep3-bs#534]
Hi guys,

Someone have  featured created for e-mail confirmation? I have one code for each square and in e-mail i want to put these code for open de door for each square , you have some feature created like this?

Thank you

**Comment by cbits68** [comment]
perhaps [hschiebold](https://github.com/hschiebold) can hel you.
I think he implemented sendin out codes  and ical attachments on e-mail as stated in #179

**Comment by matos-07** [comment]
Yes, but i have one field on DB called code_key with value and i want to push for the e-mail template on NotificationListener.php it's possible ?

**Comment by matos-07** [comment]
Hey guys 

I implemented this functionality of associating a code for each square.

Updated code in NotificationListener.php file


```
$message = sprintf($this->t('We confirm the reservation for the court of %s %s, %s . 
    Code court %s: %s. 
    Thank you'),
    $this->optionManager->get('subject.square.type'),
    $square->need('name'),
    $dateRangerHelper($reservationStart, $reservationEnd),
    $square->need('name'),
    $this->getSquareCode($square->need('name'))
);
```


Then, you need to add the getSquareCode() method to the NotificationListener class. This method will take the name of the reserved court and return its corresponding code. Here's an example of how you can implement the getSquareCode() method:

```
protected function getSquareCode($squareName)
{
    switch ($squareName) {
        case 'S.Paio':
            return '1995';
        case 'Palmeira':
            return '2739';
        case 'Panoias':
            return '019';
        default:
            return '';
    }
}
```

This method returns the code for the given court name. You can modify the code and court names to match your system.

I hope it helps.

Thanks.
