### ISSUE TITLE
Closing day

### ISSUE THREAD

**Issue by Errichamonda** [tkrebs/ep3-bs#54]
How can I set some day (for example Sunday) as closing day? Normal users can't book but admin can create events.

**Comment by tkrebs** [comment]
Unfortunately, there is no closing day functionality yet built in. You could work around by creating a recurring full day event.

**Comment by Errichamonda** [comment]
I'm trying to do it myself. How can I read form another table in database? I've created bs_squares_extras with seid, sid, closing (the day it should be closed), day_start (the day that rule starts), day_end, time_start (at what time it starts), time_end.

**Comment by tkrebs** [comment]
The clean way would be to create table classes like here:

https://github.com/tkrebs/ep3-bs/tree/master/module/Event/src/Event/Table

However, you could also just use the TableGateway from Zend Framework 2:

https://framework.zend.com/manual/2.4/en/modules/zend.db.table-gateway.html

**Comment by Errichamonda** [comment]
Yes but how can I read? in CellLogic file how can I read from the database? Sorry but I don't understand how this framework works. I've created under Square\src\Square\Table the factory and the table, Square\src\Square\Entity the SquareExtrasFactory and SquareExtras and also Square\src\Square\Manager the manager and the factory.

If the date i'm checking in CellLogic is in the rules defined in bs_squares_extra it set the cell to closed.

**Comment by tkrebs** [comment]
I'm afraid it is inevitable to understand how Zend Framework 2 works in order to make useful changes to the system. In this case, you would have to load and process the information from your new tables in the corresponding controller and pass the results to the view (scripts).
