### ISSUE TITLE
The PHP intl extension is required but not installed. Please contact your web hosting provider to get this one fixed.

### ISSUE THREAD

**Issue by jochenspc** [tkrebs/ep3-bs#55]
Hallo Herr Krebs,

ich habe heute versucht Setup auszuführen und bin auf folgende Fehlermeldung gestoßen: The PHP intl extension is required but not installed. Please contact your web hosting provider to get this one fixed.
Ich nutze Webhosting bei Strato. Haben sie damit schon Erfahrung gemacht und können mir bei der Lösung behilflich sein ?

Beste Grüße
Jochen Schäfer

**Comment by tkrebs** [comment]
Wie die Fehlermeldung schon sagt, fehlt die PHP-Erweiterung "intl", welche auf einigen (meist günstigeren) Webhosting-Paketen nicht aktiviert ist. Da kann Ihnen nur Ihr Hoster (Strato) helfen.

**Comment by jochenspc** [comment]
Hallo HErr Krebs,

vielen DAnk für die schnelle Antwort. Ich habe in der Zwischenzeit 
versucht das Buchungssystem auf meinem Synology NAS zum laufen zu 
bekommen. Trotz PHP 5.6 und intl erweiterung gelingt mir dies nicht. 
Beim aufruf der setup.php Erscheint die Meldung Fehler 500: Bei der 
Verarbeitung dieser Anforderung ist ein Fehler aufgetreten.
Eine Test PHP Datei wird fehlerfrei aufgerufen.

Haben Sie Erfahrung mit dem Betrieb auf einem Synology NAS ?

Beste Grüße
Jochen Schäfer

Am 26.04.2017 um 13:11 schrieb Tobias Krebs:
