### ISSUE TITLE
Datenbank lerren

### ISSUE THREAD

**Issue by Bakati** [tkrebs/ep3-bs#550]
Hallo an Alle,
ich möchte alle Buchungen von der Datenbank Löschen damit ich einen leeren Datenbank habe. Lediglich sollten nur die Plätze, User und Passwörter übrig bleiben. Welche Datensätze sollte ich löschen, könnt ihr mir bitte einen Tip geben?

Vielen Dank und Frohe Ostern

**Comment by vrootz** [comment]
Das kannst du ohne Hilfstool rein über das Platzbuchungssystem nur löschen, indem du jede Buchung einzelt löschst.
Ansonsten musst du dir bspw. phpmyadmin installieren und deine Datenbank dort einbinden, dann kannst du über eine grafische Oberfläche die Einträge bs_bookings löschen, allerdings löschst du dann NUR die Buchungen an sich. Gekoppelt sind diese an die BID (Booking ID) da müsste man mal schauen, wie die miteinander in Beziehung stehen. Reintheoretisch müsstest du alle Einträge mit der Buchung und dessen BID aus allen Tabellen dann löschen, damit alle zusammenhängende Einträge mit der Buchung gelöscht werden.

**Comment by Bakati** [comment]
Danke php Admin habe ich und dort kann ich die bs_bookings löschen, meines Wissens nach da sind andere zwei Tabellen die zu löschen sind aber leider weiß ich nicht mehr welche, werde mal probieren.

**Comment by cbits68** [comment]
#407 da steht alles was Du wissen musst ;-)

**Comment by Bakati** [comment]
Danke sehr, LG
