### ISSUE TITLE
Wiederholende Buchungen durch User stornierbar

### ISSUE THREAD

**Issue by some0ne2** [tkrebs/ep3-bs#553]
Hallo liebes ep3-bs Community,

besteht die Möglichkeit eine durch den Admin festgelegte Wiederholende Buchung aus "Usersicht" zu stornieren (einen einzelnen Termin aus der wiederholenden Buchung durch z.B. Krankheit abzusagen)?
Ich würde für unser Projekt solch eine Funktion benötigen, konnte diese Funktion aber nicht finden. 

Es sollte auch das Stornierungslimit greifen (sprich nur N Stunden vor Buchung sollte die Buchung stornierbar sein durch den User).

MfG:

**Comment by Matze848** [comment]
Hi,
ich habe das gleiche Problem: Die wiederkehrenden Abostunden werden von einem Verwaltungsuser für die jeweiligen echten User angelegt, könnnen aber nicht durch den User selber modifiziert werden. Beim Klick auf einen einzelen Termin erscheint das Popup, dass der Termin für einen gebucht sei, aber eben nicht mehr stornierbar sei.

![ep3-bs_userstorno_popup](https://user-images.githubusercontent.com/66040219/193786754-a32d9cf5-fad0-42ac-bcd1-bb7a0a6ab456.jpg)

Diese Funktion ist aber meiner Meinung nach sehr wichtig, hat da jemand eine Lösung für?
Besten Dank im Voraus!

**Comment by gitroli** [comment]
ja das bräuchte ich auch

**Comment by cbits68** [comment]
Dann codet das doch mal selbst :-)
Nicht böse gemeint, aber wenn Ihr Euch mal mit dem Berechtigungskonzept beschäftigt habt, dann werdet Ihr sehr schnell merken, dass man zum Stornieren von Abo Buchungen auch Abo's erstellen müssen kann.
Es gibt halt nun mal nur Benutzer, Mitarbeiter & Verwalter im System.
Es ist hier leider so, dass man die Organisation an die Software anpassen muss . Die Software an alle Anforderungen anzupassen ist nur bedingt möglich,
Ich habe daher bei uns die Trainer mit der Mitarbeiterberechtigung versehen, da diese überwiegend die Abo's benötigen.
Für die Teamtrainings übernimmt das bei uns der Sportwart oder Jugendwart oder ich als Webmaster.
Einzelne Mitglieder haben bei uns keine Abo's, können aber sehr flexibel buchen.

In einer kommerziellen Nutzung müsste ich ja mein Abo bezahlen, auch wenn ich es nicht nutze. 

Aus meiner Sicht wäre es mit der Software aber möglich, auch Benutzer als Mitarbeiter zu berechtigen, so dass diese Abo's buchen und stornieren könnten. Das hat aber natürlich einigen Nebeneffekte, u.A. die Buchungsmaske ändert sich, und die Benutzer könnten dann auch einige Dinge, die Sie nicht unbedingt können sollten (z.B. Platzhalter anlegen, ...

In einer kommerziellen Situation könnte man ja auch im Sekretariat anrufen, um einen Abo Termin zu stornieren.

Gruß
CBITS

**Comment by some0ne2** [comment]
Kurzes Update:

Habe es nun selbst angepasst, Cronjob erstellt eben Einzeltermine für jeden User, alles dazu wird per CSV konfiguriert und eben in einem dort einstellbaren Format entsprechend wiederholt.
Also ja, mit den "Abo Buchungen" ist es nicht möglich, ihr müsst selbst "Einzeltermine" erstellen.
