### ISSUE TITLE
EP3 Website not loading / refreshing in Playsignage Player

### ISSUE THREAD

**Issue by MarcusThiel** [tkrebs/ep3-bs#555]
Hello,

i have a little EP3 Installation on

https://platz.tennis-ebersteinburg.net

wich works like a charm, thank you very much for this brilliant software. I have one Problem, maybe you could help me. I have a playsignage account for a simple screen to show the bookings with a few extra widgets (with a amazon firestick with the playsignage app on it)... the widgets show the correct time/date, but the website ist totally off, i attached a picture. Playsignage say that that is what the website is delivering to the player. and they cant do anything about it, so maybe i have to make some adjustements on the ep3 site ? What can cause this ?

thanks in advance

![buchung](https://user-images.githubusercontent.com/86321305/170888824-f5a47f69-d774-41b4-b878-231aa7e0001a.jpg)
?

**Comment by Busfreak** [comment]
HI!
Offensichtlich ruft deine App den Plan nicht mit dem aktuellen Datum auf.
Das System merkt sich offensichtlich, welchen Tag du zuletzt aufgerufen hast. Ich weiß nicht, ob mit Cookies oder anders.
Versuch mal https://platz.tennis-ebersteinburg.net/?date=today

**Comment by MarcusThiel** [comment]
Danke, das funktioniert auf jeden Fall schon mal im dashboard von Playsignage .ich teste das mal morgen auf dem Platz ... merci vielmals !!

**Comment by cbits68** [comment]
Ich denke mal du solltest in der App den lokale  Browsercache deaktivieren, wenn möglich. Musste ich auf meinem Raspberry PI Display im Clubhaus auch so machen, sonst lädt er nicht den aktuellen Tag.

**Comment by MarcusThiel** [comment]
> 

Moin hat funktioniert ... die Welt kann so simpel sein ... vielen Dank !!!
