### ISSUE TITLE
Infoscreen mit Sichtbarkeit von Namen aber ohne Buchungsfunktion

### ISSUE THREAD

**Issue by Sahel2021** [tkrebs/ep3-bs#556]
Wir wollen im Clubhaus einen Bildschirm mit der Anzeige der Namen (Spieler, Abos, Veranstaltungen).
Unsere Plätze haben die Einstellungen "Sichtbarkeit von Namen für angemeldete Benutzer".

Gibt es eine Möglichkeit, den Infoscreen mit einer Art Dummy-User zu betreiben, der keine Buchungen oder Stornierungen machen kann?  Also so was wie Kiosk-Modus im angemeldetem Zustand.

**Comment by cbits68** [comment]
schau mal hier #378
