### ISSUE TITLE
need help  - new error - ep-3 no longer working

### ISSUE THREAD

**Issue by geraldjh** [tkrebs/ep3-bs#557]
hi, we are running the ep-3 system since 2 years. since 2 days it is not longer working. a new installation with a new database didn't help. I have no idea, what happened..
our server uses php 7.4
Gerald

the following error occurs when calling the website:

Fatal error: Uncaught Zend\Session\Exception\InvalidArgumentException: 'session.save_path' is not a valid sessions-related ini setting. in /home/sites/site100018351/web/tennisplatz-reservieren2.de/vendor/zendframework/zend-session/src/Config/SessionConfig.php:155 Stack trace: #0 /home/sites/site100018351/web/tennisplatz-reservieren2.de/vendor/zendframework/zend-session/src/Config/StandardConfig.php(236): Zend\Session\Config\SessionConfig->setStorageOption() #1 /home/sites/site100018351/web/tennisplatz-reservieren2.de/vendor/zendframework/zend-session/src/Config/SessionConfig.php(233): Zend\Session\Config\StandardConfig->setSavePath() #2 /home/sites/site100018351/web/tennisplatz-reservieren2.de/vendor/zendframework/zend-session/src/Config/StandardConfig.php(114): Zend\Session\Config\SessionConfig->setSavePath() #3 /home/sites/site100018351/web/tennisplatz-reservieren2.de/vendor/zendframework/zend-session/src/Service/SessionConfigFactory.php(67): Zend\Session\Config\StandardConfig->setOptions() #4 /home/sites/site100018351/ in /home/sites/site100018351/web/tennisplatz-reservieren2.de/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 941

**Comment by geraldjh** [comment]
habe die Lösung gefunden: #536 
[Bakati](https://github.com/Bakati) commented [on 19 Feb](https://github.com/tkrebs/ep3-bs/issues/536#issuecomment-1045964373)
Im Hauptverzeichniss config/autoload/global.php die Zeile 'save_path' => getcwd() . '/data/session/', einfach auskommentiert. 
Es funktioniert perfekt !!!!

**Comment by tkrebs** [comment]
👍
