### ISSUE TITLE
setup.php not working - please help

### ISSUE THREAD

**Issue by bs-csa** [tkrebs/ep3-bs#558]
Our System:
debian 11, PHP 7.4, Nginx and  mariadb 10.5

I followed the instructions in  \data\docs\install.txt  Point 1 and 2.

Step 3. "Setup the database by calling the setup.php"
only creates the error "Database required
Please setup the database prior to first usage"

Database is setup and empty, and credentials in config/autoloader/local.php are definitely correct.

If i login to the database with that credentials and execute /data/db/ep3-bs.sql manually, tables are created successfully.
But the startpage then shows the following error:

Oops ... da ist wohl etwas schief gelaufen
Option service.calendar.days does not exist
Bitte [informieren Sie uns](http://ep3.svh24.de/) bei exotischen oder nicht nachvollziehbaren Fehlermeldungen,
damit wir das Problem schnell beheben können.

[Zurück zur Startseite]
Exception details
Type
RuntimeException
Mitteilung
Option service.calendar.days does not exist
File
/var/www/ep3.....de/module/Base/src/Base/Manager/OptionManager.php:172
Stack trace
#0 /var/www/ep3.svh24.de/module/Base/src/Base/Controller/Plugin/Option.php(20): Base\Manager\OptionManager->get()
#1 [internal function]: Base\Controller\Plugin\Option->__invoke()
#2 /var/www/ep3.svh24.de/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(318): call_user_func_array()
#3 /var/www/ep3.svh24.de/module/Calendar/src/Calendar/Controller/CalendarController.php(20): Zend\Mvc\Controller\AbstractController->__call()
#4 /var/www/ep3.svh24.de/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(84): Calendar\Controller\CalendarController->indexAction()
#5 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch()
#6 /var/www/ep3.svh24.de/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func()
#7 /var/www/ep3.svh24.de/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners()
#8 /var/www/ep3.svh24.de/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(116): Zend\EventManager\EventManager->triggerEventUntil()
#9 /var/www/ep3.svh24.de/vendor/zendframework/zend-mvc/src/Controller/Plugin/Forward.php(143): Zend\Mvc\Controller\AbstractController->dispatch()
#10 /var/www/ep3.svh24.de/module/Frontend/src/Frontend/Controller/IndexController.php(13): Zend\Mvc\Controller\Plugin\Forward->dispatch()
#11 /var/www/ep3.svh24.de/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(84): Frontend\Controller\IndexController->indexAction()
#12 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch()
#13 /var/www/ep3.svh24.de/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func()
#14 /var/www/ep3.svh24.de/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners()
#15 /var/www/ep3.svh24.de/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(116): Zend\EventManager\EventManager->triggerEventUntil()
#16 /var/www/ep3.svh24.de/vendor/zendframework/zend-mvc/src/DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch()
#17 [internal function]: Zend\Mvc\DispatchListener->onDispatch()
#18 /var/www/ep3.svh24.de/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func()
#19 /var/www/ep3.svh24.de/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners()
#20 /var/www/ep3.svh24.de/vendor/zendframework/zend-mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil()
#21 /var/www/ep3.svh24.de/public/index.php(66): Zend\Mvc\Application->run()
#22 {main}

 
Any help is appreciated.

Cheers,
GW

**Comment by tkrebs** [comment]
There have been reports from other users, that the setup worked after completely emptying the database and trying again.

Completing the setup is necessary because it prompts and stores the options (like `service.calendar.days`).

**Comment by bs-csa** [comment]
Thank you for your reply, 

unfortunately setup.php does not run even with an empty database. 
It only says "Database required" and adds another "/setup.php/" to the "Use Setup tool" link button.

Can i enable some logging to see what is going wrong here?
Directory "/data/log" is empty right now.

**Comment by tkrebs** [comment]
Perhaps the issue is Nginx, as the booking system and especially the setup requires the Apache webserver (.htaccess).

**Comment by bs-csa** [comment]
Oh, did not see this requirement.
Thank you.
