### ISSUE TITLE
Welche Version habe ich?

### ISSUE THREAD

**Issue by ThoughtLife** [tkrebs/ep3-bs#559]
Hallo Community,

an sich eine ganz einfache Frage, aber ich finde die Information nicht.
Ich habe vor 3 Jahren ca. das Buchungssystem auf der Homepage installiert. Es wurde nun Zeit, dass ich dieses Update auf die 1.7.0
Im der Update.txt steht ja beschrieben was von welcher Version auf welche durchgeführt werden muss.
Leider gibt es in meiner Ordnerstruktur keinen Ordner "Version".
Wie bekomme ich nun raus welche Version bei mir aktuell installiert ist, damit ich auch weiß welche Ordner ich austauschen muss?
Oder wäre es ratsam, alle Ordner auszutauschen die in der Update.txt erwähnt werden, wenn ich das System schon seit 2-3 Jahren seit Installation nicht mehr upgedated habe?

Danke für eure Hilfe!

**Comment by tkrebs** [comment]
Gibt es bei dir vielleicht die Datei "README.md" mit dem Abschnitt "The current version is [...]"?

Ansonsten schadet es auch nicht, (von unten angefangen) alle in der "update.txt" aufgelisteten Dateien und Ordner auszutauschen.

Und wie immer: Vorher ein Backup machen und ggf. prüfen, ob nicht noch eigene Anpassungen am Code vorgenommen wurden.

**Comment by ThoughtLife** [comment]
Danke dir, da habe ich es gefunden!
