### ISSUE TITLE
Buchung von max. z.B.: 2h pro Woche pro Benutzer

### ISSUE THREAD

**Issue by icestar78** [tkrebs/ep3-bs#56]
Hallo!

Ich würde gerne die Abfrage einbauen ob der Benutzer in dieser Woche bereits seine 2h verbraucht hat.
Und wenn dies der Fall ist, die Meldung ausgeben, dass er sein Kontigent bereits verbraucht hat.

Ist es möglich diese Information aus den Tables zu bekommen (welche), um vor dem Eintragen einer Buchung in die Datenbank dies abzufragen.

**Comment by tkrebs** [comment]
#149

**Comment by tkrebs** [comment]
Umsetzung mittels regelbasierten Einschränkungssystem

Ebenfalls möglich #143

**Comment by icestar78** [comment]
Hallo,
ich muss leider gestehen ich weiß nicht genau was ein regelbasiertes Einschränkungssystem ist.

Mein Ansatz wäre gewesen vor dem Speichern der neuen Buchung  die aktuelle Kalenderwoche zu bestimmen und zu vergleichen ob in dieser Woche bereits eine Buchung dieses Users mit dem Status
!= cancelled  vorhanden ist.
Wenn nicht ->dann neue Buchung ok
Wenn ja -> Ihr Kontigent für diese Woche ist bereits aufgebraucht.

Step 2
bzw. die Buchungen in der Kalenderwoche zählen, und für den user bestimmen wieviele Buchungen pro Woche er erstellen kann.
(Zu diesem Zweck würde die max. Buchungsintervall auf 1h gesetzt werden)

Die Frage ist wo diese Abfrage und die Funktion am Besten einzubauen ist.
Im Booking Manager oder direkt in Create ?

**Comment by sitze89** [comment]
Gibt es so ein regelbasiertes Einschränkungssystem schon? möchte auch eine Maximale Buchungsanzahl p.P. einstellen.

**Comment by tkrebs** [comment]
Siehe #266
