### ISSUE TITLE
Filemanager nicht benutzbar

### ISSUE THREAD

**Issue by AchMol** [tkrebs/ep3-bs#562]
Hi all,

das System läuft bei uns im Docker Container und tut genau das, was es soll. Sehr gut und vielen Dank dafür an Herrn Krebs... :-)

Leider ist der Filemanager nicht benutzbar. Er startet zwar normal, aber keine der Schaltflächen ist benutzbar. Im Fenster steht "no way".  Der angezeigte Pfad "/" ist nicht editierbar.

Wie können wir das korrigieren bzw wo liegt der Fehler? 

<img width="1025" alt="Bildschirmfoto 2022-08-17 um 10 50 50" src="https://user-images.githubusercontent.com/36261044/185078298-2bca3cda-b4ec-4665-b288-5a871352ad02.png">

**Comment by cbits68** [comment]
Bei mir läuft das System zwar nicht im Docker aber das Problem ist das Gleiche.
Natürlich habe ich im root Verzeichnis bei meinem Provider keine Berechtigung. Insofern habe ich es bisher auch nicht mehr weiter verfolgt, warum der Filemanager nicht nutzbar ist.
Ich benutze bei meinem Provider ohnehin den sftp Zugang (FileZilla) auf den Webspace, daher benötige ich den Filemanager auch nicht wirklich. Kannst Du auf den Docker Container nicht auch über sftp zugreifen?

**Comment by AchMol** [comment]
Ok, vielen Dank, das ist schon mal ein guter Hinweis, dass es nicht am Docker liegt. Ich bin mir aber nicht einmal sicher, ob "/" jetzt wirklich das root Verzeichnis oder das root Verzeichnis des Webservers (Apache) meint. Verboten ist der Zugriff da natürlich für www-data aber wo wird das Startverzeichnis ermittelt?

Für die Verwaltung benötige ich ihn nicht, das ist schon richtig. Ich möchte aber auf der Info Seite mittels des Editors eine Grafik einfügen. Hier kann die Grafik aber nur aus Dateien ausgewählt werden, die vorher mit dem Filemanager hochgeladen wurden. Das ist die Falle...

Vielleicht gibt es ja eine Möglichkeit die Datein manuell in ein Verzeichnis zu legen und einzubinden? Aber solange ich nicht eine einzige Datei laden kann sind mir die Zusammenhänge und dafür vorgesehenen Verzeichnisse nicht klar...

**Comment by tkrebs** [comment]
Danke für die Hinweise. Der Filemanager war leider sehr veraltet und wurde in der aktuellen Version 1.8.0 nun sicherheitshalber komplett entfernt.

Bis es eine neue Alternative gibt bleibt nur der klassische Upload via separatem (S)FTP.
