### ISSUE TITLE
PHP 8 Kompatiblität - Status?

### ISSUE THREAD

**Issue by Seraangel** [tkrebs/ep3-bs#563]
Hi,

PHP 7.4 ist in 2 Monaten EoL.
Wie ist denn der Stand der Entwicklung?

Hat schon einmal jemand das EP3 mit PHP 8 getestet?
Gibt's irgendwo Fehler oder läuft es problemlos?

**Comment by Bergruebe** [comment]
Das Thema steht bei mir jetzt auch bevor, dazu habe ich nur diese Aussage gefunden:
https://github.com/tkrebs/ep3-bs/issues/526#issuecomment-1013913528
>Ich denke, die Umstellung auf PHP 8 wird mit der gleichen Strategie wie bei PHP 7.4 relativ gut möglich sein.
>
>Das wird voraussichtlich auch bei unserem Verein nötig werden. Die neue Version des Buchungssystems befindet sich zwar nach wie vor in Entwicklung, derzeit setzen wir aber auch noch die Version 1.7 ein.

**Comment by tkrebs** [comment]
Version 1.8.0 mit PHP 8.1-Support ist nun verfügbar:

https://github.com/tkrebs/ep3-bs/blob/master/UPDATE.md#update-to-180
