### ISSUE TITLE
1.8.x setzt php 8.1 voraus

### ISSUE THREAD

**Issue by cbits68** [tkrebs/ep3-bs#568]
Ich habe inzwischen meine ep3-bs Installation per git pull auf den aktuellen Stand gebracht und mal mit php 8.1 getestet.
Bisher sind noch keine Probleme aufgetaucht. Da die Außenplätze geschlossen sind und keine Benutzer mehr buchen, stornieren, ... konnte ich aber noch nicht alles testen.

Mein Problem ist auch, dass ich das Buchungssystem ja bei meinem Webhoster laufen habe, bei dem auch unserer Vereinshomepage mit Joomla läuft. Joomla läuft aktuell aber nicht sauber mit php 8.1, daher kann ich aktuell maximal auf 8.0 umstellen.
Dann läuft aber ep3-bs nicht mehr, da es zwingend 8.1 voraussetzt.

Gibt es eine Möglichkeit, dass ep3-bs auch mit php 8.0 läuft? Muss ggf. irgendwo nur die Versionsprüfung angepasst werden?

Gruß
Andreas

**Comment by tkrebs** [comment]
Für den Betrieb eines bereits installierten Systems unter PHP 8.0 sollte es ausreichen, die folgende Zeile zu entfernen:
https://github.com/tkrebs/ep3-bs/blob/master/public/index.php#L14

Für eine neue Installation muss das Gleiche auch in der `setup.php` vorgenommen werden:
https://github.com/tkrebs/ep3-bs/blob/master/public/setup.php#L16

Und falls über Composer installiert wird, muss zudem noch diese Zeile entfernt werden:
https://github.com/tkrebs/ep3-bs/blob/master/composer.json#L8
