### ISSUE TITLE
Booking Range 24h error 

### ISSUE THREAD

**Issue by StukaRT** [tkrebs/ep3-bs#57]
Hey, 
i have set the booking range for the time slot spanning 24 hours. When someone wants to book, the form has the bf-time-end input pre filled with 00:00 instead of 24:00. If you submit it like this you can not edit the booking anymore, you have to delete it from the database. If you click it it behaves like adding a new entry. If you change 00:00 in the bf-time-end input manually to 24:00 it works fine.

Any idea how to get the form to pre-fill 24:00 instead of 00:00 for bf-time-end

**Comment by tkrebs** [comment]
Am I assuming correctly that this only affects the administration panel?

For this I have added a small fix to the development branch (https://github.com/tkrebs/ep3-bs/tree/develop) which you can download and replace (the module/ directory suffices).

**Comment by StukaRT** [comment]
Yes it does. I will try the fix later, for now i worked around it by setting allowed time to 00:00 till 23:00 und a booking range of 24 hours :)

Thx for the quick repsonse though
