### ISSUE TITLE
Apache document root directly to the public directory 

### ISSUE THREAD

**Issue by wepeha105** [tkrebs/ep3-bs#573]
Hallo zusammen,

Die Software bekomme ich ans Laufen, aber ein Punkt fehlt mir noch.
Ich habe jetzt einiges getestet, gelesen, ausprobiert, aber ich komme nicht zum Ziel. In der Installationsanweisung steht:
_Deployment
Once you are satisfied with the system and want to use it in the wild, 🚨 please make sure to set the Apache document root directly to the public directory so that your domain will read like this:
https://example.com/
And not like this:
https://example.com/public/_

Wo kann ich das beeinflussen? Ich habe auch eine Subdomain eingerichtet und auf das ep3-bs Verzeichnis verwiesen. Das klappt alles
 aber zum Schluss wird immer /public/ angezeigt. Übrigens auch bei mehreren anderen Installation, von anderen Menschen.

Was muss ich tun, damit ich den Zustand 
https://example.com/
und eben nicht 
https://example.com/public/
angezeigt bekomme?

Danke im Vorraus.

**Comment by cbits68** [comment]
wenn Du bei Deinem Provider bei der Domainumleitung (intern) auf ein Verzeichnis einstellst, dann sollte die Umleitung eben nicht auf das Installationsverzeichnis der Software lauten, sondern auf das darin enthaltenen Unterverzeichnis public.
Sieht bei mir bei Strato z.B. so aus:
![Uploading 2023-01-20 20_01_03-STRATO Kunden-Login - Domainverwaltung.png…]()
Dann siehst Du in der URL auch das public nicht mehr.

**Comment by wepeha105** [comment]
Großartig. Recht herzlichen Dank, das wars.Closed
