### ISSUE TITLE
Bilder einfügen auf der Infoseite in Version 1.8.1

### ISSUE THREAD

**Issue by mjmpeace** [tkrebs/ep3-bs#580]
Aufgrund der Entfernung des Filemanagers kann man nicht wie bisher Bilder einfügen. Wie geht das denn jetzt in dieser Version?

**Comment by cbits68** [comment]
einfach den Pfad und Dateinamen beim Einfügen im Editor angeben.
Die Bilder kannst Du per ftp z.B. in den Ordner public/imgs hochladen
Wenn der root Pfad Deiner Domain auf das public Verzeichnis zeigt und Du z.B. die Datei Bilddateiname.jpg dort abgelegt hast,  ist der Pfad
/imgs/Bilddateiname.jpg
zeigt Diene Domain auf das ep3 Installationsverzeichnis, dann /public//imgs/Bilddateiname.jpg

**Comment by mjmpeace** [comment]
Ich habe jetzt Subdomains für beide Systeme und sie verweisen auf public. 
Danke für den Tipp.
