### ISSUE TITLE
ep3-bs-1.8.1 Benutzeranmeldung bringt Fehler 

### ISSUE THREAD

**Issue by jofinner** [tkrebs/ep3-bs#582]
Hallo,
beim betätigen des Registrierungs-Button und Anmelde-Button kommt folgende Fehlermeldung:

"Not Found
The requested URL was not found on this server."

Apache/2.4.52 (Ubuntu) Server at 192.168.200.90 Port 80
Installiert ist ep3 von ep3-bs-package-1.8.1.zip
PHP Version 8.1.2

Vielen Dank im voraus
Joachim Finner

**Comment by sueandjoe** [comment]
Hallo 

Ich habe nach einer langen (erfolgreichen) Testphase mit V1.7.0 auf einer Test-Domain das Reservationstool jetzt für den Aktivbetrieb auf der Vereinshomepage installiert (V1.8.1)

Die Installation hat geklappt, aber sobald ich mich einloggen oder registrieren will kommt diese Fehlermeldung:

Not Found
The requested URL /public/user/login was not found on this server.

Ich habe alles probiert, ohne Erfolg

Als Workaround habe ich meine Test-Installation jetzt auf den Aktiven Account kopiert. Das funktioniert jetzt, ist aber für mich noch nicht die Lösung.

Bitte um Hilfe...

**Comment by jofinner** [comment]
Hallo,
ich habe den Fehler in meiner Installation gefunden. Ich hatte die .htaccess_original nicht in .htaccess umbenannt

**Comment by sueandjoe** [comment]
Danke für den Tipp, jetzt klappt es

habe das in der Installationsanleitung wohl übersehen...

**Comment by Rockafella93** [comment]
Hallo, ich habe das gleiche Problem aber die .htaccess ist korrekt. Leider bekomme ich bei jeder Aktion (außer dem Aufrufen der Hauptseite) folgenden Fehler:
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by cbits68** [comment]
Wie kommst Du darauf, dass es sich um das gleiche Problem handelt? Die Fehlermeldung ist doch eine ganz andere.
