### ISSUE TITLE
Version 8.1. funktioniert nicht auf bplaced und PHP 8.2

### ISSUE THREAD

**Issue by tennstar1** [tkrebs/ep3-bs#587]
Hallo,
ich habe die Version 8.0 mit PHP 8.1. auf bplaced und auf XAMMP installiert und die funktioniert auch tadellos.

Nachdem ich die Version durch Austausch des Vendor Verzeichnisses mit PHP 8.2. gestartet habe wird die Seite [(hier der Link)](http://ep3.bplaced.net) vollkommen zerrissen und es wird die Fehlermeldung 
" _Deprecated: Creation of dynamic property Zend\Mvc\Router\Http\Part::$priority is deprecated in /users/ep3/www/src/Zend/Mvc/src/Router/Http/TreeRouteStack.php on line 223_ " 
angezeigt!
Die Seite funktioniert auch wenn das Vendor Verzeichnis ausgetauscht wurde mit PHP 8.1. nur nicht mit 8.2.

Dies ist auch nur eine Testseite, die eigentliche Seite liegt bei IONOS und läuft noch mit PHP 8.1. und ich wollte das Update und das umschalten so kurz vor der Saison erst mal ausprobieren!
Hat einer vielleicht eine Ahnung woran das liegt!

Mit freundlichen Gruß
tennstar

**Comment by OlliHe** [comment]
Hallo Tennstar,

ich hatte das gleiche Problem und die Lösung hier beschrieben:
[https://github.com/tkrebs/ep3-bs/issues/583](url)

**Comment by tennstar1** [comment]
Hallo OlliHe,

Danke für Deine Antwort, ich habe das Problem aber jetzt mal anders gelöst. 

Ich habe in der config/init.php die Zeile "define('EP3_BS_DEV_TAG', false);" von true auf false geändert und siehe da es läuft mit 
PHP 8.2.0 ohne Probleme.

Ich hatte die Version 1.8.0 installiert und habe dann, wie als Update auf 1.8.1 empfohlen, den Ordner "Vendor" ausgetauscht.

Gruß tennstar

**Comment by oXPLoiT** [comment]
@tennstar1: Merci für deine Zeilen, ich stand heute genau vor dem gleichen Problem, nachdem nun meine 1.6.4 Installation Jahrelang lief, dachte ich mir ich Update das mal eben...Bis zu o.g. Fehlermeldungen -> "Deprecated ..."
