### ISSUE TITLE
mehr als 3 plätze

### ISSUE THREAD

**Issue by ganti78** [tkrebs/ep3-bs#59]
ist es möglich, mehr als 3 plätze zu verwalten, indem einfache änderungen in der db gemacht werden oder sind zwei installationen nötig? danke

**Comment by tkrebs** [comment]
Es können beliebig viele Plätze über die Verwaltung angelegt werden.

**Comment by ganti78** [comment]
Danke. Sorry, keine Ahnung wieso ich das bisher nicht gesehen habe....
