### ISSUE TITLE
mitarbeiter/verwaltung buchung erstellen maske anpassen

### ISSUE THREAD

**Issue by holli73** [tkrebs/ep3-bs#591]
hallo,

ist es einfach moeglich fuer diese user das feld notitzen auszublenden - wir verwenden das nicht und bringt nur probleme wenn jemand mitarbeiter ist und am telefon was machen will (scrollen links/rechts funktioniert nur manchmal, bricht dann den platz view,...)

![image](https://user-images.githubusercontent.com/1434090/233842351-8beff581-8eee-469d-9278-939b0b02be82.png)

oder diese 4 column in rows zu schreiben?

danke
holli

**Comment by uli2004** [comment]
Um das Feld zu entfernen, kannst du m.E. in der /booking/module/Backend/view/backend/booking/edit.phtml die Zeilen 129 - 132 auskommentieren.

**Comment by holli73** [comment]
@uli2004 - super danke hat funktioniert - leider ist der view am mobile dann noch immer gebrochen - ich habe jetzt einfach die <TD's> noch in eine row geschachtelt und den kompletten <TD> fuer notes deaktiviert (<!-- TD>) - jetzt sieht es auch am mobile ok aus und bricht nicht das layout.
![image](https://user-images.githubusercontent.com/1434090/233976731-61d947c9-1fe9-4cf5-b9b2-da0c789fe5fa.png)
sieht auch am pc gut aus
bei meiner install ist der pfad 'module/Backend/view/backend/booking/' falls es jemand auch noch aendern moechte
