### ISSUE TITLE
Buchungen werden nicht angezeigt

### ISSUE THREAD

**Issue by jet2future** [tkrebs/ep3-bs#6]
Hi Ich habe A, B und C auf 2 Blöche einmal 09:00 bis 14:00 und 14:00-19:00 aufgeteilt.

Buche ich auf A wird es Visuell angezeigt.
Buche ich jedoch auf B oder C so erfolgt keine Anzeige und der Zeitblock wird immer noch als Frei angezeigt.

**Comment by tkrebs** [comment]
Haben die Plätze B und C eventuell eine höhere Kapazität (sprich, mehr als eine Person kann sie buchen)? Zur Prüfen wäre das in den Platzeinstellungen.

**Comment by jet2future** [comment]
Ich hab jetzt nochmal gecheckt:

Plätze sind bei mir durch die änderung der Blöcke nun waagerecht und Tage Senkrecht.

Ändere ich die Prio von Platz A auf 4 so rückt Platz B in die erste Zeile und Buchungen werden Visuell dargestellt.
Jedoch werden die Buchungen von Platz A dann nicht mehr angezeigt.

**Comment by jet2future** [comment]
Ändere ich die Zeiten so ab das es wieder 4 Blöcke sind und die Plätze wieder Senkrecht sind so werden alle Buchungen angezeigt-->
![unbenannt3](https://cloud.githubusercontent.com/assets/11949627/7169444/dcd6139a-e3c5-11e4-89f8-eb60736e6fd4.jpg)

**Comment by tkrebs** [comment]
Danke für die Details, ich habe den Fehler gefunden. Leider lässt er sich nicht ohne weiteres beheben, weswegen ich die alternative Ansicht vorübergehend deaktiviert habe. Mit dem letzten GitHub-Stand sollte es also funktionieren.

**Comment by jet2future** [comment]
Ich danke für den Workaround :)
Die Alternative Ansicht wäre cool, da ich Verschiedene Adressen zb: Moosachstraße oder Grüne Allee zur Buchung bereitstellen würde dies ist von der Textlänge nur mit der Alternativen Ansicht güt umzusetzen.
Trotzdem nochmal 1000 Dank

**Comment by tkrebs** [comment]
Habe eine Lösung für die alternative Ansicht gefunden und diese wieder aktiviert. :)

**Comment by jet2future** [comment]
Nice it works
