### ISSUE TITLE
"Illegal offset type" bei user/registration Formular

### ISSUE THREAD

**Issue by weixelbaumer** [tkrebs/ep3-bs#60]
Warning: Illegal offset **type** in vendor/zendframework/zendframework/library/Zend/I18n/Translator/Translator.php on line 443

Auf einer PHP Version 5.5.9-1ubuntu4.21 Installation mit de_DE default locale - bekomme ich bei Registrierung auf der **user/registration** Route mit zwei unterschiedlichen Passwörtern obigen Fehler der Übersetzung ... der zu einem Fallback auf den (en_US) Orignalstring führt.

![screen shot 2017-07-12 at 14 18 32](https://user-images.githubusercontent.com/2777906/28117278-0fda24bc-670d-11e7-9403-c77788379908.png)

**Comment by tkrebs** [comment]
Danke für den Hinweis, ist im Entwicklungszweig korrigiert:

https://github.com/tkrebs/ep3-bs/tree/develop

(Austausch des **/module**-Verzeichnis reicht)
