### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by olemde** [tkrebs/ep3-bs#614]
Hallo Tobias.
erstmal vielen Dank für dieses Projekt. Auch wenn ich es bisher nur aus der Demo-installation kenne. Bei mir läufts nämlich nicht so richtig. Evtl. hast Du einen Hinweis:

- Installation unter Alfahosting als Subdomain (gelinkt auf das Public-Verz.)
- Installationsfile direkt von der Homepage
- Datenbank läuft
- Homepage des ep3 läuft
- sobald man eine andere Seite öffnen will (login/register/booking) erscheint "internal Server Error"
- die htaccess habe ich sowohl im public folder reinkopiert als auch in den darüberliegenden Ordner (auch wenn das nach meiner Meinung keinen Einfluss haben sollte. 

- <IfModule mod_rewrite.c>

    RewriteEngine On
    RewriteBase /   # Try to uncomment this if you experience redirect problems

Ich kann leider bei Alfahosting die Einstellungen nicht mehr finden , wo das mod_rewrite de-/aktiviert wird. hier ist nun Cloudpit am Werk und da finde ich diese Einstellung nicht - zuvor gab es eine andere Konfig-Machine...

Diese Meldung ist bereits bei einigen anderen Usern hier kommentiert, aber ich konnte für mich noch keine Lösung finden.

vielen Dank 
Ole

**Comment by tkrebs** [comment]
Ob und welche .htaccess-Direktiven funktionieren ist Hoster-abhängig, insbesondere ob das hier benötigte Rewrite-Modul überhaupt installiert und aktiviert ist.

Da müsstest du dich an den Support deines Hosters wenden.

PS: Du könntest allerdings noch testen, ob die funktional verwandte [.htaccess-Datei von WordPress](https://wordpress.org/documentation/article/htaccess/) funktioniert.

**Comment by olemde** [comment]
Kam nicht weiter habe andere Software gewählt
