### ISSUE TITLE
Infos nur für eingeloggte User

### ISSUE THREAD

**Issue by dschousef** [tkrebs/ep3-bs#622]
Hallo zusammen, 
ich wollte fragen, ob jemand eine (einfache?) Möglichkeit kennt, Infos nur für eingeloggte User bereitzustellen....
Unser Clubheim hat seit kurzem einen zahlencodegesicherten Zugang und ich hatte die Idee, dass man diesen Code, der sich von Zeit zu Zeit ändert, evtl. im geschützten Bereich des Buchungssystems bereithalten könnte. 
Vielleicht könnte man es ja bei der Anzeige "Angemeldet als..." irgendwie mit dranhängen?
Vielen Dank für eure Ideen bzw. Unterstützung!

Viele Grüße
dschousef

**Comment by Busfreak** [comment]
Hallo dschousef,

der Text "Angemeldet als..." wird in
module\Frontend\view\frontend\index\userpanel.online.phtml
in Zeile 5 ausgegeben:
<?= sprintf($this->t('Online as %s'), $this->user->need('alias')) ?>

Dort könntest du was rein schreiben.

Komfortabler wäre natürlich, wenn du einen Wert aus der Tabelle bs_options anzeigen lässt:
<?= sprintf($this->t('Online as %s'), $this->user->need('alias')); echo(' - ' . $this->option('client.code')) ?>

Und damit du den Code nicht in der Datenbank ändern musst, fügst du ein Eingabefeld in die Einstellungen "Namen und Texte" ein:
module\Backend\src\Backend\Form\Config\TextForm.php
z.B. in Zeile 29:
'client.code' => array('Geheimer Code', 'Wird regelmäßig geändert :-)'),

Viele Grüße
;-)

**Comment by dschousef** [comment]
Wow, das ging ja schnell! Herzlichen Dank, werd ich ausprobieren!
