### ISSUE TITLE
Infoseite Link ändern

### ISSUE THREAD

**Issue by mjmpeace** [tkrebs/ep3-bs#632]
Ich möchte die Infoseite anders gestalten. Responsiv und moderner außerhalb des Buchungssystem. Wie kann ich den Link im Buchungssystem ändern oben im Menü?

**Comment by Sahel2021** [comment]
Bin mir nichtsicher, aber womöglich hier:
/ep3-bs-master/module/Service/view/service/service/help.html
Zeile 8

**Comment by mjmpeace** [comment]
Da bin ich mir unsicher - aber ich werde mal testen, was passiert, wenn ich die Url dort direkt ändere.

**Comment by Busfreak** [comment]
Der Link wird in Zeile 62 im <div id="topbar-infos" class="responsive-pass-3">
in der Datei module/Base/view/layout/layout.phtml generiert. Dort würde ich ansetzen.

**Comment by mjmpeace** [comment]
Weder das eine noch das andere klappt. in der Layout kann ich zwar target blank einfügen, das funktioniert, aber der Link eingefügt in der service Datei fiúnktioniert nicht, es wird nach unserer Domain /service/info angezeigt, obwohl ich was anderes eingetragen habe. da muss irgendwo noch ein Problem sein. Wer kann helfen. Ändere ich es in der layout direkt, gibt es script Fehler.

**Comment by mjmpeace** [comment]
Alle Versuche, die layout.html anzupassen haben nicht geklappt. Ich kann zwar dafür sorgen, dass die Infoseite im neuen Fenster öffnet, aber ein anderen Link dort eintragen klappt so nicht. Das liegt wohl daran, dass es eine Scriptverbindung gibt zu diesem Link, weil man ja den Text der Info-Seite in die Datenbank einträgt und die dort abgerufen wird. Das muss komplett verschwinden. Aber wie?

**Comment by mjmpeace** [comment]
Damit ist diese Frage gelöst. Ich schließe das ganz ab.
