### ISSUE TITLE
Buchungen/ Veranstaltungen für 4 Wochen statt nur für eine Woche anzeigen lassen.

### ISSUE THREAD

**Issue by aulicus** [tkrebs/ep3-bs#635]
Hallo ihr Spezialisten, ich habe eine Frage: Standardmäßig können registrierte Benutzer zukünftige Buchungen nur für die nächsten 7 Tage einsehen, wenn sie weiter gehen, kommt nur die Info: "Zu fern".
Wie und wo kann ich diesen Zeitraum z.B. auf 4 Wochen verlängern? Dieser Wert muss ja wohl in irgendeinem Script eingetragen sein.
Für eure Hilfe wäre ich sehr dankbar.
Opa Gilbert

**Comment by Sahel2021** [comment]
siehe [https://github.com/tkrebs/ep3-bs/issues/635](https://github.com/tkrebs/ep3-bs/issues/635)
und [https://github.com/Busfreak/ep3-bs/commit/4d37d7536e26e2a728026a2edf1fff304a3b3771](https://github.com/Busfreak/ep3-bs/commit/4d37d7536e26e2a728026a2edf1fff304a3b3771)

[Zu fern Buchung anzeigen](https://doku.tcf-platzreservierung.de/software/zu-fern-buchung-anzeigen)

**Comment by aulicus** [comment]
Problem gelöst, danke für die schnelle Hilfe.
