### ISSUE TITLE
Benutzer Emsiladresse ändern

### ISSUE THREAD

**Issue by mjmpeace** [tkrebs/ep3-bs#636]
Manchmal ändert sich die Emailadresse eines Benutzers. Wie kann ich die ändern? Versuche ich das in der Benutzerverwaltung speichert er die neue Mailadresse nicht, sondern gibt einen Fehler aus, die korrekte Mailadresse anzugeben. Die Mailadresse ist ja gleichzeitig das Login. Kann man das nur direkt in der Datenbank ändern?

**Comment by cbits68** [comment]
Bei mir geht das ohne Probleme in der Benutzerverwaltung. Welche Rechte hast Dein Benutzer, Verwaltung oder Mitarbeiter?
Die Fehlermeldung klingt ja so, als ob es eine Plausibilitätsprüfung bei der Mailadresse gibt und die Eingabe nicht plausibel ist.

**Comment by mjmpeace** [comment]
Es war ein Fehler in der Schreibweise. Ein Punkt zu wenig ;-)
Danke für den Hinweis.
