### ISSUE TITLE
Übersicht ausstehende Rechnungen

### ISSUE THREAD

**Issue by gitroli** [tkrebs/ep3-bs#64]
Hallo,

Ist es möglich im Backend eine Übersicht von ausstehenden Rechnungen zu erhalten?
Bzw. bei der Übersicht der Buchungen, wenn man den Rechnungsstatus sieht.

Danke für die Antwort.

**Comment by tkrebs** [comment]
Derzeit ist das noch nicht eingebaut. Es ist aber eine gute Idee, daher habe ich es in die Feature-Request-Liste des Buchungssystems aufgenommen.

**Comment by wklingberg** [comment]
Vielleicht könnte man diese Funktion in die erweiterte Suche bei der Benutzer-Verwaltung integrieren.

**Comment by tkrebs** [comment]
Ich habe ein zusätzliches Filter-Feld in der Buchungs-Verwaltung hinzugefügt, mit welchem neben ein paar weiteren Eigenschaften nun auch nach Rechnungsstatus gefiltert werden kann.

Das Update kann über GitHub heruntergeladen werden. Ausgetauscht werden müssen `/data/res/`, `/module/Backend/`, `/public/css/` und `/public/js/`.

**Comment by wklingberg** [comment]
Die Filterung nach Rechnungsstatus funktioniert. Vielen Dank.
"Bearbeitet" man aus der Trefferliste eine Buchung, landet man bei jeder Folgeaktion auf der "Kalender-Seite" und nicht auf der Trefferliste. Schon beim Aufruf einer Buchung gibt es nur den Navigationsbutton "Zurück zu Kalender".
