### ISSUE TITLE
Unterschiedliche Farben bei wiederholenden Buchungen

### ISSUE THREAD

**Issue by gitroli** [tkrebs/ep3-bs#65]
Hallo nochmal,

Ist das in CSS implementiert, dass ich zB auf 2 wöchig wiederholende Buchungen eine andere Farbe im Kalender hinterlegen kann, als auf wöchentlich wiederholende Buchungen?

Ich habe den Source Code durchgesehen, habe jetzt auf die Schnelle keine einfache Lösung gefunden, das zu verändern bzw. zu implementieren.

Danke für die Antwort.

**Comment by tkrebs** [comment]
Um Buchungen mit unterschiedlichen Intervallen unterscheiden zu können, müssten sie jeweils unterschiedliche CSS-Klassen erhalten. Das passiert derzeit nicht, wäre aber relativ einfach nachzurüsten.

**Comment by gitroli** [comment]
Danke für die rasche Antwort. Könnten Sie mir noch sagen, in welcher Datei ich die Zuweisung von multiple Buchungen zur CSS Klasse cc-multiple finde, dann sehe ich mir an, ob ich mehrere Klassen für unterschiedliche Wiederholungen erstellen kann. Danke

**Comment by tkrebs** [comment]
Die CSS-Klasse wird in der folgender Datei zugewiesen:

https://github.com/tkrebs/ep3-bs/blob/master/module/Calendar/src/Calendar/View/Helper/Cell/Render/OccupiedForVisitors.php

Dort stehen auch die PHP-Objekte für die Buchung und Reservierungen zur Verfügung, aus welchen sich ableiten lässt, ob und was für eine Intervall-Buchung vorliegt.

**Comment by gitroli** [comment]
Danke ich habe in der Datei den switch so umgebaut, funktioniert jetzt:

            switch ($booking->getMeta('repeat')) {
                case '7':
                    if (! $cellLabel) {
                        $cellLabel = $this->view->t('Subscription');
                    }

                    return $view->calendarCellLink($cellLabel, $view->url('square', [], $cellLinkParams), 'cc-multiple' . $cellGroup);
                case '14':
                    if (! $cellLabel) {
                        $cellLabel = $this->view->t('Subscription');
                    }

                    return $view->calendarCellLink($cellLabel, $view->url('square', [], $cellLinkParams), 'cc-multiple-14' . $cellGroup);
				default:
                    if (! $cellLabel) {
                        $cellLabel = $this->view->t('Occupied');
                    }

                    return $view->calendarCellLink($cellLabel, $view->url('square', [], $cellLinkParams), 'cc-single' . $cellGroup);
            }
