### ISSUE TITLE
Vergangene Zeitblöcke am gleichen Tag werden nicht als Vorbei markiert

### ISSUE THREAD

**Issue by gitroli** [tkrebs/ep3-bs#66]
Bei meiner Installation werden vergangene Zeitblöcke am gleichen Tag nicht als Vorbei markiert.
Diese werden nach wie vor als Frei angezeigt. Wenn man dann versucht zu buchen kommt zwar die Meldung, dass die Zeit schon vorbei ist, aber auf der bs.hbsys.de Demo Seite werden die vergangenen Zeitblöcke am gleichen Tag bereits als Vorbei markiert bzw. auch nicht ganz aktuell.

Ich würde das gerne Troubleshooten, habe aber keine Ahnung, wo ich anfangen soll?

**Comment by tkrebs** [comment]
Bist du vielleicht mit einem Benutzer angemeldet, welcher Sicht-Rechte auf den vergangenen Kalender hat?

Ansonsten ist diese Klasse relevant:

https://github.com/tkrebs/ep3-bs/blob/master/module/Calendar/src/Calendar/View/Helper/Cell/CellLogic.php

Dort insbesondere ab Zeile 20:

```
if ($walkingDate <= $now) {
    if (! ($user && $user->can('calendar.see-past'))) {
        return $view->calendarCell($this->view->t('Past'), 'cc-over');
    }
}
```

**Comment by gitroli** [comment]
Nein, ich bin gar nicht angemeldet, wenn ich auf den gestrigen Tag blättere, wird überall Vorbei angezeigt.
Ich checks mal.

**Comment by gitroli** [comment]
Wo und wann wird die $now Variable mit der aktuellen Datum bzw. Zeit zugewiesen?

**Comment by tkrebs** [comment]
Die Variable wird hier zugewiesen:

https://github.com/tkrebs/ep3-bs/blob/master/module/Calendar/src/Calendar/Controller/CalendarController.php#L69

**Comment by gitroli** [comment]
Mir fehlt irgendwie so eine if Abfrage, außer die Zeit ist bei der if Abfrage von dem vorherigen Post auch berücksichtigt?
		
if ($walkingTime < $timenow) {
			
            if (! ($user && $user->can('calendar.see-past'))) {
                return $view->calendarCell($this->view->t('Past'), 'cc-over');
            }
        }

**Comment by tkrebs** [comment]
Sowohl `$walkingDate` als auch `$now` sind DateTime-Objekte und beinhalten auch die Uhrzeit.

Eventuell ist die Zeitzone in den Einstellungen noch auf "America/New_York"?

**Comment by gitroli** [comment]
Nein sieht so aus:

<?php
/**
 * Local application configuration
 *
 * Insert your local database credentials here
 * and provide the email address the system should use.
 */

ini_set('date.timezone', 'Europe/Vienna');

return array(
    'db' => array(
        'database' => '######',
        'username' => '######',
        'password' => '#########',

        'hostname' => 'localhost',
        'port' => null,
    ),
    'mail' => array(
        'type' => 'sendmail', // or 'smtp' or 'smtp-tls'
        'address' => '######',

        'host' => '?', // for 'smtp' type only, otherwise remove or leave as is
        'user' => '?', // for 'smtp' type only, otherwise remove or leave as is
        'pw' => '?', // for 'smtp' type only, otherwise remove or leave as is

        'port' => 'auto', // for 'smtp' type only, otherwise remove or leave as is
    ),
    'i18n' => array(
        'locale' => 'de-DE',
        'currency' => 'EUR',
    ),
);

**Comment by gitroli** [comment]
Auch auf der Demoseite scheint es nur sporadisch zu funktionieren?
(siehe Bild)
Ich habe es mit Firefox und Chrome getestet.

![grafik](https://user-images.githubusercontent.com/31999445/30636143-04071392-9df5-11e7-884c-e92e38be2474.png)

**Comment by tkrebs** [comment]
In der Demo war die Zeitzone tatsächlich noch auf "America/New_York" eingestellt.
Ich habe es auf "Europe/Berlin" umgestellt und zumindest die Demo funktioniert damit.

**Comment by gitroli** [comment]
Ok habe auch mal von Europe/Vienna auf Europe/Berlin umgestellt, hat aber nichts gebracht. Ich versuche mal bei den Server Settings was zu finden. Zumindest konnte ich dir mal weiterhelfen :-)

**Comment by gitroli** [comment]
Könnte ich noch eine phpinfo von date haben von deinem Server. Bei mir sieht es so aus:
![img_0235](https://user-images.githubusercontent.com/31999445/30654823-68d3fcc4-9e2f-11e7-9adf-339dfacb7253.PNG)

**Comment by tkrebs** [comment]
Der Demo-Server hat die gleichen Werte, außer:

**"Olson" Timezone Database Version** steht auf **2016.10**
**Default timezone** sowie **date.timezone** steht auf **Europe/Berlin**

Letzteres dürfte allerdings keinen Unterschied machen, da diese Einstellung ohnehin zur Laufzeit überschrieben wird.

Vielleicht kannst du noch in der Datei

https://github.com/tkrebs/ep3-bs/blob/master/module/Calendar/src/Calendar/View/Helper/Cell/CellLogic.php

vor Zeile 20 einmal zum Testen die Variablen `$walkingDate` und `$now` ausgeben, um zu sehen, warum sie nicht in die if-Anweisung springen.

Zum Beispiel mit einem bedingunglosen:

`return $view->calendarCell($walkingDate->format('Y-m-d H:i:s') . ' > ' . $now->format('Y-m-d H:i:s'));`

**Comment by gitroli** [comment]
Die $now Variable passt nicht:
2017-09-21 08:00:00 > 2017-09-21 00:00:00

**Comment by gitroli** [comment]
Kann es sein das ich bei bei dem newDateTime Objekt die Timezone mitübergeb muss?

`// New Timezone Object
$timezone = new DateTimeZone('America/New_York');

// New DateTime Object
$date =  new DateTime('@1306123200', $timezone);  `

**Comment by gitroli** [comment]
Auch wenn ich das in der CalendarController.php testweise mache:
`$dateNow = new DateTime('2017-09-22 11:27:10');`
Steht bei der Ausgabe in den Zellen zwar das Datum was ich hier eingeb, aber Zeit 00:00:00

**Comment by tkrebs** [comment]
Hmmm ...

Ich habe gerade auch noch mal in den Code geschaut:

https://github.com/tkrebs/ep3-bs/blob/master/module/Calendar/src/Calendar/Controller/CalendarController.php

In Zeile 107 wird die Zeit von `$dateNow` unter bestimmten Bedingungen auf 0 gesetzt. Wenn du nicht angemeldet bist also inbesondere wenn `$squareManager->hasOneWithPublicNames() == true` ist.

**Comment by gitroli** [comment]
Ich habe diese Zeile testweise rausgelöcht, dann erhalte ich die aktuelle Zeit:
`$dateNow->setTime(0, 0, 0);`

Der Block sieht jetzt so aus:
`if ($getBookingUsers) {
            $userManager = $serviceManager->get('User\Manager\UserManager');
            $userManager->getByBookings($bookings);
       }`

Was macht dieser Block?
Buchungen vom aktuelle angemelden User anzeigen, wenn man auf Button Meine Buchungen klickt?

Ich habe bei mir eingestellt, das auch Besucher die Namen sehen dürfen.

**Comment by gitroli** [comment]
Ja nach dem rauslöschen dieser Zeile passt die Ansicht.
Ich nehme mal an du hast das bewusst so gemacht wenn man einstellt dass die Namen angezeigt werden, damit man noch vom ganzen Tag die Buchungen sieht? Wenn ein nicht angemeldeter Besuch allerdings auf Frei drückt und die Zeit schon um ist, kommt man auf eine Fehlerseite und das möchte ich vermeiden.

**Comment by tkrebs** [comment]
Ich habe es (im Entwicklungszweig) korrigiert.

So müsste der richtige Code aussehen:

```
if ($user && $user->can('calendar.see-data')) {
    $getBookingUsers = true;
    $dateNow->setTime(0, 0, 0);
}

if ($user && $squareManager->hasOneWithPrivateNames()) {
    $getBookingUsers = true;
}

if ($squareManager->hasOneWithPublicNames()) {
    $getBookingUsers = true;
}

if ($getBookingUsers) {
    $userManager = $serviceManager->get('User\Manager\UserManager');
    $userManager->getByBookings($bookings);
}
```

**Comment by gitroli** [comment]
Danke
