### ISSUE TITLE
Event-Ansicht für Einzelbuchungen und Abos

### ISSUE THREAD

**Issue by gitroli** [tkrebs/ep3-bs#67]
Ich würde gerne die Event-Ansicht:
![grafik](https://user-images.githubusercontent.com/31999445/30772818-d15274ca-a063-11e7-9635-8398e96dce7d.png)
Für Einzelbuchungen und Abos implementieren. Wenn zB jemand 2 Stunden am Stück bucht dass diese Zellen dann automatisch verbunden werden, das würde den Kalender übersichtlicher machen:
![grafik](https://user-images.githubusercontent.com/31999445/30772828-0b651c80-a064-11e7-8a46-ad3770a53f1b.png)

Könnte ich einen Tipp haben, welche Codeteile ich mir ansehen muss.

Danke

**Comment by tkrebs** [comment]
Technisch gesehen ist das "nur" ein zusätzliches Overlay über den eigenlichen Tabellenzellen und wird per JavaScript erstellt:

https://github.com/tkrebs/ep3-bs/blob/master/public/js/controller/calendar/index.js#L254

Theoretisch müsstest du den gesamten `$(".calendar-date-col").each(function(dateIndex) { ... })` Block einfach kopieren und an einigen Stellen anpassen können. Theoretisch.

**Comment by gitroli** [comment]
Ich habe jetzt testeweise mal bei folgender Funktion den gesamten Code rausgelöscht und die sieht jetzt so aus:
` function updateCalendarEvents()
{
;
}`

Es hat sich jetzt allerdings gar nichts verändert, die Eventdarstellung funktioniert noch ganz normal und es sind keine Fehler auf der Seite.
Ich wollte herausfinden, ob dann ev. die Overlays von der Eventansicht verschwinden, blieb aber alles gleich.

Ev. sind noch andere Funktionen beteiligt?

**Comment by gitroli** [comment]
Hab es jetzt geschafft, habe die Funktion einfach immer kopiert:
$(".calendar-date-col").each(function(dateIndex) { ... })
und dann habe ich cc-event auf cc-single geändert und so weiter

Jetzt werden die Zellen dementsprechend verbunden.
Allerdings habe ich jetzt das Problem, wenn man eine Zelle anklickt, das in der Zeitanzeige dann immer nur die erste Stunde angezeigt wird:
![grafik](https://user-images.githubusercontent.com/31999445/32327176-ddcfc98c-bfd5-11e7-85bb-8dbc59749637.png)

![grafik](https://user-images.githubusercontent.com/31999445/32327187-e94ec8f8-bfd5-11e7-954a-490b30b97507.png)

Mein Ziel wäre es, dass hier dann 17-19 Uhr steht für die Wohlmut Zelle.
Bei den Veranstaltungen funktioniert das.

Bitte nochmal um einen Tipp.
Danke

Du solltest das in der nächsten Version standardmäßig implementieren, das macht den Kalender um einiges übersichtlicher.

Danke nochmal

**Comment by gitroli** [comment]
Hier noch eine Zusatzinfo:
Es wird folgender Link generiert wenn man auf die Zelle klickt:
......../square?ds=2017-11-06&ts=17:00&te=18:00&s=2

Um mein Ziel zu erreichen müsste ein Link mit 19:00 Uhr generiert werden anstatt 18:00 Uhr

**Comment by tkrebs** [comment]
Technisch gesehen ist das Overlay, welches mehrere Zellen verbindet, eine Kopie der ersten Zelle und bekommt dementsprechend auch dessen URL.

Die URL könnte über JavaScript geändert werden, am besten kurz nachdem das Overlay erstellt worden ist. Das Skript müsste dann nur prüfen, welche Uhrzeit die letzte zusammenhängende Buchung hat und diese in der URL für "te" austauschen.

**Comment by gitroli** [comment]
ok, könnte ich auch den dateIndex in den attr bearbeiten
und aus der eventGroupCellLast das Enddatum bekommen
oder bin ich hier auf dem falschem Weg?

 /* Create event group overlay */

                    var eventGroupOverlay = $("#" + eventGroup + "-overlay-" + dateIndex);

                    if (! eventGroupOverlay.length) {
                        eventGroupOverlay = eventGroupCellFirst.clone();
                        eventGroupOverlay.appendTo( eventGroupCellFirst.closest("td") );
                        eventGroupOverlay.attr("id", eventGroup + "-overlay-" + dateIndex);
                        eventGroupOverlay.removeClass(eventGroup);

**Comment by tkrebs** [comment]
Das Enddatum bekommst du aus der URL ( `attr('href')` ) der letzten Zelle. Die Uhrzeit müsstest du dann z. B. per regulärem Ausdruck extrahieren.

Den dateIndex kannst du theoretisch bearbeiten, ich bin mir aber gerade nicht ganz sicher, wofür der überhaupt verwendet wird, abgesehen von der Nutzung als eindeutige ID.

**Comment by gitroli** [comment]
OK, ich habe jetzt den Link extrahiert in eine Variable timelink:
Der Inhalt der Variable ist jetzt so:
/square?ds=2017-11-06&ts=17:00&te=19:00&s=2

Also der richtige Link jetzt, wie kann ich diesen Link jetzt dem Overlay zuweisen?
Mein Versuch wäre:
eventGroupOverlay.attr("href") = timelink;

Leider funktioniert das nicht so wie erwartet.

**Comment by gitroli** [comment]
Hier ist mein ganzer Codebaustein, die Variable startTimeLink beinhaltet den richtigen Link:

                    /* Create event group overlay */

                    var eventGroupOverlay = $("#" + eventGroup + "-overlay-" + dateIndex);

                    if (! eventGroupOverlay.length) {
						var endTimeLink = eventGroupCellLast.attr("href");
						endTimeLink = endTimeLink.split("&te=");
						endTimeLink = endTimeLink[endTimeLink.length-1];                        
						var startTimeLink = eventGroupCellFirst.attr("href");
						startTimeLink = startTimeLink.split("&te=");
						startTimeLink = startTimeLink[0];
						startTimeLink = startTimeLink + "&te=" + endTimeLink;
											
                        eventGroupOverlay = eventGroupCellFirst.clone();
			eventGroupOverlay.appendTo( eventGroupCellFirst.closest("td") );
                        eventGroupOverlay.attr("id", eventGroup + "-overlay-" + dateIndex);
                        eventGroupOverlay.attr("href") = startTimeLink ;
                        eventGroupOverlay.removeClass(eventGroup);
                    }

**Comment by tkrebs** [comment]
Die Zuweisung funktioniert unter jQuery so:

`eventGroupOverlay.attr("href", startTimeLink);`

**Comment by gitroli** [comment]
Danke, die squarebox sieht jetzt so aus:
![grafik](https://user-images.githubusercontent.com/31999445/32575622-d3db659a-c4d4-11e7-8bf6-3f07deaa5508.png)

Eine Kleinigkeit ist noch, ich habe eingestellt, dass ein aktivierter Benutzer max 180 min am Stück buchen kann.
Klickt er jetzt allerdings auf ein Abo welches 4 Stunden am Stück ist, bekommt der Benutzer keine Squarebox angezeigt, dass der Platz von zB 11-15 Uhr belegt ist, sondern diese Meldung:
![grafik](https://user-images.githubusercontent.com/31999445/32575797-4a6ab3fa-c4d5-11e7-96b4-d465f4442ac4.png)

Meine Idee wäre jetzt, die Überprüfung bei der Anzeige der Squarebox "belegt" zu deaktivieren, wo finde ich diesen Codeteil?

**Comment by gitroli** [comment]
Habs in der SquareValidator.php gefunden.
Danke nochmal für die Hilfe.
