### ISSUE TITLE
base module not found

### ISSUE THREAD

**Issue by jasson09** [tkrebs/ep3-bs#69]
Hi.
Ich hab die Software über die Webseite downgeloadet, also das fertige Paket.
Bin nach der Anleitung vorgegangen. Beim Aufruf der setup.php kommt die Meldung "base module not found".
Auf was habe ich vergessen?
Danke schon Mal.

**Comment by tkrebs** [comment]
Gibt es die Datei

`module/base/Charon.php`

in deiner Installation und ist diese mit ausreichenden UNIX-Dateiberechtigungen (also lesbar für PHP) ausgestattet?

**Comment by jasson09** [comment]
Ich bin das Ganze nochmals von vorne angegangen. Hab mir das Repository hier runtergeladen.
Habe Composer installiert, danach hat er den Ordner /vendor erzeugt. Subdomain auf /public verwiesen. config/autoload/local.php mit den Zugangsdaten für die Datenbank befüllt. CHMOD auf die genannten Ordner in der Doku. Und ab dem Aufruf der setup.php/ kommt oben genannte Fehlermeldung. Grundsätzlich sollten alle Systemvoraussetzungen erfüllt sein bei meinem Webhoster. 
In dem Zug möchte ich Dir auch für deine Software danken und für deine Unterstützung!

**Comment by tkrebs** [comment]
Versuche mal testweise, den `module` und `vendor` Ordner jeweils mit chmod auf maximale Lese-Berechtigungen umzustellen (also 07xx).

**Comment by jasson09** [comment]
Hi.
Hat sich erledigt. Ich hab meine SubDomain Pfad geändert und dann konnte ich die setup.php ausführen. Ich hab jetzt ein anderes Problem, werde das aber neu aufmachen, damit es nachvollziehbar ist. Danke.

**Comment by larsrich** [comment]
Hallo!
Leider habe ich das selbe Problem.
Die oben genannte Datei ist vorhanden und die Änderung der Leseberechtigung habe ich auch ausprobiert.
Hat jemand noch eine andere Idee / Lösung?
Vielen Dank schonmal!
