### ISSUE TITLE
Usern - Plätze zuordnen

### ISSUE THREAD

**Issue by jet2future** [tkrebs/ep3-bs#7]
Hi,

besteht die möglichkeit gewisse Plätze nur gewissen Usern zuzuordnen?

Hab Reklamationen das zu viele Plätze sichtbar sind Da wir eine BS Instanz für alle Standorte haben und dies Verwaltungstechnisch auch einfacher ist.

Beste Grüße

**Comment by tkrebs** [comment]
Derzeit ist soetwas nicht möglich. Die Frage wäre auch, ob so eine Funktion überhaupt sinnvoll ist, oder ob man das Problem nicht eleganter lösen kann?
