### ISSUE TITLE
Fleet management

### ISSUE THREAD

**Issue by danielberlin** [tkrebs/ep3-bs#71]
Do you have any intention to extend the booking of cars as well? I'm thinking of tracking certain fields such as driven kilometres, maintenance/TÜV. Not for car rental but for organization-internal transparent visibility and management how cars are used and by whom (HiOrg/aid organization).

**Comment by tkrebs** [comment]
Interesting idea. I think the booking system could be well suited for that use case. However, it is difficult to anticipate the real world requirements of such an extension without an actual organization willing to test and evaluate it.

**Comment by danielberlin** [comment]
I have an organization to test and evaluate. :-)

**Comment by tkrebs** [comment]
It would be great if you could send me the requirements your organization has on such fleet management system:

info@bs.hbsys.de

It doesn't have to be perfectly worked out, just clarifying enough so that I could elaborate the extensions necessary to the booking system.

Thank you.

**Comment by danielberlin** [comment]
OK, will prepare the requirements and send it via email hopefully by next week.
