### ISSUE TITLE
E-Mail Adresse geändert

### ISSUE THREAD

**Issue by jasson09** [tkrebs/ep3-bs#72]
Hi. Hab bei meinem Admin User die E-Mail Adresse geändert. 
Danach hab ich einen Aktivierungslink bekommen. Nach Aufruf bin ich nun kein Admin mehr. 
Ist dies Absicht? Wie kann ich das wieder ändern? :/
Ich finde bei php Admin unter bs_users nicht das Feld Groups, etc. 

Danke.

**Comment by jasson09** [comment]
Okay, unter php Admin hab ich es gefunden bei den bs_users unter status:
**placeholder|deleted|blocked|disabled|enabled|assist|admin**
Kann man das ändern, dass wenn ich die E-Mail ändere nicht gleich aus der Admingruppe fliege?

**Comment by tkrebs** [comment]
Danke für den Hinweis, ist (im Entwicklungszweig) korrigiert.

Admins sollten User-Änderungen (inklusive am eigenen Zugang) allerdings vorzugsweise über die Benutzerverwaltung durchführen.
