### ISSUE TITLE
Aktivierter Benutzer Abo stornieren

### ISSUE THREAD

**Issue by gitroli** [tkrebs/ep3-bs#73]
Wenn ein Abo einem aktivierten Benutzer zugewiesen ist und dieser sich dann einloggt und es anklickt kommt folgende Fehlermeldung (siehe unten).
Kann man die Fehlermeldung auch eleganter darstellen?

Der Code ist hier:
`        if ($booking->need('status') == 'subscription') {
            throw new RuntimeException('You have no permission to cancel this subscription');
        }
`

`Fatal error: Uncaught RuntimeException: You have no permission to cancel this subscription in /var/www/vhosts/module/Square/src/Square/Service/SquareValidator.php:299 Stack trace: #0 /var/www/vhosts/module/Square/view/square/square/index.own.phtml(9): Square\Service\SquareValidator->isCancellable(Object(Booking\Entity\Booking)) #1 /var/www/vhosts/vendor/zendframework/zendframework/library/Zend/View/Renderer/PhpRenderer.php(501): include('/var/www/vhosts...') #2 /var/www/vhosts/vendor/zendframework/zendframework/library/Zend/View/Helper/Partial.php(61): Zend\View\Renderer\PhpRenderer->render(NULL, NULL) #3 [internal function]: Zend\View\Helper\Partial->__invoke('square/square/i...', Array) #4 /var/www/vhosts/vendor/zendframework/zendframework/library/Zend/View/Renderer/PhpRenderer.php(393): call_user_func_array(Object(Zend\View\Helper\Partia in /var/www/vhosts/module/Square/src/Square/Service/SquareValidator.php on line 299`

**Comment by tkrebs** [comment]
Danke für den Hinweis, ich habe es soeben korrigiert: Jetzt öffnet sich das normale Buchungs-Fenster.

**Comment by gitroli** [comment]
OK, was für Dateien muss ich austauschen?
Nur die SquareValidator.php? aus dem master Zweig?

**Comment by tkrebs** [comment]
Ja, diese Datei reicht aus.

**Comment by gitroli** [comment]
Danke, habe den Code geändert, die return Werte, weil ich es aus der 1.6 Version zip Datei aufgesetzt habe das System und wenn ich diese Datei tausche kommt sonst wieder ein neuer Fehler.
