### ISSUE TITLE
New install

### ISSUE THREAD

**Issue by katamiaw** [tkrebs/ep3-bs#76]
Hello,

I don't see it on the install doc:
https://github.com/tkrebs/ep3-bs/blob/master/data/docs/install.txt

For a new install, you have to rename https://github.com/tkrebs/ep3-bs/blob/master/config/init.php.dist into init.php

**Comment by tkrebs** [comment]
You do not have to rename the init.php.dist - it is only there if you want to enable debug mode in a update safe way.

**Comment by katamiaw** [comment]
So my expérience: without rename ini.php.dist, i have a blank page and i can't setup the script.

**Comment by tkrebs** [comment]
I don't know why it's not working in your setup. I just tried it without the init.php and it works as expected.

**Comment by adflowdmueller** [comment]
Same as me: works as i rename init.php.dist to init.php.
But: as I try to login, path is referenced by <subdomain>/public/user/login, which does not exist.....

**Comment by tkrebs** [comment]
This has been fixed by now.
