### ISSUE TITLE
Benutzer erlauben in der Vergangenheit zu buchen

### ISSUE THREAD

**Issue by gitroli** [tkrebs/ep3-bs#77]
Hallo,
ich brauche nochmal Hilfe.
Ich möchte aktivierten Benutzern erlauben, dass sie 1h in der Vergangenheit buchen können.
Ansicht habe ich bereits so gelöst:
    protected function determineCell($walkingDate, $walkingTime, $timeBlock, $now, $square, $user, $reservationsForCol, $eventsForCol)
    {
        $view = $this->getView();

        if ($walkingDate <= $now->modify('-1 hour')) {
			$now->modify('+1 hour');
            if (! ($user && $user->can('calendar.see-past'))) {
                return $view->calendarCell($this->view->t('Past'), 'cc-over');
            }
        }
		$now->modify('+1 hour');

Wo kann ich einstellen, dass dann diese Meldung nicht kommt und ich buchen kann:
![grafik](https://user-images.githubusercontent.com/31999445/33083451-b4f8f54c-cedf-11e7-994f-7245908093ec.png)

**Comment by tkrebs** [comment]
Schau mal hier:

https://github.com/tkrebs/ep3-bs/blob/master/module/Square/src/Square/Service/SquareValidator.php#L119

**Comment by gitroli** [comment]
OK, Danke habe den Block in der Square Validator auskommentiert.
