### ISSUE TITLE
Falsche Buchungen bei 30min Zeitblöcken

### ISSUE THREAD

**Issue by gitroli** [tkrebs/ep3-bs#78]
Ich habe folgende Einstellungen bei den Plätzen:
![grafik](https://user-images.githubusercontent.com/31999445/33120652-0db2ac9e-cf73-11e7-9ea8-de645cecc656.png)
Wenn ich als aktivierter Benutzer 1 Stunde buche:
![grafik](https://user-images.githubusercontent.com/31999445/33120706-3b5f7d20-cf73-11e7-91ca-319649a974cd.png)
Dann ist die Anzeige folgendermaßen im Kalender:
![grafik](https://user-images.githubusercontent.com/31999445/33120814-789186fc-cf73-11e7-8b36-8d7ce0cbc61b.png)

Also es werden nur 30 min gebucht, buche ich 2 Stunden passt alles, nur wenn 1 Stunde gebucht wird, tritt das Problem auf.
Ich habe es auch nochmal mit den Original Installationsdateien versucht, da ich nun doch schon viele Anpassungen habe, aber hier ist es das gleiche.

**Comment by tkrebs** [comment]
Welcher Zeitraum steht denn nach der Buchung in der Verwaltung?

**Comment by gitroli** [comment]
Da steht auch 15-15:30

Am 22.11.2017 um 15:07 schrieb Tobias Krebs <notifications@github.com<mailto:notifications@github.com>>:


Welcher Zeitraum steht denn nach der Buchung in der Verwaltung?

-

**Comment by tkrebs** [comment]
Okay, ich teste das mal mit gleichen Einstellungen bei mir und gebe dir dann Rückmeldung.

**Comment by gitroli** [comment]
Bist du schon dazu gekommen es zu testen?

Danke

**Comment by tkrebs** [comment]
Leider noch nicht, habe ich mir aber für das kommende Wochenende vorgenommen.

**Comment by gitroli** [comment]
ich habe das Problem eingrenzen können und zwar wird der Link so übergeben in 30min:
![grafik](https://user-images.githubusercontent.com/31999445/33807632-1c9bcfea-ddda-11e7-87f8-26b375169cbe.png)

Workaround:
Bei der Dropdown auf eine andere Zeit schalten und wieder zurück schalten dann wird 1 Stunde gebucht.
![grafik](https://user-images.githubusercontent.com/31999445/33807677-acc7efae-ddda-11e7-80dc-464e2416955d.png)

Lösungsansatz: Könnte man, wenn 30 min Zeitblöcke eingestellt sind, 30min bei te hinzuaddieren.

**Comment by tkrebs** [comment]
Der Fehler wurde im Entwicklungszweig behoben. Konkret wurde folgende Datei korrigiert:

https://github.com/tkrebs/ep3-bs/commit/752cdf049b4c9589997b05c76549a68c936be2d8
