### ISSUE TITLE
Bei Installation werden vergangene Stunden am gleichen Tag nicht als "Vorbei" angezeigt

### ISSUE THREAD

**Issue by wklingberg** [tkrebs/ep3-bs#79]
Bei meiner Installation werden die vergangenen Stunden des gleichen Tages nur als "Vorbei" angezeigt, wenn man noch nicht angemeldet ist.
Ein "aktivierter Benutzer" erhält "Frei".
Beim Versuch zu buchen, kommt die Meldung "Oops ... da ist wohl etwas schief gelaufen **Das ist bereits vorbei**".

**Comment by tkrebs** [comment]
Ist der Benutzer wirklich auf "Aktivierter Benutzer" gestellt? Dann darf das eigentlich nicht vorkommen. Hast du manuelle Änderungen am System vorgenommen oder ist es eine Standard-Installation?

**Comment by wklingberg** [comment]
Der Benutzer ist auf "Aktivierter Benutzer" gestellt und es ist eine Standard-Installation.

**Comment by tkrebs** [comment]
Ist das betroffene Buchungssystem online erreichbar? Ansonsten wüsste ich gerade nicht, woran das noch liegen könnte. Eventuell noch mal die aktuellste Version herunterladen (sofern nicht schon geschehen).

**Comment by wklingberg** [comment]
Das System ist unter http://klingberg01.bn-paf.de/EP3 erreichbar.

**Comment by wklingberg** [comment]
Nach Übernahme der Entwickler-Module wird jetzt korrekt "Vorbei" angezeigt.

**Comment by geopicture** [comment]
Was genau hast du bei "Übernahme der Entwickler-Module" gemacht? Die neuesten Module vom github repo verwendet?

**Comment by geopicture** [comment]
siehe #66

**Comment by wklingberg** [comment]
Ich hatte Ende Dezember die Version 1.6 geholt.
