### ISSUE TITLE
E-Mail-Benachrichtigung

### ISSUE THREAD

**Issue by zcara** [tkrebs/ep3-bs#8]
Hallo,

besteht evtl. die Möglichkeit, die E-Mail-Benachrichtigung, welche bei Buchung/ Stornierung an "Aktvierte Benutzer" gesendet werden, zusätzlich an "Verwaltung" und/oder "Mitarbeiter" zu senden?

Vielen Dank.
zcara

**Comment by tkrebs** [comment]
Ich habe diese Möglichkeit als Option unter "Einstellungen > Namen und Texte" hinzugefügt.

**Comment by zcara** [comment]
Funktioniert. Vielen Dank.

Eine kleine Sache: ist bei der Stornierung gerade aufgefallen. Die Mail wird nicht auf deutsch übersetzt. 
Stört jetzt aber nicht so sehr...

**Comment by tkrebs** [comment]
Ich habe die fehlende Übersetzung repariert. Zudem habe ich in der E-Mail an die Verwaltung noch Name und E-Mail Adresse des betroffenen Benutzers hinzugefügt.

**Comment by RSalLich** [comment]
Erstmal vielen Dank für das tolle Programm. Habe ein Problem bei der Emailbenachrichtigung. Wenn sich ein User registriert, bekommt er die Mail mit dem Aktivierungslink. Bucht er, oder storniert, bekommt er keine Mail, ich als Verwalter bekomme aber die Kopie. Woran kann es liegen? Und wo kann ich den Text, der in der Mail drin steht, ändern? Vielen Dank.

**Comment by tkrebs** [comment]
Jeder Benutzer kann in seinen Einstellungen auswählen, ob er bei Buchungen und Stornierungen E-Mails erhalten möchte. Standardmäßig sind die jedoch ausgeschaltet. Die Verwaltungs-E-Mails werden hingegen immer geschickt, sofern die entsprechende Einstellung gesetzt ist.

Der Text kann derzeit leider nur "manuell" im Quellcode geändert werden. Könnte man mal als ToDo aufnehmen, hier noch eigene Anmerkungen eingeben zu können.

**Comment by RSalLich** [comment]
Vielen Dank für den Hinweis. Wäre es möglich, dass die Buchungs- und Stornierungsmails standardmäßig eingeschaltet sind? Nur wenn es den Benutzer "nervt", sollte er es auschalten können.

**Comment by tkrebs** [comment]
Ich habe es entsprechend umgestellt, E-Mail-Benachrichtigungen sind nun standardmäßig eingeschaltet. Die Änderung befindet sich derzeit nur im Entwicklungszweig:

https://github.com/tkrebs/ep3-bs/tree/develop

**Comment by RSalLich** [comment]
Vielen Dank. Ich denke, so ist es sinnvoller.
