### ISSUE TITLE
Benutzerdaten löschen bei offenen Buchungen

### ISSUE THREAD

**Issue by wklingberg** [tkrebs/ep3-bs#80]
Bei meiner Installation kann ein Benutzer über "Meine Daten" die Funktion "Benutzerkonto löschen" ohne Hinweis oder Warnung ausführen, auch wenn noch offene Buchungen vorhanden sind.

**Comment by tkrebs** [comment]
Wenn der Benutzer sein Konto über "Meine Daten" löscht, wird das Konto intern nur auf Status "Gelöscht" gesetzt, bleibt aber (und damit auch seine potenziellen Buchungen) technisch vorhanden.

**Comment by wklingberg** [comment]
Es ist richtig, dass beim Löschen der Benutzer den Status "Gelöschter Benutzer" erhält und auch seine aktiven Buchungen bestehen bleiben. Aus meiner Sicht sollte es den Zustand "Aktive Buchungen eines gelöschten Benutzers" nicht geben und deshalb bei vorhandenen aktiven Buchungen das Löschen mit einer entsprechenden Meldung verhindert werden.

**Comment by tkrebs** [comment]
Dass man als Benutzer sein eigenes Konto "löschen" kann dient doch, wie mittlerweile überall im Internet, nur dazu, das Gefühl von Kontrolle zu vermitteln. Und das sollte man dann auch gewähren, unabhängig davon ob Buchungen bestehen oder nicht.

**Comment by wklingberg** [comment]
Der Aufwand, seine Buchungen vorher zu stornieren, wäre für den Benutzer gering. Damit würden die Plätze wieder freigegeben und die Buchungskosten vermieden. Es wäre auch im Internet gut, wenn der Anwender seine eingestellten Daten explizit löschen könnte, bevor er sich abmeldet.
