### ISSUE TITLE
Umschalten auf Englisch

### ISSUE THREAD

**Issue by wklingberg** [tkrebs/ep3-bs#81]
Kann die Umschaltmöglichkeit auf Englisch, also die kleine Flagge rechts oben, per Einstellung unterdrückt werden?

**Comment by tkrebs** [comment]
Das müsste durch folgende Einstellung in der `config/autoload/local.php` funktionieren:

```php
'i18n' => array(
    ...
    'choice' => false,
),`

**Comment by wklingberg** [comment]
Die Änderung im local.php in 
    'i18n' => array(
        'locale' => 'de-DE',
        'currency' => 'EUR', 'choice' => false,
    ),
führt zu dem Fehler
Warning: Invalid argument supplied for foreach() in /var/www/vhosts/klingberg01.bn-paf.de/httpdocs/EP3/module/Base/src/Base/Manager/Listener/ConfigLocaleListener.php on line 59

**Comment by tkrebs** [comment]
Okay, versuch mal alternativ:

```php
'choice' => [],

**Comment by wklingberg** [comment]
'choice' => [], in der local.php hat nichts gebracht.
Habe in der global.php  den Eintrag 'en-US' => 'English', entfernt. Jetzt ist nur noch die deutsche Flagge zu sehen.
