### ISSUE TITLE
Keine Benachrichtigung trotz Aktivierung

### ISSUE THREAD

**Issue by wklingberg** [tkrebs/ep3-bs#82]
Obwohl für den "Aktivierten Benutzer" im Bereich "Meine Daten > Benachrichtigungen" die Checkbox "Bei Buchungen und Stornierungen" gesetzt ist, erhält er weder bei einer Buchung noch bei einer Stornierung eine Benachrichtigung per Mail. Die Kopie an den Admin wird jeweils versandt.

**Comment by tkrebs** [comment]
Probier mal den E-Mail-Versand per SMTP. Vielleicht wird die E-Mail an die Kunden-Adresse blockiert.

**Comment by wklingberg** [comment]
Die Kunden-Adresse ist mein privater E-Mail-Account. Der funktioniert und es ist auch keine Buchungs-Mail im Spam-Ordner.

**Comment by tkrebs** [comment]
Manche E-Mail-Hoster sind da strenger als andere und blockieren bestimmte E-Mails.

**Comment by wklingberg** [comment]
Hallo Tobias,
es lag an dem nicht geänderten Wert von "mail > address" in der Datei / config / autoload / 
local.php . Es stand noch "info@bookings.example.com" drin.
