### ISSUE TITLE
Buchungsmaske

### ISSUE THREAD

**Issue by Joysdesign** [tkrebs/ep3-bs#83]
Kann man die Buchungsmaske für den Admin, auch freigeben für Buchungen für normale Benutzer?

Ich würde gerne als normaler Benutzer auch die Möglichkeit haben, Notizen
anzufügen.
Bzw. in welcher Datei liegt die Eingabemaske?

**Comment by tkrebs** [comment]
Das Buchungsformular für Admins dafür zu verwenden wird schwer, da hängen zu viele Berechtigungsprüfungen dran.

Einfacher wäre da schon, ein zusätzliches Notizen-Eingabefeld in den normalen Buchungsprozess mit einzubauen. Technisch ist das nicht schwierig, erfordert aber ein paar Programmierkenntnisse.

Die sinnvollsten Dateien dafür wären vermutlich:

https://github.com/tkrebs/ep3-bs/blob/master/module/Square/view/square/booking/customization.phtml
für das Formular und

https://github.com/tkrebs/ep3-bs/blob/master/module/Square/src/Square/Controller/BookingController.php
für die Verarbeitung

**Comment by Joysdesign** [comment]
Ok. Danke für die schnelle Antwort.
Werde mich mal dran versuchen....

**Comment by gitroli** [comment]
Ich versuche hier auch gerade etwas, ich möchte dass der aktivierte Benutzer die Buchung dann auf einen anderen Benutzer buchen kann. Ich suche gerade im Code wo der Buchung bei einem aktivierten Benutzer der aktuelle Benutzer übergeben wird?

**Comment by gitroli** [comment]
Hintergrund ist, es soll vor Ort ein Buchungsterminal aufgestellt werden und hier ist ein Terminaluser ständig angemeldet und man soll dann im Buchungsprozess einfach den tatsächlichen User auswählen können. Der Terminaluser soll aber trotzdem Preise angezeigt bekommen und nur 14 Tage im Voraus buchen, ...

**Comment by tkrebs** [comment]
Prinzipiell wird der Benutzer, auf den gebucht werden soll, hier ganz einfach als erstes Argument an den BookingService übergeben:

https://github.com/tkrebs/ep3-bs/blob/master/module/Square/src/Square/Controller/BookingController.php#L179

Da kann natürlich auch jeder andere Benutzer übergeben werden, sollte er wie auch immer bekannt sein.

**Comment by gitroli** [comment]
OK super.
Jetzt möchte ich noch im Formular:
https://github.com/tkrebs/ep3-bs/blob/master/module/Square/view/square/booking/customization.phtml

Ein User Eingabefeld hinzufügen.
Mit diesen Zeilen hätte ich es mal versucht:
<table class="default-table">
                        <?= $this->formRowCompact($form, 'bf-user') ?>
                    </table>

                    <?php if ($this->booking && $this->booking->getExtra('user')): ?>
                        <?php $user = $this->booking->getExtra('user') ?>

Komme aber irgendwie nicht weiter. Die Zeilen habe ich aus dem edit.phtml kopiert.
Hast du nochmal einen Codevorschlag für mich.

Danke.

**Comment by tkrebs** [comment]
Grundsätzlich der richtige Ansatz, aber natürlich ist nie etwas so einfach wie es sein sollte ... ;)

Die Daten im "Customization"-Schritt werden nicht als klassisches Formular abgesendet, sondern per JavaScript an die "Weiter"-URL angehangen. Das heißt, du brauchst prinzipiell ein einfaches HTML-Eingabefeld und musst dann mit JavaScript auf Änderungen darauf prüfen, vergleiche hier:

https://github.com/tkrebs/ep3-bs/blob/master/public/js/controller/square/booking/customization.js#L15

**Comment by gitroli** [comment]
Habe jetzt die index.free.phtml folgendermaßen angepasst:
![grafik](https://user-images.githubusercontent.com/31999445/33705852-3724b426-db32-11e7-89f7-4fd0f0741fe5.png)

Das Gebucht auf Textfeld ist folgender Code:
<input type="text" name="gebuchtauf">

Jetzt möchte ich, dass ich hier den Usernamen eingeben kann auf den gebucht wird.
Am besten wäre es, wenn sie auch ausgelesen werden so wie im edit Mode.

Oder vielleicht ist dieser Ansatz leichter:
Wenn im 2. Schritt ich 2 Spieler auswähle und dann das Feld Spielername 2 erscheint:
![grafik](https://user-images.githubusercontent.com/31999445/33706321-0ec8455e-db34-11e7-8bd7-6f13aa7358d3.png)

Das auf den Usernamen gebucht wird, welchen ich hier bei Spieler 2 eingebe.
Ist dieser Ansatz einfacher zu realisieren?

**Comment by tkrebs** [comment]
Ich würde empfehlen, in das "Gebucht auf"-Feld die E-Mail-Adresse des Benutzers eintragen zu lassen und den entsprechenden Benutzer darüber im Controller zu finden und einzutragen.

Hintergrund: Die Vorschlag-Funktion aus dem Edit-Mode ist nicht für die "Öffentlichkeit" geeignet, da darüber tendenziell alle Benutzer(-namen) des Systems von jedem eingesehen werden können. Das ist ein großes Datenschutzproblem.

**Comment by gitroli** [comment]
ok verstehe, könntest du mir trotzdem diese Frage beantworten:
Und zwar wenn ein aktivierter Benutzer den edit Modus aufrufe kommt folgende Meldung:
![grafik](https://user-images.githubusercontent.com/31999445/33717914-f3f95e3e-db5b-11e7-855f-8b3f0dd0a5b3.png)

Wo im Code kann ich diese Rechte Überprüfung abschalten?

Hintergrund: Das Terminal welches vor Ort aufgestellt ist, betreibe ich unter einer anderen URL wo spezielle Anpassungen im Interface gemacht wurden. Dann passiert diese Anpassung auch nur für das Terminal und nicht für die anderen User.

**Comment by tkrebs** [comment]
Das kommt auf den Controller an, der die Prüfung durchführt.

Generell gibt es in jedem Controller folgende Zeile:

https://github.com/tkrebs/ep3-bs/blob/master/module/Backend/src/Backend/Controller/BookingController.php#L70

Wenn diese Zeile entfernt wird, findet keine Überprüfung mehr statt. Es kann aber noch weitere Aufrufe von `->authorize()` geben.

**Comment by tkrebs** [comment]
Nachtrag: Falls mit dem Aufruf von `authorize()` direkt die `$sessionUser`-Variable deklariert wird, müsste es statt Entfernen der Zeile lauten:

`$sessionUser = $this->authorize();`

**Comment by gitroli** [comment]
ok, ich bin fast am Ziel, ich kann das edit Formular jetzt als aktivierter Benutzer aufrufen.
Danach drücke ich allerdings auf Speichern, dann kommt wieder die Meldung, dass ich das nicht darf.
Hier habe ich bereits bei allen ->authorize() alles aus der Klammer gelöscht.
https://github.com/tkrebs/ep3-bs/blob/master/module/Backend/src/Backend/Controller/BookingController.php

Ist beim edit Formular, wenn man auf Speichern drückt, ein anderer Controller im Spiel?

**Comment by gitroli** [comment]
Mir ist gerade noch was eingefallen, wie ich vielleicht leichter zu meinem Ziel komme:
Ev. könnte ich beim Starten des edit Formular die Userrolle des Terminalusers von enabled auf assist stellen und beim Speichern des edit Formulars wieder auf enabled.

**Comment by gitroli** [comment]
Kannst du hierzu noch helfen?
Wäre sehr gut, wenn ich nochmal einen Tipp bekomme. 
Danke

**Comment by tkrebs** [comment]
Wenn der Benutzer dann alledings das Formular aufruft und ohne Speichern wieder verlässt hat er dauerhaft erhöhte Rechte.

Grundsätzlich kannst du den Status per

```php
$user->set('status', 'assist');

$user->setMeta('allow.calendar.see-data', 'true');
```

einstellen, sowie, falls du dir Zwischendaten merken willst, per

```php
$user->setMeta('original_status', 'enabled');

$originalStatus = $user->getMeta('original_status');
```

Entgültig in der Datenbank gespeichert werden die Änderungen dann über den UserManager:

```php
$userManager->save($user);
```

**Comment by gitroli** [comment]
Danke der Hinweis hat mir geholfen, ich bin am Ziel

**Comment by azich01** [comment]
wäre mal interessant gewesen , zu sehen wie deine Lösung jetzt aussieht.
Gruß
Andreas

**Comment by gitroli** [comment]
![grafik](https://user-images.githubusercontent.com/31999445/62692318-bc992500-b9d0-11e9-8c13-1ef51a02e5e8.png)

**Comment by gitroli** [comment]
a sorry das war der falsche screenshot, was genau möchtest du sehen

**Comment by azich01** [comment]
a. wie die Buchungsmaske mit den Notizen jetzt aussieht
b. Welche Dateien, wie verändert wurden.
Wir bräuchten auch die Möglichkeit bei der Buchung Notitzen einzufügen.

Gruß
Andreas

**Comment by tkrebs** [comment]
Im Entwicklungszweig ist vorige Woche eine Einstellung
"Erlaube optionale Anmerkungen bei der Buchung"
pro Platz hinzugekommen:

https://github.com/tkrebs/ep3-bs/commit/11493eb974eedb2f559145d98bcecf83b372a3aa

Diese bewirkt ein Freitext-Eingabefeld für optionale Anmerkungen beim Buchen.
