### ISSUE TITLE
E-Mail Benachrichtigung an Benutzer und Systemadmin wenn Buchung von Admin erstellt wird

### ISSUE THREAD

**Issue by gitroli** [tkrebs/ep3-bs#86]
Ist es möglich eine E-Mail Benachrichtigung zu versenden an Benutzer und Systemadmin, wenn die Buchung von Admin erstellt wird?

**Comment by tkrebs** [comment]
Derzeit nicht, ist aber eine gute Idee. Ich habe es auf die Feature-Liste geschrieben.

**Comment by gitroli** [comment]
ok danke

**Comment by gitroli** [comment]
Ich brauche hier doch vorab eine kleine Hilfe, weil ich jetzt das Problem habe, wenn vor Ort am Terminal gebucht wird, das erfolgt über das Edit Formular, keine Mailbenachrichtigung an den Sysadmin geschickt wird und es somit leider schon vorgekommen ist, dass wenn der Hallenbetreiber nicht online im Plan nachgesehen hat, dass die Halle versperrt war, da er sich ansonsten immer auf die Mails verlässt.

Ich habe folgenden Codeblock im NotificationListener.php gefunden:
`public function onCreateSingle(Event $event)
    {
        $booking = $event->getTarget();
        $reservation = current($booking->getExtra('reservations'));
        $square = $this->squareManager->get($booking->need('sid'));
        $user = $this->userManager->get($booking->need('uid'));

        $dateFormatHelper = $this->dateFormatHelper;
        $dateRangerHelper = $this->dateRangeHelper;

	    $reservationTimeStart = explode(':', $reservation->need('time_start'));
        $reservationTimeEnd = explode(':', $reservation->need('time_end'));

        $reservationStart = new \DateTime($reservation->need('date'));
        $reservationStart->setTime($reservationTimeStart[0], $reservationTimeStart[1]);

        $reservationEnd = new \DateTime($reservation->need('date'));
        $reservationEnd->setTime($reservationTimeEnd[0], $reservationTimeEnd[1]);

        $subject = sprintf($this->t('Your %s-booking for %s'),
            $this->optionManager->get('subject.square.type'),
            $dateFormatHelper($reservationStart, \IntlDateFormatter::MEDIUM, \IntlDateFormatter::SHORT));

        $message = sprintf($this->t('we have reserved %s %s, %s for you. Thank you for your booking.'),
            $this->optionManager->get('subject.square.type'),
            $square->need('name'),
            $dateRangerHelper($reservationStart, $reservationEnd));

        if ($user->getMeta('notification.bookings', 'true') == 'true') {
            $this->userMailService->send($user, $subject, $message);
        }

	    if ($this->optionManager->get('client.contact.email.user-notifications')) {

		    $backendSubject = sprintf($this->t('%s\'s %s-booking for %s'),
		        $user->need('alias'), $this->optionManager->get('subject.square.type'),
			    $dateFormatHelper($reservationStart, \IntlDateFormatter::MEDIUM, \IntlDateFormatter::SHORT));

		    $addendum = sprintf($this->t('Originally sent to %s (%s).'),
	            $user->need('alias'), $user->need('email'));

	        $this->backendMailService->send($backendSubject, $message, array(), $addendum);
        }
    }`

Kann ich diese Funktion auch irgendwie beim Speichern des edit Formulars aufrufen und die Daten auch richtig übergeben?

Falls das jetzt zu komplex umzusetzen ist auf die Schnelle, würde mir auch eine Mailbenachrichtigung an den Sysadmin reichen, wo nur drinnen steht: Es erfolgte eine Buchung am Terminal, ohne Zeit- und Platzvariablen zu übergeben, dann muss er halt online nachsehen, wann gebucht worden ist, aber er weiß zumindest das eine Buchung erfolgt ist.

**Comment by tkrebs** [comment]
Du kannst im Controller an der gewünschten Stelle mit folgendem Aufruf eine E-Mail an die in den Einstellungen festgelegte Admin-Adresse senden:

```php
$subject = 'Betreff ...';
$text = "Zeile 1\nZeile 2"; // \n für Zeilenumbruch

$this->getServiceLocator()->get('Backend\Service\MailService')->send($subject, $text);
```

Da kannst du dann die wichtigsten Informationen einfach hineinschreiben.

**Comment by tkrebs** [comment]
Die Zeit- und Platzvariablen müsstest du im Anschluss an die Buchung eigentlich auch im Controller zur Verfügung haben und kannst sie relativ einfach in den E-Mail-Text einbauen.

Im Gegensatz zu der NotificationListener.php kannst du das ja direkt mit bspw.

```php
$square->need('name')
```

bzw. für Datum und Zeit

```php
$someDate->format('H:i - d.m.Y')
```

ausgeben.

**Comment by gitroli** [comment]
Habe es implementieren können, danke für die Hilfe.
