### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by ttneu** [tkrebs/ep3-bs#87]
Da sich das Layout bei sehr vielen Plätzen verzerrt bzw. es unübersichtlich wird würde ich gern Spalte mit Zeile tauschen. Ist das möglich? Also die Plätze in der Zeile und die Uhrzeiten in der Spalte anzeigen.
Sofern nicht möglich bin ich aber für andere Lösungen dankbar.

**Comment by tkrebs** [comment]
Die Funktion selbst ist bereits im System eingebaut, wird allerdings nur automatisch aktiv wenn es pro Tag weniger als drei buchbare Zeitblöcke gibt.

Testweise kannst du aber in folgender Datei / Zeile:

https://github.com/tkrebs/ep3-bs/blob/master/module/Calendar/view/calendar/calendar/index.phtml#L14

Einmal manuell `index.portrait.phtml` statt `index.landscape.phtml` eingeben. Dadurch werden die Plätze und Uhrzeiten immer vertauscht.

Kombiniere dies am besten mit der Einstellung "nur 1 Tag im Kalender anzeigen".

Ich schaue mal, ob ich dafür nicht eine manuelle Einstellungsmöglichkeit schaffe.

**Comment by ttneu** [comment]
Das hat super funktioniert. Vielen Dank.
Klasse Programm. Nur weiter so!

**Comment by ttneu** [comment]
Ich habe doch noch eine Frage.
Kann man jetzt den Tabellenkopf <th> in der CSS Datei fixieren?

**Comment by tkrebs** [comment]
Für individuelle CSS-Anpassungen gibt es folgende Datei:

https://github.com/tkrebs/ep3-bs/blob/master/public/css-client/default.css

**Comment by ttneu** [comment]
Die Einstellungen in dieser Datei default.css werden nicht übernommen?
Habe mal folgendes ausprobiert:

.calendar-date-table full-width{
    max-height: 160px;
    overflow: auto;
}
Ist das Layout nicht in der Datei default.min.css gespeichert?

**Comment by ttneu** [comment]
In der Datei TimeRow.php ist die entsprechende HTML Struktur die ich anpassen müßte, damit die Tabellenkopfzeile (Zeit) fixiert wird. Komme hier aber nicht weiter. Die Kopfzeile läßt sich einfach nicht festsetzen.
CSS-Klasse ist calendar-time-row?

**Comment by tkrebs** [comment]
Schau dir noch mal die Syntax deiner CSS-Anpassungen an, z. B.

```css
.calendar-date-table full-width {
```
muss lauten

```css
.calendar-date-table.full-width {
```

Zudem kann es je nach CSS-Deklaration sein, dass deine Anpassungen nicht spezifisch genug sind:

https://developer.mozilla.org/de/docs/Web/CSS/Spezifit%C3%A4t
