### ISSUE TITLE
Lightbox in Chrome funktioniert nicht einwandfrei

### ISSUE THREAD

**Issue by gitroli** [tkrebs/ep3-bs#88]
Wenn man in Chrome einen Platz bucht öffnet sich die lightbox:
![grafik](https://user-images.githubusercontent.com/31999445/33827951-65aaaba8-de6a-11e7-936c-17d8c3bc54e5.png)

Wählt man im Drop Down Menü zB 2 Stunden aus, wird die lightbox geschlossen:
![grafik](https://user-images.githubusercontent.com/31999445/33827991-940e6822-de6a-11e7-84d5-225273889a88.png)

Mit Firefox funktioniert es.

**Comment by tkrebs** [comment]
Danke für den Hinweis, ist korrigiert.

Ausgetauscht werden müssen folgende zwei Dateien:

https://github.com/tkrebs/ep3-bs/tree/master/public/js/controller/square
