### ISSUE TITLE
erweiterte Suche mit Mail-Adresse liefert kein Ergebnis

### ISSUE THREAD

**Issue by wklingberg** [tkrebs/ep3-bs#89]
Die erweiterte Suche mit der Mail-Adresse (e-mail = nnnn@xxxx.de) bringt als Ergebnis "keine Benutzer für diese Suche gefunden", obwohl ein Benutzer mit der angegebenen Mail-Adresse vorhanden ist.

**Comment by tkrebs** [comment]
Stimmt, danke für den Hinweis, ist im Entwicklungszweig (https://github.com/tkrebs/ep3-bs/tree/develop) korrigiert.

Mit (email = ...) funktioniert es übrigens trotzdem.

**Comment by wklingberg** [comment]
Danke. Nach Übernahme der Entwicklungs-Module klappt es auch mit E-Mail.
