### ISSUE TITLE
Fehlermeldung bei der Installation

### ISSUE THREAD

**Issue by Sommerwerk** [tkrebs/ep3-bs#9]
Ich bekomme immer wieder folgende Fehler Meldung:

Oops ... da ist wohl etwas schief gelaufen
SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected

habe schon fast alles versucht was kann das noch sein was mache ich falsch?

Besten Dank

**Comment by tkrebs** [comment]
Bitte stelle sicher, dass die Datenbank-Zugangsdaten in der Datei config/autoload/local.php korrekt eingetragen sind.

**Comment by Sommerwerk** [comment]
Welchen Webspace würden Sie mir empfehlen da es bei bplaced ja nicht geht
wegen Zend

MFG

Am 11. Juni 2015 um 23:14 schrieb Tobias Krebs <notifications@github.com>:

**Comment by jet2future** [comment]
Variante 1: Dedicated Server (VM Server) z.B. Strato, Hosteurope
Variante 2: Kontaktieren Sie ihren Hoster des Webspaces und bitten Sie ihn diese Features zu aktivieren. Alternativ können Sie auch Hoster wechseln.

Sorry für die Einmischung ;)

Beste Grüße,
Jet

**Comment by Sommerwerk** [comment]
Aber Sie wissen jetzt auch nicht welcher Webspace Hoster so was anbietet extra ein VM server anmieten möchte ich ohne vorherigem Test nicht :-)

MFG Sommerwerk

**Comment by jet2future** [comment]
doch bei einem weiß ich es garantiert www.itskoenig.de

**Comment by Sommerwerk** [comment]
super vielen dank den werde ich dann mal antesten :-)
