### ISSUE TITLE
Admin-Buchung für Benutzer bei Eingabe der Mail-Adresse erzeugt einen neuen Platzhalter-Benutzer

### ISSUE THREAD

**Issue by wklingberg** [tkrebs/ep3-bs#90]
Bucht der Admin eine Einzel-Stunde oder ein Abo und gibt er im Formularfeld "gebucht auf" die Mail-Adresse eines aktiven Benutzers an, dann wird - ohne Hinweis - ein neuer Benutzer mit Status "Platzhalter" angelegt.
Offensichtlich wird hier nur im "Namensfeld" der Benutzer gesucht.

**Comment by tkrebs** [comment]
Danke für den Hinweis, auch das ist im Entwicklungszweig (https://github.com/tkrebs/ep3-bs/tree/develop) korrigiert.

Herunterladen kannst du den aktuellen Stand über den GitHub-ZIP-Download:

https://github.com/tkrebs/ep3-bs/archive/develop.zip

Der Austausch des /module/-Verzeichnisses reicht aus.

**Comment by wklingberg** [comment]
Danke. Nach Übernahme module-Verzeichnisses tritt der Effekt nicht mehr auf.
