### ISSUE TITLE
Bei Buchung durch Admin keine Anzeige der Rechnung

### ISSUE THREAD

**Issue by wklingberg** [tkrebs/ep3-bs#91]
Erfolgt die Buchung durch den Admin für einen anderen Benutzer, wird bei diesem Benutzer im Fenster "Meine Buchungen" für diese Buchung kein Button zur Anzeige der Rechnung generiert.

**Comment by tkrebs** [comment]
Bei der Buchung als Admin wird die Rechnung nicht automatisch erstellt, da das nicht zwangsläufig gewünscht ist. Die Vorgehensweise ist hier, erst die Buchung zu erstellen und anschließend die Rechnung zu bearbeiten. Hier können dann individuelle Rechnungs-Positionen erstellt werden oder alternativ per Button

**Neue Position durch Anwenden der Preis-Regeln auf diese Buchung**

die berechnete Standard-Buchungs-Position.

Da dieser Bearbeitungsschritt aber zugegebenermaßen nicht ganz offensichtlich ist, habe ich beim Anlegen der Buchung unter der Checkbox "Benutzer anschließend bearbeiten" eine weitere Checkbox namens "Rechnung anschließend bearbeiten" hinzugefügt:

https://github.com/tkrebs/ep3-bs/tree/develop

**Comment by wklingberg** [comment]
Vielen Dank Thomas für die schnelle Erweiterung. So wird auch der nicht geübte Admin auf die Bearbeitung der Rechnung hingewiesen.
