### ISSUE TITLE
PHP 7.1.12 Errors auf der Registrierungsseite

### ISSUE THREAD

**Issue by gitroli** [tkrebs/ep3-bs#94]
Ich habe das System unter PHP 7.0.26 laufen. Hier gibt es keine Probleme.
Unter PHP 7.1.12 kommt es auf der Seite, wo sich die User registrieren können zu folgenden Fehlern:

Deprecated: Function mcrypt_get_key_size() is deprecated in /var/www/vhosts/buchung/tennis/vendor/zendframework/zendframework/library/Zend/Crypt/Symmetric/Mcrypt.php on line 216

Deprecated: Function mcrypt_get_iv_size() is deprecated in /var/www/vhosts/buchung/tennis/vendor/zendframework/zendframework/library/Zend/Crypt/Symmetric/Mcrypt.php on line 393

Deprecated: Function mcrypt_module_get_supported_key_sizes() is deprecated in /var/www/vhosts/buchung/tennis/vendor/zendframework/zendframework/library/Zend/Crypt/Symmetric/Mcrypt.php on line 234

Deprecated: Function mcrypt_get_key_size() is deprecated in /var/www/vhosts/buchung/tennis/vendor/zendframework/zendframework/library/Zend/Crypt/Symmetric/Mcrypt.php on line 216

Deprecated: Function mcrypt_get_iv_size() is deprecated in /var/www/vhosts/buchung/tennis/vendor/zendframework/zendframework/library/Zend/Crypt/Symmetric/Mcrypt.php on line 393

Deprecated: Function mcrypt_get_block_size() is deprecated in /var/www/vhosts/buchung/tennis/vendor/zendframework/zendframework/library/Zend/Crypt/Symmetric/Mcrypt.php on line 506

Deprecated: Function mcrypt_get_iv_size() is deprecated in /var/www/vhosts/buchung/tennis/vendor/zendframework/zendframework/library/Zend/Crypt/Symmetric/Mcrypt.php on line 393

Deprecated: Function mcrypt_get_key_size() is deprecated in /var/www/vhosts/buchung/tennis/vendor/zendframework/zendframework/library/Zend/Crypt/Symmetric/Mcrypt.php on line 216

Deprecated: Function mcrypt_encrypt() is deprecated in /var/www/vhosts/buchung/tennis/vendor/zendframework/zendframework/library/Zend/Crypt/Symmetric/Mcrypt.php on line 349

**Comment by tkrebs** [comment]
Die Warnungen können deaktiviert werden, indem in der `config/init.php` die Konstante `EP3_BS_DEV` auf `false` gestellt wird. Abgesehen davon sollte die Warnung mit einer aktuelleren Version des Zend Frameworks verschwinden.

**Comment by gitroli** [comment]
ok, bei mir gibt es im config Ordner keine init.php
ich habe testweise eine erstellt:
<?php

define('EP3_BS_DEV', false);

Leider werden die selben Errors ausgegeben.

**Comment by gitroli** [comment]
init.php:
define('EP3_BS_DEV', false);

Leider werden die selben Fehler ausgegeben

**Comment by tkrebs** [comment]
Vermutlich hast du nicht die aktuellste Version des Buchungssystems bzw. insbesondere des Frameworks. Das Paket auf der Website hinkt dem Stand auf GitHub immer ein paar Monate hinterher.

**Comment by gitroli** [comment]
ok danke für die Infos
