### ISSUE TITLE
Benutzerdaten laden

### ISSUE THREAD

**Issue by wklingberg** [tkrebs/ep3-bs#95]
Gibt es eine Möglichkeit, Benutzerdaten, z.B. über eine CSV-Datei mit den Vereinsmitgliedern, zu laden bzw. ist dies in der To-Do-Liste?

**Comment by tkrebs** [comment]
Der Import von CSV-Dateien ist z. B. über eine separate Datenbank-Verwaltung wie phpMyAdmin möglich. Ein direkt in das Buchungssystem eingebautes Import/Export-Modul steht aber auf der ToDo-Liste.

**Comment by wklingberg** [comment]
Welchen Wert muss ich für das Feld "pw" in der Import-Datei verwenden?

**Comment by tkrebs** [comment]
#370
