### ISSUE TITLE
Aufruf der Squarebox beim Seitenauruf

### ISSUE THREAD

**Issue by gitroli** [tkrebs/ep3-bs#96]
Ich würde gerne die Squarebox beim Seitenaufruf gleich anzeigen um dort aktuelle News zu platzieren.
Mit welchem Code kann ich die Squarebox aufrufen?
Danke

**Comment by tkrebs** [comment]
Die Squarebox-Funktionen befinden sich in folgender Datei:

https://github.com/tkrebs/ep3-bs/blob/master/public/js/controller/calendar/index.js

Am einfachsten wäre es, die Squarebox beim Laden des Kalenders anzuzeigen:

```js
$(document).ready(function() {

    loadSquarebox('/news.html');

    // ...
```

Die `news.html` müsste dann nur unter `public/news.html` liegen.

**Comment by gitroli** [comment]
Ok danke, das funktioniert schon sehr gut.
Allerdings wenn man jetzt zwischen den einzelnen Tagen hin und her blättert, kommt auch jedesmal die Squarebox, das wird die User zur Verzweiflung bringen. Kann ich den Code auch woanders platzieren, dass die Squarebox nur beim Seitenaufruf kommt oder ist das schwierig zu realisieren? Hab schon versucht auf das JS-Skript in der layout.phtml im Base Modul zu verweisen. Aber das scheint nicht zu funktionieren.

**Comment by gitroli** [comment]
Folgender Lösungsansatz ist mir jetzt eingefallen:
Abfrage per Javascript ob der User angemeldet ist oder nicht.
Ist der User angemeldet, wird keine Squarebox mehr angezeigt.
Ist der User nicht angemeldet, wird die Squarebox angezeigt.

Kann ich das per Javascript abfragen?

**Comment by tkrebs** [comment]
Eleganteste Lösung:

Beim erstmaligen Anzeigen via JavaScript ein Cookie setzen und bei Folgeaufrufen prüfen, ob dieses vorhanden ist. Optional mit Gültigkeitsdauer (z. B. 8 Std.), damit der Benutzer mögliche neue News auch wieder sieht.

**Comment by gitroli** [comment]
Ok, danke für den Tipp. Funktioniert sehr gut.
