### ISSUE TITLE
Integration Outlook Kalender (Resource), Freigabeoption für Buchungen

### ISSUE THREAD

**Issue by scaflex** [tkrebs/ep3-bs#97]
Guten Tag!
Gerne würden wir wissen, ob und sich folgendes umsetzten lässt: 

1.	Kann das Buchungstool Daten an Outlook/Exchange (Resource) bzw den Kalender übertragen? 
2.	Gibt es eine Option um Buchungen durch einen Mitarbeiter bestätigen zu lassen? Person x fragt den Raum an, aber erst nach Freigabe wird die Buchungsbestätigung verschickt. 

Danke und Gruß

**Comment by tkrebs** [comment]
Guten Tag, die Grundversion des Buchungssystems enthält diese beiden Funktionen nicht standardmäßig. Das müsste über das Plugin-System implementiert werden.

**Comment by JohnGrix** [comment]
@tkrebs, könntest du bitte näher erläutern, was du mit „Plugin-System“ meinst?

Meine Frage bezieht sich insbesondere auf den ersten Punkt: „Kann das Buchungstool Daten an Outlook/Exchange (Ressourcen) oder den Kalender übertragen?“

Ich würde es begrüßen, wenn man alle Kalendereinträge als öffentliche iCal-Datei exportieren könnte, sodass sie auf einer Kalender-App abgelesen werden können. Eine Synchronisierungsfunktion wäre ebenfalls wünschenswert, sodass man beispielsweise von Outlook aus Einträge hinzufügen könnte.

**Comment by tkrebs** [comment]
Ich meinte damit, dass diese Funktionalität selbst programmiert werden muss, da sie im Buchungssystem derzeit nicht enthalten ist. Und das wiederum kann über ein eigenes Modul passieren (im `modulex/`-Verzeichnis), was ich oben als "Plugin-System" bezeichnet habe.

Das Modul-System des Zend Frameworks ist hier dokumentiert:
https://zf2-documentation-br.readthedocs.io/pt/stable/modules/zend.module-manager.intro.html
