### ISSUE TITLE
Anzahl offener Buchungen begrenzen

### ISSUE THREAD

**Issue by wklingberg** [tkrebs/ep3-bs#98]
Gibt es bereits die Anforderung, die Anzahl der offenen Buchungen eines Benutzers zu begrenzen?

**Comment by tkrebs** [comment]
Nein, wäre prinzipiell aber eine sinnvolle Funktion. Für die meisten Betreiber wäre es vermutlich am wichtigsten, die Begrenzung anhand der **unbezahlten** Buchungen festzumachen, oder?

**Comment by wklingberg** [comment]
Falls man es nur von der fiskalischen Seite sieht, wäre das eine Möglichkeit.
Wenn man aber eine Überbelegung der Plätze vermeiden will und in der Regel keine Kosten erhoben werden, wäre es besser, es an der "in der Zukunft liegenden" Buchungen festzumachen.

**Comment by gitroli** [comment]
Für dieses Feature wäre ich auch, das macht vor allem für Freiluftplätze im Verein Sinn, da hier die Benutzer nichts zahlen und erst wieder buchen können, wenn ihre aktuelle Buchung vorbei ist, sonst belegt ein Benutzer im Vorfeld schon zu viele Plätze/Stunden und die anderen Mitglieder können keinen Platz reservieren.

**Comment by wagpat** [comment]
Ich würde die Begrenzung auch auf die 'in der Zukunft liegenden' Buchungen festlegen

**Comment by Felgi** [comment]
Ich würde dieses Feature auch benötigen aus demselben Grund den gitroli oben genannt hat.

**Comment by sitze89** [comment]
Halloo zusammen, 
Gibt es hier schon eine Möglichkeit dies zu begrenzen?

**Comment by tkrebs** [comment]
#266
