### ISSUE TITLE
Gleich nach erfolgreicher Installation - Configuration required

### ISSUE THREAD

**Issue by webhero01** [tkrebs/ep3-bs#99]
Hallo zusammen,

die Installation (ep3-bs-package-1.6) lief bei mir erfolgreich durch. Dann hab bei der Erfolgsmeldung auf den Link zum Buchungssystem geklickt und ich bekam sofort die Meldung "Configuration required". In die Datenbank wurde ja geschrieben beim Setup, also müßte doch auch nicht dieser Fehler kommen. Modrewrite funktioniert auf dem Server und AllowOverride steht auf all, laut dem Mitarbeiter meines Hosters. Woran kann das jetzt noch liegen?
Hab zwei mal die Installation jetzt komplett durchgemacht und es funktioniert nicht. Für Tipps wäre ich echt dankbar.
In der .htaccess ist 
RewriteEngine On
#RewriteBase /
dann kommt oben besagter Fehler. Bei
RewriteBase /
bekomme ich "Internal Server Error"

Danke für Eure Hilfe!
Gruß
Thomas

**Comment by tkrebs** [comment]
Versuche es noch mal mit der aktuellsten Version (die bis eben noch nicht auf der Website, sondern nur auf GitHub war):

http://bs.hbsys.de/packages/ep3-bs-package-1.6.1.zip

**Comment by webhero01** [comment]
Vielen Dank für das neue Paket!
Alle Dateien im Verzeichnis gelöscht. Datenbank gelöscht. Mysql-Datenbank neu angelegt und deine neuen Dateien überspielt. Zugangsdaten für die Datenbank eingetragen und ich bekomme die gleichen Fehler auch, wenn ich die .htaccess so wie im ersten Post wieder ändere.
Configuration required bleibt bestehen.
Hab Probiert die Subdomain anstatt auf /public in den root zeigen zu lassen, am Problem ändert sich leider nichts. Problem die Datenbank aufzurufen.

**Comment by tkrebs** [comment]
Wurden während der Installation die MySQL-Tabellen angelegt?

In der Datenbank müssten insgesamt 15 Tabellen stehen, von `bs_bookings` bis `bs_users_meta`.

**Comment by webhero01** [comment]
Ja es wurden 15 Tabellen von bs_bookings bis bs_users_meta angelegt!

**Comment by tkrebs** [comment]
Kannst du mal in der Datei `/module/Base/Module.php` in Zeile 38 (hinter `include 'Charon.php';`) folgende neue Zeile einfügen und schauen, welche Fehlermeldung anschließend erscheint:

```php
exit($e->getMessage());

**Comment by webhero01** [comment]
Connect Error: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)

**Comment by tkrebs** [comment]
Ich habe eine Vermutung. Teste mal bitte, was passiert, wenn du in der Datei `application.php` in Zeile 15 das `false` in `true` änderst, also:

```php
define('EP3_BS_DEV', true);

**Comment by webhero01** [comment]
Das war es! tausend Dank! Kannst du mir kurz erklären, warum das auf meinem Server nicht funktioniert hat. Hat etwas mit den Caches zu tun.

Kann ich jetzt 

 `exit($e->getMessage());`

wieder löschen?

**Comment by tkrebs** [comment]
Wenn man das Buchungssystem zum ersten mal aufruft ohne bereits die Zugangsdaten eingetragen zu haben, wird diese leere Konfiguration gecached.

Die Zeile mit "exit" kann wieder gelöscht werden.
